### ISSUE TITLE
dotnet-install.ps1 too verbose

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/cli#10329]
## Steps to reproduce

I see this when cloning and building dotnet/corefx.

It prints:

```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x64.zip
dotnet-install: Adding to current process PATH: "F:\gh\corefx\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
```

The third line confuses me:
```
dotnet-install: Adding to current process PATH: "F:\gh\corefx\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
```

I'm not running PowerShell, and don't know about PATH. Maybe the script invoker cares, but as a user I don't. Shouldn't this message me silenced unless the caller uses a "-Verbose" or similar switch?

## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
Not true. You are running powershell, at least to run the script, as it is a powershell script.

I believe the verbosity here is just fine. It tells you that for the duration of a script that you may have used to invoke the install script, the dotnet you just installed will be on the PATH.

**Comment by livarcocc** [comment]
Actually, we put this note in because people were confused by not being able to run the SDK that they just installed.

I really don't see what is so concerning about displaying this message in the default verbosity. Is it causing confusion now? How is it getting in the way of you using the "outer script"?

**Comment by BruceForstall** [comment]
I see the message when I clone `https://github.com/dotnet/corefx` and type "build". I get:
```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x64.zip
dotnet-install: Adding to current process PATH: "F:\gh\corefx\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
```

This is confusing to me because I am in a CMD window. I haven't run PowerShell. So seeing a message about PowerShell makes no sense to me. Plus I don't expect the script I invoked to change my PATH.

I'm also surprised that anyone that knows how scripting works would be confused that if you invoke "powershell dotnet-install.ps1" that you would expect a PATH variable change to persist to the caller.

Now, maybe you could argue the corefx / arcade scripts should suppress all `dotnet-install` output, and should output their own status messages.

IMO, our scripts are far too verbose in general for details the user doesn't need to know or shouldn't care about. Like:
```
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/2.1.401/dotnet-sdk-2.1.401-win-x64.zip
```
Do I really need to know that? You already told me where it was downloaded from, so why say it again? Why say _how_ you are doing it ("Extracting zip from...")? Why output anything? If anything, why not output just:
```
dotnet-install: Installing dotnet CLI
```

**Comment by Coalpha** [comment]
Okay, what's happening here is that when you type "build" into your cmd.exe window, you're actually running `build.cmd` which is within the root of the corefx project that you cloned. If you open `build.cmd` you can see that it runs `build.ps1` which is somewhere inside `corefx/env`.
![image](https://user-images.githubusercontent.com/22552895/48739068-ad3a3780-ec07-11e8-9299-6e93105aa3c2.png) So yes, you are running PowerShell and the reason that this shows information about the Path variable is so you know that you can immediately run the dotnet framework if it was not run within a subshell / child process. The Path variable within shells, cmd and Powershell included, is where the computer looks for programs when you type a command in. The reason it talks about child processes is since updating variables in a child process will not update them within the parent process for most cases. For instance:
![image](https://user-images.githubusercontent.com/22552895/48739513-14a4b700-ec09-11e8-8aa3-1d7c07177f55.png)
