### ISSUE TITLE
2.2 prwview 3 not usable in visual studiok, giving NETSDK1045

### ISSUE THREAD

**Issue by jkotas** [dotnet/cli#10362]
_From @NetTecture on November 19, 2018 18:0_

6>C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.

Totally unabel to redirect to sdk 2.2, which IS installed but does not show up in the dropdown for projects.

_Copied from original issue: dotnet/coreclr#21088_

**Comment by livarcocc** [comment]
An RTW build of Visual Studio will not use a preview version of the .NET Core SDK by default. You must opt-in on using preview bits of the .NET Core SDK.

Which is why VS is not finding the 2.2 preview3 SDK in your disk. You can opt-in to previews in VS by going to Tools -> Options -> Projects and Solutions -> .NET Core. Then you can mark the Use previews of the .NET Core SDK checkbox.

**Comment by NetTecture** [comment]
@livarcocc Ok, accepted. I can actually more than live with that. What I hate is that this is seemingly the ONE part where the eror message does not say "Activate this in settings when you want to use a preview SDK" and leaves a user with "it is somewhere in the blogs and release notes". And THAT is not good ;)

**Comment by livarcocc** [comment]
We are working on making the messages better in Dev16.
