### ISSUE TITLE
Avast detects virus when downloading

### ISSUE THREAD

**Issue by derpcoder** [dotnet/cli#1038]
Hello,

I'm having issues downloading the CLI tooling, whenever I start downloading, halfway through, Avast marks it as a virus. I'm attaching an image of the Avast message.

![Avast message](http://i.imgur.com/VLbJfme.png)

**Comment by piotrpMSFT** [comment]
@Sridhar-MS can you try to repro this?

**Comment by Sridhar-MS** [comment]
Initial intuition is because the MSI is not signed, but I will give it a try.

**Comment by piotrpMSFT** [comment]
@livarcocc has a signed MSI we can use as a counter example if we see a repro.

**Comment by shootdaj** [comment]
I just tried this and got the Avast suspicious item has been detected warning. This happened during the setup as well.

**Comment by Eilon** [comment]
We've recently seen a number of reports of various AV/anti-malware software (e.g. Bitdefender) reporting false positives in various Microsoft releases. Not saying that's the case here, but we've seen it before. E.g. https://github.com/aspnet/Home/issues/1064. The issue was ultimately reported to Bitdefender as a false positive.

**Comment by krwq** [comment]
This was fixed for BitDefender, we didn't have any reports since then on any other antiviruses. Please reopen if this is still happening

**Comment by manifestarium** [comment]
Still happening.
