### ISSUE TITLE
Please increase the time-out for downloads within the dotnet-install.ps1 script from 10 minutes to 30 minutes

### ISSUE THREAD

**Issue by Sathyaish** [dotnet/cli#10396]
# Increase in the download time-out limit from 10 to 30 minutes

A few days ago, I was trying to set up the source code for MS Build on my machine so I could play with it, but the build process for setting up the code on my machine kept failing. I finally figured that one of the problems why it was failing was that it was running a Powershell script named `dotnet-install.ps1` which was downloaded from the URL `https://dotnetcli.azureedge.net/dotnet/Sdk/2.1 .401/dotnet-sdk-2.1.401-win-x64.zip`, and in the script, a 10 minute time-out was declared for the download.

I have a 2 Mbps connection and that file takes only slightly more than 10 minutes on my computer. 

[The specific line of code](https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.ps1#L230) to change is in the script block that's passed as an argument to the `Invoke-With-Retry` method from within the `GetHTTPResponse` method in the Powershell script `dotnet-install.ps1`.

`$HttpClient.Timeout = New-TimeSpan -Minutes 10`

For details of the issue, please read [this comment](https://github.com/Microsoft/msbuild/issues/3937#issuecomment-442037965) of mine in this issue in the MS Build repo.

**Comment by peterhuene** [comment]
@johnbeisner I think the proposed timeout of 30 minutes is reasonable, although do we need a timeout when installing from `dotnet-install.ps1`?  Is there a downside to making it ` InfiniteTimeSpan` (whatever the syntax that is for powershell), thus leaving the decision as to whether or not the download is taking to long to the CI system or user running the script?

Even at 0.5 Mbs, it requires the better part of an hour to download a 160 MB SDK installer.  Since a lot of users around the world depend on the installer script, I would hate to mandate a 1 Mbs of faster connection.

**Comment by johnbeisner** [comment]
timeout was increased to 20 min
