### ISSUE TITLE
Add Warning? dotnet publish --output of multiple projects corrupts dependencies (DLL hell)

### ISSUE THREAD

**Issue by rrnewton** [dotnet/cli#10456]
## Steps to reproduce

Build two projects with the same output:

```
dotnet publish --output <absolutepath> A.csproj
dotnet publish --output <absolutepath> B.csproj
```

## Expected  behavior

Errors when the A and B projects attempt to copy conflicting versions of some dependency (`Foo.dll`).

OR 

Tells us that we're being very naughty and not to ever publish two projects to the same directory.

## Actual behavior

B's version of `Foo.dll` clobbers the second.  Executables installed by A can run with undefined behavior because they pick up the wrong version of this library (reviving DLL hell).

## Environment data
`dotnet --info` output:

We're releasing a project that is testing on Mac, Windows, Linux and inside Docker containers.  This is consistent across all the versions of the .NET core SDK we're using (oldest 2.1.202 under Docker, newest is 2.1.500 on Azure DevOps Pipelines hosts).  Here's one example from an ADO run:

```
 .NET Core SDK (reflecting any global.json):
Version:   2.1.500
Commit:    b68b931422
Runtime Environment:
OS Name:     ubuntu
OS Version:  16.04
OS Platform: Linux
RID:         ubuntu.16.04-x64
Base Path:   /usr/share/dotnet/sdk/2.1.500/

Host (useful for support):
Version: 2.1.6
Commit:  3f4f8eebd8
```

**Comment by dasMulli** [comment]
What if you want to override the same project's publish output with an updated version of the same project's publish output? you'd end up with new versions of the main dll and possibly even dependencies.

The main consensus over publishing multiple projects to the same location currently is that it just isn't supported because of exactly this reason (conflicting versions of DLLs). Just as doing `dotnet publish` on solution files.

**Comment by rrnewton** [comment]
### This is related to the following issues:

 * publish multiple projects at once: https://github.com/dotnet/cli/issues/4825
 * deduplicating the output when publishing a multi-project solution: https://github.com/dotnet/cli/issues/10119
 * clean output folder: https://github.com/dotnet/cli/issues/2855
 * (tangentially) to other examples of stomping output (multi target): https://github.com/dotnet/cli/issues/2216

### Background

I'm currently on a team at Microsoft Research that is releasing an open source project.  In spite of the fact that most everyone involved in the project is a C#/.NET veteran, they were used to Visual Studio, and when trying the dotnet CLI it "seemed fine" to publish four projects to the same output directory.

Indeed, it gives a false sense of confidence, because if the projects have coherent dependencies, then wow, the dependencies appear shared/deduplicated like dotnet CLI is doing something "smart" (as requested by #10119).  But actually, the files are just stomping each other and we saw bugs as soon as any version of a dependencie (Remote.Linq.dll in our case) gets clobbered by a conflicting version.

### Observations

It takes a particular set of policies for this to become a silent failure / corruption.  It could be avoided in several ways:

 * IF the output directory were simply cleaned every time (#2855), we would have immediately noticed our mistake, because all publishes but the last would have disappeared.

 * IF there were a "publish --fragile" mode, it could check before overwriting a file and error if the files were not identical.  (That way, we could clean the destination first, then built multiple projects and it would succeed if and only if they have perfectly coherent dependencies.)

 * IF there were a notion of multi-project publish (#4825) then it would have either dealt with this (separate subdirectories for dependencies, perhaps deduplicated) or would have errored in a manner similar to the "--fragile" solution.

Finally, dotnet publish could simply have had heurustics to try to "guess" if it looks like we're publishing multiple projects on top of each other, and *yell at us*.  (This is surely the most backwards compatible approach.)

### Temporary solution

Once we realized this mistake, we needed a deduplication approach as requested by #10119.  For that I have created a hacky Bash script that works for Mac OS and Linux, [found in this GIST](https://gist.github.com/rrnewton/9989a2d7eab83836e9f1327cd9e20f15).  It symlinks the duplicated dependency files between different subfolders, and we also symlink the executables themselves to the top of the publish destination so there's only one folder to add to `$PATH`.

But what about Windows?  The symlink story is a mess there and I don't see a good deduplication option.  (I'm not even sure how to link/forward `bin/a.exe` to `bin/a_subdir/a.exe` in a way that picks up the .DLL dependencies inside the subdir.)

**Comment by rrnewton** [comment]
@dasMulli  - A different idea -- if there were (or already are) some metadata breadcrumbs left by `dotnet publish`, then it could distinguish provenance, i.e. "which project was this file published from".  Publish could then permit overwriting from the same project (update/incremental rebuild) but define it as an error to clobber a file from a different project with different contents.

(Clobbering a file with the *same* contents should itself probably be a suppressible warning to shout in people's face that they are on really thin ice.)

Actually, while somewhat baroque I think this semantics would be fully backwards compatible with existing valid publish uses and would have given us the slap on the wrist we deserved for attempting the publish-to-same-directory thing.

**Comment by livarcocc** [comment]
I don't believe this is something we will actually tackle.

Regarding your suggestion above:

1. We don't want to clean the folder every time as that would make the publish operation more costly, both because we would be cleaning before publishing, but also because we would be copying more files, as we currently have checks in place to only copy over what we need.
2. So, you would only use this option when re-publishing without changes. What happens when you actually changed your dependency. I don't see this as something we will give priority to.
3. I guess we already have an issue tracking that one.

Like I said, either we already have issues tracking parts of this or there are things here that we will not get to any time soon. Because of that, I am going to go ahead and close this issue.

**Comment by rrnewton** [comment]
> So, you would only use this option when re-publishing without changes. What happens when you actually changed your dependency. I don't see this as something we will give priority to.

I believe that referred to the "--fragile" suggestion, and, yes it would really just be a tool for merging directories and errorring on conflicts.  Indeed, this could be a separate merge/dedup tool like the hacky script I linked to (unfortunately not exactly captured by standard `mv` or `rsync` options.)

But there's also the subsequent mini-proposal in the comment above yours -- I'd like your take on that @livarcocc.  That one requires no extra flags, is backwards compatible, and simply warns/errors when something bad is happening.  A strong version of the proposal is to track enough metadata about previous publishes to allow merging behavior but error when it goes wrong.

A *weaker* (and much easier to implement) version of the proposal would not allow merging at all, but just error if it's attempted.  This could be implemented by just putting a little mark somewhere on a published directory that says which project it came from (probably already there).

Then if you attempt to republish over that same directory, from a different project (without cleaning it first), you get an error.  That's it.  Just tell the user "don't do this".

**Comment by dasMulli** [comment]
@livarcocc is there a tracking issue for publishing on .sln files? I've seen some more issues over the last month involving publishing on solution files.

A lot of them just have a `DotNetCoreCLI@2` azure devops yml task with `command: publish` that they copied from somewhere and then things start to go wrong when the project grows.

Not sure if there are any plans for helping in this scenario - personally I'd be in favor of a breaking change for 3.0 since in many cases, the users have been in dangerous waters before.
