### ISSUE TITLE
Add run `dotnet new tool-manifest` to the error message of cannot find manifest

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#10499]
We should guide the user to run _dotnet new tool-manifest_ if they want to create it when there is no manifest in _dotnet tool restore_ or _dotnet tool install mytool_

**Comment by KathleenDollard** [comment]
Agree to guide for creation on `dotnet tool install`, but I'm not sure for `dotnet tool restore`, because I think a reasonable course of action is to always run this after cloning.  Maybe:

`dotnet tool restore` with no manifest

"There is no tool manifest file, so no tools were restored."

`dotnet tool install mytool` with no manifest

"There is no tool manifest file. If you want to install a global tool, add '-g'. If you want to add to a tool manifest, you must first create it with 'dotnet new tool-manifest'"
