### ISSUE TITLE
WinRT implementation DLL should be copied to the right location 

### ISSUE THREAD

**Issue by rido-min** [dotnet/cli#10692]
To enable 3rd party Windows Runtime Components to be consumed from .NET Core 3 projects we need to ensure that the `.winmd` and/or `.dll` files are copied to the right location. 

/cc @sbanni

**Comment by peterhuene** [comment]
I believe this has been fixed with microsoft/msbuild#4418.  I believe the original problem was that MSBuild wasn't discovering related items for WinRT C++ projects.

If there are additional cases of .winmd or the implementation .dll not being copied locally for .NET Core projects, would you mind reopening this issue with the repro steps that demonstrate the issue?  Thanks!
