### ISSUE TITLE
publish doesn't accept a --packages arg

### ISSUE THREAD

**Issue by glennc** [dotnet/cli#1075]
If I restore an applications packages to a directory using `dotnet restore --packages <path>` then want to publish that app then I need to be able to have publish use the location I restored to.

I had expected to see --packages as an option on publish, compile, etc. Any command that will require looking for assemblies. Or am I missing something?

**Comment by brthor** [comment]
:+1: 
There was some conversation on this a while back:
#261

**Comment by livarcocc** [comment]
Is this really an issue with publish or is this something that restore should have handled when generating the lock files?

**Comment by glennc** [comment]
I don't think baking base path knowledge into the lock file is the right approach. It doesn't have any knowledge of that now AFAIK, and I would be hesitant to add it.

**Comment by livarcocc** [comment]
You are absolutely right, it does not.

And I completely agree that this is needed, not only for publish, but for build and compile as well.

**Comment by davidfowl** [comment]
@livarcocc Ugh, no. We should be careful where we add these command line arguments that augment where things look. The problem with argument is that there's different software looking at where to find packages and they all need to be in sync or the pipeline will fall apart:

- nuget restores packages to a specific location
- The MSBuild nuget target looks for packages
- `dotnet compile/build` and the project model API looks for packages
- The runtime looks for packages based on the deps file
- Visual studio also looks for packages

That's why DNX opted for `global.json` (and potentially nuget.config0 for the way to replace it for things like build/restore/publish. 

Environment variables and command line args are for one off command liney things that don't need to persist or be repeated.

**Comment by livarcocc** [comment]
@davidfowl My point was more in the sense that whatever we do, needs to be done across the commands, to your point.

However, it seems like we have a break of experience at the moment right? You can restore to a different cache location, but none of the commands that actually could use that cache will, because they are not aware of it.

The real issue is how do we make these commands aware of this custom cache location? a command line argument is one option and I see your points. What do we need to reach a decision to correct/enable this scenario?

**Comment by blackdwarf** [comment]
@livarcocc @davidfowl what is the story here in the end?

**Comment by livarcocc** [comment]
I think NuGet takes care of this now. If you do a dotnet restore and specify a packages folder, it sticks that in a reg key or env variable or whatever that it uses to find this later. @davidfowl can confirm. If that's the case, maybe we can just close this.

**Comment by piotrpMSFT** [comment]
@emgarten can you confirm this was fixed in NuGet and close the issue?

**Comment by emgarten** [comment]
NuGet supports reading the packages folder from a command line argument, NuGet.Config, and the environment variable *NUGET_PACKAGES*. NuGet restore doesn't store this information anywhere, it just consumes it.

Publish should find the folder in the same way. Is that happening today?

**Comment by emgarten** [comment]
NuGet is not able to control where publish finds packages.

**Comment by piotrpMSFT** [comment]
Fixed by @eerhardt in https://github.com/dotnet/cli/pull/3937/

**Comment by eerhardt** [comment]
Full disclosure, this is only fixed in the feature/msbuild branch.  And we didn't add `--packages`.  Instead NuGet writes the paths used into the lock file, and CLI calls NuGet to resolve where the package is.  Users don't need to pass `--packages` into every command.  Instead, just `dotnet restore` takes `--packages`, and it is remembered for the rest of the commands.
