### ISSUE TITLE
Incredibly misleading message when the executable cannot be found: "No executable found matching command"

### ISSUE THREAD

**Issue by Doan-Van-Tuan** [dotnet/cli#10911]
## Steps to reproduce
Running this command:
dotnet not-existing.dll

## Expected  behavior
The message should say clearly not-existing.dll cannot be found.

## Actual behavior
The actual message is "No executable found matching command "dotnet-not-existing.dll"", which is misleading. When I encountered it the first time, I thought it was an environment issue, or a bug caused the system searching for dotnet-not-existing.dll.

**Comment by livarcocc** [comment]
If you do not have an SDK installed, you would get a message regarding only the .dll.

However, because you do have an SDK installed, then a lot more happens and the SdK has different extensions points that need to be accounted for. Having said that, I do agree that we need to improve on this error message.

@wli3 can you work with @KathleenDollard to improve this? For some reason, I actually thought we had some improvements lined up as part of the local tools work.

**Comment by KathleenDollard** [comment]
I'd like this message to help the user more. Maybe something like:

Could not run anything - file not found. 
  If you passed '[fileName].dll' it was not found
  If you intended to call a dotnet com, you may have misspelled it
  If you were calling a global tool, 'dotnet-[foo]' was not found 

Let's try to be slightly smart on the filename in first and third message. But we don't need to get carried away because if we display this, the user probably just did a typo, so we could get pretty much anything.

**Comment by wli3** [comment]
closed via https://github.com/dotnet/cli/pull/10914
