### ISSUE TITLE
dotnet build doesn't work when filtered to a supported framework for current SDK

### ISSUE THREAD

**Issue by richlander** [dotnet/cli#11056]
I am wanting to build a project with the .NET Core 2.2 SDK. The project targets .NET Core 3.0 and 2.2. It should work, but instead, it makes me sad.

```console
C:\git\testapps\cpumath>type cpumath.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.0;net472;netcoreapp2.2</TargetFrameworks>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.CpuMath" Version="0.11.0" />
  </ItemGroup>

</Project>
C:\git\testapps\cpumath>dotnet build -f netcoreapp2.2
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.2.105\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [C:\git\testapps\cpumath\cpumath.csproj]

C:\git\testapps\cpumath>dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 3.0.0-preview4-27529-09
  Commit:  0a688d1b7e
```

**Comment by peterhuene** [comment]
Is there a reason for not wanting to build this with a 3.0 SDK targeting netcoreapp2.2?

I think this is a side effect of having to generate the restore graph for every TFM in the project, including `netcoreapp3.0` and thus it would require a 3.0 SDK.

@nguerrera @dsplaisted thoughts on this?

**Comment by dsplaisted** [comment]
Yes, this was never something we intended to support.

**Comment by richlander** [comment]
Got it. That makes sense. This experience made sense given the env I had setup and the project I wanted to build.

If we don't have any motivating evidence that people have a strong reason to need this, we should stay with the POR, per @dsplaisted.

**Comment by dsplaisted** [comment]
Basically, NuGet restores for all target frameworks even if you specify a given framework to build / publish for.  This avoids having to re-restore each time and thrashing the assets file each time you specify a different target framework.  So that would be the trade-off if we wanted to enable this scenario.

Note that I think you could do something like what you want by specifying `/p:TargetFrameworks=netcoreapp2.2` instead of `-f netcoreapp2.2`.

**Comment by Suchiman** [comment]
Can this workaround be at least documented somewhere? This was extremely hard to find and that behavior is very counter intuitive.

Example scenario: I find a random .NET Core project on github like https://github.com/Splamy/TS3AudioBot#building-manually
It tells me to install .NET Core 2.2 and build with `--framework netcoreapp2.2` (it's multi targeting 3.0 as well).
Now you receive this error and are dumbfounded
`
/usr/share/dotnet/sdk/2.2.402/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(137,5):
error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.
Either target .NET Core 2.2 or lower, or use a version of the .NET SDK that supports .NET Core 3.0.
`
In particular
`Either target .NET Core 2.2` <--- it does target that, but also 3.0

Could restore failures for targets other than the one you're trying to build turned into a warning instead?

**Comment by dsplaisted** [comment]
We recommend using the latest SDK even for projects targeting earlier runtimes.  Probably the instructions for building the TS3AudioBot project weren't updated when it added .NET Core 3.0 support.

We recommend using the latest SDK because that's where all of our fixes and improvements go.  For example, even if we were to do as you suggest and skip restoring frameworks that aren't supported, that change would go in a future SDK (ie the .NET 5 SDK or later), and wouldn't help in the case where the 2.2 SDK was trying to restore assets for .NET Core 3.0.
