### ISSUE TITLE
dotnet pack for web projects not only does nothing, it gives no explanation as to why

### ISSUE THREAD

**Issue by chrisfcarroll** [dotnet/cli#11163]
## Steps to reproduce
1. dotnet pack a web project. For instance, your deployment pipeline may go via a nuget feed.
2. Note the complete absence of output **and** the complete absence of any explanation for the lack of output.
3. Spend a couple of hours failing to find the warning – buried at the bottom of https://docs.microsoft.com/en-gb/dotnet/core/tools/dotnet-pack – that this won't work by design.
https://github.com/dotnet/docs/issues/11847#issuecomment-483421470

For the love of all that is counter-intuitive, why would you invent this “feature”?

thankyou for your kind consideration of this frustration :-)

## Expected  behavior
That `dotnet pack` does the 'obvious' thing in all cases, i.e. packs the project. OR, explains that "dotnet pack is inappropriate for a web project because _"

## Actual behavior
Nothing happens *and there is no explanation as to why*

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:  7cecb35b92

**Comment by peterhuene** [comment]
@chrisfcarroll thanks for reporting this issue to us.

I think the default for `IsPackable` is coming from [here](https://github.com/aspnet/websdk/blob/d6ba9de37748a12e7b8ea28bb7def3c954b1317f/src/ProjectSystem/Targets/Microsoft.NET.Sdk.Web.ProjectSystem.props#L25) for web projects.

I think this belongs to the Web SDK to set `WarnOnPackingNonPackableProject` to `true` (if not set) so that users know that `dotnet pack` will have no effect by default.

**Comment by peterhuene** [comment]
This issue was moved to aspnet/websdk#591
