### ISSUE TITLE
Add dotnet build --no-dependencies

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1148]
In order to enable incremental builds in visual studio where msbuild coordinates the P2P graph, we need to have the ability to disable P2P graph walking but still allow incremental build for the main project. To enable this we need to add a `--no-dependencies` flag to `dotnet build`.

/cc @cdmihai @piotrpMSFT

**Comment by cdmihai** [comment]
For this situation in which MSBuild is driving the build and walking the dependency graph there indeed needs to be a way to tell dotnet-build to build only the root project incrementally (otherwise it does a recursive built on every msbuild invocation). 

However, this mode of operation is dangerous / error prone if used directly by developers. Therefore we should discourage its use with a meaningfull flag name (e.g. `–msbuild-driver-mode`) and maybe a warning stating that no dependencies are being built.

**Comment by davidfowl** [comment]
> However, this mode of operation is dangerous / error prone if used directly by developers. Therefore we should discourage its use with a meaningfull flag name (e.g. –msbuild-driver-mode) and maybe a warning stating that no dependencies are being built.

That's pretty overkill. The flag name is fine. We'll just document what it does and if it fails, you got what you asked for.

**Comment by cdmihai** [comment]
Implemented in #1272
