### ISSUE TITLE
dotnet should ignore .dcproj 

### ISSUE THREAD

**Issue by Leon99** [dotnet/cli#11593]
As far as I'm aware, `dotnet` has nothing to do with .dcproj, however, it considers a .dcproj to be an eligible project file. As a result, after adding docker compose support in VS, which creates a .dcproj next to the .sln, `dotnet build` no longer works when executed in the root folder reporting ` error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.` and requires .sln to be explicitly specified.

Seems to be remotely related to https://github.com/dotnet/cli/issues/6178.

**Comment by livarcocc** [comment]
Actually, dcproj is handleded by the CLI. We have an empty docker SDK so that when building through the command line that project is effectly skipped.

The issue here is as the message describes: you have two buildable things on the same folder and we can't disambiguate through them.

Also, the CLI should not have a list of project types that work for them because folks can extend the CLI in ways that we can't foresee and add support to a project that is not natively supported by the CLI.

You would have hit this same issue if you had a csproj and a sln on the same folder. My suggestion is to move the dcproj to a different folder than the solution file or specify the full path to what you want to build when invoking dotnet.

Now, I am not sure VS should be creating the project in the solution folder, for that, I would suggest maybe filling a VSFeedback ticket through VS directly.

Also, notice that we if you had a sln file and a project file in the folder (just these two as project files) and they were named exactly the same, like foo.sln and foo.dcproj, than msbuild would identify that and give preference to foo.sln.

Other than that, the behavior here is as expected.

**Comment by Leon99** [comment]
> Actually, dcproj is handleded by the CLI. We have an empty docker SDK so that when building through the command line that project is effectly skipped.

> The issue here is as the message describes: you have two buildable things on the same folder and we can't disambiguate through them.

> Also, the CLI should not have a list of project types that work for them because folks can extend the CLI in ways that we can't foresee and add support to a project that is not natively supported by the CLI.

Thanks for thorough explanation @livarcocc. My understanding is that you either use VS SDKs from `dotnet`, which is weird given that they are supposed to be fully decoupled and independent products or you supply an "empty docker SDK" with dotnet SDK, which doesn't make much sense at all. Am I right here?

>You would have hit this same issue if you had a csproj and a sln on the same folder

Now, this is clearly a case with two buildable things. No questions here.

> My suggestion is to move the dcproj to a different folder than the solution file

I tried it and it doesn't work - it requires adjusting Dockerfiles which, in order, crashes VS. I filed a ticket through VS Feedback, but that doesn't change the fact that the problem could be avoided at all.

> specify the full path to what you want to build when invoking dotnet.

This is what I had to do for now, but it's suboptimal and will require mass changes in case the name of the .sln changes.

>Also, notice that we if you had a sln file and a project file in the folder (just these two as project files) and they were named exactly the same, like foo.sln and foo.dcproj, than msbuild would identify that and give preference to foo.sln.

This may be useful, thanks.
