### ISSUE TITLE
CLI option to Build with full .NET Framework MSBuild

### ISSUE THREAD

**Issue by TFTomSun** [dotnet/cli#12129]
I'm currently trying to build a net472 application that has a ComReference. ComReferences are not yet support by the msbuild that is integrated in the dotnet core sdk.

I would like to propose a feature that allows us to use the dotnet cli to spawn a full .net framework MSBuild process. Something like

> dotnet msbuild-net /t:Publish ....

I think it wouldn't be a big issue to implement this. But it would help the developers to prepare everything for the future. Currently I would now have to find a why to get the path to the full msbuild.exe. Btw. is there a easy way to determine the latest msbuild.exe on a machine (e.g. via envrionment variable?

**Comment by dasMulli** [comment]
I recommend using vswhere to get the MSBuild location - https://github.com/microsoft/vswhere

I think this has come up before for both VS msbuild and Mono's msbuild. Personally I believe it would be a good tool (global / local tool), but shouldn't be part of the core .NET CLI.

Another interesting question: Should the CLI only resolve to a version of MSBuild that in turn is compatible with the SDK you are running from the command line? E.g. you're on an MSBuild 16 based CLI but only have VS2017 installed - should the CLI have a logic to prevent against calling it or just go ahead and do it but then VS' MSBuild 15 would choose a lower SDK version, probably failing a build (e.g. building .NET Core 3.0 projects).

Also, I think that just having a `dotnet msbuild-net` isn't very helpful to most developers since you'd need to know how all other build related commands translate to msbuild syntax
(`dotnet publish -c Release --self-contained false -r win-x64` => `dotnet msbuild-net -t:Publish -p:Configuration=Release -p:SelfContained=False -p:RuntimeIdentifier=win-x64`).
And adding an `--net-msbulid` parameter to all CLI verbs might not work as expected as well, e.g. due to aforementioned version selection.

**Comment by TFTomSun** [comment]
Since vswhere is a bit complicated to use, i've created a global tool msbuild-net for me. The code can be found here:
https://github.com/microsoft/vswhere/issues/196

**Comment by 3F** [comment]
@TFTomSun, In the past I had a similar problem before vswhere distribution together with VS:

* https://github.com/Microsoft/vswhere/issues/41

Finally, after some decision for an unified solution we're still using this https://github.com/3F/hMSBuild 
... compiled text-based embeddable pure batch-scripts (no powershell, no dotnet-cli).

> who are still working in an classic environment

**Comment by livarcocc** [comment]
This is not something that we have plans of enabling in the .NET Core SDK itself. Our current belief is that you need to target projects that are not currently support by the .NET Core version of msbuild (using dotnet build, etc), that you instead use msbuild.exe directly.
