### ISSUE TITLE
Please publish 2.1.801+dependencies

### ISSUE THREAD

**Issue by Zanadar** [dotnet/cli#12173]
## Steps to reproduce
Hey folks. Like like this release is missing. Any chance you could publish a `2.1.801+dependencies` release? Thanks!

## Environment data
`dotnet --info` output:

**Comment by peterhuene** [comment]
@Zanadar thanks for bringing this to our attention.

I've created the `v2.1.801+dependencies` and `v2.2.401+dependencies` tags.

For this release, the commit for both the "version" and "version+dependencies" tags are the same.  This was caused by the dependencies already be updated for the 2.1.800/2.2.400 release.  However an important fix taken after we had finalized those builds, but before we had released them.  This caused us to release 2.1.801 and 2.2.401 instead, which already contained the updated dependencies.

**Comment by Zanadar** [comment]
Thanks! @peterhuene Will future releases all have dependencies updated? Or should be continue to track `+dependencies` tags?

**Comment by peterhuene** [comment]
Given the way our build works, they will continue to have "+dependencies" tags that should be used when building an individual repo like `dotnet/cli`.

Basically there's a unified build of all the many repos comprising .NET Core and the version information flows through that build only.  Once a build is released, each repo takes a dependency version update PR that bumps the versions to match those produced from the unified build.  This enables the repos to build individually to match what the unified build produced.
