### ISSUE TITLE
dotnet-new to create project with avaiable TargetFramework

### ISSUE THREAD

**Issue by am11** [dotnet/cli#12627]
## Steps to reproduce

Install latest master in a fresh environment:

```sh
$ curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -Channel master

$ ~/.dotnet/dotnet new console -o /tmp/testdrive
$ ~/.dotnet/dotnet run -p /tmp/testdrive
```

## Expected  behavior

`Hello World!` is printed.

## Actual behavior

```sh
/tmp/testdrive/testdrive.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 3.0.0-rc1-19456-20)
/tmp/testdrive/testdrive.csproj : error NU1102:   - Found 7 version(s) in nuget.org [ Nearest version: 3.0.0-preview9-19423-09 ]
/tmp/testdrive/testdrive.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Host.osx-x64 with version (= 3.0.0-rc1-19456-20)
/tmp/testdrive/testdrive.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 3.0.0-preview9-19423-09 ]

The build failed. Fix the build errors and run again.
```

## Workaround

Replace netcoreapp3.0 with netcoreapp5.0 in csproj:

```sh
$ sed -iE "s/\(TargetFramework>\).*\(<\/Tar\)/\1netcoreapp5.0\2/g" \
    /tmp/testdrive/testdrive.csproj

$ ~/.dotnet/dotnet run -p /tmp/testdrive
Hello World!
```

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-alpha1-014647
 Commit:    3551fc0fcb

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /Users/adeel/.dotnet/sdk/5.0.100-alpha1-014647/

Host (useful for support):
  Version: 5.0.0-alpha1.19462.23
  Commit:  a4822402f4

.NET Core SDKs installed:
  5.0.100-alpha1-014647 [/Users/adeel/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 5.0.0-alpha1.19427.5 [/Users/adeel/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0-alpha1.19462.23 [/Users/adeel/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
This is by design.

You are using a nightly build of the CLI for 5.0, where we are still bringing it online.

Also, the reason why it fails to find packages is because the 5.0 CLI will not carry with it targeting packs for older tfms. They will need to be acquired from NuGet, but as 3.0 hasn't shipped yet, you will need to add package feeds to your project in order for restore to find them.

You can find the feeds needed at dotnet/core-sdk before the downloads section of the readme over there.

For netcoreapp5.0, you don't need that because the CLI does carry targeting packs for the TFM that it targets by default (even though the templates haven't been updated just yet).

**Comment by am11** [comment]
Thanks for the explanation @livarcocc.

Can we expect that the generated csproj contain `<TargetFramework>netcoreapp5.0</TargetFramework>` in this case (simply because the current system does not have 3.0 SDK)? `dotnet-cli` seems to have the context available/cached about installed SDKs (as the error message indicates).

**Comment by livarcocc** [comment]
It will, likely in a couple of weeks, once we are through with 3.0 and have 3.1 underway.
