### ISSUE TITLE
Terminal Freezes for a seconds on boot

### ISSUE THREAD

**Issue by javadparvaresh** [dotnet/cli#12694]
## Steps to reproduce
Ubuntu 18
Terminator : 
dotnet-cli version : 3.0.100

## Expected  behavior
Terminal freezes after for about 10 seconds until application booted and started working 

## Actual behavior
As soon as you call `dotnet run` command, it freezes terminal for a seconds until firs log prints out, then it start working

## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  95a0a61858

.NET Core SDKs installed:
  2.1.105 [/usr/share/dotnet/sdk]
  2.1.503 [/usr/share/dotnet/sdk]
  2.2.103 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by livarcocc** [comment]
`dotnet run` does a lot of work before actually running your app and we decided we didn't want the output from that work to get mixed up with the output for the app being run.

It builds your project (which also involves an implicit restore) and then evaluates your project to determine the command to run to execute the project. Finally, it then spins up another process which is the project's executable.

While that's happening, nothing will get printed out. There is a separate issue out there tracking making dotnet run more performance.

Also, dotnet run is meant as a development tool (equivalent of F5). If you are simply trying to run your application, you should use `dotnet app.dll` or app(.exe). I mention this because many people think dotnet run is the only way to execute a .NET Core app.

**Comment by javadparvaresh** [comment]
@livarcocc i agree with you, but in this process if you send the kill signal to the command ( in development environment which we usually use `dotnet run` ..) it just broke the terminal and sometimes i really need to open an other one to keep continue working. i thought maybe this issue is related to that one. but your explanation totally make sense. tnx
