### ISSUE TITLE
Remove warning NU1006 from "dotnet build"

### ISSUE THREAD

**Issue by forki** [dotnet/cli#1277]
"dotnet build" looks at the project.json.lock file and tries to detect if dependencies were changed in the project.json file:

    D:\code\test\project.lock.json(1,0): warning NU1006: Dependencies in project.json were modified. Please run "dotnet restore" to generate a new lock file.

This looks like a nice usability feature, but is not in the spirit of a lock file. I think the build should not care about dependency resolution at all. If the project.json.lock file is found, then it has everything it needs to run the build.

If you agree, then I'm happy to send a PR which removes the warning.

**Comment by davidfowl** [comment]
I don't agree, we actually plan to add more diagnostics to build that looks at dependencies. It actually is in the spirit of the lock file for tools to provide analysis after the fact.

**Comment by forki** [comment]
but isn't the stuff that the package management tools should do? Why is it in dotnet cli?
And is there a way to disabled concrete warnings like this one?

**Comment by davidfowl** [comment]
Just this because nuget produces the lock file doesn't mean other tools can't read it to produce useful diagnostics... It's similar to what the resolve assembly reference task does with in msbuild (it uses assembly metadata rather than package metadata).

There's no way to disable those warnings at the moment. Though I'll not sure why you would disable that one in particular...

**Comment by forki** [comment]
because restore is a feature of the package manager and only the package manager knows if things are valid or not.

**Comment by davidfowl** [comment]
Except that's not really true. The lock file format is defined and has specific elements and in this particular example, the error is telling the user that they probably need to run restore because they edited the `project.json` dependencies (since that section is embedded in the lock file).

I don't see why it's wrong for another tool to warn about that. That's the entire purpose of the lock file. It's a way for nuget to communicate "what happened" to other tools. We even light up diagnostics in visual studio based on the lock file (we can tell you what packages ended up winning over ones that were requested).

**Comment by forki** [comment]
thanks

**Comment by forki** [comment]
Sorry I have to reopen.

Consider the following small example: https://github.com/forki/coreclrwarning

![image](https://cloud.githubusercontent.com/assets/57396/12888660/7e298a2e-ce7b-11e5-8f75-cf1b9f4a3a41.png)

It's showing the warning immediatly after restore. That looks like a false positive.

**Comment by forki** [comment]
related:

* dotnet new
* dotnet restore
* dotnet build

==>

![image](https://cloud.githubusercontent.com/assets/57396/12888841/3d2fbc86-ce7c-11e5-944e-204fb97ab3d0.png)

**Comment by davidfowl** [comment]
Looks like a bug then

**Comment by piotrpMSFT** [comment]
This was a bug. It no longer repros.
