### ISSUE TITLE
mscorlib.dll: why ngen only?

### ISSUE THREAD

**Issue by discostu105** [dotnet/cli#1296]
The latest dotnet cli windows installer puts certain coreclr/corefx libraries into _<installdir>/runtime/coreclr/_. What I have noticed is, that most libraries are not ngen'd, but mscorlib only exists as mscorlib.ni.dll (ngen'd).

My problem with that fact is that in my experience ngen'd assemblies are hard to profile. Specifically, I mean adding new types or methods as well as instrumenting methods via the Profiling API is not possible. My profiling-tool relies on heavily on instrumentation inside mscorlib.dll.

So, my question is what the rationale behind this decision was. Is this expected to change? Can we have mscorlib.dll back, or do we need to expect more coreclr/corefx libraries to be shipped ngen'd.

Also, I've been wondering how "everything is a package" matches with the fact that currently coreclr.dll and other libraries are located in _<installdir>/runtime/coreclr/_?

**Comment by wjk** [comment]
@discostu105 Are you certain it is an ngen assembly? What technique are you using to determine if an assembly is ngen or not? Simply comparing ngen and non-ngen assemblies using ILDASM yields no immediately observable differences. According to MSDN, ngen assemblies are found in one place only: `C:\Windows\assembly`. AFAIK, it is entirely possible to rename `foo.dll` to `foo.ni.dll` and it will still run, but that doesn't make it an ngen assembly, especially under CoreCLR, where CoreConsole and similar entry points [look for `.ni.dll` before `.dll`](https://github.com/dotnet/coreclr/blob/master/src/coreclr/hosts/coreconsole/coreconsole.cpp#L292-L293), but treat them identically as far as I can tell. (ngen.exe is not part of CoreCLR.)

As to your other question, about _/runtime/coreclr/_: This directory exists so that if you `dotnet compile` a program, and then immediately try to run it, it will still launch, even though the dependencies are not copied from their packages like they are when you run `dotnet publish`. The `corehost` tool [included with .NET CLI](https://github.com/dotnet/cli/tree/rel/1.0.0/src/corehost) looks for this directory via the `%DOTNET_HOME%` environment variable, and falls back to the DLLs there if they are not in the same folder as the EXE (which only occurs if you run `dotnet publish`).

Hope this helps!

**Comment by discostu105** [comment]
@wjk Thanks for your response! I assumed it to be ngen, because of _.ni.dll_ postfix and I assumed it needed a non-_.ni.dll_ for fallback. But you are right, after hooking in a profiler via _Profiling API_, I did in fact get JITCompilationStarted callbacks for mscorlib methods. So, obviously the fallback to JIT IL-Code rather than use the pre-compiled machine code (through COR_PRF_USE_PROFILE_IMAGES) works after all even with only _mscorlib.ni.dll_. That's great! :)
