### ISSUE TITLE
Determinism as the default? 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#1297]
Roslyn introduced deterministic builds as a feature in version 1.1.  Deterministic builds means that for the same inputs the compiler will produce identical (byte for byte) outputs.  This is not true of builds today where a number of values change on every build: MVID, PDB id, timestamps, etc ... 

Deterministic builds are advantageous because it allows for features like memoizing test results, fully repeatable builds, highly scalable builds, etc ...   Also just basic sanity around builds: identical inputs should have identical outputs.  

This feature is disabled by default when the compiler is run via MSBuild because it interacts poorly with many existing projects.  Several Visual Studio templates used to include the following snippet that is not compatible with deterministic builds:

``` csharp
[assembly: AssemblyVersion("1.0.0.*")]
```

The \* here is an error when combined with `/deterministic`.  The \* asks for the number to change on every build which is a contradiction when doing deterministic builds.  

Given that CLI is new we don't have the legacy code issue and have the flexibility to make deterministic builds the default.  

Thoughts? 

For the curious, here are the set of inputs that contribute to deterministic builds: 

> https://github.com/dotnet/roslyn/blob/master/docs/compilers/Deterministic%20Inputs.md

**Comment by akoeplinger** [comment]
+:100: 

I'm a big fan of deterministic compilation, we switched it on by default in Mono 4.0 and afaik didn't have any complaints yet.

**Comment by enricosada** [comment]
:+1: about that

the `AssemblyVersion` usually doesnt change a lot (break references) instead `AssemblyFileVersion` it's often used to set the version. Using fixed `1.0.0.0` it's ok

> fully repeatable builds

I dont want to hijack the issue, but i see `referenced assemblies` as deterministic input.

Repeteable builds it's a really an important feature, i need that because i must compile old programs and everything should work (sometimes **after months or years**, in enterprise happen a lot). 

Usual workflow is clone repo -> build -> same build (ok .dll may change a bit but it's compatible). If roslyn can build exactly the same dll, it's awesome!.
But fully repeatable build require also dependancies. I can easy do that with old tools like csproj and committing packages to repo (i read about azure team does that in a azure blog) or use paket to pin dependancies (a lot easier :+1: ).

But atm `dotnet restore` workflow doesnt make that possibile, without committing project.json.lock (and that's not the usual/suggested workflow, it's big to diff, the lock file it's .gitignore by default, etc). 
Maybe that's another issue i know but i think it's related (or prerequisite?) to actually using roslyn deterministic build in real world

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
