### ISSUE TITLE
Enable debug on native library call

### ISSUE THREAD

**Issue by andrew-vandenbrink** [dotnet/cli#1341]
Not sure if I put the issue in the correct place
https://github.com/aspnet/Mvc/issues/4063

But there are problem to native library call, 2 at least:
1. Setting the path of native library search path
I would like to have an api to set native library search path, this will make it easier to host web application in shared host

2. Debuging native library crash
I have this postgres interop which always crash when its freeing memory
```
[DllImport("libpq", EntryPoint = "PQfinish", CallingConvention = CallingConvention.Cdecl)]
        internal static extern void PQfinish(IntPtr connection);
        private static void Close(IntPtr connection)
        {
            PQfinish(connection);
        }
```
I barely able to solve this as the only message I have
```
The program '[13344] dnx.exe' has exited with code -2147483645 (0x80000003).
```
There is no option to enable unmanaged code in visual studio too

**Comment by moozzyk** [comment]
When attaching to the process you can select types of code you want to debug. 
[note this is specific dnx]
start your app with the `--debug` flag 
in vs attach to the process - select Native and CoreClr code type
after the first time your native dll is used (i.e. after the first call to a dllimported function) load symbols for not native dll (if not loaded automatically) and you should be able to set break points in your native code etc. 

I am closing this issue since it does not seem to belong to cli. Because you are using dnx it should be in the http://github.com/aspnet/dnx repo.
