### ISSUE TITLE
dotnet-test fails to find executable

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#1534]
dotnet test fails to find the executable dotnet-test-xunit.dll when executing on OSX and Linux even when executing from the same directory as the tests. (NB this is not the same as #1184 ) This occurs if dnxcore50 is not the first TFM listed in the test project.

Using OSX, dotnet v 1.0.0.001509
```
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
```
Example: https://travis-ci.org/aspnet/Microsoft.Data.Sqlite/jobs/111259306#L1877

**Comment by livarcocc** [comment]
@natemcmaster I believe the problem here is the net451 that you have at frameworks in your project.json. For that framework, we don't know how to find dotnet-test-xunit, since you put the dependency inside the dnxcore50 only. So, dotnet test tries to run for that tfm (net451) and it fails. Why do you have net451 tfm in your test project as well? Remove it and you should be ok.

**Comment by natemcmaster** [comment]
`dotnet-test` finds and runs just fine if dnxcore50 is the first TFM listed. But if net451 is first it throws the error above.

We test both dnxcore50 and net451 because we cross compile to this and dotnet5.4.

**Comment by blackdwarf** [comment]
@livarcocc so should we just fix this so that it fails only after all frameworks are exhausted from the `project.json` file and none has the test runner defined?

**Comment by livarcocc** [comment]
@blackdwarf Not so sure that that is the right thing to do. If we iterate through the TFMs looking for one where we can run, what is the purpose of having multiples there to begin with?

I agree that we should support multiple TFMs, in the sense that we run tests for all of them, given that they support the runner, and if any of them fail, we fail.

It should be all or nothing and not 1.

Makes sense?

@natemcmaster Please note that in that case, it is not running the second Tfm, which I believe is not what you wanted. Like I said above, we should run them all and fail if any of them fails.

**Comment by natemcmaster** [comment]
Fortunately reordering tfms fixes the issue easy enough (e.g. https://github.com/aspnet/Microsoft.Data.Sqlite/commit/c4e9cd2ec6def2e1c8c242a168f535fee4798f59). 

My 2 cents: if a test runner doesn't supported all tfms, dotnet-test should warn but otherwise carry on to the other tfms.

**Comment by livarcocc** [comment]
@natemcmaster What is the purpose of having that non-supported Tfm in the test project at all then? And you are aware that we are not running tests for net451in your case right? We run them for dnxcore50 and stop.

@blackdwarf @piotrpMSFT This is my proposal, we run tests for every tfm in the project.json. Otherwise, I don't see the purpose of having them there. If any of them fail, we can warn or error out. We need to decide. I believe this should be the fix to this issue. Also, I would probably mark it as enhancement.

**Comment by natemcmaster** [comment]
Although dotnet-test doesn't execute net451, we still want full .NET testing. @aspnet projects are currently configured to test net451 by running xunit.runner.console on the output of `dotnet publish --framework net451`.

At the very least, it would be nice to add `dotnet test -f|--framework [tfm]`.

**Comment by livarcocc** [comment]
@natemcmaster I see. You just want to build for the tfm.

We actually have plans to add that more parameters to dotnet test. See https://github.com/dotnet/cli/issues/1376. We are also working to add support on the runner for full .net framework.

**Comment by natemcmaster** [comment]
+1 for full .net test runner. Is there an issue tracking progress on that?

**Comment by markwilkie** [comment]
@MattGal is working on making our Helix test runners easier to extend.  Any takers to enable one for full .NET?

**Comment by livarcocc** [comment]
I have added -f to dotnet test. As for running for multiple frameworks, I will track that here: https://github.com/dotnet/cli/issues/913.
