### ISSUE TITLE
Get help from test runners

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#1549]
If you run `dotnet test --help` you get the help for `dotnet-test` but not for the runner that's behind `dotnet-test`.

As far as I can tell, there's no way to get help about the arguments of the underlying runner.

**Comment by piotrpMSFT** [comment]
@livarcocc

**Comment by eerhardt** [comment]
+1 from me.  Hit this issue today and had to ask the team how to run a single test.  I would have been able to figure it out myself if `--help` would have listed the options from xunit.

**Comment by victorhurdugaci** [comment]
Just a curiosity... Why is dotnet test a special command? Why can't it be a regular "tool"? That way, `--help` would be straightforward

**Comment by eerhardt** [comment]
> Just a curiosity... Why is dotnet test a special command? Why can't it be a regular "tool"? That way, --help would be straightforward

I think because `dotnet test` isn't a single "tool" like the "xunit test runner" is.  Instead, `dotnet test` is more abstract and can plug in any test runner.  Since it can plug in any test runner, it is at a higher level.  Since it can plug in any test runner, --help isn't straightforward, because it needs to call the underlying tool for its --help, and aggregate `dotnet test` options with the underlying runner's options.

**Comment by piotrpMSFT** [comment]
the new `dotnet test` based on the `dotnet vstest` console is no longer a thin wrapper on the underlying console runner. The `--help` for `dotnet test` is now complete.
