### ISSUE TITLE
Should we support side by side installations of x64 and x86 MSIs?

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#1570]

**Comment by robmen** [comment]
What is the scenario where'd you want to do this?

**Comment by GuardRex** [comment]
Side-by-side installs appears to be the default now regardless of architecture (x64-x64, x86-x86, and x64-x86) apparently (guessing here) due to the need to keep multiple shared frameworks for apps using different shared framework versions on a given development system (or shared frameworks on a server).

![capture](https://cloud.githubusercontent.com/assets/1622880/14112446/567d7482-f594-11e5-82ea-4da95a8a1da6.PNG)

Was it discussed/decided not to have a switch (i.e., checkbox in the MSI installer) to force the installer to remove/overwrite any prior installed `dotnet cli` versions and shared frameworks on the machine?

I'm coming at this from the angle of embracing the standalone app model, so shared frameworks and prior version `dotnet cli` tools are usually something I won't have an interest in pursuing.

**Comment by davidfowl** [comment]
The msi only matters for tools if you're doing standalone development. The framework comes from packages when running standalone

**Comment by piotrpMSFT** [comment]
We support SxS installs on the architecture pivot.
