### ISSUE TITLE
dotnet pack --no-symbols

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#1599]
Should we have an option to not create a symbols package in dotnet pack? Or maybe, have it not create a symbols pack by default and have an option to add it?

What is the purpose of always generating it?

cc @KrzysztofCwalina

**Comment by KrzysztofCwalina** [comment]
I agree with @livarcocc.

**Comment by Excolo** [comment]
I had a slight issue with the symbols package being created. In my TeamCity build configuration, I use dotnet pack to package the project and nuget to publish the project to a private NuGet repository. The problem was that the TeamCity build step for publishing with NuGet, didn't allow me to exclude certain patterns (only allows include) when defining which NuGet packages to publish. 

Thus the symbols package would be published as well, my NuGet repository would scream at me and the build configuration fail. 

I found this issue and decided to add the --no-symbols argument myself, which solved it. I can post a PR if it's something you would like.

**Comment by Thorocaine** [comment]
@Excolo  I agree that this is annoying, but to solve it I just added a delete step after the pack step. I know it could be argued that it shouldn't have to be needed, but until there is `--no-symbols` support, it does work.

**Comment by NightWatchman** [comment]
I'm not getting any symbols at all when running dotnet pack using version 1.0.0-preview4-004233.  Apparently this issue has been solved.  Now the question is how do I get symbols when I want them?

**Comment by blackdwarf** [comment]
@NightWatchman `--include-symbols` should do the trick.
