### ISSUE TITLE
Publishing doesn't publish modified Views when compilation is skipped

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#1614]
If I modify a View manually (and that's all I do), then perform a `dotnet publish`, the modified View is not moved into the published output. Therefore, a deployment will deploy a stale View. This one is easy to repro: Just mod a View file and do nothing else, re-publish ... you will get ...
```
Project www_XXXXX_com (.NETStandardApp,Version=v1.5) was previously compiled.
Skipping compilation.
```
... check the published output. The View you modded will not get published to the output.

![capture1](https://cloud.githubusercontent.com/assets/1622880/13369543/e10d95d0-dcaa-11e5-87e4-9498e429cf7b.PNG)

![capture2](https://cloud.githubusercontent.com/assets/1622880/13369525/c76637b8-dcaa-11e5-9d38-c353437e98c6.PNG)

[EDIT] This prob also applies to any `content` file that is modified.

**Comment by blackdwarf** [comment]
@GuardRex would be awesome if you could provide us with a repo with an easy repro.

**Comment by GuardRex** [comment]
@blackdwarf Any project should do with `content` (e.g., the HelloMvc `cli-sample` app will repro this https://github.com/aspnet/cli-samples/tree/master/HelloMvc).

1. Build/publish the project.
2. Open the `Views/Home/Index.cshtml` file and make a small text change. Add a character anywhere.
3. Build/Publish the project. You should get the "skipping compilation" message.
4. Check the built/published output. The modified View file was not moved on build/publish to output.

Apparently, `content` files' modification dates are not checked against prior built/published output when skipping compilation. It turns out this issue will happen not just for Views but for any `content` folder files.

**Comment by davidfowl** [comment]
The logic is currently very broken because publish is the only thing that should be copying content. It's currently also being copied on compile which is just plain wrong. I'm hoping that we do a single pass to clean up all of the broken behavior with output dirs and assumptions made around content and other things.

**Comment by cdmihai** [comment]
Regarding incremental compilation, should the content files be part of incremental compilation? 
Or should publish always copy the content files, regardless of what the compilation outcome was (build / skipped). It sounds like this should be the responsibility of publish, and build should not be aware of the content files.

**Comment by GuardRex** [comment]
I only hope for publish to be addressed. I only mentioned build to fully
describe the current behavior.

**Comment by livarcocc** [comment]
@cdmihai Not sure I agree, that would mean that if I wanted to use something from Content, I would have to publish and I may have to do so just for Content. There are a bunch of cases where a publish hasn't been needed to far and just the deps file is fine.

**Comment by blackdwarf** [comment]
@livarcocc would help if you outline those cases.

**Comment by livarcocc** [comment]
Well, nearly every test project in the CLI uses this. Most of them have a Content dependency to binplace the "test assets" they depend on. Today, all we do is a build and it works just fine. If we make the change, we would then have to do a publish.

This is also true for a few projects in corefxlab and all we do in there is build.

**Comment by cdmihai** [comment]
OK, so my understanding is that the responsibility of Publish is to copy the TFM / RID flavor of dependencies and content files into a folder so you get something that runs for that TFM / RID.

Snooping through the Publish code it looks like publish should always copy the content files, indifferent of whether build was incremental or not: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-publish/PublishCommand.cs#L160
If that does not happen, there's a bug somewhere in Publish / StructuredCopyTo.

Build apparently also does a Mini Publish (copied over from compile) for the current RID, so that the output of Build is runnable. This involves copying the content files as well (and then I guess Publish copies them over again).

Looking through Mini Publish code, it only happens after an invocation to dotnet-compile, so it's skipped if the root project skips compilation due to incrementality: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-build/CompileContext.cs#L400
To address this issue in Build, line 400 needs to be moved somewhere else so it always runs, indifferent of incremental outcome. This could shoot incrementality in the foot if Mini Publish modifies timestamps of the input / output files that incrementality looks for

**Comment by GuardRex** [comment]
This behavior no longer repros since my OP back in February. Closing now.

**Comment by GuardRex** [comment]
Might be a problem after all: https://github.com/dotnet/cli/issues/2989

**Comment by GuardRex** [comment]
Solved by adding back `.UseContentRoot(Directory.GetCurrentDirectory())` to `WebHostBuilder`. **Never** take that off there you silly green dino!

Thanks @davidfowl -- Truly, one of the greatest.
