### ISSUE TITLE
build output file names and version.txt file unification

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#1637]
Currently the build output links follow this pattern:

```
https://dotnetcli.blob.core.windows.net/dotnet/<Channel>/<Bucket>/<Version1>/dotnet-<OSID1>.<Version2>.<Extension>
https://dotnetcli.blob.core.windows.net/dotnet/<Channel>/dnvm/latest.<OSID2>.version
<Channel>=(dev|beta)
<Bucket>=(Installers|Binaries)
<OSID1>=(win-x64|win-x32|ubuntu-x64|osx-x64|centos-x64)
<OSID2>=(win.x64|win.x86|centos|ubuntu)
<Version1>=(Latest|<4-number-version>)
<Version2>=(latest|<4-number-version>)
```

Issues/questions with that:
- [x] ~~nightly vs dev~~ Channels: future | preview | production
- [x] ~~Channel should match the channel from the spec: (dev|nightly)|preview|production~~ Channels: future | preview | production
- [x] ~~OSID1 and OSID2 are not matching each other - this should be unified, ideally with `<RID>`~~ OSID should match RID as closely as possible. Note, however, that for windows this will be `win-x86`|`win-x64` since we don't have installers that target specific RIDs.
- [x] ~~Should `<Bucket>` exist?~~ Bucket is not necessary.
- [x] `<Version>=latest` should be at minimum the same capitalization and ideally should disappear and be replaced with a "latest" link to a specific build
- [x] ~~Should `/dnvm/` be part of the path?~~ Bucket is not necessary.
- [x] ~~RIDs should be AMD64 instead of x64 (otherwise we got AMD64 vs IA64)~~ x64 is fine. The convention is that x64==AMD64 and ia64 == IA64.

@piotrpMSFT @Sridhar-MS @brthor @livarcocc

**Comment by brthor** [comment]
My opinions:
1 and 2. Having the channel called dev is fine but having the initial conflict with this was that we shouldn't have a `-dev` debian package. This is because this convention has meaning:
https://www.debian.org/doc/debian-policy/ch-sharedlibs.html (go to 8.4)

3 and 4. IMO OSID1 and OSID2 should both be RIDs. Why invent our own concepts here.

5. It's probably not necessary but is nice for reasoning about things. Don't have an opinion here.
6. :+1: 
7. No, IMO

**Comment by blackdwarf** [comment]
@brthor everyone else is calling these nightlies. I don't see an issue with that approach. Does "nightly" have a convention in Debian?

**Comment by piotrpMSFT** [comment]
I don't think nightly is right.

We end up with three channels:
- Production
- Preview (rel/1.0.0)
- Future (master)

Within each channel we have two logical indexes
- Latest (Nightly)
- LKG (stable)

Thoughts?

**Comment by brthor** [comment]
@blackdwarf not as far as I know. Avoiding the `-dev` suffix was a driver behind calling these nightlies.

@piotrpMSFT I agree it's not quite right especially since we don't ship nightly. Future does seem more appropriate. Am I right in understanding we would ship a `dotnet-future` package with your suggestion?

**Comment by blackdwarf** [comment]
@piotrpMSFT why is nightly not right? Are the indices you mention logical or physical?

**Comment by blackdwarf** [comment]
Oh, I see, because we don't ship nightlies. OK, Futures would be ok. Dev I don't like.

**Comment by piotrpMSFT** [comment]
@krwq it looks like a bunch of things got resolved. Can you roll up these changes so we can focus on remaining gaps?

**Comment by blackdwarf** [comment]
@piotrpMSFT what got resolved and how does the spec need to update to reflect?

**Comment by piotrpMSFT** [comment]
I think many of the questions in this issue got addressed. I'm asking the issue be updated to remove variables.

**Comment by Sridhar-MS** [comment]
@krwq I see no use for `Bucket` and `dnvm`. You can remove them.

**Comment by blackdwarf** [comment]
@piotrpMSFT oh, that. OK :)

**Comment by piotrpMSFT** [comment]
I consolidated the feedback in the issue above. Seems like we got through everything.

**Comment by Sridhar-MS** [comment]
@piotrpMSFT If we are using RID for OSID, then what will the OSID look like for OSX build artifacts?
Is it `osx.10.10-x64` or `osx.10.11-x64` since since support on both OSX.10.10 and OSX.10.11? 

Other options
- Or should we just match the `Microsoft.NETCore.Runtime.CoreCLR` RID? CLI is going to be supported only on platforms where CoreCLR is supported.
- Or use this convention {OSName}.{LowestOSVersionCLISupports}.{Arch}?

**Comment by krwq** [comment]
> Or use this convention {OSName}.{LowestOSVersionCLISupports}.{Arch}? 
I really like this idea. If Windows ever does breaking changes or we could strip some binaries we could easily version it. Examples: win7.x64 could have api-ms-*.dll files, win8.x64 we can get rid of them. OSX does breaking change - we can easily increase the number - I think we should also get rid of the dot between OSName and OSVersion

**Comment by piotrpMSFT** [comment]
Let's match CoreCLR RID. Once Shared Framework is available, CLI itself is purely portable and our installers will need to match the CoreCLR's they're bundled with. Let's reflect our dependencies instead of inventing something new.
