### ISSUE TITLE
dotnet run should not output informational messages for build

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#1651]
## Steps to reproduce
1. mkdir new && cd new
2. dotnet new
3. dotnet restore
4. dotnet build
5. dotnet run
## Expected  behavior

`dotnet run` outputs "Hello World". 
## Actual behavior

`dotnet run` outputs the following:

``` console
Project new (DNXCore,Version=v5.0) was previously compiled. Skipping compilation.
Hello World!
```
## Environment data

`dotnet --version` output:

``` console
.NET Command Line Tools (1.0.0-beta-001511)

Product Information:
 Version:     1.0.0-beta-001511
 Commit Sha:  211f0e7af3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 Runtime Id:  osx.10.11-x64
```

The only build messages that should be propagated to the user are failures, that is, the inability to build. These kinds of warnings in `dotnet run` are weird and non-actionable. 

/cc @piotrpMSFT

**Comment by piotrpMSFT** [comment]
agreed. We should capture the build output and print it only on failure.

@blackdwarf can we create a fit-n-finish Label for these kinds of issues?

**Comment by blackdwarf** [comment]
@piotrpMSFT there you go.

**Comment by Peter-Schneider** [comment]
One question: In your steps to reproduce you do a `dotnet build` and `dotnet run` afterwards. The `dotnet build` is not needed as the `dotnet run` command runs the `dotnet build` command if you're not invoking it interactively. Therefore I think it should be enough to print out the message via `Reporter.Verbose` (supporting the env variable if you want to see the message) instead of `Reporter.Output` in the build command (see line here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-build/CompileContext.cs#L135). The Reporter.Output.WriteLine is used several times in `dotnet build`, which might be adjusted. Right at the moment several commands vary in their output method (some use Console.WriteLine, others  Reporter.Output) - in short: it might be a good idea to use a common method.

**Comment by blackdwarf** [comment]
@Peter-Schneider I'm fine with whatever implementation is decided and passed through the PR review. I would just like dotnet run to not output messages that are non-actionable.

**Comment by piotrpMSFT** [comment]
@Peter-Schneider we discussed this and decided that these messages should remain in standard output for regular compilation. However, we have identified a few cases in which we want to hide these messages if there is no build error:
- `dotnet test` building before running tests
- 'dotnet run` building before running

Will that address your concern as well?

**Comment by blackdwarf** [comment]
This is actually done with `dotnet run` in the Preview 3 bits. It will now by default output build information only if there are errors. So, closing this.
