### ISSUE TITLE
Running individual test projects

### ISSUE THREAD

**Issue by jaredpar** [dotnet/cli#1664]
What is the fastest ways to run tests for a particular test project? 

Right now the only way I can find is to use build.cmd.  That takes far too long for being useful in developing unit tests.  I don't need to build all three stages of the compiler.  Just want to build this test project using the latest, run tests and iterate.  

How can I accomplish that in dotnet/cli?

**Comment by piotrpMSFT** [comment]
I do this with two console windows.

In one, I'm in the asset directory and I run `dotnet build && cp bin/Debug.../...dll ../../artifacts/.../stage2/bin/`. Once that finishes, in the other I am in the root of the test project and I run `dotnet test`.

**Comment by jaredpar** [comment]
Why is the `cp` step necessary here?  Isn't this something that `dotnet build` should be handling?

**Comment by livarcocc** [comment]
@jaredpar If you are talking about the CLI tests, we have function/E2E tests, that exercise dotnet itself (the exe) found in the stage2 folder (which is why you need the CP command Peter mentioned above). We also have pure unit tests, like dotnet-compile.UnitTests or dotnet-test.UnitTests. For these, all you have to do is dotnet build after you make changes to the test or the product code and then dotnet run. In these cases, you are right, build will take care of rebuilding and binplacing the relevant binaries.

Makes sense?

**Comment by jaredpar** [comment]
Sure.  Do we have that documented anywhere?  

Right now as a developer coming to this repro the only documentation available says to run `build.cmd`.  That's incredibly slow for a developer loop.

**Comment by livarcocc** [comment]
@piotrpMSFT @krwq @blackdwarf Do you guys have a suggestion where to put this information? @jaredpar is absolutely right, we need to put this somewhere.

**Comment by blackdwarf** [comment]
@livarcocc there is the developer getting started guide in the docs. Feel free to put it there.

**Comment by livarcocc** [comment]
I have https://github.com/dotnet/cli/pull/1872 out to add this extra information.
