### ISSUE TITLE
No prompt in 'dotnet repl'

### ISSUE THREAD

**Issue by cston** [dotnet/cli#171]
Prompt is echoed after input rather than before.

```
c:\>dotnet repl
Microsoft (R) Visual C# Interactive Compiler version 1.2.0.51106
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
1 + 2
> 3
1 - 2
> -1

```

**Comment by anurse** [comment]
This is because of how we forward the process output. Unfortunately, once you redirect Standard In/Out, everything is line-buffered and it doesn't appear to be possible to disable the buffering. @glennc found the same thing.

The only real fix right now is to use Process.Start without redirection and allow the processes to attach to the parent console.
