### ISSUE TITLE
Content should not be copied on build

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#1758]
## Steps to reproduce
```
dotnet build
```

## Expected  behavior
things described as `content` in `project.json` should *NOT* be copied to the output folder

## Actual behavior
things described as `content` in `project.json` are copied to the output folder

**Comment by andschwa** [comment]
Why should they not be be copied to the output folder? How else is build going to copy content that the app needs to run?

**Comment by DamianEdwards** [comment]
The current proposal is to replace `content` with new properties under `compilationOptions` and `publishingOptions` to allow explicit control of this. For ASP.NET Core applications, copying content to the output folder for every build is a) too slow, and b) breaks many of our "edit a file and refresh the browser" workflows, e.g. views (which are dynamically compiled by the application) and static files like JS that are served directly to the browser.

**Comment by livarcocc** [comment]
@davidfowl @DamianEdwards So, do we have a design for this? Is this written down somewhere? Have we fixed this already?

**Comment by livarcocc** [comment]
@davidfowl Fowler, once we have answers for the questions above, please assign it back to me.

**Comment by andschwa** [comment]
We're switching our use of publish to build for a big internal project. Please do not implement this without a way to specify files to be copied to output on build.

**Comment by piotrpMSFT** [comment]
@andschwa you should not be using build output outside of the development pipeline. I'm not sure what it means to move from publish to build, then...

**Comment by andschwa** [comment]
We were previously depending on publish for development builds because we needed a flat list of all dependencies to run anything. That's been fixed so we can use build (and even run) during development.

The only problem is that we still need to copy some runtime dependent native libraries that are built outside of CLI to the same location as the host. We're using content to do this until a better option becomes available.

**Comment by DamianEdwards** [comment]
There will be settings in `"compilationOptions"` to allow the copying of files during compilation/build.

**Comment by andschwa** [comment]
Exactly. I'm just trying to say that we need the settings in compilationOptions before the changes in this issue are integrated, please :smile:.

Also, will those settings be able to be applied on a per runtime basis? That would be awesome. Right now we use a wildcard that fortunately does not fail if there are no matches to deal with our three cases: no library, .so, and .dylib.

**Comment by cdmihai** [comment]
Doesn't this make it ambiguous what compilationOptions means? Is it compiler specific, or build specific? I would keep compilationOptions for only controlling the compiler, and then introduce flags into build for controlling build,so build could have a `--do-not-make-runnable` flag. Otherwise it gets ambiguous on when should something be in compilerOptions, and when should it be a verb flag.

In addition, I would also have build call publish in order to achieve its goals (using the --no-build command)

**Comment by piotrpMSFT** [comment]
@davidfowl what release are you targeting for this change?

**Comment by davidfowl** [comment]
RC2

**Comment by DamianEdwards** [comment]
This is covered by the work in #792
