### ISSUE TITLE
Preprocess files are beeing ignored

### ISSUE THREAD

**Issue by m0sa** [dotnet/cli#1812]
## Steps to reproduce

    dotnet new
    mkdir compiler
    mkdir compiler/preprocess
    echo "bang" > compiler/preprocess/test.cs
    dotnet restore && dotnet build

## Expected  behavior

The build should blow up, or warn that preprocessing is not supported, not just silently ignore stuff. What is the roadmap for preprocessing? There seems to be a distinct lack of information around this.

## Actual behavior

Build is successful, prepreocess sources are ignore, there are no warnings or errors.

## Environment data
`dotnet --version` output:

     .NET Command Line Tools (1.0.0-beta-001598)
     
     Product Information:
      Version:     1.0.0-beta-001598
      Commit Sha:  N/A
     
     Runtime Environment:
      OS Name:     ubuntu
      OS Version:  14.04
      OS Platform: Linux
      Runtime Id:  ubuntu.14.04-x64

**Comment by enricosada** [comment]
what are preprocess files? it's a dnx feature?

**Comment by mausch** [comment]
@enricosada yep, check out https://github.com/aspnet/dnx/issues/39 for a full description.

**Comment by m0sa** [comment]
Relevant sources in dotnet CLI master:
- https://github.com/dotnet/cli/blob/46fa840122cf23c3ec78a75c83fe9da03a625721/src/Microsoft.DotNet.ProjectModel/Files/ProjectFilesCollection.cs#L113

... and in DNX master:
- https://github.com/aspnet/dnx/blob/bfd9c678c9beba7470b65c3fd354769b3b22789d/src/Microsoft.Dnx.Compilation.CSharp/RoslynCompiler.cs#L103
- https://github.com/aspnet/dnx/blob/bfd9c678c9beba7470b65c3fd354769b3b22789d/src/Microsoft.Dnx.Compilation.CSharp/RoslynCompiler.cs#L142

**Comment by enricosada** [comment]
thx @mausch

**Comment by davidfowl** [comment]
Yea this feature is dead and isn't coming back unfortunately.

**Comment by m0sa** [comment]
@davidfowl this is big news to me. How is view precompilation going to work?

**Comment by mausch** [comment]
Please consider bringing this back. This and xplat are by far the most exciting features I'm looking forward to. `ICompileModule` has massive potential for reducing boilerplate in everyday C# code. I've even [started a project around it](https://github.com/mausch/CsDerive) basically implementing the equivalent of Java's annotation processors (which has been a feature of Java since **2006**!).
And the cool thing is, it's already implemented. You only have to copy the code from DNX, so why not?

**Comment by davidfowl** [comment]
The c# team are looking at implementing something similar called generators tho I'm sure what phase it's at.

/cc @jaredpar

**Comment by per-samuelsson** [comment]
> Yea this feature is dead and isn't coming back unfortunately.

No, really?! :cry: That's just a game-changer for the thing we're building, and we've build quite a lot on it since the launch of DNX.

So is there like any way right now to hook into the compilation process? Even if it's more low-level than than `ICompileModule` (including hooking into native bootstrapping)?

**Comment by m0sa** [comment]
@per-samuelsson https://github.com/dotnet/roslyn/issues/5561 seems to be the official discussion about the feature replacing this one

**Comment by per-samuelsson** [comment]
>  dotnet/roslyn#5561 seems to be the official discussion about the feature replacing this one

Thanks @m0sa. By chance I found that issue some hour ago and started reading uo on it (and linked issues) to see if I could grasp it, and see if it fit our needs. It's still some things to digest there for me. I hope it turns out well.

You pointing me in that direction, and when I saw you just posted there days ago, is helpful indeed, because then I know I'm likely reading at the right place. :smile:

**Comment by jaredpar** [comment]
The Roslyn source generator feature work is actually well under way.  The progress can be followed on this branch:

> https://github.com/dotnet/roslyn/tree/features/generators

**Comment by per-samuelsson** [comment]
@jaredpar 

Thanks. Those were new to me, and very valuable. Any kind of resources you have on this would be very welcome, as it's quite different from the thing we've implemented on top of `DNX/ICompileModule`, and we kind of need to reconsider our whole design from scratch.

**Comment by blackdwarf** [comment]
Given the above communication, I'm clsoing this issue.
