### ISSUE TITLE
No executable found matching command "dotnet-publish-iis" etc.

### ISSUE THREAD

**Issue by xatabhk** [dotnet/cli#1858]
## Steps to reproduce

   "tools": {
        "dotnet-publish-iis": "1.0.0-*",
        "dotnet-razor-tooling": "1.0.0-*",
        "dotnet-ef": "1.0.0-*"
    },

>dotnet restore
>dotnet ef
>dotnet publish-iis
## Actual behavior

No executable found matching command "dotnet-ef"
No executable found matching command "dotnet-publish-iis"

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001741)

Product Information:
 Version:     1.0.0-beta-001741
 Commit Sha:  622cb17d7c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64
[zaxitech_core_demo.zip](https://github.com/dotnet/cli/files/173349/zaxitech_core_demo.zip)

**Comment by blackdwarf** [comment]
@xatabhk did the restore operation finish succesfully?

**Comment by xatabhk** [comment]
@blackdwarf blackdwarf Yes. Here is a screenshot.
![no_tools_err](https://cloud.githubusercontent.com/assets/6814395/13852629/eeaa3222-ec9d-11e5-8581-b00d17b3da0e.png)

**Comment by blackdwarf** [comment]
@xatabhk can you share your `project.json`? I see from the screenshot that you are building for 4.5.1.

/cc @piotrpMSFT

**Comment by xatabhk** [comment]
@blackdwarf blackdwarf  project.json. Net450 or dnx451, the same result.
[project.txt](https://github.com/dotnet/cli/files/178385/project.txt)

**Comment by muratg** [comment]
cc @moozzyk who saw this when we updated to a newer CLI.

This looks like a regression.

**Comment by zumicts** [comment]
Using `dnxcore50` and get the same error.

**Comment by moozzyk** [comment]
Looks like if the application targets a different framework than the tool itself resolving the tool fails. (The  [SelectTarget](https://github.com/dotnet/cli/blob/rel/1.0.0/src/Microsoft.DotNet.ProjectModel/ProjectContextBuilder.cs#L388-L410) method returns null) 

I was able to make `dotnet-publish-iis` work it by modifying the target framework of the tool and the target framework of the app to match but it's totally wrong. My understanding the tools are always dnxcore50/netstandardapp1.x but my project can be net451 only. This means I can't run the tool in a net451 project even though it should not matter since the tool is not tied to the project.

**Comment by moozzyk** [comment]
@piotrpMSFT @blackdwarf - do you have any ETA for fixing or triaging this?

**Comment by DamianEdwards** [comment]
**ping**

**Comment by Eilon** [comment]
@piotrpMSFT @Petermarcu any status update on this?

**Comment by brthor** [comment]
Significant changes to this were checked in as part of #1920 

In the latest cli, tools are always resolved against the TfM netstandardapp1.5, in the future this will be netcoreapp1.5

**Comment by brthor** [comment]
I managed to repro this even with the latest bits, fix is in PR.

#2011
