### ISSUE TITLE
Auto RID is incorrect for uap10.0 packages

### ISSUE THREAD

**Issue by onovotny** [dotnet/cli#1896]
## Steps to reproduce
Create project.json with a uap10.0 target. Restore 

Repro here:
https://onedrive.live.com/redir?resid=B98D981155DF4D47!818874&authkey=!AEPXTFkv_F1lqNs&ithint=file%2czip

## Expected  behavior
Restore should succeed

## Actual behavior
```
error: System.Runtime.InteropServices.WindowsRuntime 4.0.1-rc2-23910 provides a compile-time reference assembly for System.Runtime.InteropServices.WindowsRuntime on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86. 
error: System.Runtime.WindowsRuntime.UI.Xaml 4.0.1-rc2-23910 provides a compile-time reference assembly for System.Runtime.WindowsRuntime.UI.Xaml on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86. 
error: System.Runtime.WindowsRuntime 4.0.11-rc2-23910 provides a compile-time reference assembly for System.Runtime.WindowsRuntime on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86. 
error: System.AppContext 4.1.0-rc2-23910 provides a compile-time reference assembly for System.AppContext on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86. 
error: Some packages are not compatible with UAP,Version=v10.0 (win7-x86). 
```

According to @ericstj, the `System.AppContext` is a known issue, but it seems the CLI tools are incorrectly using a Win7 RID.

## Environment data
`dotnet --version` output:
.NET Command Line Tools (1.0.0-beta-001752)

Product Information:
 Version:     1.0.0-beta-001752
 Commit Sha:  ec6cbad55b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14279
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by onovotny** [comment]
Split from here https://github.com/dotnet/corefx/issues/6603#issuecomment-195225605

**Comment by onovotny** [comment]
Latest bit:

```
error: System.Runtime.WindowsRuntime 4.0.11-rc2-23918 provides a compile-time reference assembly for System.Runtime.WindowsRuntime on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86.
error: System.Runtime.WindowsRuntime.UI.Xaml 4.0.1-rc2-23918 provides a compile-time reference assembly for System.Runtime.WindowsRuntime.UI.Xaml on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86.
error: System.Reflection.TypeExtensions 4.1.0-rc2-23918 provides a compile-time reference assembly for System.Reflection.TypeExtensions on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86.
error: Some packages are not compatible with UAP,Version=v10.0 (win7-x86).
```

**Comment by emgarten** [comment]
@onovotny auto RID infer will be removed from NuGet: https://github.com/NuGet/Home/issues/2114

Once you define a ``runtimes`` section in your project.json file containing the correct set of RIDs to restore NuGet will use these instead of the fallback rids it currently infers and restores for (win7-x86).

**Comment by onovotny** [comment]
Cannot do that since runtimes are for the whole thing-- I'm cross compiling:

Here's the project.json:
https://gist.github.com/onovotny/3b6b1493ee4f26277ec5

**Comment by emgarten** [comment]
RID infer is for the entire project.json also.

**Comment by onovotny** [comment]
I'm not sure what you're suggesting here? I don't want to specify a win8 runtime for the whole project.json for those when other targets would work on win7/unix/any?

**Comment by emgarten** [comment]
Runtimes cannot be specified on a per TFM basis currently. The auto RID here comes from the environment you are running dotnet restore on, it is unrelated to the TFM itself.

**Comment by onovotny** [comment]
Okay...so my real question is what's the solution to this and is there already an better issue to track this (or should there be one?)

I was guessing that auto-RID was the issue given the comments in the issue linked in the summary, but the end result is that I cannot successfully restore this project.json currently.

**Comment by emgarten** [comment]
It looks like the project.json above creates a nupkg with libraries for win81, wpa81, and uap10.0. RIDs are meant for apps/executables and I don't see an entry point here so I'm assuming it's not that. Correct me if I'm wrong and there is more involved here (I'm sure there is).  

My suggestion is to add ``"any": { }`` to your runtimes section. The RID will come from the consuming project, your portable library/nupkg here doesn't need any runtime assets. The RID information isn't put into the nupkg output, nupkgs only pivot on TFM (currently).

If you find some that restore still fails due to missing runtime assets you can add ``"include": "compile"`` to remove all runtime assets and the check. 

The project that consumes the output of the project you shared will restore with RIDs that bring in all the runtime assets needed to run your nupkg.

**Comment by onovotny** [comment]
You are correct in that this is just for a library. The linked solution has the full repro, just open up Rx.NET-New.sln and watch the restore progress/window. That's when I saw the errors.

I don't have any executables except the test project, and that targets `netstandardapp15` and `net461`. 

That's why this whole thing is confusing to me. I wouldn't expect to get those restore errors since those uap10.0 assets shouldn't be applicable to any executable/application in the solution.

**Comment by emgarten** [comment]
I see the confusion. Auto RID infer handles things correctly for new TFMs because they are split, your test project under ``netstandardapp15`` will restore RID graphs and that allows you to run tests. ``netstandard`` ignores all RIDs and does not create RID graphs because it is portable.

In your project auto RID infer is incorrectly restoring RIDs for all of the frameworks because they are not considered portable/compile only.

This will be easier once auto RID infer has been removed from nuget. Today there is no option to completely remove RID graphs for your project, which is why you'll need to use either the ``any`` RID or exclude runtime assets.

Overall this issue is correct, RID infer is wrong, but the RIDs here should be zero. By default this will be the case once this PR goes in:
https://github.com/NuGet/NuGet.Client/pull/391

**Comment by emgarten** [comment]
Auto rid has been removed.

**Comment by onovotny** [comment]
Sweet -- what CLI version would I see this change in? I'm on 1.0.0-beta-002024

**Comment by emgarten** [comment]
@onovotny that should have the fix. You can double check that sdk\1.0.0-beta-002022\NuGet.CommandLine.XPlat.dll is 3.5.0-beta-1068

Are the errors the same? Does project.lock.json contain RID specific target graphs?

**Comment by onovotny** [comment]
Yup, I have that xplat.xll version and the errors are the same..

```
errors in C:\Users\oren\Source\git\reactive-extensions-private\Rx.NET\Source\System.Reactive.Windows.Threading\project.json
    System.Runtime.WindowsRuntime.UI.Xaml 4.0.1-rc2-23925 provides a compile-time reference assembly for System.Runtime.WindowsRuntime.UI.Xaml on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x64.
    System.Runtime.WindowsRuntime 4.0.11-rc2-23925 provides a compile-time reference assembly for System.Runtime.WindowsRuntime on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x64.
    Some packages are not compatible with UAP,Version=v10.0 (win7-x64).
    System.Runtime.WindowsRuntime.UI.Xaml 4.0.1-rc2-23925 provides a compile-time reference assembly for System.Runtime.WindowsRuntime.UI.Xaml on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86.
    System.Runtime.WindowsRuntime 4.0.11-rc2-23925 provides a compile-time reference assembly for System.Runtime.WindowsRuntime on UAP,Version=v10.0, but there is no run-time assembly compatible with win7-x86.
    Some packages are not compatible with UAP,Version=v10.0 (win7-x86).
```
Easiest repro, use the attached solution and run `dotnet restore` on it.

https://onedrive.live.com/redir?resid=B98D981155DF4D47!822876&authkey=!AMOcAKcx4za69ug&ithint=file%2czip

**Comment by emgarten** [comment]
This was fixed in NuGet but it looks like dotnet restore does not allow for turning this off.
https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-restore/Program.cs#L39-L40

//cc @anurse

**Comment by anurse** [comment]
RID inference was removed in Preview 1. Is this issue still relevant? Please feel free to re-open if there are still issues with this.
