### ISSUE TITLE
Install script (bash) will repeatedly install the dotnet package even the same version already exists

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#1964]
## Steps to reproduce
1. Execute `./install.sh -c beta -d ./.dotnet` to install __dotnet__ to a local folder.
2. Execute the same command again.

## Expected  behavior
The command detects that the same version of __dotnet__ is already installed at the given folder therefore skip the second execution.

## Actual behavior
The tarball is downloaded again as well as the instllation.

## Environment data
`dotnet --version` output:

**Comment by eerhardt** [comment]
This repros on all platforms, Unix and Windows. The issue is we moved the .version file and the build scripts can no longer find it.

**Comment by eerhardt** [comment]
I think instead of having the scripts rely on the .version file, we should have `dotnet --version` return just the simple version number with no extra formatting.  And then the scripts can just call dotnet --version to get the version number. However it is implemented under the covers is no business of the scripts.

**Comment by krwq** [comment]
This should've solved it https://github.com/dotnet/cli/pull/2041
