### ISSUE TITLE
dotnet publish includes a lot of unncessary (and non-referenced dependencies)

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2058]
## Steps to reproduce
dotnet new
dotnet restore
dotnet build
dotnet publish

## Expected  behavior
The contents of the publish folder should just be the app (there are no additional dependencies outside of the shared framework)

## Actual behavior
A ton of additional dependencies are dropped.

## Environment data
`dotnet --version` output:
1.0.0-beta-001980

**Comment by joepeer** [comment]
I'm expecting this kind of behavior through a dotnet publish.  But I'm not getting it.
See [2205](https://github.com/dotnet/cli/issues/2045)
I'm expecting an exe, the runtime and all dependencies to be present.  So I can deploy to another Windows machine that has  nothing "net core"

Is dotnet publish will only now give something runnable through dotnet run?

**Comment by piotrpMSFT** [comment]
@joepeer in order to make your app standalone, you must specify "runtimes" in your project.json file so restore can get the packages for your target environments, build can produce the right layouts, and publish can take advantage of these artifacts. This is "standalone" mode.

Without a runtimes section publish creates a portable application which requires a Shared Framework to be installed for execution, but allows your app to run anywhere that a Shared Framework is available.

**Comment by piotrpMSFT** [comment]
@jeffschwMSFT still seeing this? I believe it's fixed.

**Comment by jeffschwMSFT** [comment]
Now that the sharedfx work has worked through, I am seeing the expected behavior for publish (only my components and the ones that my app uniquely requests).

**Comment by GuardRex** [comment]
@jeffschwMSFT Side note FYI to you, since we may both be working with standalone apps ...

I compiled a standalone test app this morning with the `NETStandard.Library` meta-package, and published output came to 50.6MB. I swapped that for the shard framework meta-package, `Microsoft.NETCore.App` (which brings in, among a lot of other things, `NETStandard.Library`), and the outputs came to 57MB, so there was a ~6.4MB increase in app footprint with the larger, shared framework meta-package.

Samples, since they are of the shared app variety, target the shared app metapackage, which (at least here) isn't necessary for the standalone app. I mention all this based on your OP concern about "a lot of unnecessary ... dependencies." I have the same concerns.
