### ISSUE TITLE
dotnet run -h doesn't provide any run-specific help

### ISSUE THREAD

**Issue by ljw1004** [dotnet/cli#2172]
## Steps to reproduce

`dotnet run -h`

## Expected  behavior

It should print information about the "run" command

## Actual behavior

It only prints the same overall information that I get from "dotnet -h"

## Environment data
`dotnet --version` output: 1.0.0-beta-002133 on OSX

**Comment by ljw1004** [comment]
@livarcocc any reason why closing? I really struggled to know how to pass command-line arguments to "dotnet run". I didn't know how to pass arguments to the "run" command itself, vs arguments to my own "static void Main(string[] args)"

**Comment by livarcocc** [comment]
Because if you do dotnet run -h now it will show help information relevant to run:

✘ ✝  ~/Documents/git/temp  dotnet run -h
.NET Run Command

Usage: dotnet run [options] [[--] <arg>...]]

Options:
  -h|--help           Show help information
  -f|--framework      Compile a specific framework
  -c|--configuration  Configuration under which to build
  -p|--project        The path to the project to run (defaults to the current directory). Can be a path to a project.json or a project directory

**Comment by ljw1004** [comment]
Oh great thanks!
