### ISSUE TITLE
Random failure on ASP.NET ci machine to do with file in use

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#2241]
```
[xunit-test] The process cannot access the file 'D:\b\w\2fd214bda56c4e65\src\Microsoft.AspNetCore.Mvc.Core\obj\Release\netstandard1.5\.SDKVersion' because it is being used by another process. 
```

/cc @cdmihai @livarcocc

**Comment by davidfowl** [comment]
We're running `dotnet test` in parallel. Seems like this change https://github.com/dotnet/cli/commit/f14b4cbd3d04b1846208a5f31f811adf26a6bc45 now makes it more likely to fail.

**Comment by cdmihai** [comment]
Can you please include the entire stack trace for that exception?

It looks like multiple tests are building into the same output directory. Which will of course fail due to the same file being open for write (and if it does not race on the .version file, then it could race on the intermediate response or the csc response file, or the compiler outputs).

**Comment by livarcocc** [comment]
In the CLI, we copy the files to a folder named after the test being run to avoid this sort of issue. Could you guys do something similar?

**Comment by piotrpMSFT** [comment]
Seems like this got solved. Please reopen if still an issue.
