### ISSUE TITLE
Throw an error when an invalid value for a script is passed in the project.json

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#2257]
## Steps to reproduce

Modify your project.json and add a "scripts": true to it.
Try to do build or some other action that would cause the project.json to be loaded by the CLI
## Expected  behavior

This should throw an exception saying that this is an invalid project.json and point to what the error is.
## Actual behavior

It silently loads the project.json and ignores the scripts property.

**Comment by piotrpMSFT** [comment]
@anurse @pakrym 

The existing ProjectModel implementation, to which @livarcocc added test as part of another change, is fairly inconsistent in its handling of JSON. In particular, when dealing with unexpected values. Some examples:

* When string arrays are expected, some properties are allowed to have only string [] values. Other properties accept string values as well, treating them as single-element arrays.
* When a particular type is expected [instance, array, object] but not found, some property readers will assume the value to be null while others will throw.

Before we RTM we need to fix these discrepancies and provide a consistent, predictable experience. At the moment, the intent is to be permissive in allowed values and strict about unacceptable values. So:
* Treat instance values as single-element arrays
* Throw on invalid values [e.g. string when expecting object]

Since you were both strongly involved in the current implementation it would be great to get your thoughts on causes for the inconsistent behavior and the intended fixes.

@blackdwarf there will be breaking changes as a result of fixing the surface area of this library. We will need to communicate this early and aggressively.

**Comment by pakrym** [comment]
There also is https://github.com/dotnet/cli/pull/2248 work, I think we should finish that spec and base all changes on it.

**Comment by blackdwarf** [comment]
@piotrpMSFT what will be the breaking changes?

**Comment by blackdwarf** [comment]
Since we are moving to MSBuild and csproj, this issue is no longer applicable, and I will close it as such. Whatever validation is done for various tasks in the csproj, the MSBuild is the place where they should happend.
