### ISSUE TITLE
Installer is not removing prior installs of dotnet cli

### ISSUE THREAD

**Issue by GuardRex** [dotnet/cli#2261]
![capture](https://cloud.githubusercontent.com/assets/1622880/14263588/f755e240-fa80-11e5-91fb-04808d169490.PNG)

I think I asked about this elsewhere and was told this is "Ok," but is that really correct? Shouldn't these prior versions be removed as we go along with `rel/1.0.0` installers?

**Comment by piotrpMSFT** [comment]
This is by-design.

A core outcome of the Shared Framework work is that we want the Shared Framework and CLI to update in-place as infrequently as possible. When we ship 1.0.0 and then 1.0.1 these will both install side-by-side with one-another. This enables folks to continue running against their original dependencies instead of being broken irreparably by updates.

Given that this is a very new model, we decided to turn on the same mechanism for all builds so we can get some experience with how it behaves. This has already identified a number of concerns in the original implementation and these have been fixed. 

At the moment we plan to leave 1.0.0 in this state up to release. This lets us both get experience with the model and ensure that the `vNext` mechanics are in place before we ship `vCurrent`.

We're quite curious in feedback about this change. The balance between stability [everything side-by-side], security [some updates in-place], and footprint [just one version] is tricky and there's not a silver bullet. I'm going to close the issue since there's nothing to fix at the moment, but let's use it to capture folks' opinions nonetheless!

**Comment by GuardRex** [comment]
That's cool, but there will be standalone people, and a checkbox in the installer to "Remove prior installs" will save a bunch of trips to `Programs and Features` to get rid of the old ones for us standalone folks.

That could have been put into place even during this period for RC2-nightly people, like me. Installing these is a daily thing; and as you can see by my screenshot, I have to go in there every few days and kill off the old ones.

I'm fine. I just wanted to check with you on it. Thanks.
