### ISSUE TITLE
Audit the list of Ubuntu runtime dependencies - currently 44

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2308]
We should audit the list of 44 libs required to run on Ubuntu with the goal of reducing the list to a more manageable set (eg. Windows has 1, Mac has 1, and Centos has 9).

Current list of dependencies for Ubuntu:
libc6
libedit2
libffi6
libgcc1
libicu52
liblldb-3.6
libllvm3.6
liblttng-ust0
liblzma5
libncurses5
libpython2.7
libstdc++6
libtinfo5
libunwind8
liburcu1
libuuid1
zlib1g
libasn1-8-heimdal
libcomerr2
libcurl3
libgcrypt11
libgnutls26
libgpg-error0
libgssapi3-heimdal
libgssapi-krb5-2
libhcrypto4-heimdal
libheimbase1-heimdal
libheimntlm0-heimdal
libhx509-5-heimdal
libidn11
libk5crypto3
libkeyutils1
libkrb5-26-heimdal
libkrb5-3
libkrb5support0
libldap-2.4-2
libp11-kit0
libroken18-heimdal
librtmp0
libsasl2-2
libsqlite3-0
libssl1.0.0
libtasn1-6
libwind0-heimdal

**Comment by brthor** [comment]
This list was generated by using ldd on the runtime/corefx binaries themselves.

The dependency set can likely be reduced by using a set of parent packages (this list represents the full set of transitive dependencies).

CentOS has not gone through the same process to get the required packages, so that is likely a gap. On OS X (as I understand it) everything is already on the box except libssl.

cc @ellismg

**Comment by blackdwarf** [comment]
@brthor @ellismg did we do this work?

**Comment by piotrpMSFT** [comment]
Moved to core-setup repo
