### ISSUE TITLE
dotnet publish --nocompile  

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#233]
dotnet publish should support being plugged into a build orchestration workflow wherein the dotnet-compile step took place earlier and need not be repeated.

**Comment by piotrpMSFT** [comment]
codesign. described just above.

**Comment by dsplaisted** [comment]
On MSBuild, we would also like to be able to do a publish without compilation.  In our case, we want to do it on a project.json file that doesn't even include any source files.  We'd like to be able to create NuGet packages for the different components of MSBuild, list them in a project.json, and then do a restore and publish to resolve all the dependencies and publish everything to a folder.  In this case, the app entry point(s) would come from NuGet packages instead of being compiled from source.

If I try to do this today, I get this error when I run dotnet publish: `deploytest 1.0.0 does not have an entry point defined.`

**Comment by davidfowl** [comment]
Why are you using dotnet publish at all? Are you just using it to gather files?

**Comment by weshaggard** [comment]
>Are you just using it to gather files?

Yes. We have the same scenario as @dsplaisted for bootstrapping the corefx repo. We want to use it to gather the right files from the nuget packages so we can get them into a flat directory for running  other .NET Core based tools. 

cc @joperezr

**Comment by piotrpMSFT** [comment]
@anurse fixed [at least part of] the issue @dsplaisted was seeing in #348. Is that scenario still blocked?

**Comment by livarcocc** [comment]
The output path fix should be placing the binaries in the right place now. Closing. If you guys still need something to happen here, please, re-open.

**Comment by weshaggard** [comment]
@livarcocc Perhaps I'm missing something but how does change #348 add the --nocompile option? It looks like it adds a way to publish a library but not a way to actually publish without compile, which is still an interesting scenario for publishing just a set of dependencies. We do that for corefx's BuildTools for example.

**Comment by piotrpMSFT** [comment]
That is separate from the intent of this issue, but we should track it. This one was intended to enable a separate compile (and sign) step which @livarcocc recently enabled.
