### ISSUE TITLE
After first-time project creation, we get: error occurred attempting to run the project model server process

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#2427]
## Steps to reproduce
Dev14 U2 + AspNetCoreTools RC2
1. New ASP.NET Core web app > Web Application
 
## Expected  behavior
Project to create

## Actual behavior
When creating a project for the first-time, sometimes we run into this dialog

![image](https://cloud.githubusercontent.com/assets/8246794/14469910/a47c3670-009b-11e6-9e46-cb25161426a2.png)

## Environment data
`dotnet --info` output:

**Comment by muratg** [comment]
@balachir does this happen only sometimes (and if so, how often)?  Does the client side have retries?

**Comment by troydai** [comment]
`dotnet` may not be started, or when the VS tries to connect to the `dotnet` the process hasn't fully started yet.

**Comment by balachir** [comment]
A few of us have run into this. After installing the RC2 tooling bits, when creating the project for the very first time, the dialog pops up. If you hit OK and try creating a project again, then we don't see this issue anymore, so it's a little difficult to repro.

I don't think we have retries on the client-side. /cc: @BillHiebert

**Comment by troydai** [comment]
The issue requires a newly installed VS. @balachir is building a test environment for me.

**Comment by piotrpMSFT** [comment]
@troydai what's the status of this issue?

**Comment by troydai** [comment]
@BillHiebert and @balachir has been investigating this since last week. They're not able to repo this on any machine other than a slow Maddog test machine. These is little I can do at this point. 

@BillHiebert and @balachir may have more to update.

**Comment by balachir** [comment]
We are continuing to see this reported in the tests that our China team is running with the RC2 tooling bits using the Maddog machines. Yesterday, I was able to reproduce this on one of my RC2 VMs with a checkpoint, I shall try reverting to that checkpoint to see if that gives a consistent repro. Hopefully, we'll get a repro and that will help us make progress on this investigation.

**Comment by piotrpMSFT** [comment]
@balachir are we any closer to a repro? If it's so inconsistent, would you ship RC2 without addressing this issue?

**Comment by troydai** [comment]
Here's what we found now. 

The issue happens for only:
1. VS is just installed;
2. Create a new web project

Research the log captured by Process Monitor during the repo, we found that `dotnet.exe` process terminates in 1 second after it is started by Visual Studio. The exit status is -1.

It doesn't repo afterwards. 

It doesn't repo if between step 1 and 2 open a command line and run `dotnet --version`. It seems like running `dotnet` for the first time somehow initialize or set up something.

It doesn't repo if we set `COREHOST_TRACE=1` to capture corehost log.

The problem is likely lied in the `dotnet` muxer and/or in the native code.

**Comment by balachir** [comment]
@piotrpMSFT, we are seeing this issue reported by our China testing team pretty consistently with Maddog machines, and by a few others locally when they have installed the tooling build on less powerful machines. So we should definitely address this for RC2.

Adding to what Troy mentioned above, this one has been a tricky one to investigate because it reproduces the very first-time only. Troy and I did some investigations on one of my VM where I could repro and had saved a checkpoint after installing the RC2 tooling but before starting up VS. I've asked the China team to setup some more Maddog machines tonight as well, which are likely to reproduce the issue. So we should be able to make some more progress on the investigation tomorrow.

**Comment by troydai** [comment]
@piotrpMSFT please advice who we can talk to regarding to the symptom. It is fairly clear now it is not a problem of dotnet-projectmodel-server itself. It more likely a dotnet.exe or muxer issue.

**Comment by piotrpMSFT** [comment]
@schellap can help if this is a dotnet.exe issue.

**Comment by piotrpMSFT** [comment]
@troydai @balachir do we know if dotnet.dll is being loaded? Are any tools being referenced by the project? Does CLI produce any command line output?

**Comment by schellap** [comment]
> than a slow Maddog test machine

> It doesn't repo if we set COREHOST_TRACE=1 to capture corehost log.
> The problem is likely lied in the dotnet muxer and/or in the native code.

It could be a muxer issue but just setting this logging environment shouldn't be a reason to conclude so. It sounds from the above statements it is a timing issue.

Also, why is the process name in the alert box a version number? `"attempting to run a project model server process (1.0.0-rc2-002345)"`

**Comment by piotrpMSFT** [comment]
@schellap just told me that @BillHiebert has taken on this issue.

**Comment by BillHiebert** [comment]
We suspect this is a timing issue. After starting the project model server, VS waits up to 5 seconds to make the tcp connection. On slow VM's, we have noticed that the first run of dotnet.exe is really slow - haven't investigated why.  Most likely it is timing out, in which case the process is terminated.  We've increased the timeout and we should know in the next day or so.

**Comment by livarcocc** [comment]
@BillHiebert Did increasing the time out solve this problem?

**Comment by muratg** [comment]
Also, did anyone repro this on a *second* project creation? If it's just a time out problem, wouldn't it occasionally fail in the second time too? (AFAIK it doesn't repro after the first time.)

**Comment by piotrpMSFT** [comment]
This has been open for two months without repro. Closing.

**Comment by superlogical** [comment]
I just had this happen after installing the `1.0.0-preview3-003161` of the CLI

````
c:\dev>dotnet --version
1.0.0-preview3-003161
````

**Comment by radams0x** [comment]
I get this exact error on the 1.0.0 RTM: The following error occurred attempting to run the project model server process (1.0.0-preview2-003121) No connection could be made because the target server actively refused it

I get it for an existing project which I'm trying to upgrade from RC2. The machine is a Windows 10 VM running in Parallels on an extremely fast Macbook Pro Retina 16GB  - I would be awfully surprised it it was performance related.

**Comment by MikeBreytenbach** [comment]
Switching off Windows Firewall seems to solve this for me

**Comment by CrashRecovery** [comment]
I have created two Web application projects and opening either one of them results in this error message:

![image](https://cloud.githubusercontent.com/assets/24959896/21720182/c6b7b1ce-d3ef-11e6-92a1-5d44f956be2f.png)

I've tried shutting down and restarting Visual Studio; also tried re/installing the CORE sdk.  Neither of those worked to resolve the problem.  I'm going to try running from command line next but decided to post here because I just downloaded tools and started attempted work on a web app and this problem is still occurring in Jan 2017.

**Comment by CrashRecovery** [comment]
Tried "dotnet run" at command line with default working directory.  This ran, and text output included "Welcome to .Net Core" and "Configuring..." and then took quite a while to "initially populate your local package cache".

Once this was done, tried reopening project and there was no error message and was able to run sample web application under debug / diagnostics session.  I'm not sure this will be the last I see of the error, but hoping so.

**Comment by anupghanshala** [comment]
I am facing same issue as above & still unable to resolved it

**Comment by livarcocc** [comment]
If you are on VS2015 and you have a 1.0.1 or 1.0.0 (or higher) CLI installed on the box, you need to set you global.json to use a preview2 CLI. The project-model-server was needed for project.json and since the latest CLI no longer supports project.json, that tool is no longer available.

**Comment by radams0x** [comment]
Thanks livarcocc - could you give us the specific global.json edits needed? Thanks!
