### ISSUE TITLE
Generalize project.json "scripts"

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#244]
Rather than specific lifecycle events, we could have a more general model where **every** `dotnet-[command]` command (**where a project context is available**) runs the following sequence of events:

1. `pre[command]` script in the `project.json`
2. `[command]` implementation
3. `post[command]` script in the `project.json`

Open questions:

1. Should the driver do this or the individual commands? If the driver, that means the driver has to be aware of project context. It also wouldn't know which commands are intended to be used in a project context so some weird things could happen, for example running `dotnet init` in a folder with a `project.json` might run a `preinit` script in that project, if one existed. My feeling is that the commands should do it (via a simple wrapper)

2. Do all the events share the same invocation model? For example, currently the `pre/postcompile` events run once **per compilation** not **per invocation**, which means they run for each framework that is built in a cross-compilation model. They also provide different variable expansions for different contexts. How important is it to try to preserve this in a general model?

3. Should we restructure the project.json syntax? Maybe something like this:

```json
{
    "events": {
        "compile": {
            "before": [ "echo some script" ],
            "after": [ "echo some script" ]
        }
    }
}
```

/cc @piotrpMSFT @davidfowl

**Comment by Petermarcu** [comment]
As you mention, these commands are going to be project/context specific. In different contexts, you may want the script to do something completely different. In that case would I have to have the [pre]command inside the context so the right one is run. That whole route seems very complicated.
We also need to consider the impact of supporting these scripting events on usability within the context of a declarative build system. Do the inputs and outputs of these scripts flow in some way? Are there issues with incremental that start to crop up?

**Comment by krwq** [comment]
I think that the idea is good although I think that project should represent a project while set of a commands should be contained in the script next to it. I think it is better to recommend to have project.json + build.bat/sh

**Comment by tpetricek** [comment]
I think this would be very nice feature to have. The generalization sounds like a nice idea, but if it was making the implementation too complex, I think having the dnx-style scripts would cover most use cases.

I started looking into porting www.fssnip.net to CoreCLR using Suave and in order to be able to run the site using just `dotnet restore` and `dotnet run`, we would need to invoke JavaScript minification from a post-restore script (so that we can restore Node.js components first).

I see this issue has not been updated in a while - is this still planned? I think running some commands in post-restore (e.g. to minify JavaScript) will be a very common use case in any vNext web application.

**Comment by Krzysztof-Cieslak** [comment]
:+1: for @tpetricek. It would be nice feature to have not only from JavaScript / Node point of view, but basically any client side tooling - for example client side applications written in Elm. Adding this would let us to have sane, unified build pipeline.

**Comment by am11** [comment]
:+1: 

Please also consider exposing msbuild's `AfterBuild` event through cli script; which is different than `[post/pre][compile/build]` events provided by cli/dnx as latter get executed *before* MSBuild's last `_CopyFilesMarkedCopyLocal` task.

When MSBuild builds Azure cloud service project (`ccproj`), if the worker/web project is `xproj` it tries to local produced assembly in `%project:BuildOutputDir%`, while the actual dll resides in:
`%project:BuildOutputDir%\\%build:Configuration%\\%build:TargetFramework%`. Hence MSbuild fails.

As a work around I have (dnx version with rc1):

```json
"postbuild": [
      "echo \"copying \\\"%project:BuildOutputDir%\\%build:Configuration%\\%build:TargetFramework%\\*.*\\\" to \\\"%project:BuildOutputDir%\\\"",
      "copy \"%project:BuildOutputDir%\\%build:Configuration%\\%build:TargetFramework%\\*.*\" \"%project:BuildOutputDir%\"",

      "echo \"copying \\\"%project:BuildOutputDir%\\%build:Configuration%\\%build:TargetFramework%\\*.*\\\" to \\\"%project:BuildOutputDir%\\..\\..\\obj\\%PROJECT_NAME__%\\%build:Configuration%\\\"",
      "copy \"%project:BuildOutputDir%\\%build:Configuration%\\%build:TargetFramework%\\*.*\" \"%project:BuildOutputDir%\\..\\..\\obj\\%PROJECT_NAME__%\\%build:Configuration%\""
    ]
```

Now when I build the solution with this setup, on first attempt MSBuild fails on building ccproj (because postbuid executed before `_CopyFilesMarkedCopyLocal`), but the subsequent build passes (literally Ctrl+Shift+B twice on a clean solution succeeds).

With that being said, I believe there are many "After Build [x]copy" scenarios in user land that would prefer `afterbuild` over `postcompile`.

**Comment by ah-** [comment]
I'd also really like to see pre/postrestore. See https://github.com/NuGet/Home/issues/2260 for the corresponding NuGet issue.

**Comment by apawsey** [comment]
I'd like to add my two (more like 50 now I've actually finished) cents as I've been struggling for days with the current scripts functionality with dnx and dotnet.  And there is at least one useful nugget of information in here, I promise :)

I think the generalized approach is excellent, and it must be down to each command to define it's available scripts.  Your (not sure of the correct terminology here) second level command architecture, lends itself specifically to a plug-able pipeline.  You have the build command, then the pack which invokes the build, and surely there's no reason why there couldn't be a future publishToNuget command, which will invoke pack, which will invoke build... and so on.  Therefore surely, it would be important to separate the definitions and leave it up to each command to define what it can and can't run, what variables are and aren't supported etc.

Secondly, I would propose, it's up to the command to define when those scripts run.  For example, if the compile command supports a precompile script, you would expect it run before every compile that occurs.  (Unless I'm mistaken) the default behaviour of the compile command is to compile the project for all frameworks, for a given configuration (actually not sure what that defaults to though).  Therefore if my project specifies 3 frameworks, I expect 3 precompile scripts to run.  However then the command could also support a precompileprocess (terrible name I know, but sure Microsoft has a department for this kind of problem :) ) that would run before anything.  Therefore the execution would be in weird pseudo code:

[precompileprocess script]
for each framework in configuration
   [precompile script]
   compile
   [postcompile script]
end
[postcompileprocess script]

Crucially, this model is only for the compile command, not necessarily for any other.

Finally, one of the most important things I've experienced, is each command, and possibly each step within the command, must reinitialize it's context as it executes  (this also implies, the commands should actually share as little context as possible, also implying the inputs/outputs do not flow).  I say this because I wanted to add a prebuild command to bump the build number, which involves updating the version tag in the project.json.  However the project.json was already read as the whole build process started, therefore although my build number gets bumped, the change isn't noticed, and the build output has the build number from before the prebuild executed.

This also makes everything fairly easy to document, as each command is documented separately, and where there is a call from one to the other, you can just direct people to that commands documentation.

My apologies for the lengthy feedback, but as I said, I have been battling for days with various build processes that I've been trying to make work with dnu and dotnet, and obviously there's a bit of frustration built up here!  (phew)

Hopefully at least something in here is useful to someone.

Thanks,
Adam.

(extra note: as a matter of general pattern and best practice, I would suggest, that where commands wrap other commands, there should be the option to run that command without the internal one.  eg: the --no-build option for pack, so if there was a future publishToNuget it should also have a --no-pack option)

**Comment by apawsey** [comment]
Should also note, I am happy to put my code where my mouth is, and contribute to this.  Not sure how much outside contribution there is in the cli project.

**Comment by dazinator** [comment]
`postpack` is currently declared in the project.json schema, but when I run a `dotnet pack` it doesn't appear to run (preview 2). Is this correct?

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
