### ISSUE TITLE
Installing CLI windows installer makes a 'swidtag' folder

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#2451]
## Steps to reproduce
Install https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe

## Expected  behavior
I shouldn't have a "swidtag" folder under C:\Program Files\dotnet

## Actual behavior
I have a "swidtag" folder under C:\Program Files\dotnet.  It has one file:
Microsoft .NET Core CLI for Windows (1.0.0.002357 beta).swidtag

```xml
<?xml version="1.0" encoding="utf-8"?>
<SoftwareIdentity tagId="wix:bundle/2687D5B8-E184-4219-950D-26C192C39A58" name="Microsoft .NET Core CLI for Windows (1.0.0.002357 beta)" version="1.0.0.2357" versionScheme="multipartnumeric" xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd">
  <Entity name="Microsoft Corporation" regid="microsoft.com" role="softwareCreator tagCreator" />
  <Meta persistentId="wix:bundle.upgrade/394AD2FB-57A6-6288-4348-C1CB264A5559" />
</SoftwareIdentity>
```

/cc @robmen

**Comment by robmen** [comment]
Software ID Tags (swidtags) are defined in the ISO-19770-2 spec. They are being required by (typically large) entities (think companies and governments) to help manage software. Per the spec the tag should be installed in a "swidtag" folder under the location where the software is installed.

I haven't kept up with the install location of dotnet/cli (so that could be wrong) but otherwise the data looks correct to me.

**Comment by robmen** [comment]
@piotrpMSFT I believe this can be closed.
