### ISSUE TITLE
SDK can't be uninstalled

### ISSUE THREAD

**Issue by weidazhao** [dotnet/cli#2464]
## Steps to reproduce
1. Install the latest .NET Core SDK Installer x64.
2. Uninstall it from "Programs and Features".

## Expected  behavior
Shared host, shared framework and SDK should be all uninstalled.

## Actual behavior
Shared host and shared framework gets uninstalled, but SDK is left.

**Comment by krwq** [comment]
cc: @Sridhar-MS

**Comment by Sridhar-MS** [comment]
@weidazhao Can you give more details?
- CLI version
- OS
- Any previous installation of CLI?

**Comment by weidazhao** [comment]
CLI version: 1.0.0-rc2-002374
OS: Windows 10
Any previous installation of CLI? Yes, I installed previous versions but uninstalled them before installing the new ones.

**Comment by Sridhar-MS** [comment]
@weidazhao I am not able to repro this on my windows 10 machine. Can you provide additional info?
Run this command to uninstall the CLI
`dotnet-dev-win-x64.1.0.0-rc2-002374.exe /uninstall /log uninstalllog.txt` and attach the uninstalllog,txt.

**Comment by weidazhao** [comment]
No longer repro after I ran the command :(  I will close the issue for now. If I can find a stable repro, I will reopen the bug. Thanks.

**Comment by weidazhao** [comment]
I tried 2378 and it seems to repro again.

[uninstalllog.txt](https://github.com/dotnet/cli/files/218202/uninstalllog.txt)
[uninstalllog_000_dotnet_host_win_x64.1.0.0_rc2_002378.msi.txt](https://github.com/dotnet/cli/files/218203/uninstalllog_000_dotnet_host_win_x64.1.0.0_rc2_002378.msi.txt)
[uninstalllog_001_dotnet_sharedframework_win_x64.1.0.0_rc2_3002378.msi.txt](https://github.com/dotnet/cli/files/218201/uninstalllog_001_dotnet_sharedframework_win_x64.1.0.0_rc2_3002378.msi.txt)

**Comment by piotrpMSFT** [comment]
@weidazhao I wonder if this is an expectations issue

SDK depends on Shared Framework which depends on Host. When you uninstall the SDK it is intended to remove ONLY the SDK pieces and not the framework nor the host. This is because the SDK is one consumer of the Fx, while you may accumulate others [e.g. by installing apps]. When uninstalling, it's the user's decision if they want to remove these components. We can't do it for them because we don't know that we won't break running applications.

We thought about using mechanisms like ref-counting + installer magic but chose not to, for a number of reasons:
- we want to have a consistent cross-platform experience. Installer magic is very platform specific
- we want for x-copy deployable apps to be a first-class experience. this makes ref counting impossible since you cannot depend on the ability to produce machine-wide state
- we have experience with such mechanisms in the past. unfortunately, folks typically don't make their installers uninstall-proof until after users report being broken

Given that context, is this still a bug?

**Comment by weidazhao** [comment]
@piotrpMSFT , I believe what I saw was opposite: shared FX and shared host got uninstalled, but SDK didn't.

**Comment by Sridhar-MS** [comment]
@weidazhao A lot of fixes went into the windows installer last couple of weeks. Please try with the latest builds - https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0-preview1-002700/dotnet-dev-win-x64.1.0.0-preview1-002700.exe and reopen the issue if you are still facing it.
