### ISSUE TITLE
Restore should happen automatically

### ISSUE THREAD

**Issue by sokket** [dotnet/cli#2468]
## Steps to reproduce
1) Have any project using dotnet CLI
2) Change project.json
3) run dotnet build

## Expected  behavior
The CLI knows that a restore needs to happen since an error is thrown; the CLI should then do the restore automatically rather than do an outdated build and probably fail.

## Actual behavior
The CLI throws a warning but then tries to compile with outdated information

## Environment data
`dotnet --info` output: 
.NET Command Line Tools (1.0.0-beta-002173)

Product Information:
 Version:     1.0.0-beta-002173
 Commit Sha:  b3e8612812

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by enricosada** [comment]
pls dont add too much magic, not everything has the same workflow.

maybe i need to run `dotnet restore -f /path/to/my/packages` or other command line args, instead of plain `dotnet restore`.

`restore` it's a separate step from `build`. that's it, is not too bad
And the `build` is already too entangled to nuget (the `restore`), and is a pain

**Comment by blackdwarf** [comment]
Dupe #1742
