### ISSUE TITLE
Shared Framework Does Not Appear to be Pre-Compiled

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#2476]
Version: 1.0.0-rc2-002357

The shared framework does not appear to be pre-compiled, which results in long build times - 7.543 seconds in my measurements for a Hello World console app.

The compilation processes themselves are spending 90% of their time in the JIT.

**Comment by gkhanna79** [comment]
@brthor PTAL. 

@brianrob Where are the non-compiled binaries coming from? Shared folder or SDK folder?

CC @JohnChen0 @schellap

**Comment by brthor** [comment]
The sharedfx directory should be crossgen'd, but we rename them to eliminate the .ni.

Any binaries in the sdk directory are not currently crossgen'd however.

**Comment by brianrob** [comment]
SDK has some DLLs that are loaded and contents JIT compiled.  These (or at least some of them) should be pre-compiled.

When I originally created this issue, we hadn't confirmed that the DLLs in shared were being properly crossgen'd.  As of now, I believe that @JohnChen0 has confirmed that they are, but at a minimum, Roslyn has partial NGEN enabled, so that's where some of the non-generics JIT time is coming from.

**Comment by piotrpMSFT** [comment]
@brianrob @JohnChen0 we need automation for validating that our payloads are appropriately crossgen'd. This needs to work across platforms. Once we have this we'll add a test and we'll enforce that it's passing. Can you help?

**Comment by gkhanna79** [comment]
@piotrpMSFT SharedFX is being compiled but CLI is carrying some IL binaries, due to explicitly overriding packages in SharedFX, that come into play and get JITted resulting in the slowdown. Is there a plan to address that?

**Comment by brianrob** [comment]
@piotrpMSFT and @gkhanna79, I think that both of the items that you propose should be done.

1. @gkhanna79, @JohnChen0 it would be good to have a way to confirm that crossgen succeeded, but I suspect the definition of succeeded is complicated.
2. @piotrpMSFT, it would be good to make sure that the CLI is always targeting the shared FX when a dependency exist in the shared FX.  Right now, it appears that at least some of Roslyn is app-local because the version doesn't match what's in the shared FX.  Would it make sense to have a guard against using a non-sharedFX version of a package that exists in the shared FX for CLI?  This would ensure that there aren't performance regressions due to the fact that the app local binaries are not pre-compiled.

**Comment by JohnChen0** [comment]
@piotrpMSFT @brianrob At the minimum, running crossgen.exe can be considered successful if the return status is 0. A better definition of succeeded is more complicated, as @brianrob suspected.

**Comment by lt72** [comment]
As much as defining success is hard, adding diagnostics may not be not so hard. Since there is a large investment in crossgen tooling, it would definitely be advisable to add the ability to log what methods get compiled (or viceversa, or both) to the crossgen tool, as well as adding the ability to dump what methods are compiled in a tool like nidump. 
That way it would be much easier to understand where things go wrong when we need to.

**Comment by JohnChen0** [comment]
The difficulty is not in adding diagnostics, but in determining what is the right set of diagnostics. Currently, CrossGen is already generating a large amount of diagnostics, but most of the users simply ignore them. We could turn every warning into a fatal error, in order to force users to fix every warning, but our past experience has been some warnings can be hard to fix in some scenarios.

Even if we can make CrossGen more strict in disallowing errors, there can still be issues that slip through. One thing we just found out today is some of the assemblies used by Roslyn have partial NGen flag turned on. Partial NGen had been used in Visual Studio to reduce address space usage, but is probably undesirable in CLI. Of course, CrossGen can't tell whether the partial NGen flag was turned on intentionally or by accident.

Of course, good diagnostics are important. But we should take the time to define what are the right diagnostics, instead of spewing out everything we can think of.

**Comment by piotrpMSFT** [comment]
Partial NGen is disabled and Shared Framework is NGen'd
