### ISSUE TITLE
Add dnxcore50 imports back to dotnet new for RC2

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#2499]

**Comment by piotrpMSFT** [comment]
Do we have 'official' `default imports`?

**Comment by Petermarcu** [comment]
There is another conversation @blackdwarf is driving to define what those should be. At this point, it appears the only real "safe" import we can add is dnxcore50. PCL tfm's have side effects that need to be better understood.

**Comment by blackdwarf** [comment]
@Petermarcu @piotrpMSFT yup. :)

**Comment by piotrpMSFT** [comment]
so is the ask to add an import for dnxcore50 for now, then wait for subsequent issues?

**Comment by blackdwarf** [comment]
@piotrpMSFT the ask is to have a good set of imports that will allow our users to be able to walk outside of the .net core fx without blowing up but also to not include those that we know have weird side-effects. @davidfowl has the nitty-gritty. We are looking into which set this is and will update the issue once we have it. 

Sidenote: The more I think about it, the more I feel `dnxcore50` for `netcoreapp1.0` is the only thing that makes sense, since that target essentially says that the package works on .NET Core. But I could be wrong, @ericstj is the authority here.

**Comment by piotrpMSFT** [comment]
I want to implement the fix right now but it sounds like we don't know what we want yet...

**Comment by Petermarcu** [comment]
That's right. I think the safe thing to add back in dnxcore50. Those are packages that did the work to move to RC1 of .NET Core. This would make it so we are not regressing the package set that can be used in that scenario.

**Comment by piotrpMSFT** [comment]
Ok. So I'm treating this bug as 'add dnxcore50 import to dotnet new template`. If we decide to add others in the future please create new issues.

**Comment by eerhardt** [comment]
I'm not convinced we should be adding the `dnxcore50` import to our templates.  The packages that target `dnxcore50` aren't guaranteed to actually work end-to-end in .NET Core.

For example, adding a dependency to Newtonsoft blows up immediately in `dotnet restore` and it very clearly says "this package doesn't work in the framework you are targeting".  By adding the import, that makes `dotnet restore` ignore that the package doesn't work, and pulls in this dependency anyway.
However, when you go to run code that uses Newtonsoft, it blows up at runtime because Newtonsoft doesn't have all its dependencies listed, and it depends on an assembly that isn't in the Shared Framework: `System.Runtime.Serialization.Primitives`.

IMO - it is better to tell the developer upfront that the new dependency isn't going to work i.e. `dotnet restore` fails.  Then let them get further down the development process and find out later something is busted because the package isn't made for .NET Core.

@weshaggard @ericstj

**Comment by GuardRex** [comment]
> IMO - it is better to tell the developer upfront that the new dependency isn't going to work i.e. dotnet restore fails.

I bet there will be cases where some new package is added to a project that wouldn't ordinarily restore on its frameworks but just so happens to match an existing `imports` entry that was put there purposefully earlier ... then later ... :boom:

The restore doesn't necessarily need to fail completely in these cases but at least state in the output that the package is not supported (as it says without a match in `imports`) but add that the package is being accepted anyway due to a match in `imports`.

**Comment by piotrpMSFT** [comment]
I think the feedback on this issue is pretty compelling and @blackdwarf should think about whether adding imports actually improves User Experience. For the time being, since we're locking down RC2, I went ahead and fixed this issue as stated.

The test is good as-is. The intent of this issue is not to make arbitrary dependencies work. It is only to enable the restoration of packages that target dnxcore50. As this issue nicely shows, we cannot make any broader promises.
