### ISSUE TITLE
Find the correct registry keys that the Windows Installer should create

### ISSUE THREAD

**Issue by Sridhar-MS** [dotnet/cli#250]
https://github.com/dotnet/cli/blob/master/packaging/windows/registrykeys.wxs

Currently the following reg keys are set
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Dotnet CLI\Setup
- Install DWord '1'
- InstallDir String 'install directory'
- Version String 'dotnet cli version'

**Comment by piotrpMSFT** [comment]
HKLM\SOFTWARE\dotnet\cli\Setup?

This is a .NET Foundation project so I don't think we should use Microsoft. I'd also like to parent CLI with dotnet.

**Comment by Sridhar-MS** [comment]
/cc: @joeloff I like get your feedback on the registry keys needed by aspnet installer to check for dotnet CLI installations.

**Comment by mellinoe** [comment]
Should we try to avoid using the acronym "CLI" in directories, installers, etc? We had an issue regarding its ambiguity which didn't really get resolved very specifically. I don't think the acronym has surfaced in many other places than the repo name right now.

**Comment by Sridhar-MS** [comment]
@mellinoe What issue are you talking about? 

Azure CLI also follows the pattern of `azure\cli` in it's directory structure.

**Comment by joeloff** [comment]
@Sridhar-MS For the registry keys, what we did in DNX is just write a global key and a local key. The global key contained the root folder of the runtimes folder. The local key had specific information about the version of each installer DNX, DNXMOno, DNXCore-Linux, etc.

The 64-bit installers wrote the keys to both the 32-bit and 64-bit hive since 32-bit installers can't read the 64-bit hive and we have lots of 32-bit MSIs in VS for example that might need to access that information on a 64-bit OS.

Here's an example. The first key is global and shared component across all DNX installers

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NET Cross-Platform Runtime Environment]
"InstallDir"="C:\\Program Files\\DNX\\runtimes\\"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NET Cross-Platform Runtime Environment\.NET Core]

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NET Cross-Platform Runtime Environment\.NET Core\Win]

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NET Cross-Platform Runtime Environment\.NET Core\Win\v1-rc1]
"Install"=dword:00000001
"Version"="1.0.11117.0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NET Cross-Platform Runtime Environment\.NET Framework 4.6]

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NET Cross-Platform Runtime Environment\.NET Framework 4.6\Win]

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NET Cross-Platform Runtime Environment\.NET Framework 4.6\Win\v1-rc1]
"Install"=dword:00000001
"Version"="1.0.11117.0"

**Comment by blackdwarf** [comment]
@Sridhar-MS is this done?

**Comment by piotrpMSFT** [comment]
This was fixed in preview1.
