### ISSUE TITLE
outdated packages on apt-get

### ISSUE THREAD

**Issue by tugberkugurlu** [dotnet/cli#2583]
I am looking to see how I can get dotnet CLI working on travis CI but installation steps for apt-get [here ](http://dotnet.github.io/getting-started/) seems to outdated or new releases are not available there. Following the instructions there and running `sudo apt-cache madison dotnet` gives me `1.0.0.001793-1` as latest version. I cannot see `1.0.0-rc2-*` releases there.

**Comment by tonysneed** [comment]
👍  It would be nice to be able to build a docker image similar to the one here: https://hub.docker.com/r/microsoft/dotnet, but it seems like the a recent build should be posted for apt-get to work.  Any workarounds for this?

**Comment by Petermarcu** [comment]
@brthor , @MichaelSimons can you guys give guidance here?

**Comment by brthor** [comment]
@tugberkugurlu Our packages are no longer named `dotnet`

Those packages still exist because our current lkg is amongst them. 

try this:
`apt-cache search dotnet-dev`

Then you can install like this (long package name):
`apt-get install dotnet-dev-1.0.0-rc2-002416`

This is an effect of our new Side by side model of installation, you can have multiple framework or cli versions installed on a machine. 

@MichaelSimons Could comment more on our docker image 😄

**Comment by MichaelSimons** [comment]
The following Dockerfile illustrates how you can install a newer version.

```
FROM buildpack-deps:trusty-scm

# Work around https://github.com/dotnet/cli/issues/1582 until Docker releases a
# fix (https://github.com/docker/docker/issues/20818). This workaround allows
# the container to be run with the default seccomp Docker settings by avoiding
# the restart_syscall made by LTTng which causes a failed assertion.
ENV LTTNG_UST_REGISTER_TIMEOUT 0

RUN echo "deb [arch=amd64] http://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list \
    && apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893 \
    && apt-get update \
    && apt-get install -y --no-install-recommends dotnet-dev-1.0.0-rc2-002416 \
    && rm -rf /var/lib/apt/lists/*
```

We will be updating the https://hub.docker.com/r/microsoft/dotnet image once RC2 is released.  In the meantime if you want to experiment with the latest bits consider using the https://hub.docker.com/r/microsoft/dotnet-preview image.

**Comment by tonysneed** [comment]
@MichaelSimons @tugberkugurlu Thanks, this is exactly what I was looking for.

**Comment by tonysneed** [comment]
I tried running a container from a Dockerfile based on the dotnet-preview image.  But the NuGet dependencies could not be resolved.  This is part of the docker log:

```
/app/project.json(9,31): error NU1001: The dependency Microsoft.CSharp >= 4.0.1-rc2-23931 could not be resolved.
```

Grateful for any tips. 😄

**Comment by MichaelSimons** [comment]
@tonysneed - Please refer to https://github.com/dotnet/cli/issues/2545 for details about the error you encountered and how to workaround it.

**Comment by tonysneed** [comment]
Thanks for the workaround for the Nu1001 error.  This error went away, but I have another one:

```
Errors in /app/HelloWeb/project.json
    Unable to resolve 'Microsoft.AspNetCore.Server.Kestrel (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.AspNetCore.StaticFiles (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
```

**Comment by tugberkugurlu** [comment]
@MichaelSimons I am getting the following error under Travis CI:

```
0.49s$ sudo apt-get install -y --no-install-recommends dotnet-dev-1.0.0-rc2-002416
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 dotnet-dev-1.0.0-rc2-002416 : Depends: libstdc++6 (>= 4.8) but 4.6.3-1ubuntu5 is to be installed
                               Depends: clang-3.5 but it is not installable
                               Depends: dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc2-3002416 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

See this for entire log: https://travis-ci.org/tugberkugurlu/AspNetCore.Identity.MongoDB/builds/125548660#L1219

This is what I am doing: https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB/blob/4a1a251eb91984b09f23fca0a0e7048bbd23e2ea/.travis.yml#L15-L18

Any thoughts?

**Comment by NinoFloris** [comment]
@tugberkugurlu I just ran into this today to get a docker container running with RC2, you have to install the debs manually like so

````dockerfile
FROM buildpack-deps:trusty-scm

RUN	apt-get update \
	&& apt-get install -y curl \
		libicu52 liblldb-3.6 liblttng-ust0 libunwind8 \
		clang-3.5 \
	&& apt-get -y autoremove \
	&& apt-get -y clean \
	&& rm -rf /var/lib/apt/lists/*

RUN curl -o /tmp/host.deb -sSL https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb \
	&& dpkg -i /tmp/host.deb \
	&& rm /tmp/*.deb

RUN curl -o /tmp/sharedframework.deb -sSL https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-sharedframework-ubuntu-x64.latest.deb \
	&& dpkg -i /tmp/sharedframework.deb \
	&& rm /tmp/*.deb

RUN curl -o /tmp/sdk.deb -sSL https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-sdk-ubuntu-x64.latest.deb \
	&& dpkg -i /tmp/sdk.deb \
	&& rm /tmp/*.deb

# Workaround for https://github.com/dotnet/cli/issues/1582, Bug only appears in Docker < 1.11.0
ENV LTTNG_UST_REGISTER_TIMEOUT -1
````

**Comment by MichaelSimons** [comment]
@tugberkugurlu When I looked at the Travis CI log, it looks like Ubuntu 12.04 is being used.  Is this correct?  Ubuntu 12.04 is not officially supported.  I would suggest using the officially supported version 14.04 if possible.

**Comment by tugberkugurlu** [comment]
@MichaelSimons :+1: that was the issue, all seems good now: https://travis-ci.org/tugberkugurlu/AspNetCore.Identity.MongoDB/builds/125608880

**Comment by tonysneed** [comment]
@MichaelSimons I was able to create an image based on *microsoft/dotnet-preview*: https://github.com/tonysneed/Demo.DotNetCoreDocker.  However, I got the following error when running a container based on the image: **Project app does not have a lock file**. I posted a question regarding this on the [docker hub page](https://hub.docker.com/r/microsoft/dotnet-preview/). I was able to eliminate the error by running `chown`, but then I could not mount host directories.  Any assistance would be greatly appreciated!

**Comment by MichaelSimons** [comment]
@tonysneed, Did you have a project.json.lock file in the app directory before running `docker build`?  What behavior do you see if you clone your repo into a clean directory?  Also can you explain the purpose of `VOLUME nuget:/root/.nuget`?  I am not sure I understand

**Comment by tonysneed** [comment]
> Did you have a project.json.lock file in the app directory before running docker build? 

There's no project.json.lock file present before running `docker build`, because the [Dockerfile](https://github.com/tonysneed/Demo.DotNetCoreDocker/blob/master/Dockerfile) includes `RUN ["dotnet", "restore"]`, which generates the project.json.lock file.

> What behavior do you see if you clone your repo into a clean directory?

After cloning the repo to a clean directory, I run these commands:

```
docker build -t tonysneed/dotnet-aspnet .
docker run -d -p 5000:5000 --name dotnet-aspnet -v $(pwd):/app tonysneed/dotnet-aspnet
```

This will build the image, then run a container with a volume pointing to the current directory.  But the container will exit with the error: **Project app does not have a lock file**.  If I inspect the container, I can verify that the project.json.lock file *does* exist, but it appears there is a problem with asp.net core using it.

If I execute the `docker run` command without the `-v` switch, then there is no error, and the container runs normally as expected, so long as the Dockerfile includes `RUN chown -R 1000:1000 project.lock.json`.  If I remove this line, then I'll get the error: **Project app does not have a lock file**.

> Also can you explain the purpose of VOLUME nuget:/root/.nuget?

The purpose of this volume is to allow nuget packages to be persisted on the VM file system, so that they do not have to be re-downloaded every time the container is created.  This speeds up the `dotnet restore`.

**Comment by tonysneed** [comment]
If you look at @markrendle's [docknet-docker](https://github.com/rendlelabs/docknet-docker) repo, you'll see that he also needs to use `chown` to change ownership of created files to main user on host: [dotnetproxy](https://github.com/rendlelabs/docknet-docker/blob/master/dotnetproxy).

**Comment by brthor** [comment]
@tonysneed We hit a similar issue in CLI with file permissions when using volumes in our build. By default the user in  a docker container is root. 

I don't know if that's the exact issue you're hitting, but we found a good solution using docker build args:
https://github.com/docker/docker/issues/7198#issuecomment-159736577

**Comment by tonysneed** [comment]
Thanks @brthor, I'll give that a try.

**Comment by MichaelSimons** [comment]
@tonysneed, I'm confused by 'VOLUME nuget:/root/.nuget` so please excuse me if I am misunderstanding.  Isn't this creating a mount point within the image with the literal name 'nuget:/root/.nuget'?  I'm not making the connection on how `dotnet restore` is using this. I was thinking to achieve what you wanted you would either want to mount a host directory as a volume within the container or mount a shared-storage volume.

**Comment by tonysneed** [comment]
> Isn't this creating a mount point within the image with the literal name nuget:/root/.nuget?

It should create a mount point with the specified name `nuget` and mark it with a source that is outside the container, so that the data in that source is preserved, even if the container is deleted.  I've used this approach, for example, when creating containers for a `mongo` image, where I want data in mongodb to be preserved when I recreate containers for mongo.  I didn't want to mount a host directory because I wanted to store the data on the VM rather than on my dev box.

Having said all that, I have been mulling this over, and I wouldn't mind storing NuGet packages on my dev box and mounting a host directory.  This is how Mark Rendle does it, and it's why he runs `chown` also for the directories where NuGet packages are downloaded.  I would then remove the `VOLUME` from the Dockerfile, because you can't mount a host directory from a Dockerfile.  I can try mounting them when creating the container, after changing ownership, and see if `dotnet run` still complains that the project app does not have a project.lock.json file.

**Comment by tonysneed** [comment]
What I ended up doing was simply to include a `project.lock.json` file when building the docker image.  This eliminated the error: *Project app does not have a lock file*, and it obviated the need for running `chown`.  I also removed the `VOLUME` instruction from the updated [Dockerfile](https://github.com/tonysneed/Demo.DotNetCoreDocker/blob/master/Dockerfile).  This should serve as a viable workaround until a solution is found.

**Comment by blackdwarf** [comment]
What is the status of this issue? From the lack of recent discussion and the overall thread, it seems to be the root issue has been solved?

**Comment by tonysneed** [comment]
I haven't seen this issue in the current dotnet image.

**Comment by blackdwarf** [comment]
Thanks @tonysneed. Seems it is OK to close it then. Please reopen if the issue returns.
