### ISSUE TITLE
[Mac OS X] System.Net.Http.WinHttpHandler throwing FileNotFoundException for 'winhttp.dll'

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/cli#2585]
Ported from: https://github.com/dotnet/corefx/issues/7835

I have a portable application that has a reference to the beta version (I think that is the latest) of System.Net.Http.dll.

project.json
 {
 "version": "1.0.0-",
 "compilationOptions": {
 "emitEntryPoint": true
 },
 "dependencies": {
 "Microsoft.NETCore.App": {
 "type": "platform",
 "version": "1.0.0-rc2-3002394"
 },
 "System.Net.Http": "4.0.0-beta-"
 },
 "frameworks": {
 "netcoreapp1.0": {
 "imports" : ["dnxcore50", "portable-net45+win8"]
 }
 }
 }

The app restores and builds successfully. But when it is run it fails with the following:

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'winhttp.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
 at System.Net.Http.Interop.WinHttpSetStatusCallback(SafeInternetHandle handle, WINHTTP_STATUS_CALLBACK callback, UInt32 notificationFlags, IntPtr reserved)
 at System.Net.Http.WinHttpHandler.SetStatusCallback(SafeInternetHandle requestHandle, WINHTTP_STATUS_CALLBACK callback)
 at System.Net.Http.WinHttpHandler.d__1.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.b__6_1(Object state)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
 at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
 at System.Threading.ThreadPoolWorkQueue.Dispatch()

Even though System.Net.Http is in the sharedfx I was able to override with this version.  There are a few issues here, the largest is that I could fall off the golden path (use the sharedfx binaries) without an error. The secondary issue is how did I end up with a Windows version of this dll?

[curl.tar.gz](https://github.com/dotnet/cli/files/226779/curl.tar.gz)

**Comment by Petermarcu** [comment]
The fact that the downgrade wasn't obvious is either a bug for the CLI or for NuGet. Getting the wrong asset from the package may be a corefx issue. @ericstj

**Comment by GuardRex** [comment]
@jeffschwMSFT Did this happen because the `imports` masked it being restored? ... when without the `imports` it does fail and state that the package is incompat?

**Comment by jeffschwMSFT** [comment]
@GuardRex yes the import is necessary to select a compatible package.  Right now there is not a netstandard version of System.Net.Http

**Comment by GuardRex** [comment]
@jeffschwMSFT The reason I asked was that there is/was an open question about `imports` masking incompatible packages that seemed related to your issue: https://github.com/dotnet/cli/issues/2499#issuecomment-211645044

I have this gut feeling that `imports` added to make a known-ok-package "good" for a TFM will mask some other packages brought in later (or by accident) that may restore and compile but not work. I was wondering if that's what happened here: The `imports` masked that this package was incompatible; otherwise, you would have received an exception at restore and not :boom: on you at runtime. My suggestion is they should always have some little output that an incompatible package is being accepted when `imports` is allowing it in ... just as a heads-up to the dev on restore.

**Comment by piotrpMSFT** [comment]
@jeffschwMSFT the latest System.Net.Http is here:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Net.Http/4.0.1-rc2-24022

Can you try that one and re-open if it proves problematic? This is likely a better CoreFx issue, if that's the case.
