### ISSUE TITLE
dotnet.exe doesn't pass non-ASCII characters into the managed code correctly on Windows

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#2649]
When passing the command line args through to the managed code, the native host code isn't converting the strings correctly.

## Steps to reproduce

```
    public class Program
    {
        public static void Main(string[] args)
        {
            File.WriteAllLines("output.txt", args);
        }
    }
```

`dotnet.exe run Tést`

## Expected  behavior

The Output.txt file should contain

`Tést`

## Actual behavior

The Output.txt file contains

`TÃƒÂ©st`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002476)

Product Information:
 Version:     1.0.0-rc2-002476
 Commit Sha:  1a8d393b9b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

@schellap @gkhanna79 @piotrpMSFT

**Comment by gregg-miskelly** [comment]
Matt, yup, this issue is very related, except that IMHO, the CLI fix is wrong (at least long term) - they fixed the CLI to try and work around the design flaw in CoreCLR, but the design flaw is still there in CoreCLR, and their fix will not work with Unicode paths.

I opened https://github.com/dotnet/coreclr/issues/4634 to actually fix the design flaw. We may need to do something like their hack for RC2 though.
