### ISSUE TITLE
Not useful message when passing --no-incremental

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#2748]
## Steps to reproduce

dotnet build --no-incremental
## Expected  behavior

build the project, no messages about improving compilation time
## Actual behavior

```
dotnet build --no-incremental
Project Microsoft.DotNet.InternalAbstractions (.NETStandard,Version=v1.3) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
```
## Environment data

`dotnet --info` output:

```
Product Information:
 Version:     1.0.0
 Commit Sha:  4062595c11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by cdmihai** [comment]
I'd leave the message there as a reminder that something is not right and the compilation times CAN be improved :)

It avoids the scenario where a user has a stuffy shell script that calls build --no-incremental, but the user forgets about the flag and then silently suffers long compilation times due to forced rebuilds.

**Comment by billwert** [comment]
I strongly agree with @krwq here. If the user tells the compiler not to be incremental, that should be the end of it.

**Comment by blackdwarf** [comment]
Similar to #2853, the message is completely different/non-existent in the Preview 4 tooling, that is, MSBuild-based tools. Will close this down as well. @krwq feel free to reopen if you find this still repros or have more input.
