### ISSUE TITLE
Consider Implementing a Compiler Server to Eliminate Roslyn Start-Up Cost

### ISSUE THREAD

**Issue by brianrob** [dotnet/cli#2751]
As an alternative to hosting Roslyn inside the dotnet build process, another option to be considered is to implement a compiler server.  This would mean only paying start-up cost once and having a compiler in-memory with caches primed and ready-to-go.

**Comment by brianrob** [comment]
@jaredpar, I believe you're already looking at this.

**Comment by jaredpar** [comment]
@brianrob indeed.  Have a couple of prototypes I've tested.  The actual server functionality is portable and already factored out into a portable layer.  The issues with moving it to CLI is around the following:

1. Picking a transport layer.  On Windows desktop we use named pipes in large part because we can set ACLs on them.  Need to think about a good equivalent which is portable. 
2. Need to define the user story.  The compiler server start up / shutdown sequence and general lifetime is not a good story on Windows.  I'd prefer on CLI we have a much more definitive model in these areas.

**Comment by blackdwarf** [comment]
Is this still an issue now that we have moved to MSBuild?

**Comment by brianrob** [comment]
Not sure if this is already the case with MSBuild.  @jaredpar?

**Comment by jaredpar** [comment]
The move to MSBuild means the infrastructure for managing the server essentially comes for free.  There is still a bit of work to do to fully flesh out the prototype and package it.  In particular I'm unclear how CLI lays out MSBuild bits including the Roslyn binaries.  That is important as we will likely ship a different implementation of the server for CoreClr than we do for desktop.  Today I believe CLI only handles us a single package.  

Roslyn issue tracknig bulk of the remaining work

https://github.com/dotnet/roslyn/issues/9696

**Comment by blackdwarf** [comment]
@jaredpar thanks for the info. Since a lot more work remains, I imagine that this is not a 1.0.0 feature?

**Comment by jaredpar** [comment]
@blackdwarf 1.0.0 for which product?  CLI?

**Comment by blackdwarf** [comment]
@jaredpar yes, Core tools.

**Comment by livarcocc** [comment]
We now have VBCSCompiler.
