### ISSUE TITLE
Can't run console app built for win10-x64 (probably other rids as well)

### ISSUE THREAD

**Issue by BillHiebert** [dotnet/cli#2760]
dotnet version: 1.0.0-rc2-002520

## Steps to reproduce
1. New console app
2. Remove type: platform from dependency
3. Add runtimes: {"win10-x64" : {}}
4. dotnet build
5 Output should be in bin\debug\netcoreapp10\win10-x64
6. run the built executable

See the following error
Could not resolve coreclr path

**Comment by brthor** [comment]
> New console app

Is this using dotnet new, or a different template?

**Comment by BillHiebert** [comment]
@brthor 
A different template. I turned on COREHOST_TRACE and it shows the following (with 1.0.0-rc2-002543):
Checking if CoreCLR path exists=[C:\Users\billhie\AppData\Local\dotnet\runtime\coreclr\coreclr.dll]
Checking if CoreCLR path exists=[C:\Program Files\dotnet\bin\coreclr.dll]
Could not resolve CoreCLR path. For more details, enable tracing by setting COREHOST_TRACE environment variable to 1

Sure enough I don't have a bin folder under c:\program files\dotnet. I did install the SDK  which should have included the runtime as well.

**Comment by brthor** [comment]
Can you share the project.json please?

**Comment by BillHiebert** [comment]
`{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "runtimes": {
    "win10-x64": { }
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002426"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {}
  }
}`

I suspect is the platform dependency which is causing the issue

**Comment by brthor** [comment]
Thanks for the info @BillHiebert , looking into this now

**Comment by brthor** [comment]
@BillHiebert did you run restore in between steps 3 and 4?

**Comment by brthor** [comment]
I've reproed this using the following steps:

1. Create Project.json
```
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "runtimes": {
    "win10-x64": { }
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002426",
      "type": "platform"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {}
  }
}
```

2. dotnet restore
3. remove "type":"platform"
4. dotnet build
5. run `bin\Debug\netcoreapp1.0\win10-x64\OUTPUT.exe`

The base cause here is that `dotnet restore` was not run in between steps 3 and 4, and it puts the project in a half-portable, half-standalone state. Build outputs a host and runtimeconfig.json like it's a standalone app but the deps.json reflects a portable app with no coreclr.dll entry. 

So immediate workaround is to run `dotnet restore` between steps 3 and 4, and the fix in build should be to throw an error rather than succeed in this state.

**Comment by brthor** [comment]
The issue ended up being simple, build is keying off the wrong things to determine if the project is portable. Now we'll see this error, which tells you to restore again. 

I'm not sure if the right thing is for build to succeed here, but this error seems acceptable and matches the state of the project (project.json and project.lock.json are mismatched)

```
System.InvalidOperationException: Can not find runtime target for framework '.
NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x6
4, win81-x64, win8-x64, win7-x64'. Possible causes:
1. The project has not been restored or restore failed - run `dotnet restore`
2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64'
 in the 'runtimes' section.
```

**Comment by brthor** [comment]
After some more testing, this issue goes deeper.. The other fixed bug appears to have been unrelated or a red herring.

When we restore a "type": "platform" dependency, this is reflected in the project.lock.json as "type":"package"

```
"Microsoft.NETCore.App/1.0.0-rc2-3002426": {
        "type": "package",
```
However, the lock files generated with and without `"type":"platform"` are different. Notably "coreclr.dll" is not listed as a native export. What this means is that to the cli, the lock file restored with `"type":"platform"` appears compatible with the project file without `"type":"platform"`. As far as I can tell, the CLI has no way to determine if there's a mismatch in this scenario. 

cc @anurse @emgarten @yishaigalatzer 
Is this intentional behavior in NuGet? Is it a bug that "type":"platform" dependencies are listed as "type":"package" in the lock file?

**Comment by anurse** [comment]
`type` in the lock file and `type` in the project file are completely different properties, they don't correlate.

`type:platform` implies the NuGet setting `exclude:runtime,native` which would explain why `coreclr.dll` is not a native export. This is a portable project.

**Comment by brthor** [comment]
That is pretty confusing. 

Knowing that doesn't help solve the problem though. How can we determine from a lock file whether "type": "platform" was specified? This seems like an important scenario for cli to be able to determine whether the current project file is compatible with the current lock file.

**Comment by brthor** [comment]
@anurse Perhaps the issue here then is not that "type":"package" should be "type":"platform" in the lock file but that the `projectFileDependencyGroups` should reflect the types of the dependencies.

**Comment by oviwankenobi** [comment]
hi
I am facing this error now

error : Can not find runtime target for framework '
1>.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x6
1>4, win81-x64, win8-x64, win7-x64'. Possible causes:
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 1. The project has not been restored or res
1>tore failed - run `dotnet restore`
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 2. **The project does not list one of 'win10-
1>x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.**
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.Do
1>tNet.Common.Targets(262,5): error : 3. You may be trying to publish a library,
1>which is not supported. Use `dotnet pack` to distribute libraries.

I am sure number 3.  suggested is not the case cause I a not trying to publish but build.
number 1. is not either cause the "dotnet restore" succeeds without error.

how do I approach understanding and fixing suggested item 2. ? 

thank you
