### ISSUE TITLE
Ubuntu build fails if project.json contains "delaySign": true option in compilationOptions section

### ISSUE THREAD

**Issue by hovsepm** [dotnet/cli#2862]
## Steps to reproduce

git clone git@github.com:hovsepm/azure-sdk-for-net.git 
git checkout netcore
./test_on_linux.sh 

My project.json file contains following section:

```
"compilationOptions": {                 
  "delaySign": true,                          
  "keyFile": "../../../../tools/MSSharedLibKey.snk"                              
},
```
## Expected  behavior

Both Windows and Ubuntu builds succeed or there is a way to opt out for default signing options on a specific platform
## Actual behavior

Windows succeeds but Ubuntu 14.04 fails with following error:
/home/travis/build/hovsepm/azure-sdk-for-net/src/TestFramework/Microsoft.Rest.ClientRuntime.Azure.TestFramework/error CS7102: Compilation options 'PublicSign' and 'DelaySign' can't both be specified at the same time.
## Environment data

`dotnet --info` output: I'm not able to run it on linux (Travis CI). 
.travis.yml that contains Ubuntu box configuration is located in the root folder of git@github.com:hovsepm/azure-sdk-for-net.git  in the netcore branch.

**Comment by piotrpMSFT** [comment]
@hovsepm thanks for filing this. This is a bug in CLI, specifically here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-compile-csc/Program.cs#L169. We cannot full-sign on Windows so if there is a keyfile and we're not on Windows then we automatically set PublicSign = true. The bug is that we don't account for Delay Sign when addressing this special case. If DelaySign is specified then we should not be defaulting PublicSign to true.

Fortunately, there is a workaround: add the `publicSign` property and set its value to 'false'.

**Comment by livarcocc** [comment]
I believe this is no longer applicable. Please, re-activate if there is anything else that is needed.
