### ISSUE TITLE
Incorrect error message (missing placeholder?)

### ISSUE THREAD

**Issue by victorhurdugaci** [dotnet/cli#2887]
I think this error message is missing a placeholder after "Lock file":

```
Error       Lock file Microsoft.DotNet.ProjectModel.Graph.LockFile contains msbuild projects but there is no export file    WebApplication21    C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  241 Build   
```

**Comment by blackdwarf** [comment]
I'm pretty sure that this issue is not longer valid in the new world of MSBuild-based tooling. If it is, the most likely home for this issue is not the CLI but rather the dotnet/sdk repo. 

@victorhurdugaci can you please install the latest RC of VS2017, install the .NET Core tools and see if this repros?

**Comment by livarcocc** [comment]
Yep, not applicable anymore.
