### ISSUE TITLE
Cannot publish ubuntu-x64 standalone app on windows

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2890]
## Steps to reproduce
1. Restore packages
2. `PS C:\Source\cli-samples\HelloMvc> dotnet publish -r ubuntu-x64`

[HelloMVC](https://github.com/aspnet/cli-samples/tree/master/HelloMvc) with the following project.json
```
{
  "buildOptions": {
    "preserveCompilationContext": true,
    "emitEntryPoint": true,
    "debugType": "portable"
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views"
    ]
  },
  "dependencies": {
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
    "Microsoft.AspNetCore.Mvc": "1.0.0-*",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
    "Microsoft.Extensions.Logging.Console": "1.0.0-*",
    "Microsoft.NETCore.App": {
      "version": "1.0.0-*"
    }
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+wp80+win8+wpa81+dnxcore50",
        "portable-net451+win8"
      ]
    }
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-*",
      "imports": "portable-net45+wp80+win8+wpa81+dnxcore50"
    }
  },
  "scripts": {
    "postpublish": "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
  }, 
  
  "runtimes": { 
    "ubuntu-x64": {}
  }
}
```
## Expected  behavior
Publishing succeeds.

## Actual behavior
```
PS C:\Source\cli-samples\HelloMvc> dotnet publish -r ubuntu-x64
Publishing HelloMvc for .NETCoreApp,Version=v1.0/ubuntu-x64
Project HelloMvc (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling HelloMvc for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.9402395
Failed to make the following project runnable: HelloMvc (.NETCoreApp,Version=v1.0) reason: Expected coreclr library not found in package graph. Please try running dotnet restore again.
Published 0/1 projects successfully
```

## Environment data
`dotnet --info` output:

```
PS C:\Source\cli-samples\HelloMvc> dotnet --info
.NET Command Line Tools (1.0.0-rc2-002655)

Product Information:
 Version:     1.0.0-rc2-002655
 Commit Sha:  3e96a05f9c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by brthor** [comment]
@moozzyk This error was added so Standalone Apps published without coreclr throw an error prior to host activation. 

This means libcoreclr.so is not present in your package graph, probably because `ubuntu-x64` is not a rid we publish any runtime packages for (as far as I know).

Try it out with `ubuntu.14.04-x64` ?

**Comment by piotrpMSFT** [comment]
Please re-open if this still fails with a good RID.

**Comment by moozzyk** [comment]
How am I supposed to know that I need to use exact RID? My runtime section looks just like this: 
`
  "runtimes": { 
    "ubuntu-x64": {}
  }
` 
so there is no version.

**Comment by moozzyk** [comment]
If I put `ubuntu.14.04-x64` in my project.json and use this as the -r value then I don't get an error. Still the experience sucks - if I use a RID I cannot publish for in my project.json I should get an error/warning (possibly during restore).

**Comment by brthor** [comment]
> How am I supposed to know that I need to use exact RID?

I think this is a documentation issue.

The issue here is that `ubuntu-x64` is not necessarily a "wrong" rid and indeed individual packages can create their own custom rid graphs using runtime.json. So at restore time, there's not necessarily a way to say that your rid is wrong. 

Even at build/publish time the best we can do for a Standalone app is make sure that whatever package graph exists for the rid you've selected contains coreclr.dll or it's xplat equivalent. If, for example, you had a package which declared that `ubuntu-x64` imported `ubuntu14.04-x64` (ordering might be backwards) then this should work just fine with `ubuntu-x64`.

**Comment by moozzyk** [comment]
That's OK. As long as it is documented it should be fine. The error message could and should be improved though.
