### ISSUE TITLE
Need a warning/error if an application cannot be publish for the RID included in runtimes section

### ISSUE THREAD

**Issue by moozzyk** [dotnet/cli#2894]
## Steps to reproduce

If you use a general RID like this in the project.json file:

```
  "runtimes": { 
    "ubuntu-x64": {}
  }
```

Then the application cannot be published or run. 
## Expected  behavior

A warning or an error saying that the RID used in the runtimes section is not usable. 
## Actual behavior

(Possibly) a technically correct yet completely useless from the user perspective message:

```
dotnet publish -r ubuntu-x64

Failed to make the following project runnable: HelloMvc (.NETCoreApp,Version=v1.0) reason: Expected coreclr library not found in package graph. Please try running dotnet restore again.
```
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-rc2-002655)

Product Information:
 Version:     1.0.0-rc2-002655
 Commit Sha:  3e96a05f9c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by brthor** [comment]
From #2890

The issue here is that ubuntu-x64 is not necessarily a "wrong" rid and indeed individual packages can create their own custom rid graphs using runtime.json. So at restore time, there's not necessarily a way to say that your rid is wrong.

Even at build/publish time the best we can do for a Standalone app is make sure that whatever package graph exists for the rid you've selected contains coreclr.dll or it's xplat equivalent. If, for example, you had a package which declared that ubuntu-x64 imported ubuntu14.04-x64 (ordering might be backwards) then this should work just fine with ubuntu-x64.

We could change the error provided to provide a better experience:
"Expected coreclr library not found in package graph. Please check that you are using a compatible RID try running dotnet restore again."

**Comment by livarcocc** [comment]
Now, you will get an error like below:

```
Project is targeting runtime 'osx10.12-x64' but did not resolve any runtime-specific packages for the 'Microsoft.NETCore.App' package.  This runtime may not be supported by .NET Core.
```

I believe this seems enough. If I got this wrong, just comment and we can re-activate the issue and continue the conversation.
