### ISSUE TITLE
Should dotnet-publish support publishing without runtime?

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/cli#290]
The scenario was raised by @glennc in a chat on Fri. The idea is to `dotnet-publish` publish the user's code and all of the code's dependencies but not the runtime. I guess the runtime would be expected on the deployment target for the application.

/cc @davidfowl @piotrpMSFT

**Comment by Petermarcu** [comment]
Yes, publish needs to be able to create a layout that could be deployed to a machine with a shared framework. The shared would be .net core based on coreclr in this case.

**Comment by davidfowl** [comment]
Yea compile does this already. We need to consolidate

**Comment by blackdwarf** [comment]
OK, that's pretty clear sentiment then. So, should it behave like above? That is, running `dotnet publish --no-runtime` produces the same layout as currently *sans* the runtime files?

**Comment by piotrpMSFT** [comment]
--runtime:shared?

**Comment by blackdwarf** [comment]
@piotrpMSFT that is an even better suggestion really. Though...one thing I don't like is that it is yet another "magic string" that the user needs to know. --no-runtime or --exclude-runtime is much clearer...though, the user would then need to know the semantics.

**Comment by piotrpMSFT** [comment]
@Sridhar-MS you've been thinking about a flavor of this scenario lately
If Runtime and Framework are shared then the output of Compile should suffice. This gets messed up a bit by any native dependencies, though, since those would be platform specific.

I think this is what we're after:

|  App contents | Win7-x64 | OSX-x64 | Linux-x64| Shared |
|:--------:|:-------:|:-------:|:-------:|
| Managed|N/A | N/A | N/A | `compile output` |
| Managed + Native| `compile output` + win bits | `compile output` + osx bits | `compile output` + Linux bits| N/A|

**Comment by brthor** [comment]
Fixed #343
