### ISSUE TITLE
does not drop binary

### ISSUE THREAD

**Issue by aficustree** [dotnet/cli#2909]
## Steps to reproduce
dotnet new
dotnet restore
dotnet run
dotnet build

## Expected  behavior
binary in ./bin/Debug/netcoreapp1.0/

## Actual behavior
ls from ./bin/Debug/netcoreapp1.0/.
netcoretest6.deps.json              netcoretest6.runtimeconfig.dev.json
netcoretest6.dll                    netcoretest6.runtimeconfig.json
netcoretest6.pdb

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc2-002673)

Product Information:
 Version:     1.0.0-rc2-002673
 Commit Sha:  c0aeb91d61

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by piotrpMSFT** [comment]
This is by-design. The default project template produced by `dotnet new` creates a portable application. This application can be executed on any RID [otherwise, any supported OS+CPU Architecture] for which a .NET Shared Framework is available. 

When the Shared Framework is installed an executable called `dotnet` is added to the path. You can now run your application by executing `dotnet path/to/your.dll`. Give this a shot on multiple OS's. For example, you can run the app on your OS X device, then copy the same dll to a Windows or Linux device and execute it in exactly the same way!

**Comment by aficustree** [comment]
Thanks @piotrpMSFT . I didn't understand the change when i upgraded from the version on the landing page of 'get started'. Many thanks!
