### ISSUE TITLE
dotnet compile does not work on MAC OS 10.11.1

### ISSUE THREAD

**Issue by hunter-xue** [dotnet/cli#294]
Get error message: 
My MAC OS X version is: EI Capitan 10.11.1
xuedeMacBook-Air:p02 xuehaitao$ dotnet compile 
Compiling p02 for DNXCore,Version=v5.0
Could not find file '/usr/local/bin/corehost'.

**Comment by davidfowl** [comment]
How did we regress compile? Don't we use it to produce the cli?

**Comment by blackdwarf** [comment]
Compile works, as in, it drops the IL, but the last step, copying over the corehost, fails. @brthor investigated and has some conclusions on why this is failing on OS X. BTW, it works on Windows and on Ubuntu, as far as I can tell.

**Comment by muratg** [comment]
Repro'd. Is someone fixing this?

**Comment by brthor** [comment]
@davidfowl @muratg @blackdwarf @hunter-xue 

I did some digging on this on Friday, and it looks like this only happens when CoreHost/CoreConsole binaries are symlinked on OSX.

As a temporary workaround (might need sudo): 
`cp /usr/local/share/dotnet/cli/bin/corehost /usr/local/bin/corehost`

Issue is being tracked here:
https://github.com/dotnet/coreclr/issues/2128

**Comment by blackdwarf** [comment]
I guess the workaround can be to add the copy step to the postinstall for PKG creation, correct? I will try to do that today. Assigning to myself.

**Comment by muratg** [comment]
Not sure if it's related or not, but `dotnet run` also does nothing, and just exits on a basic Hello World app.  (App runs fine with dnx)
