### ISSUE TITLE
Add no console compile/publish command

### ISSUE THREAD

**Issue by xanather** [dotnet/cli#296]
As it stands executables that are deployed by CLI always open a console. It may be preferred to have a "hide console" option/parameter if the program is developed to run as a background process/service or the program itself intends to create its own input/ouput UI.

**Comment by davidfowl** [comment]
Sounds windows specific

**Comment by xanather** [comment]
Why do you think that? How do native ubuntu/mac apps only show a GUI without a terminal?

**Comment by davidfowl** [comment]
How do you do this with node or go or rust? Or any of the other languages (e.g is it a compiler flag?) ? I know Java has javaw but I dunno how the other application models work on top of the base. This isn't the general purpose tool chain for all models and I think it depends on what the additional steps look like that determine where they should live.

**Comment by xanather** [comment]
Seems like its more difficult to do on other platforms.
On Mac OS X you need to manually create a bundle. I assume Linux systems would work in a similar way?

http://stackoverflow.com/questions/23861914/how-to-hide-terminal-window-in-mac-osx

Since creating OS-specific packages/bundles would be slightly out of scope of this toolset I suppose I wont be supported. It would still help to have an option/parameter when compiling on Windows however to prevent a console window showing.

**Comment by piotrpMSFT** [comment]
This is a parent/child process relationship. The parent process can hide the window for the child process.
 https://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.createnowindow.aspx

What's the gap?

**Comment by mellinoe** [comment]
> The parent process can hide the window for the child process.

I'm pretty sure the ask is for a way to make the original process (corehost or whatever other native host is being used) start without a console window. For Windows that means linking to the WINDOWS subsystem: https://msdn.microsoft.com/en-us/library/fcc1zstk.aspx. I've done this with coreconsole, but I actually could never figure out the CMake options to make it possible, so I just manually edited the generated project file.

I have no idea how this works for other platforms, perhaps there is something similar. Based on what @xanather said, you need to make a bundle for OSX. Perhaps that is what the [osxbundlerun](https://github.com/dotnet/coreclr/tree/master/src/coreclr/hosts/osxbundlerun) host is for?

**Comment by blackdwarf** [comment]
I will close this as the issue seems out of scope of the toolset. If in error, please reopen.

**Comment by xanather** [comment]
@blackdwarf Are you sure this issue is out of scope? I can see .net core targeting GUI and/or background services/executables in the future. Having a flag for the platforms which support it will help, do we expect people to compile their own native launcher to prevent a console displaying (this is what I will have to do)?

**Comment by jsclary** [comment]
@xanther @blackdwarf  Yep, this is what I'm looking at now.  Launching an OpenTK.NETCore based UI window is fine but there's no safe way to get rid of the console that I've been able to locate.  There's a way via P/Invoke but it's fraught with peril.

Windows and the Unicies do things the opposite way around quite often.  On unix, executables are all pretty much the same.  If you want to use an executable without a GUI inside of a GUI, you have to create a terminal window yourself and then run it.  If you want to run a GUI app from a terminal but keep using the terminal, you have to background it yourself. 

On Windows, the OS automagically creates the console (if the parent proc isn't cmd.exe and doesn't suppress it) for console apps.  It also backgrounds GUI apps automagically -- an important distinction.  A console app can have a GUI.   A GUI app can actually create a console (via AllocConsole()) but it's always a newly allocated console window even if the app was started from an existing console window.  Any application starting a new child executable has to actively suppress the console or GUI if it doesn't want it visible.  

The correct way to handle a console-less GUI app in Windows is to set the IMAGE_SUBSYSTEM in the PE header of the executable. It's normally specified in the CIL with ".subsystem" with a value of 2 for GUI or 3 for CUI and there's a bunch of other possibilities but those are most common.  For C#, generation of the .subsystem metadata is controlled by csc.exe /target:exe vs /target:winexe but I don't know about other languages or if there's way to add it declaratively via AssemblyInfo.cs.  I'd guess we'd get back the declarative option once the conversion back to *.csproj happens, but then the tools will have to respect it.

There's really no good way around having two separate launchers on windows. Java has java.exe and javaw.exe for this reason.  A two-stage start doesn't work because if you start as GUI first, you get backgrounded, and if you start console, it'll allocate extra resources and flash a brief console window and taskbar icon.

Unless there's another option, I'll probably need to create a post-build step to flip the byte in the launcher's PE header.  Trying to find and hide the console is a non-starter since it's an ugly non-portable hack and the console used by the app may not have been created by/for the app.  You definitely don't want to hide or de-allocate a parent console.
