### ISSUE TITLE
Not able to success using dotnet restore in windows 10 x64 

### ISSUE THREAD

**Issue by Challagolla** [dotnet/cli#2985]
## Steps to reproduce
Installed the latest .NET Core SDK Installer from https://github.com/dotnet/cli.
run dotnet restore
## Expected  behavior
restore should be successful

## Actual behavior
getting the following errors

error: Microsoft.AspNetCore.Server.IISIntegration.Tools 1.0.0-rc2-20832 is not compatible with DNXCore,Version=v5.0.
error: Some packages are not compatible with DNXCore,Version=v5.0.
error: Microsoft.AspNetCore.Server.IISIntegration.Tools 1.0.0-rc2-20832 is not compatible with DNXCore,Version=v5.0 (win7-x64).
error: Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).
info : Committing restore...
log  : Restore failed in 612ms.

Errors in C:\sources\SBMSources\SbmApsNew\Idp\src\Aps.Idp.Web\obj\fdee63f0-92b0-467a-9111-3efa04c1143f\bin\project.json
    Microsoft.AspNetCore.Server.IISIntegration.Tools 1.0.0-rc2-20832 is not compatible with DNXCore,Version=v5.0.
    Some packages are not compatible with DNXCore,Version=v5.0.
    Microsoft.AspNetCore.Server.IISIntegration.Tools 1.0.0-rc2-20832 is not compatible with DNXCore,Version=v5.0 (win7-x64).
    Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64).

NuGet Config files used:
    C:\sources\SBMSources\SbmApsNew\Idp\NuGet.Config
    C:\Users\ramiadmin\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.myget.org/F/aspnetcirelease/api/v3/index.json
    https://api.nuget.org/v3/index.json
    https://www.myget.org/F/aspnet-contrib/api/v3/index.json
    https://www.myget.org/F/xunit/api/v3/index.json

## Environment data

.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 Runtime Id:  win10-x64

**Comment by GuardRex** [comment]
@Challagolla Are you trying to update an RC1 app to RC2?

**Comment by GuardRex** [comment]
Note that you need to go with latest version of `dotnet cli`. Since you look like you tried to get the latest from the `rel/1.0.0` branch at GH, I bet you are running into this issue: https://github.com/dotnet/cli/issues/2948

Also, I have some links that might help if you're performing a project upgrade to RC2: https://github.com/dotnet/cli/issues/2135#issuecomment-212692267

**Comment by Challagolla** [comment]
@GuardRex I am not trying to update form RC1 to RC2. i have been working on RC2 only. I have restored the same application on windows 8.1 x64 machine but, when i run the dotnet restore on windows 10 x64, i am getting the problem. i will check based on the above mentioned issues.

**Comment by GuardRex** [comment]
@Challagolla Ok, yeah. Since you're seeing that -1598 version ... and perhaps you already tried using `Programs and Features` to get rid of old `dotnet cli`'s ... if that's still lingering ... yeah ... you'll have to do some manual work there to reset and dump old bits. That should get you up to latest, then with sime luck :four_leaf_clover: things will go well after that.

**Comment by piotrpMSFT** [comment]
Since there was no followup I'm assuming some luck was found :D
