### ISSUE TITLE
Should `dotnet publish` also take the elements specified in "copyToOutput"?

### ISSUE THREAD

**Issue by DavidObando** [dotnet/cli#3029]
## Steps to reproduce

This is more of a design question than a bug, up to the CLI team to decide.

Have an app such as [HelloWorldMvc](https://github.com/aspnet/Performance/tree/dev/testapp/HelloWorldMvc). In its project.json it specifies "copyToOutput":

```
    "copyToOutput": {
      "include": [
        "Views",
        "wwwroot"
      ]
    }
```

When I execute `dotnet run` it runs fine. When I execute `dotnet publish` and then `dotnet path\to\publish.dll` I get runtime errors as the files it required weren't copied. Shouldn't the build includes be "inherited" by the publishOptions includes? In the meantime I'll add:

```
  "publishOptions": {
    "include": [
      "Views",
      "wwwroot"
    ]
  }
```
## Expected  behavior

No need to specify the same stuff twice, unless there's differences in what's needed for build and for publish. Publish can be overriden if that's what's intended.
## Actual behavior

Without "publishOptions" my published app won't run well, even tough under `dotnet run` it runs as expected.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

```
Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14295
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by GuardRex** [comment]
@DavidObando I don't think that would be safe behavior. I don't think publishing should be guessing what is needed for deployable outputs based on `copyToOutput`. I hear what you're saying ... it would be leaner to avoid needing the `publishOptions` explicitly spelled-out in your situation, but this would be a security risk to make any such assumptions IMO. I think it's safer to force the dev to tell publish exactly what to include/exclude. cc/ @blowdart

**Comment by blackdwarf** [comment]
@DamianEdwards here as well, but I would agree with @GuardRex.

**Comment by xoofx** [comment]
Related to this problem:
- #3294 for the behaviour with pack, that's more a "breaking changes" from the usual behaviour we have in csproj.
- #2902 for the fact that usually (in csproj), the CopyToOutput was honoured between dependencies.

In csproj, whenever I put CopyToOutput on a file (plus the ability to remap dest folders with "Link", equivalent of "mappings" in project.json), I expect this to be part of any publishing process. Afair, this is how it is working with normal console apps, clickonce, UWP apps, and this is how it is working also with Mono projects (Android, iOS). Never done some heavy ASP.NET apps, but I'm pretty sure it was also working like this (between dependencies)

I have always used `copyToOutput` as additional data files that are part of the apps (sometimes for native dlls, though now with "runtimes" it is taken into account by the pack process), along the distributed dll.

Otherwise, what would be the purpose of `copyToOutput` in `buildOptions` if we have to duplicate things for `packOptions` and `publishOptions`? In which case we would use it?

Could we try to clarify the usage of `copyToOutput`?

**Comment by andschwa** [comment]
I am definitely desiring an ability to tell either `copyToOutput` or `publishOptions` to just inherit the other's definition. This shouldn't be an automatic default, but it'd be awesome if we could specify it, say with `"publishOptions": { "inherit": "copyToOutput" }` or something similar.

As of right now, to update to the new schema, I'm having to duplicate the value of `content` under both new keys.

**Comment by blackdwarf** [comment]
I believe that the desired behavior is now in given the move to MSBuild and csproj. I will close this issue, but please reopen if it still repros with the latest CLI tooling that is based on MSBuild. Thanks!
