### ISSUE TITLE
Merge is broken on Windows and CoreCLR is broken on OS X

### ISSUE THREAD

**Issue by haf** [dotnet/cli#3043]
## Steps to reproduce
Here's a log https://ci.appveyor.com/project/haf/suave/build/1.0.112/job/hmbmk93sdrjrjv5h#L2605 of running https://github.com/SuaveIO/suave/blob/master/appveyor.yml

## Expected  behavior
No crash, and if crash a notification of the path name/string that is invalid. For running the packages without merging, CoreCLR is broken on OS X, complaining about a policy error. Repro for that is to run the above, take the package, `git clone git@github.com:SuaveIO/Suave-CoreCLR-sample.git && cd Suave-CorCLR-sample && dotnet new --lang f# && dotnet restore && dotnet run`.

## Actual behavior
Crash and burn.

## Environment data
`dotnet --info` output:

```
➜  suave coreclr/dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.10
 OS Platform: Darwin
 RID:         osx.10.10-x64
```

**Comment by enricosada** [comment]
I am actively checking this

**Comment by blackdwarf** [comment]
@enricosada @haf is this then a CLI issue?

**Comment by haf** [comment]
Probably not. Closing until more progress from Enrico.

**Comment by enricosada** [comment]
@blackdwarf ok fixed, problem was rc2 pass double quotes to tools arguments, previous version `1.0.0-beta-002071` was stripping it. That's ok was an old version

for example `dotnet mergnupkg --source "path/to/package.nupkg"` was passing `--source` and `"path/to/package.nug"` (without stripping double quotes)

fixed with [dotnet-mergenupkg v0.10.2](https://github.com/enricosada/dotnet-mergenupkg/releases/tag/v0.10.2)

**Comment by haf** [comment]
Will you PR to suave too?

**Comment by enricosada** [comment]
done better, check https://github.com/SuaveIO/suave/pull/439
that pr work with released rc2, not the old version. also examples/Example work
