### ISSUE TITLE
RC2 error in VS 2015 - Failed to initialize CoreCLR, HRESULT: 0x80131500

### ISSUE THREAD

**Issue by alaatm** [dotnet/cli#3070]
## Steps to reproduce

Install RC2 on a machine that previously had RC1 installed and removed through Add/Remove Programs.
Open VS 2015 and create a new.net core console/web or library template.
## Expected  behavior

New solution created successfully.
## Actual behavior

I get the following error:

![image](https://cloud.githubusercontent.com/assets/2095803/15357526/0e11ec6e-1d08-11e6-90b7-a5d5c5d9220d.png)

If I try building i get the following error:

Failed to initialize CoreCLR, HRESULT: 0x80131500
And it points to: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets (line 241) which is below:

`<Dnx
      RuntimeExe="$(SDKToolingExe)"
      Condition="'$(_DesignTimeHostBuild)' != 'true'"
      ProjectFolder="$(MSBuildProjectDirectory)"
      Arguments="$(_BuildArguments)"
      />`
## Environment data

`dotnet --info` output:

  Product Information:
   Version:     1.0.0-preview1-002702
   Commit Sha:  6cde21225e

  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.10586
   OS Platform: Windows
   RID:         win10-x64

**Comment by dontbesorry80** [comment]
Alaatm.
I have the same problem as this.. How did you manage to resolve it?

**Comment by alaatm** [comment]
@dontbesorry80 I haven't managed to resolve it. I closed the issue thinking it was a tooling problem (https://github.com/aspnet/Tooling/issues/489) but I'm re-opening again.

**Comment by ArieJones** [comment]
I am having the same issue..... Is there an update to this yet? 
My particular issue was once I loaded the RC2 tooling my RC1 projects exhibited the following behavior 

1. Dependencies folder and npm folder under it show as "- not installed" 
2. When debugging the application I could no longer perform watch or quickwatch operations. Breakpoints work but are essentially useless now 

So I uninstalled RC2 tooling which should have brought me back to previous state but instead it wouldn't recognize the project formats and so my solutions would not load in VS. 

So I have reinstalled RC2 and am trying to upgrade the projects to RC2...I am using a simple class library project in a larger solution to start with and cannot get it to build because of this error ... 

So now , I cannot debug any of my RC1 projects and cannot upgrade to RC2.. .so basically Microsoft Purgatory .

**Comment by marspd** [comment]
I'm having exactly the same problem as you ArieJones. Have you managed to find a solution at all?

**Comment by ArieJones** [comment]
I had to uninstall EVERYTHING 2015...delete the associated folder for the version in program files and the MSBuild folder and then reinstall.....
When I tired to just uninstall and reinstall VS it didn't work...

This is a pretty major problem since they have this install link showing up in the notifications area in vs

**Comment by marspd** [comment]
It's taken me over 5 hours to completely remove everything and re-install VS2015 and at the end of it all......... same problem as I started with. This is so frustrating!

**Comment by dontbesorry80** [comment]
I found I had problems when installing the latest versions. However if I removed all the dot net core stuff then installed the official ones from here:
https://www.microsoft.com/net/core#windows
It seemed to work for me.

**Comment by marspd** [comment]
Thanks for the comment but I've tried that. I've tried all sorts and still no joy.

I have found that it is a VS tooling issue. If I start a command prompt the dotnet tool works and I can restore, build and run the application.

**Comment by ArieJones** [comment]
@marspd you have to ensure that you manually delete the specific version folder for BOTH visual studio and msbuild and reboot before doing a reinstall of VS

**Comment by dontbesorry80** [comment]
Yes. However, I didn't need to re-install VS just the manual uninstall of the other versions was enough for me.

**Comment by marspd** [comment]
I did all that but I guess I will have to try again tomorrow. I'm giving in for today. Thanks for the suggestions guys.

**Comment by sisovin045** [comment]
I have the same issue, I can use dotnet restore and dotnet run in console, but I have to close VS 2015 first. I have uninstall VS 2015 SP2, then reinstall, but it still have the same error above.

**Comment by marspd** [comment]
My problem was two fold. I still had a left over installation of part of the RC1 tools which I had to remove by installing RC1 again and then immediately uninstalling. I also had Telerik's JustMock which had to be removed before things would work properly.
I hope that helps some.

**Comment by ArieJones** [comment]
@marspd I am probably going to be trying again this weekend to see if I can successfully upgrade to the tooling. So are you currently on the RC2 tooling now? There are similar issues posted on the tooling site where they promised to get back with everyone but we haven't seen anything in over a week.
So more than likely MSFT is just like "YOLO, good luck with the next set of preview tools"

**Comment by marspd** [comment]
Mine is working OK now since I resolved the issues I described above. Good luck over the weekend.

**Comment by sisovin045** [comment]
@marspd, thank you. I follows your issue to remove Terelik's JustMock, which had conflict with RC2, then is working fine, I have resolved the issues as you, have the best trip over the weekend.

**Comment by piotrpMSFT** [comment]
We've spent time hardening the installer against these sorts of issues and fixing up the host to provide better messages. We should not see this sort of frustration moving forward.
