### ISSUE TITLE
dotnet uninstall debian packages fails with 1.0.0-beta-001675

### ISSUE THREAD

**Issue by michalogluszka** [dotnet/cli#3090]
## Steps to reproduce
(current documentation mention this as first step: https://www.microsoft.com/net/core#ubuntu)
- run dotnet-uninstall-debian-packages.sh

## Expected  behavior
 - Documentation to be changed, or
 - Script should remove dotnet and dotnet-host as well

## Actual behavior
`$ sudo ./dotnet-uninstall-debian-packages.sh`
Unable to find dotnet installation to remove.
But...
`$ dpkg -l dotnet`
`dotnet                                        1.0.0.001675-1`
And
`$ dotnet`
`.NET Command Line Tools (1.0.0-beta-001675)`

## Workaround
Actually I have been able to uninstall this with apt-get, so I'm not sure is this actually having an impact on anything.

## Environment data
`dotnet --info` output:
(unfortunatelly already uninstalled)
 
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

@brthor

**Comment by brthor** [comment]
Hi @michalogluszka,

The uninstallation script was only intended to remove packages created post-sharedframework, which does not include the `dotnet` package. This includes packages like `dotnet-host` and `dotnet-dev-1.0.0-preview1-002702`

This would be easy enough add, but as you noticed the fix is as simple as doing `apt-get remove dotnet`. If you were to try to install the newer packages, they have a direct declared conflict with the `dotnet` package so it can be easily understood that they are not compatible.

cc @blackdwarf @piotrpMSFT

**Comment by michalogluszka** [comment]
Thanks for explanation. I'll close this ticket. 
P.S. As I see documentation has changed already. Issue with apt-get certificates has been resolved. Good Luck!

**Comment by brthor** [comment]
no problem, thanks!
