### ISSUE TITLE
Magic sdf files

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#311]
Does anyone know why every single time I do git clean I get warning similar to this:
```
warning: failed to remove Microsoft.DotNet.Cli.opensdf
```
What's generating files with this extension? This looks like someone did:
```
Console.Write("sdf");
```
for debugging purposes and forgot to remove :smile:

**Comment by mellinoe** [comment]
It looks like "opensdf" files have something to do with C++ projects in Visual Studio. Perhaps it's because you have the solution open and it's not able to delete the file while the solution is open? If I had to guess it's probably from something CMake generates for the corehost project and can't be deleted while the project is open.

**Comment by anurse** [comment]
Yeah, these are from the Visual C++ project. It's a constant problem in any repo with C++ projects. We can remove them from the solution though, it seems like few people need to use the C++ project and the opensdf file isn't generated unless you open the projects.

**Comment by mikedn** [comment]
If they're from VC++ then you can avoid the issue if you configure VC++ to store the database in another place instead of the source directory, see VS options, Text Editor, C/C++, Advanced, Fallback Location.

**Comment by krwq** [comment]
Thanks guys! :+1: I think we can close it
