### ISSUE TITLE
[ProjectModel.Server] PMS does not send updated snapshots after restore complete and there was no .nuget/packages folder

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#3112]
## Steps to reproduce

1. Create a new WebApp wait for restore to succeed.
2. Close WebApp solution
3. go to your %userprofile%\.nuget and remove packages subfolder
4. Open WebApp solution again 
5. Restore should start and succeed but dependencies and intellisense show errors

## Expected  behavior

No errors

## Actual behavior

What is going on is when Solution opens PMS sends Dependencies snapshots with unresolved dependencies , restore triggers and then after that PMS does not send any other snapshots at all – i.e. after restore succeeded PMS does not send updated snapshots.

I see those messages in the restore output:

log  : Lock file has not changed. Skipping lock file write. Path: C:\Users\antonpis\Documents\Visual Studio 2015\Projects\1\GlobalJsonSources\WebApplication4\src\WebApplication1\project.lock.json
log  : Lock file has not changed. Skipping lock file write. Path: C:\Users\antonpis\Documents\Visual Studio 2015\Projects\1\GlobalJsonSources\WebApplication4\src\WebApplication4\project.lock.json
log  : C:\Users\antonpis\Documents\Visual Studio 2015\Projects\1\GlobalJsonSources\WebApplication4\src\WebApplication1\WebApplication1.xproj

So I guess PMS checks if lock file was changed and then sends updates. It was not changed in this case by restore. PMS needs additional checks for this scenario.

## Environment data
`dotnet --info` output:

C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by muratg** [comment]
cc  @troydai

**Comment by troydai** [comment]
Today project model server doesn't validate if the assembly path resolved in lock file are invalidate. So this is a feature request.

There are two parts for this scenario.

Project model server is passive. So it doesn't actively monitor file changes or removal. It reacts to `FileChanged` or `RestoreCompleted` request. So when `.nuget` folder is cleared, there should be the client to notify project model server about the change. It could be VS, that means VS should monitor the resolved assembly and request for dependencies update when any of these assemblies are updated/removed.

Suppose project model server is notified that resolved packages are changed. We need to add logic to project model server to validate if each single dependencies are resolved correctly. This means a big number of disk operations. Aka, performance impact.

**Comment by abpiskunov** [comment]
By RestoreComplete request - what do you mean?

**Comment by troydai** [comment]
Project Model Server is passive. That means we don't initiate the conversation. So when you remove `.nuget/packages` folder externally. The server won't react because nothing happens in its perspective. A request should be sent to the server trigger it to resolve dependencies again. That's the responsibility of client (VS).

**Comment by abpiskunov** [comment]
what is RestoreComplete you mentioned above?

**Comment by troydai** [comment]
https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-projectmodel-server/ProjectManager.cs#L203

**Comment by abpiskunov** [comment]
I just added a small change to send you DependenciesChanged request after restore complete explicitly and PMS does return new snapshots, but they are the same as they were before restore, i.e. containing error diagnostics for all packages:

 "ErrorCode": "NU1001",
      "SourceFilePath": "C:\\Users\\antonpis\\Documents\\Visual Studio 2015\\Projects\\1\\GlobalJsonSources\\WebApplication4\\src\\WebApplication4\\project.json",
      "Message": "The dependency Microsoft.AspNetCore.Hosting >= 1.0.0-rc2-final could not be resolved.",

Restore succeeded, project.lock.json was not changed.  So question:

1. why PMS sends us errors with initial snapshots when there no .nuget/packages? Lock file is in place when project opens, it did have all dependencies resolved there.
2. Why after restore succeeded and lock file not changed, after tooling requests new snapshots - old snapshots with missing dependencies are sent?

**Comment by troydai** [comment]
Answers:

1. Project model does check if folders exit only when a package description is created (https://github.com/dotnet/cli/blob/18f9018eb9a5ea100b65170adc25f3ad6752dd2e/src/Microsoft.DotNet.ProjectModel/Resolution/PackageDependencyProvider.cs#L44). Therefore in the scenario where lock file is generated, folders are removed and then open project in VS, the missing files are detected because cache is empty all project models are newly created. 

2. Once the server is up and running. The package description objects are cached. There aren't mechanism now to re-evaluate if package files are missing. Therefore no matter how many requests are sent for new dependencies, the model will not be changed.

As I mentioned, the mechanism is subjected to change to implement this feature. The server should  either 1. add new request to force re-evaluate all package dependencies' actual existence; or 2. re-evaluate every time a dependencies update is asked.

Option 1 require we add new request type to the protocol. Option 2 leave the protocol intact but introduce performance hit.

**Comment by abpiskunov** [comment]
I think neither option is good enough .. In option 1 tooling would have to monitor nuget/packages and we don't want to do that. IN option 2 PMS might have a perf impact.

What about Option3: PMS cache is refreshed if : It is empty and new RefreshDependencies or FilesChanged request sent to PMS? You would only check nuget cache folder until next successful or partially successful restore (when we send you RefreshDependencies request)?

**Comment by troydai** [comment]
One thing to remember, neither project model server or VS can actually monitor the packages cache folder because it is not deterministic. The `.nuget/packages` is used when `dotnet restore` is ran with default setting. It can be ran with `--packages` option, in that case the packages folder is customized.

To determine if a package is removed from disk, the server has to evaluate each packages description. Unless file monitor is set up for each nupkg file.

I have some question about how optino 3 withs with this scenario, too. Please help me understand it.

Here's the scenario I'm think about.
1. Open a project in VS, the server is then started.
2. Restore ran.
3. The server refresh the dependencies and set up the cache.
4. `.nuget/packages` folder is cleared. 
_At this moment, without external request, the server won't do anything._
5. Build failure in VS.
_Because lock file is not updated

**Comment by abpiskunov** [comment]
No the flow is different see my repro steps:

After you close project, then delete nuget/p packages, then open project.

At this moment PM's starts and returns us dependencies with errors. We start restore. Restore succeeds. Nuget/packages is back. We request dependencies refresh from the PM's. At this time your cache is still empty and you received a dependencies request - reevaluate your cache now since it is empty.

Thanks,
Anton

On May 18, 2016, at 6:11 PM, Troy Dai <notifications@github.com<mailto:notifications@github.com>> wrote:


One thing to remember, neither project model server or VS can actually monitor the packages cache folder because it is not deterministic. The .nuget/packages is used when dotnet restore is ran with default setting. It can be ran with --packages option, in that case the packages folder is customized.

To determine if a package is removed from disk, the server has to evaluate each packages description. Unless file monitor is set up for each nupkg file.

I have some question about how optino 3 withs with this scenario, too. Please help me understand it.

Here's the scenario I'm think about.
1. Open a project in VS, the server is then started.
2. Restore ran.
3. The server refresh the dependencies and set up the cache.
4. .nuget/packages folder is cleared.
At this moment, without external request, the server won't do anything.
5. Build failure in VS.
_Because lock file is not updated

-

**Comment by troydai** [comment]
I see. Now here's the misunderstanding: even the dependencies are unresolved, the objects are still cached. So the cache is never empty after the server is started. 

I need to try out this scenario in automation. It looks weird to me that after the restore happens the dependencies are not updated. They should be since lock files are updated. If that's the case this sounds like a legit bug.

**Comment by abpiskunov** [comment]
Yes, and the lock file is not updated by nuget since dependencies did not change in our scenario.

Thanks,
Anton

On May 18, 2016, at 7:11 PM, Troy Dai <notifications@github.com<mailto:notifications@github.com>> wrote:


I see. Now here's the misunderstanding: even the dependencies are unresolved, the objects are still cached. So the cache is never empty after the server is started.

I need to try out this scenario in automation. It looks weird to me that after the restore happens the dependencies are not updated. They should be since lock files are updated. If that's the case this sounds like a legit bug.

-

**Comment by troydai** [comment]
I assign this to myself for investigation. I'll report back for the particular issue mentioned in the later part of the discussion. For the overall feature, we need a coordinate design together with tooling to determine if it is feasible in given windows between now and RTM.

**Comment by troydai** [comment]
I tried this scenario in VS preview1 release.

1. Create a new web application
2. Restore, save and close the project.
3. Remove `.nuget\packages` folder
4. Open the project in VS

VS starts restore correctly and all packages are re-download. Afterwards, no error.

The same scenario is valid through runtime automation, too. See branch: https://github.com/dotnet/cli/tree/troy-3112.

The server returns dependencies with correct error. 

So the scenario for reopen project is coverred.

**Comment by abpiskunov** [comment]
Lets do it together today, it did repro consistently.


On May 24, 2016, at 1:27 AM, Troy Dai <notifications@github.com<mailto:notifications@github.com>> wrote:


I tried this scenario in VS preview1 release.

  1.  Create a new web application
  2.  Restore, save and close the project.
  3.  Remove .nuget\packages folder
  4.  Open the project in VS

VS starts restore correctly and all packages are re-download. Afterwards, no error.

The same scenario is valid through runtime automation, too. See branch: https://github.com/dotnet/cli/tree/troy-3112.

The server returns dependencies with correct error.

So the scenario for reopen project is coverred.

-

**Comment by troydai** [comment]
I saw the issue you mentioned. After the restore accomplish there are issues show up actually. The existence of assemblies are not reset. I'll file a new issue for that and close this one.

**Comment by troydai** [comment]
@abpiskunov https://github.com/dotnet/cli/issues/3220

**Comment by troydai** [comment]
Close as a narrowed down scenario is going to be addressed in #3220 .
