### ISSUE TITLE
DocumentationMode compileOptions

### ISSUE THREAD

**Issue by davidfowl** [dotnet/cli#312]
From https://github.com/aspnet/dnx/issues/3189

**Comment by anurse** [comment]
FYI, since we aren't using Roslyn we won't be able to have quite the same level of control. We'll have to use the `-doc` switch which will set `DocumentationMode` to `Diagnose` and emit warnings for missing doc comments. It doesn't currently appear to be possible to have `csc` generate an XML file without the warnings (though I suppose we could add the command line switch to suppress the warning as well?). I may be wrong, but that's my initial impression, doing the implementation and testing work on that now.
