### ISSUE TITLE
dotnet-install.sh tries to download a non existing tar.gz file on Debian 8

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#3152]
I am unable to install dotnet on Debian Jessie.

When executing `curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version 1.0.0-preview1-002702`, the installer reports it cannot download `https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview1-002702/dotnet-dev-debian-x64.1.0.0-preview1-002702.tar.gz`.

**Comment by tmds** [comment]
There is a file at (preview->beta) https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/1.0.0-preview1-002702/dotnet-dev-debian-x64.1.0.0-preview1-002702.tar.gz.

So probably the installer is broken by: https://github.com/dotnet/cli/commit/bf9b5a928845998cc0268cf95559aea0e559183f#diff-3385102241bcd3718b9ca13a0c55b9af
/cc @eerhardt

**Comment by eerhardt** [comment]
@tmds - If you want to install the "Preview1" bits, you should use the install scripts in the "Preview1" branch.  The scripts are versioned with the releases, so we can make changes like where the files get uploaded to in Azure, how they get laid out on disk, etc.

So instead of:

`https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh`

use

`https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh`

An advantage you get here is that it will default to the "latest" build, which is the official Preview1 build, and you don't need to pass in `--version` at all.

(Alternatively, if you need to continue using the rel/1.0.0 script, you could fix this by passing in `--channel beta` to the script.)

**Comment by blackdwarf** [comment]
@eerhardt hm, than we need to change this in the instructions.

**Comment by piotrpMSFT** [comment]
@blackdwarf yes, the instructions should point to the preview1 branch. Rel/1.0.0 is already actively working on preview2!

**Comment by blackdwarf** [comment]
This is now done. You can check out https://www.microsoft.com/net/core#debian and see it. Closing the issue with this change.

**Comment by dsgouda** [comment]
eerhardt  do you think the URL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh would also change in the future (our daily builds depend on this script), also do improvements/bug fixes to the code get posted to this branch?

**Comment by eerhardt** [comment]
> eerhardt do you think the URL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview1/scripts/obtain/dotnet-install.sh would also change in the future (our daily builds depend on this script), also do improvements/bug fixes to the code get posted to this branch?

No, `rel/1.0.0-preview1` shipped on Monday and the only time this branch will change anymore will be for servicing/hotfix changes, which will be rare, if any.

But a change like we just made to `rel/1.0.0` will not happen in `rel/1.0.0-preview1`.  That would be a huge breaking change which we wouldn't be able to make unless it was absolutely necessary (like a security issue).

**Comment by dsgouda** [comment]
Tagging @brianrob for reference
