### ISSUE TITLE
windows authentication NTLM

### ISSUE THREAD

**Issue by zigzag95** [dotnet/cli#3289]
Hello,
How to enable windows authentication.

I used to use

 var listener = app.ServerFeatures.Get<WebListener>(); if (listener != null) { listener.AuthenticationManager.AuthenticationSchemes = Microsoft.Net.Http.Server.AuthenticationSchemes.NTLM; } 

But listener is null when running from console dot net run 
and It's not null when running from VS

**Comment by piotrpMSFT** [comment]
@danroth27 can you help route this?

**Comment by danroth27** [comment]
@zigzag95 @Tratcher When running directly from a console app you are running on top of Kestrel, our cross-platform managed web server. Since Windows authentication is platform specific it is not available when running on Kestrel. When running in VS you are actually running behind IIS Express, which does support Windows authentication.

**Comment by Tratcher** [comment]
Note if you are using WebListener this has changed for RC2 as follows:
```
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseStartup<Startup>()
                .UseWebListener(options =>
                {
                    options.Listener.AuthenticationManager.AuthenticationSchemes = AuthenticationSchemes.NTLM;
                })
                .Build();

            host.Run();
        }
```
