### ISSUE TITLE
Decrease size of self contained Console App

### ISSUE THREAD

**Issue by xoofx** [dotnet/cli#3297]
Hi there,

While playing with packaging self-contained App, I tried to remove as much libraries as I can that are not used by my application or not critical. 
For instance, I removed for example the following dll:
-  `mscordbi.dll`
- `mscordaccore.dll`
-  `mscorlib.ni.dll`
- `mscorrc.debug.dll`
- `dbgshim.dll`
- `sos.dll`
- All `Microsoft.*.dll` as I'm not using them

I may have also try to run a post linker to find out which System.*dll are actually used...

Assuming I want to distribute an app, do you think it is reasonable to remove these assemblies/native dlls?
Do you have any recommendations that I would have to be careful?

Thanks!

**Comment by mellinoe** [comment]
Most of the assemblies you listed are for debugging support, so they can most likely be removed without any issue if you do not expect folks to debug the app itself (probably an okay assumption for a standalone app). `mscorlib.ni.dll` probably shouldn't be removed; it's the native-generated image of mscorlib and will improve startup time. I'm assuming you're able to delete it because `mscorlib.dll` (containing just IL) is also present.

As for the rest of the un-needed System assemblies: this is most likely because you are using the Microsoft.NETCore.App meta-package, which transitively includes a large amount of the BCL. The dependencies are not trimmed down to the set that your app actually uses, as far as I'm aware. You can instead remove that dependency and add individual BCL packages until you find a minimal set that works. You will need, at a minimum, the runtime and host packages so that coreclr and a host are included. Those packages are Microsoft.NETCore.Runtime and Microsoft.NETCore.DotNetHostPolicy.

**Comment by xoofx** [comment]
Cool, the `Microsoft.NETCore.Runtime` and `Microsoft.NETCore.DotNetHostPolicy` is already making it a bit more tiny, thanks!

**Comment by GuardRex** [comment]
@mellinoe @piotrpMSFT Curious: Why shouldn't this become a "fit 'n finish" work item? Payload size for self-contained is an issue for those of us needing this app type. If it could be knocked down several megs, that would be a huge benefit for deploying to servers.

This issue was mentioned in https://github.com/dotnet/cli/issues/2496 with ...

> standalone trades off one perf win [slightly faster] for a big perf loss [double the payload size].

... but it looks like based on your chat with @xoofx that there are some things that could be done to reduce payload size. A quick look at those yields a significant total ...

DLL | Size (KB)
------|-----------
mscordbi.dll | 1312
mscordaccore.dll | 1610
mscorrc.debug.dll | 363
dbgshim.dll | 121
sos.dll | 865
**Total** | **4271**
