### ISSUE TITLE
unable to install with latest ubuntu installers

### ISSUE THREAD

**Issue by nathana1** [dotnet/cli#3320]
## Steps to reproduce
1. Download the 3 installers linked on the home page and install in order with dpkg -i.
2. The shared host and framework both install without error but the sdk fails with this message (4371 is installed):
dotnet-dev-1.0.0-preview2-002913 depends on dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc3-004338; however:
  Package dotnet-sharedframework-microsoft.netcore.app-1.0.0-rc3-004338 is not installed.
3. Download and install the specified version directly:  https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/1.0.0-rc3-004338/dotnet-sharedframework-ubuntu-x64.1.0.0-rc3-004338.deb
4. The latest SDK now successfully installs
5. Try dotnet new and then dotnet restore.  Restore fails with this error:
Unable to resolve 'Microsoft.NETCore.App (>= 1.0.0-rc3-004338)' for '.NETCoreApp,Version=v1.0'.

## Expected  behavior
1.  Latest SDK installs with the latest host and framework.
2.  Able to build and run a new app after installation

## Actual behavior
1.  Latest SDK doesn't install with latest shared framework, it's necessary to find the correct version
2.  Not able to dotnet restore fails on a new app

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-002913)

Product Information:
 Version:            1.0.0-preview2-002913
 Commit SHA-1 hash:  b1b7caac3d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64

**Comment by avikenjale** [comment]
Same issue on Win X64.

**Comment by piotrpMSFT** [comment]
@brthor may have looked into this already, but I have some guesses as to what is going on.

The original install issue is due to a newer Shared Framework being available as `latest` while a new CLI has not yet been built. We should probably provide an additional link to install the `matching` Shared Framework in the windows of time wherein `latest` is newer than `matching`. I created issue https://github.com/dotnet/cli/issues/3416 to track this.

The issue with `Microsoft.NetCore.App` is likely due to a missing NuGet feed. We only put named releases on NuGet.org which means that interim builds like the one you are trying to install do not have their NuGet packages available without explicitly referencing https://dotnet.myget.org/F/dotnet-core/api/v3/index.json.

@avikenjale's workaround works because it pulls in the latest named release of the Shared Framework, namely RC2.

**Comment by piotrpMSFT** [comment]
@nathana1 please try adding the above referenced myget feed to your NuGet configuration and give restore a shot. Alternatively, you can do `dotnet restore -f https://github.com/dotnet/cli/issues/3416`

**Comment by brthor** [comment]
The issues are as @piotrpMSFT stated here. 

I think the right fix is to move the `latest` .NET Core installers to the readme of https://github.com/core-setup and only reference the compatible .NET Core installers from the cli readme.

We can add it to the update-dependencies script so the link is updated appropriately.

**Comment by piotrpMSFT** [comment]
I'm pushing this out to preview3 now that it's understood. If we can fix this sooner that would be great, but it's not release blocking as-is.

**Comment by bitcrazed** [comment]
Is "able to install .NET on Ubuntu" not a release blocker?

**Comment by brthor** [comment]
You are still able to install .NET via the debian feeds, it's using the explicit .deb download links on the cli page which is broken because they are not targetting the correct versions of .NET Core and the Host

**Comment by xplicit** [comment]
@brthor Where are these feed located? Readme page points only to https://dotnetcli.blob.core.windows.net/dotnet/preview/Installers/Latest/dotnet-host-ubuntu-x64.latest.deb ... deb files

**Comment by brthor** [comment]
See here: https://www.microsoft.com/net/core#ubuntu

**Comment by brthor** [comment]
You can install latest via 
`apt-get install dotnet-dev-1.0.0-preview2-003091`

**Comment by bitcrazed** [comment]
@brthor Many thanks
