### ISSUE TITLE
Can't reference Microsoft.TeamFoundation.Client in net461 app

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/cli#3460]
## Steps to reproduce
1. Create a new .NET Core App
2. Change framework to net461 instead of netcoreapp1.0
3. Try to add a reference to framework assembly "Microsoft.TeamFoundation.Client"
## Expected  behavior

I expect that it would be added and can compile against
## Actual behavior

It doesn't show up in the project.json intellisense, and when I try to add it via the reference dialog, I don't see it and get the following error when I browse to it:

> .NET Core projects only support referencing .NET framework assemblies in this release. To reference other assemblies, they need to be included in a NuGet package and reference that package

I can create a nuget package for it, but I consider it a regression from the previous console experience. In case someone is wondering why I'm using a the cli for this is because it references other libraries which are .NET Core projects.
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by twsouthwick** [comment]
This seems related https://github.com/dotnet/cli/issues/1681, but having to create a nuget package to reference something in the GAC is a bad experience.

**Comment by pfedotovsky** [comment]
I have exactly the same issue - need to reference a bunch of DLLs within ASP.NET Core project. I don't want to create a nuget package, because I need to constantly update it whenever dlls are changed.
Please add support for referencing DLLs!

**Comment by blackdwarf** [comment]
There are two issues here:

1. **Allow adding a reference to the GAC** - this was not supported in the project.json tools and it seems that it will not be supported in the current MSBuild-based SDK. The issue for this, however, should live in dotnet/sdk repo.
2. **Allow adding DLL references** - this is a core MSBuild capability and it is supported via standard `<Reference>` element. I would advise against this, of course, given how brittle that makes the project if they move around. But, in general it is supported in the latest. 

With the above, I will close this issue since the core problem is actually in the SDK now. If you feel this is in error, please reopen. Thanks!
