### ISSUE TITLE
[Win7 Sp1 x86] Run the project do F5, pop up“a debug component is not installed”

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#3473]
INSTALL STEPS
Win7 Sp1 x86 ENU+Dev14 U3 RC VSP + DotNetCoreRTWTooling
DotNetCoreRTWTooling build: DotNetCore.1.0.0.RC3-25-VS2015Tools.Preview2.exe 
 
REPRO STEPS
1.File > New Project > ASP.NET Core Web Application->Web application
2. Select "Web Application" template in the One Asp Net dialog, change authentication to "Individual Accounts"
3.build and run
 
ACTUAL
do F5,meet error
![image](https://cloud.githubusercontent.com/assets/8246794/15947437/4fff6bde-2e50-11e6-8af0-01e6a235e19a.png)

ADDITIONAL INFO
 
Also, check if it reproduces with following configurations:
1."Win7 Sp1 x86 + Dev14 U2 VSP + DotNetCoreRC2Tooling" : not repro
2."Win7 Sp1 x86 + Dev14 U2 VSP + DotNetCoreRC2Tooling + Dev14 U3 RC" : not repro

**Comment by mikem8361** [comment]
@noahfalk, @BillHiebert, @gregg-miskelly 

It looks like the problem is when mscordbi.dll is attempting to load mscordaccore.dll: 

```
'devenv.exe' (Win32): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc3-004338\mscordaccore.dll'. Cannot find or open the PDB file.
'devenv.exe' (Win32): Unloaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0-rc3-004338\mscordaccore.dll'
Exception thrown at 0x75DAD3CF in devenv.exe: Microsoft C++ exception: HRException at memory location 0x168EF708.
```
It looks like the dac is loaded and then unloaded, but  CORDBG_E_DEBUG_COMPONENT_MISSING is thrown because LoadLIbrary returns a ERROR_MOD_NOT_FOUND in shimprocess.cpp:

 ```
    hDacDll.Assign(WszLoadLibrary(wszAccessDllPath));
    if (!hDacDll)
    {
        DWORD dwLastError = GetLastError();
        if (dwLastError == ERROR_MOD_NOT_FOUND)
        {
            // Give a more specific error in the case where we can't find the DAC dll.
            ThrowHR(CORDBG_E_DEBUG_COMPONENT_MISSING);
        }
        else
        {
            ThrowWin32(dwLastError);
        }
    }
    hDacDll.SuppressRelease();
    return (HMODULE) hDacDll;
```
It looks like the dbgshim.dll in `C:\Program Files\Microsoft Visual Studio 14.0\Common7\Packages\Debugger\dbgshim.dll` is used to launch this process. Gregg is that the shim that is supposed to be used for .NET Core (coreclr) project?

**Comment by gregg-miskelly** [comment]
@mikem8361: Yup, we use the same dbgshim for all CoreCLR debugging. I am assuming this is trying to load DAC or DBI? Did you try running depends on them or using loader snaps to see what is missing?

**Comment by mikem8361** [comment]
I realized after that the question about dbgshim is kind of moot.  DBI is already loaded (dbgshim was successful) and it is trying to load the DAC and that fails.  I’m still coming up to speed on how to debug this.  I’ve been debugging Linux/OSX issues too much and haven’t done much recently on win7/x86.

**Comment by gregg-miskelly** [comment]
@mikem8361 you want to enable loader snapper which you can do from gflags.exe. Since this in Win7 only, my guess is that the problem is going to be that mscordaccore.dll is depending on API set dlls, and either these dlls are missing, or the call is being made without the LoadLibraryEx flag to indicate that the directory containing the dll should be searched.

**Comment by mikem8361** [comment]
Depends says it can't find these modules:

API-MS-WIN-SHCORE-SCALING-L1-1-0.DLL
DCOMP.DLL
IESHIMS.DLL

Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: A circular dependency was detected.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

**Comment by mikem8361** [comment]
gflags.exe doesn't seem available on the repro machine.

**Comment by mikem8361** [comment]
The LoadLibraryEx used is passing 0 for the flags.

**Comment by noahfalk** [comment]
@mikem8361 - gflags is just a gui wrapper around setting registry keys. You can either set them directory or copy gflags from any other machine that does have it. I think it is part of the Windows SDK. Here is a page that mentions the underlying registry key though I have never done it that way so I can't confirm this is correct:
http://www.codeproject.com/Articles/35205/Loader-snaps

If its helpful the behavior I would expect to see is that mscordaccore.dll in that directory depends on the api set shims (long dlls with names like api-ms-*.dll). All of those shims should be colocated in the same directory as coreclr and mscordbi and when loaded they will forward all the calls to existing system dlls such as kernel32.dll. Obviously something isn't going according to plan of course, but this should give you a baseline to compare the current behavior against.

**Comment by gregg-miskelly** [comment]
@noahfalk @mikem8361 the default search order for LoadLibrary will NOT check next to the dll being loaded. I think we want to use the 'alternate' search order. See 'Standard Search Order for Desktop Applications' in https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx.

**Comment by mikem8361** [comment]
Not repro.
