### ISSUE TITLE
Error dialog when trying to run a test from dotnet

### ISSUE THREAD

**Issue by Chrisboh** [dotnet/cli#3505]
## Steps to reproduce

dotnet new -t xunittest
dotnet restore
dotnet run
## Expected  behavior

I would expect the test cases to run.  If we are forcing the user to have to run dotnet test then we should tell them so for this project type.
## Actual behavior

Nothing runs and you get an exception.

Unhandled Exception: System.MissingMethodException: Entry point not found in assembly 'test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

You also get an annoying dialog on OSX.
## Environment data

`dotnet --info` output:

**Comment by blackdwarf** [comment]
@Chrisboh you need to use `dotnet test`. We have docs that show this: https://dotnet.github.io/docs/core-concepts/testing/unit-testing-with-dotnet-test.html. However, I will leave this issue for RTM (of tooling) since the suggestion of having custom messages after dropping a template could be a good feature for the new `dotnet new`. 

/cc @sayedihashimi

**Comment by sayedihashimi** [comment]
For the final RTM version we should be able to display next steps which are specific to each template. 

cc @mlorbetske

**Comment by piotrpMSFT** [comment]
Moved to https://github.com/Microsoft/vstest/issues/367
