### ISSUE TITLE
We should shut off tests in our official VSO builds

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#3527]
Our build takes away too long for such a small product.  We should consider not running tests on our official VSO bulids. Our tests take up the bulk of the time in an official build. The "Test and Package" step in our Win x64 build takes 35 minutes, while the entire build takes 66 minutes.

Instead, we can have a "rolling CI" build on the side running the tests. That way the official build can be published as fast as possible - which is necessary when we want to spin multiple re-builds of the whole .NET Core stack.

@Petermarcu @piotrpMSFT @brthor @livarcocc

**Comment by piotrpMSFT** [comment]
Our tests are also very wasteful. We rebuild the same artifacts many times in order to test. We need to eliminate the .nobuild files, replace them with better segregation of Test Assets, build those just once, and re-use the artifacts. We do not perform 35 minutes of valuable testing during these builds.

If we wanted to reduce the test coverage during VSO builds I don't think we should go to 0. At a minimum, we should be running our end-to-end tests. i also think this strategy would require that we prevent any merges that do not pass full CI.

**Comment by brthor** [comment]
What is the benefit of publishing a potentially broken build though? If we're spinning builds more often, but waiting the same (or longer) time for test results that doesn't make us more productive in resolving issues in the cli. It will make publishing potentially broken builds faster though. 

We've seen a number of issues that only repro'd in VSO for whatever reason in the lifetime of the CLI.

I think a perf effort on our tests would be more valuable in reducing the time to publish our VSO builds without reducing coverage. One way we can go about this is to reduce the number of tests we have that require process hopping or invoking CSC, and increase unit test coverage. @livarcocc has been talking about this while.

**Comment by piotrpMSFT** [comment]
If we wanted to reduce test time in VSO, we'd need to start tracking the builds of a SHA that have been already accomplished in Jenkins and bypass only those. A blanket disabling of tests in VSO will only get us into trouble as time passes.

**Comment by eerhardt** [comment]
This is how CoreFX and CoreCLR build.

@ellismg @weshaggard @ericstj @stephentoub  to weigh in on whether this practice is working for those repos.

**Comment by ellismg** [comment]
> to weigh in on whether this practice is working for those repos.

We haven't had any major problems.  One of the reasons we build this way is that we have tons of test projects and we want to be able to do as much work in parallel as possible.  As part of our official build, we kick off test runs in Helix, which gives us coverage for all inner and outerloop tests.  The test runs complete much quicker than building on the build machines because we have 10-20 machines that service each test queue.

We haven't seen many cases where we have a build that builds but doesn't run.  Jenkins has been doing a good enough job of guarding us there.

I would expect as we increase our testing infrastructure we would start segmenting how we tag our builds.  Latest would be "it just built" and "LKG" may become "it passed all our inner-loop and outer-loop testing".

We have seen a few cases in the past where cross repository testing caught issues (e.g CoreCLR broke us in some subtle way) but this is something that wasn't seen in their tests, so just running there tests as part of build wouldn't have helped us at all.

**Comment by weshaggard** [comment]
To be clear in our official builds for corefx we do separate our product and test builds but we do still run them as part of our official builds, but we don't block publishing the product on those results. However we do still have test results for every build. 

For our CI systems we do build and test of Inner loop tests only which is a smaller faster set of tests so that is also something worth considering for CLI.

**Comment by livarcocc** [comment]
Is this still up for discussion? I will close it for now. Re-activate if you still want to do this.

**Comment by eerhardt** [comment]
I still want to do this.  Until we can get 100% non-flaky tests in our official builds, we need to be able to shut off tests so we can get CLI builds out in a pinch.

See 
https://mseng.visualstudio.com/dotnetcore/_build/index?buildId=3299515
https://mseng.visualstudio.com/dotnetcore/_build/index?buildId=3298376

for two failing official builds that block us from getting a new build out.

**Comment by piotrpMSFT** [comment]
The code is in place, but we need to update build definitions.

**Comment by piotrpMSFT** [comment]
updated rel/1.0.0
