### ISSUE TITLE
[ProjectModel.Server] When project.json syntax error added during restore there should be no "Dependencies unresolved" errors.

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#3539]
## Steps to reproduce

1. Create a new Web App
2. While initial restore is stil runing, open project.json and add a 'a' after some "dependnecy":"version", (comma)

## Expected  behavior

after initial restore complete, dependnecies should be resolved and there should be only syntax error for project.json

## Actual behavior

Lots of "Dependency unresolved" errors

## Environment data
`dotnet --info` output:

C:\Windows\system32>dotnet --info
.NET Command Line Tools (1.0.0-preview2-002966)

Product Information:
 Version:            1.0.0-preview2-002966
 Commit SHA-1 hash:  b512ddb8b8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by troydai** [comment]
Project model server works as it is designed in this case:

1. A new project is created, project model server is started to initialize the project.
2. The server sends dependency diagnostics because lock file is missing at this point. There diagnostics are shown as errors/
3. Restore begins.
4. User accidentally faults the project.json.
5. Restore finishes. VS sends "Files Changed" request.
6. Because of the faulted project.json, the server returns single "Error" message. Note the "Dependencies diagnostics" are not sent because the wrong project.json interrupted remaining work.
7. Error list is not cleared.

I suggest wont fix.

**Comment by abpiskunov** [comment]
Well, if we want things to be better, step 6, before sending single error should make sure there no other Diagnostics hanging around, i.e. should send empty Diagnostics first to clean error list from previous restores and then send a single error for current file changed event..

However i will leave it to your to decide if issue meets the priority bar.

**Comment by troydai** [comment]
Close as won't fix base on discussion with @piotrpMSFT . @abpiskunov can you remove the `blocking-partner` tag?
