### ISSUE TITLE
How to build a library for both UWP and WinRT?

### ISSUE THREAD

**Issue by xperiandri** [dotnet/cli#3561]
I have some extension for Windows.Data.Json which work for WinRT as well as for UWP.
How can I set up `project.json` to target UWP and WinRT (Phone and Desktop)?

``` Json
{
  "version": "1.0.0-*",

  "frameworks": {
    ".NETPortable,Version=v4.6,Profile=Profile151": {
      "frameworkAssemblies": {
        "System.Windows": ""
      }
    },
    "uap10.0": {
      "buildOptions": {
        "define": [ "WINDOWS_UWP" ]
      },
      "dependencies": {
        "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0"
      }
    }
  }
}

```

**Comment by ericstj** [comment]
Related to : https://github.com/dotnet/cli/issues/583

DotNET CLI doesn't support producing such libraries yet since it doesn't plug into the msbuild-based extension SDK system that defines the windows surface area (windows.winmd), as well as all the targets used by that project type for dealing with resources (eg: pri files), xaml, etc.  

As @onovotny pointed out [here](https://github.com/Reactive-Extensions/Rx.NET/pull/151#issuecomment-187163471) you could use the technique used in Corefx, but I suspect you'd just hit more issues trying to use DotNET CLI to build a UWP-specific library as I hinted above.

**Comment by xperiandri** [comment]
Is this a right approach?
``` JSON
{
  "version": "1.0.0-*",

  "frameworks": {
    ".NETPortable,Version=v4.6,Profile=Profile32": {
      "imports": "dotnet5.1",
      "frameworkAssemblies": {
        "mscorlib": "",
        "System": "",
        "System.Core": "",
        "System.Collections": "",
        "System.Globalization": "",
        "System.Linq": "",
        "System.Linq.Expressions": "",
        "System.Reflection": "",
        "System.Reflection.Extensions": "",
        "System.Runtime": "",
        "System.Runtime.Extensions": "",
        "System.Runtime.InteropServices": "",
        "System.Windows": ""
      },
      "dependencies": {
        "Microsoft.TargetingPack.Private.WinRT": "1.0.1"
      }
    },
    "uap10.0": {
      "buildOptions": {
        "define": [ "WINDOWS_UWP" ]
      },
      "imports": "dotnet5.4",
      "dependencies": {
        "Microsoft.NETCore.UniversalWindowsPlatform": "5.2.0",
        "Microsoft.TargetingPack.Private.WinRT": "1.0.1"
      }
    }
  },
  "buildOptions": {
    "xmlDoc": true
  }
}
```

**Comment by ericstj** [comment]
Like I said, you probably shouldn't be using DotNET CLI for building libraries targeting WinRT due to the lack of proper support.  If it works for you that's all I can say: it works for you today.  It's not something that's officially supported.  You're better off using the VS project types that are specifically designed for that support, DotNET CLI doesn't bring much new to the table for these project types.

**Comment by blackdwarf** [comment]
I'm going to close this issue with @ericstj answer as the correct guidance moving forward.
