### ISSUE TITLE
'dotnet new' stuck inside Docker

### ISSUE THREAD

**Issue by marwooj** [dotnet/cli#3585]
## Steps to reproduce
Install inside docker:
https://www.microsoft.com/net/core#docker
and run:
dotnet new

## Expected  behavior
Should end and give control to console.

## Actual behavior
This will write:
Created new C# project in /root/.
And will not end.
Projects files are created, but I have to kill docker and start container again.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     debian
 OS Version:  8
 OS Platform: Linux
 RID:         debian.8-x64

**Comment by dleeapho** [comment]
@marwooj this sounds similar to [`latest` image freezes immediately after running `dotnet new` #26](https://github.com/dotnet/dotnet-docker/issues/26). Can you verify your Docker environment (version and host kernel version) to see if it fits with the root cause [Docker #18180](https://github.com/docker/docker/issues/18180#issuecomment-193708192)?

**Comment by naamunds** [comment]
@marwooj Are you still seeing this issue?  Have you been able to verify if it was caused by [Docker #18180](https://github.com/docker/docker/issues/18180#issuecomment-193708192)?

**Comment by naamunds** [comment]
Closing issue.  If you have additional questions or issues, please let us know or log a new issue.
