### ISSUE TITLE
Change dotnet "restore" 

### ISSUE THREAD

**Issue by clrjunkie** [dotnet/cli#360]
The word "Restore" strongly suggests "problem".

I think a better naming would be:

dotnet update

or 

dotnet sync

**Comment by davidfowl** [comment]
Restore is the verb that nuget uses and we chose to keep it consistent (tbh I don't see that changing).

**Comment by clrjunky** [comment]
You normally do "restore" is after a "crash"

if you really want to emphasize downloading then::

"dotnet pull" or "dotnet fetch" would be better.

But I think "dotnet update" is the simplest, you bring yourself up to date with what you need.

**Comment by clrjunky** [comment]
Think happy :)

**Comment by anurse** [comment]
Restore has been used throughout NuGet's history (https://docs.nuget.org/consume/package-restore), I think we'd prefer to keep in sync with all the existing NuGet documentation rather than create a new concept. In an ideal world, maybe a name change could be useful but I think consistency is more important here.

**Comment by clrjunky** [comment]
There is no new concept...

dotnet update restores nuget packages.

Sorry but in my opinion "restore" makes the OOB ugly. 

Nuget history is .net history not *nix/mac history and quite frankly I don't recall ever using NuGet Package Restore.

But that's just my 2c...

**Comment by krwq** [comment]
I personally would like `dotnet install` best although IMO restore doesn't sound too bad (or maybe I could've got used to that name).

`update` suggests that you want to bump versions to me which is not what is happening.
`restore` literally would mean what you described although it kind of made sense in VS when you think of experience of installing nuget package and then restoring it. In here it doesn't necessarily is accurate
`install` I think should both download and add it to the project so if we keep existing behavior that's not gonna be accurate name either.
`download` or `get` wouldn't be too bad too

**Comment by clrjunky** [comment]
My intention with "update" was to convey updating your project to include all required dependencies (as apposed to "upgrade")

However, I agree this also suggests a version bump. "Install" is better than "Restore" but by the same intuition it sounds to me a bit weird since "dotnet" is already installed so why do I need to do install again.

After giving this further thought I think what really bothers me is the initial experience, where you need to "fix" something after you installed it.

A "Restore" might be appropriate when there is a problem (the rare case) in which case "nuget-restore" would be more clear.

I don't know what "donet init" does aside from creating the project template, so given that purpose why can't it download the dependencies as well?

If there is a true need to separate the processes than "dotnet sync" is also a good alternative to "restore".

**Comment by clrjunky** [comment]
Actually "package-restore" (not nuget-restore) for the point above...

**Comment by krwq** [comment]
I agree more intuitive would probably be `dotnet package install` although I think this is quite popular convention to shorten it to just `intstall`. Restore I agree can be interpreted quite negatively.

Currently the reason `dotnet init` requires `restore` is because we currently don't have a mechanism for auto-downloading framework packages although that is in our plans.

The final goal for why we require `dotnet restore` (or whatever the final name will be) is because packages in general can come from any sources and that comes with a certain risk. I.e.: we don't want to auto download some 5GB evil package for you and want to only download what we call trusted source which in the end will be our own libraries and perhaps maybe customizable. Currently that mechanism is not implemented yet.

**Comment by clrjunky** [comment]
Sounds like we're on the same page :)

**Comment by krwq** [comment]
:smiley:  :+1:

**Comment by blackdwarf** [comment]
I don't think we are going to change the "restore" verb any time soon. :) Closing this. Please reopen if it is still needed.
