### ISSUE TITLE
Project is not recompiled if app.config is changed

### ISSUE THREAD

**Issue by pfedotovsky** [dotnet/cli#3605]
## Steps to reproduce

Sample project to reproduce the problem: http://github.com/pfedotovsky/aspnet-tests
1. Compile (`dotnet publish`)
2. Change app.config, e.g. add new endpoint
3. Run `dotnet publish` again
## Expected  behavior

**.exe.config** file should be changed in output directory
## Actual behavior

"Project AppConfigIssue (.NETFramework,Version=v4.5.2) was previously compiled. Skipping compilation."

Resulting **.exe.config** file doesn't have any changes.
## Environment data

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
Looking at the repro, the key issue is that the script that was specified in the `postCompile` directive is not ran since the compilation is skipped. In MSBuild, this is easily solved using the targets and the script would, if I read it correctly, be replaced with a custom target that invokes a `<Copy>` task that is ran after `Build` or `CoreCompile` task. This will ensure that the task runs after compiling the code, and it will run regardless of whether the code was compiled beforehand. You can learn more about the `<Target>` element on the [official docs](https://msdn.microsoft.com/en-us/library/t50z2hka.aspx). 

A small example of such a target follows:

```xml
<Target Name="CopyTest" AfterTargets="Build;">
    <Copy SourceFiles="app.config" DestinationFiles="$(OutputPath)\app.exe.config" />
</Target>
```

I also tested out the repro and any change in app.config is copied over to the build output. 

With this, I will close this issue as resolved by the latest tools and moving to MSBuild. If you think this was in error or this problem repros on latest, please reopen.
