### ISSUE TITLE
RC2 compiles much slower than RC1

### ISSUE THREAD

**Issue by ryanhall27** [dotnet/cli#3609]
## Steps to reproduce

2 sample projects to reproduce the issue.
https://github.com/ryanhall27/Compile-RC1
https://github.com/ryanhall27/Compile-RC2

Simply open in Visual Studio and do a Rebuild several times.  You will see that the RC2 project always takes a minimum of 1 second to build, while the RC1 takes .01 seconds to build.  Screenshot provided below.

![rc1vsrc2compile](https://cloud.githubusercontent.com/assets/3359985/16105571/33d1e85a-3351-11e6-9b31-d0bc885c4b48.jpg)

Most of my solutions have around 5 class libraries + 1 MVC website.  So over time, 6 seconds vs 0.06 seconds really adds up.
## Expected  behavior

Fast compile times
## Actual behavior

Slow compile times
## Environment data

See sample projects.

**Comment by piotrpMSFT** [comment]
Anecdotaly, since starting the transition to csproj after preview2 we've seen the CLI build times improve by > 60%. Of course, we cannot say that this was all due to swapping the build engine since many other changes and improvements went in. However, the overall experience and feeling is much faster.

I'm going to close this since we no longer have project.json code to improve but will be looking forward to hearing folks' thoughts on Preview3 perf.
