### ISSUE TITLE
RID on Linux Mint is set to `ubuntu.14.04` instead of `linuxmint.17`

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#3615]
CLI sets the RID for Linux Mint as Ubuntu. Although the distros are basically is the same, there are still [separate RIDs](https://github.com/dotnet/corefx/blob/release/1.0.0/pkg/Microsoft.NETCore.Platforms/runtime.json#L309-L334) for `linuxmint.17` and `ubuntu.14.04`. CLI should set the RID appropriately.
## Linux Mint 17.2

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003116)

Product Information:
 Version:            1.0.0-preview2-003116
 Commit SHA-1 hash:  3022ef6759

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
```

`uname -a` output:

```
Linux mint17 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

`/etc/os-release`

```
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
```

**Comment by piotrpMSFT** [comment]
@natemcmaster CLI gets the Rid from [PlatformAbstractions](https://github.com/dotnet/core-setup/blob/master/src/Microsoft.DotNet.PlatformAbstractions/Native/PlatformApis.cs#L100) which in turn reads the OS name from `/etc/os-release`. As you said, Mint self-reports as Ubuntu which causes this behavior. Since RIDs need to be consistent across consumers in the dotnet ecosystem, it's PlatformAbstractions that needs to be updated. CLI can then pick up the new version.
