### ISSUE TITLE
CLI builds should produce SHA hashes for artifacts

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/cli#3693]
The CLI builds should be producing SHA hashes for the various artifacts that customers would download on their machine.  This will allow them to do checksum verification to ensure MITM has not occurred.  

This is needed for the [.NET Dockerfiles](https://github.com/dotnet/dotnet-docker) as it is part of the criteria for making the .NET images official Docker images.

@blackdwarf

**Comment by blackdwarf** [comment]
Yeah, this is a good point, we should really be doing this.

**Comment by brthor** [comment]
Fully believe these hashes should also be signed, or they offer only a minimal guarantee of integrity.

**Comment by blackdwarf** [comment]
@brthor agreed.

**Comment by naamunds** [comment]
Here is the plan for this work:
- Add logic to the CLI builds to generate the hashes for each installation artifact.  The hashes would be calculated without relying on PRSS support, as in Zlatko’s PS script.
- Also as part of the CLI builds, upload the hashes to Azure Storage, using a separate storage account for added security.
- The hashes would not be signed, because we would be providing them as a way of verifying file integrity and as a weaker way of verifying file authenticity than file signing.  Storing the hashes in a different location (using a separate account) from the artifacts themselves would reduce the probability of a MITM attack affecting both.  If we deem that insufficient and want to provide signing as a stronger method of verifying authenticity, we should consider signing the installation artifacts themselves.  (In correction to Michael’s email, my understanding from Livar is that the DLLs and MSIs are currently being signed, but the other installation artifacts are not.)

I'll work with @blackdwarf to implement this.
