### ISSUE TITLE
dotnet build fails on os x with nuget errors, restore works

### ISSUE THREAD

**Issue by Feasoron** [dotnet/cli#3702]
## Steps to reproduce

With my project, I run dontet restore, and it restores fine. On dotnet build, I get an error for every package.
## Expected  behavior

The code compiles (or at least attempts to)
## Actual behavior

A line for every dependency along the lines of
/project.json(15,50): error NU1001: Microsoft.AspNetCore.Hosting >= 1.0.0-\* could not be resolved.
## Environment data

`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.11
 OS Platform: Darwin
 RID:         osx.10.11-x64

**Comment by dlebedynskyi** [comment]
@Feasoron  did this started recently? we are getting issues like 
```

Errors in D:\ws\4700-UI-CI\Equity\src\Equity.Web\project.json
    System.Linq.Expressions 4.1.0 provides a compile-time reference assembly for System.Linq.Expressions on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win10-x64.
```
for every package. Was fine on friday. trying to figure out whats going but it fills like we start getting rc3 while rc3 was expected

**Comment by Feasoron** [comment]
That 90% did it for me as well. I still have a third party MyGet package failing.

**Comment by am11** [comment]
Not quite sure whether we are hitting the same issue (or our issue solely belongs to NuGet or Azure Media Service), but these steps to repro might be related: projectkudu/kudu#2173.

Kudu environment is using dotnet `1.0.0-preview2-003131` and we use `nuget restore` instead of `dotnet restore` because our solution (`sln`) is hybrid of `xproj` and `csproj` typed inter-dependent projects, which only `nuget restore` seems to handle. Moreover, Kudu environment has NuGet v3.5 RC in PATH by default.

We have many dependencies in our project and only [Azure media service extensions](http://www.nuget.org/packages/windowsazure.mediaservices.extensions/) package breaks the build, thereby the auto-deployment. However, the package gets restored successfully with NuGet v3.5 RC. If we instead use NuGet v3.4, all the packages (including AMS ext.) still get restored successfully and the build succeeds.

cc @davidebbo, @yishaigalatzer

**Comment by davidebbo** [comment]
It's a casing regression in nuget 3.5. See details in https://github.com/projectkudu/kudu/issues/2173#issuecomment-252437048. Though I don't know if it's the same issue that @Feasoron has.

**Comment by yishaigalatzer** [comment]
I believe this change is breaking the preview scenarios by design. Prior to it package ids are case sensitive on a case sensitive file system, and they are truly case insensitive. So now everything is normalized to lower case. You should clean the caches and all packages and start again. However you need a matching cli that can do it correctly (not sure about this detail Joel will know more)


________________________________
