### ISSUE TITLE
Building mixed project solutions with shared dependencies fail with file access errors

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/cli#3740]
## Steps to reproduce

Have two Test projects, one with the new project.json (Proj A) format targeting .NET 4.6.1 and one with the old format (Proj B).
Have both reference Xunit libraries including visual studio test runner '2.2.0-beta2-build1149'.

(see attached repro)
[XunitFileInUseRepro.zip](https://github.com/dotnet/cli/files/341341/XunitFileInUseRepro.zip)
## Expected  behavior

Building the project in Visual Studio 2015 U3 succeeds.
## Actual behavior

Error:
Failed to make the following project runnable: CoreProject (.NETFramework,Version=v4.6.1) reason: The process cannot access the file 'c:\temp\repro\xunitfileinuserepro\packages\xunit.runner.visualstudio.2.2.0-beta2-build1149\build_common\xunit.abstractions.dll' because it is being used by another process. CoreProject C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets  262 

Notes:
I imagine this is a concurrency problem, due to two different build tools trying to copy the referenced file around at the same time.

In MSBuild there is a retry mechanism if the file is in use (MSBUILDALWAYSRETRY=1).
Something similar should be implemented for the dnx toolchain.

Atleast on  my system the problem is 100% reproducable. Your mileage might vary based on system performance (e.g. virus scanners).
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by balmeras** [comment]
I'm facing a similar issue (error : Failed to make the following project runnable: TestBuildError2 (.NETCoreApp,Version=v1.0) reason: The process cannot access the file 'c:\users\bertrand\.nuget\packages\xunit.core\2.1.0\build\_desktop\xunit.execution.desktop.dll' because it is being used by another process.)

I've managed to build the project by manually hacking the project.fragment.lock.json file.
However each time this file is regenerated, I have to manually edit it again. So it's not ideal.

[TestBuildError2.zip](https://github.com/dotnet/cli/files/406518/TestBuildError2.zip)

**Comment by pvlakshm** [comment]
@piotrpMSFT this issue seems to be related to build (and is probably already mitigated in preview3+ tooling?). If so, can this issue be closed?

**Comment by blackdwarf** [comment]
@pvlakshm I think you are right. This should not happen in the new world since we don't have two build systems.

**Comment by blackdwarf** [comment]
Will close this one. If it repros again by any chance, please reopen. Thanks!
