### ISSUE TITLE
dotnet pack fails with "Unable to find a project.json in src/**/project.json"

### ISSUE THREAD

**Issue by JorritSalverda** [dotnet/cli#3771]
## Steps to reproduce

When running a build on AppVeyor the restore and build steps work fine, but the dotnet pack cannot find project.json.

My appveyor.yml has at least the following parts:

```
image: Visual Studio 2015

build_script:
- dotnet restore --no-cache
- dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
- dotnet pack src/**/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER% --no-build
```

On my mac with os x this works fine. I tested `dotnet pack **/project.json` as well - without src/ - but it doesn't make a difference.
## Expected  behavior

Expect that it packs all projects inside the src/ directory.
## Actual behavior

Results in the following error

`Unable to find a project.json in src/**/project.json`
## Environment data

`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)
Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5
Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
```

**Comment by OzieGamma** [comment]
Seems like dotnet pack doesn't support globbing https://github.com/dotnet/cli/issues/3366

**Comment by piotrpMSFT** [comment]
the preview3 CLI will require a pack invocation to include a full path to a csproj or to be kicked off in the directory that contains a csproj. Looking forward, performing operations on multiple projects with one invocation will be done via .sln files. So `dotnet pack path/to/my.sln` will likely pack all the projects in that sln. This hasn't been fully designed yet.

I'm closing the issue since we're not planning to support globbing for these sorts of operations. However, you should be able to use shell globbing with piping to achieve similar goals.
