### ISSUE TITLE
dotnet publish will missing libuv.dylib when runtime set to osx

### ISSUE THREAD

**Issue by Haraguroicha** [dotnet/cli#3791]
## Steps to reproduce

dotnet publish -r osx.10.10-x64
dotnet publish -r osx.10.11-x64
dotnet publish -r osx.10.12-x64
## Expected  behavior

copy `libuv.dylib` into `bin/{Target}/{framework}/{runtime}/` folder during building the source and `dotnet run` will not display any exceptions
## Actual behavior

`dotnet publish` on ubuntu 14.04 and OS X 10.12 and copy back to OS X, then run `dotnet run` then:
Unhandled Exception:
System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: libuv

after execute `cp ~/.nuget/packages/Libuv/*/runtimes/osx/native/libuv.dylib ./bin/{Target}/{framework}/osx*/` then `dotnet run` again, it will not display exception
## Environment data

`dotnet --info` output:
1. on ubuntu 14.04
   
   ```
   $ dotnet --info
   .NET Command Line Tools (1.0.0-preview2-003121)
   
   Product Information:
   Version:            1.0.0-preview2-003121
   Commit SHA-1 hash:  1e9d529bc5
   
   Runtime Environment:
   OS Name:     ubuntu
   OS Version:  14.04
   OS Platform: Linux
   RID:         ubuntu.14.04-x64
   ```
2. on OS X 10.12
   
   ```
   $ dotnet --info
   .NET Command Line Tools (1.0.0-preview2-003121)
   
   Product Information:
   Version:            1.0.0-preview2-003121
   Commit SHA-1 hash:  1e9d529bc5
   
   Runtime Environment:
   OS Name:     Mac OS X
   OS Version:  10.12
   OS Platform: Darwin
   RID:         osx.10.12-x64
   ```

**Comment by blackdwarf** [comment]
This is fixed in the MSBuild-based tools. If you install the latest from this repo and then do `dotnet new` and add the following: `<RuntimeIdentifiers>ubuntu.14.04-x64;osx.10.11-x64</RuntimeIdentifiers>` and then restore and publish with that runtime, you will see `libuv.dylib` in the output folder.

Will close this as mitigated by the move to MSBuild. If you see this reproing with the latest tools, please reopen. Thanks!
