### ISSUE TITLE
Perform safety checks for incremental compilation

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#382]
Incremental and concurrent compilation is unsafe when compilation relies on tools with potential side effects (tools that can cause data races or modify the state of other projects that have been deemed safe to skip compilation. Or tools that integrate timestamps or guids into the build output).

The presence of such cases needs to be recorded so that incremental and concurrent compilation can be turned off (or at least warn about potential bad builds).

Safety checks that need to be done:
- post / pre compilation scripts are present. These scripts can do anything, so they are unsafe.  
- compiler name is not one of the known compiler names (csc, vb, maybe F#). The known compilers will soon be deterministic. Others might not be.
- PATH fallback triggers for tools. Tools loaded from PATH and not from Nuget dependencies might not be available on all machines and cause the build to break. Issue #226 discusses moving away from PATH and keeping tools in Nuget packages.

The user experience for how the user interacts with safety checks is detailed in #232

**Comment by piotrpMSFT** [comment]
Some of these concerns are reasonable for the CLI itself, though others seem better associated with an orchestrator that has additional requirements. The CLI should, for example, support arbitrary compilers. Some of those compilers might not be desirable for use with particular orchestrators, but this is not for the CLI to support.

I'd like to understand how you're thinking about seeing these characteristics manifested. Some thoughts:
* an orchestrator can validate that project.json does not use pre/post scripts. 
* an orchestrator can also inspect project.json to validate that a project is only using compilers that the orchestrator is comfortable with.
* PATH is interesting. are you imagining a switch to turn off PATH probing? If so, why not just clean the path before running dotnet?

**Comment by NikolaiTillmann** [comment]
All of the concerns need to be addressed for safe incremental compilation.

Once we have the warnings agreed upon and in place, we want to enhance/rearrange the dotnet-compile program as follows. 

First dotnet-compile will check the preconditions by walking the project contexts and emit warnings if they are not met (but nothing actually builds at this time). Then, if some preconditions are not met, all compilation will effectively proceed as it does today (no incrementality, doing everything sequentially). Otherwise, if all preconditions are met, then it will proceed doing and incremental build (and possibly doing some build steps in parallel, see #383 ).

However, before we implement all that, we want independently lay the foundation by first getting in the warnings.

I think we should just build all of that into the basic dotnet-compile program. Fanning out at this stage into having two different orchestrators (one that is only ever doing things non-incremental sequential without any warnings, but gives ultimate freedom in running arbitrary scripts in between steps, and another one that can do incremental builds under certain assumptions) seems like a confusing overkill, both in terms of implementation and user experience.

Running scripts and other compilers is certainly useful, and we should later (for vNext) work on ways to specify what they do in a way that a build orchestrator can understand them, and still be safe to do incremental builds. But then we are really talking about a new build orchestrator. For now, it seems reasonable to leave the ability to run scripts and other compilers in place if somebody *really* needs it, with a warning that performance degrades (and better support will come in vNext).

PATH probing is deeply problematic. Timestamps on inputs and outputs wouldn't tell us if the PATH, or whatever executables (or their indirect dependencies, whatever those are) that reside in those paths, changed. You want that things recompile when the compiler, or any relevant input, changed. In particular in a world of rapidly evolving tools. NuGet packages are rather well encapsulated and come with dependency information. We can talk in much more detail about how we can track changes for NuGet packages, but it should be clear that we are in much better shape there to understand our dependencies, and it's certainly not as easy as launching the wrong command window to effectively sabotage your incremental build. We could totally introduce a hard switch instead of just a soft warning. Ideally, the default would be "off", to avoid surprises by default ("hey, I just enlisted, and cannot compile" --- "but it works for me" --- oops, different environments).

**Comment by cdmihai** [comment]
Implemented in #625
