### ISSUE TITLE
dotnet-run doesn't work from any directories

### ISSUE THREAD

**Issue by aquiladev** [dotnet/cli#3852]
## Steps to reproduce
1. Create web project from template
2. Open Command Prompt from any directory differs from the project root directory
3. Run command with absolute path to the project.json file:

    `dotnet run --project C:\Projects\First\src\WebApp\project.json`
4. Command result:
    
    ...
    Now listening on: http://localhost:5000
    Application started. Press Ctrl+C to shut down.
5. Open in browser http://localhost:5000

## Expected  behavior
The application is ok

## Actual behavior
Returns 500 Internal Server Error

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
@aquiladev can you see what is the actual error in the console?

/cc @davidfowl @anurse

**Comment by anurse** [comment]
It's likely that your app is not able to resolve the path to a view because the "Content Root" (i.e. where Views are located, etc.) is not correct. By default the Content Root of the app is the current directory. This can be specified yourself though and you can use a command line argument or other heuristic to change it. See https://docs.asp.net/en/latest/intro.html#content-root

The main reason this is done is that the app itself doesn't actually know where the project.json is, because `dotnet run` compiles the project and then separately executes the output.

**Comment by blackdwarf** [comment]
Given @anurse comment and lack of activity for a week, will close this. Reopen if it still repros.
