### ISSUE TITLE
Not all libraries from nupkg get copied

### ISSUE THREAD

**Issue by syberside** [dotnet/cli#3929]
## Summary
Not all libraries from package are copied to build output folder.
For example
project.json
`{
  "dependencies": {
    "Saxon-HE": "9.7.0.7"
  },
`
generated project,lock.json
`{  
  "targets": {
    ".NETFramework,Version=v4.5.1": {
      "Saxon-HE/9.7.0.7": {
        "type": "package",
        "frameworkAssemblies": [
          "System",
          "System.Xml"
        ],
        "compile": {
          "lib/net40/saxon9he-api.dll": {}
        },
        "runtime": {
          "lib/net40/saxon9he-api.dll": {}
        }
      },
...
"Saxon-HE/9.7.0.7": {
      "sha512": "1KfGrNElAcFaMAoE+PevCe1XAXX2ihqw0m/UtKFID/si2G74tGfmfQ4TS17/OttnzzRj+s0htACnAjE+1deD4g==",
      "type": "package",
      "path": "Saxon-HE/9.7.0.7",
      "files": [
        "Saxon-HE.9.7.0.7.nupkg.sha512",
        "Saxon-HE.nuspec",
        "lib/net40/IKVM.OpenJDK.Charsets.dll",
        "lib/net40/IKVM.OpenJDK.Core.dll",
        "lib/net40/IKVM.OpenJDK.Text.dll",
        "lib/net40/IKVM.OpenJDK.Util.dll",
        "lib/net40/IKVM.OpenJDK.XML.API.dll",
        "lib/net40/IKVM.Runtime.dll",
        "lib/net40/saxon9he-api.dll",
        "lib/net40/saxon9he-api.xml",
        "lib/net40/saxon9he.dll",
        "notices/APACHE-RESOLVER.txt",
        "notices/APACHE-XERCES.txt",
        "notices/CERN.txt",
        "notices/FRIJTERS.txt",
        "notices/GPL+CLASSPATH.txt",
        "notices/JAMESCLARK.txt",
        "notices/LICENSE.txt",
        "notices/THAI.txt",
        "notices/UNICODE.txt",
        "tools/Query.exe",
        "tools/Query.exe.config",
        "tools/Transform.exe",
        "tools/Transform.exe.config"
      ]
    },
`
So actual content of package is listed in project.lock.json, but ignored when build.

## Steps to reproduce
1. Create empty project (in my case ASP.NET Core App)
2. Add nuget dependency on Saxon-HE 9.7.0.7
3. Add any code, that uses Saxon, for example
`var processor = new Processor();`

## Expected  behavior
Get instance of the processor.

## Actual behavior
FileNotFoundException, can't load library or dependencies for "saxon9he, Version=9.7.0.7, Culture=neutral, PublicKeyToken=e1fdd002d5083fe6"

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64

## Note
If I copy missed *.dll's to output folder manually - application start works as expected

Thanks.

**Comment by piotrpMSFT** [comment]
This looks like a packaging issue. I created a .NET Core console application and added the same dependency as above:

````
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        },
        "Saxon-HE": "9.7.0.7"
      },
      "imports": "dnxcore50"
    }
````

when restoring the project:

````
Package Saxon-HE 9.7.0.7 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Saxon-HE 9.7.0.7 supports: net40 (.NETFramework,Version=v4.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
````

Since the package, as authored, does not include any .NET Core content there was nothing to copy.

I also tried changing the target framework to `net451` in case the intent here is to build a desktop framework project instead. This restored successfully and presented me with a lock file that includes:

````
      "Saxon-HE/9.7.0.7": {
        "type": "package",
        "frameworkAssemblies": [
          "System",
          "System.Xml"
        ],
        "compile": {
          "lib/net40/saxon9he-api.dll": {}
        },
        "runtime": {
          "lib/net40/saxon9he-api.dll": {}
        }
      }
````

I validated that this dll did get copied to the publish output of my project.

Finally, I noticed that the `nupkg` for `Saxon-HE` contains many other dll's. However, only `saxon9he-api.dll` is referenced in the nuspec for this package:

````

    <references>
      <reference file="saxon9he-api.dll" />
    </references>

````

As such, the NuGet [references](https://docs.nuget.org/create/nuspec-reference#specifying-explicit-assembly-references) feature kicked in and limited the project's dependencies to that dll.

This issue appears to be a NuGet packaging issue in saxon-he. The package should be updated to either enumerate all required assemblies or to enumerate none and allow the default behavior to kick in.

**Comment by Erikvl87** [comment]
@syberside, I am having the same struggles regarding the Saxon package when targeting v4.5.1, so I've created a bug report at https://saxonica.plan.io/issues/2873

**Comment by syberside** [comment]
@Erikvl87, thx. I wanted to do the same but fault to find correct place for report.

**Comment by michaelhkay** [comment]
Please note that the NuGet package for Saxon was created by a third party, not by Saxonica. We are currently investigating whether .NET Core can/should be supported for Saxon on .NET.

**Comment by maxtoroq** [comment]
@piotrpMSFT The package works fine with MSBuild based projects. The behavior in Visual Studio has always been that, when you add a reference to an assembly, other assemblies in the same directory are also copied (please correct me if I'm wrong).

The Explicit Assembly References feature description in NuGet is not very good, but it says:

> Likewise, the feature can be used to for unit test frameworks such as XUnit which need its tools assemblies to be located next to the runtime assemblies, but excluded from project references.

What's you interpretation of the above paragraph? XUnit need its tools assemblies next to the runtime assemblies because the tools assemblies are needed at runtime?

**Comment by tflanitzer** [comment]
Since I was facing the same problem and directly referencing local assemblies is not supported either at the moment, I have created a nuget package that lists both required assemblies. Its called Saxon-HE-fixedrefs and available on nuget.org.
