### ISSUE TITLE
How will the update of 1.0 project files be handled exactly?

### ISSUE THREAD

**Issue by orloffm** [dotnet/cli#4043]
I am confused about what's going to happen with the current projects in 1.1. I've asked the question on SO here: http://stackoverflow.com/q/38920297/1271135, but it got downvoted and put on hold, so I'd like to ask it here. I hope it is the proper place.

So currently, in the mid-August 2016 .NET Cor'ish 1.0 world, it is possible to create three types of libraries:
1. Use `dotnet new -t lib`, which creates only `project.json`.
2. Use VS 2015 U3 to create a portable library and then switch it to ".NET Standard". This creates both a `.csproj` file and a `project.json` file.
3. Install ".NET Core tooling Preview 2" and use VS 2015 U3 to create a ".NET Core" library. This creates an `.xproj` file and also a `project.json` file.

I have three questions about this:
1. Will VS 2015/"15" and `dotnet` after the [expected 1.1  update](https://github.com/dotnet/core/blob/master/roadmap.md#ship-dates) both support conversion of all three types, and will they perform such conversion in the same way, no matter which tool is used?
2. Will the result of the update be the same for all three cases? If so, what will it be?
   - A single `.csproj` with all the magical GUIDs and treated by Visual Studio as a "portable library"?
3. How will a .NET Core console application be updated? Since executable apps can't be portable, will `.csproj` start supporting multiple frameworks/platforms?

**Comment by gulbanana** [comment]
for your last question - multi-TFM csproj is definitely planned
see: https://github.com/dotnet/roslyn-project-system/issues/323

**Comment by eerhardt** [comment]
@blackdwarf @brthor - 

Do we have any plans on migrating

`2. Use VS 2015 U3 to create a portable library and then switch it to ".NET Standard". This creates both a .csproj file and a project.json file.`?

We are currently working on migrating the other 2 types of projects.  See https://github.com/dotnet/cli/issues/4096

**Comment by blackdwarf** [comment]
@eerhardt good question, I'm not sure how this would work, as our migration efforts have been focused on the project.json (+ xproj) combination.

**Comment by piotrpMSFT** [comment]
@blackdwarf is right on. As I understand it, the (2) scenario is strictly a `classic` csproj experience as CLI has no knowledge or handling for that scenario. Scenarios (1) and (3) are covered by the migration tool as it doesn't take the source of a PJ into account.

@orloffm can you create a simple repro of the (2) scenario for us to play with? I'm especially curious as to what the project.json does there.

Conversion will happen the same way for VS and CLI because VS invokes the CLI to `migrate` a project.json.

The result will not have magic GUIDs. The folks working on https://github.com/dotnet/sdk have done a great job of modernizing the csproj file to eliminate as many GUIDs and other calculable artifacts as possible. Visual Studio has targetted handling for these new csproj files and they were designed to interact favorably with classic csproj projects.

**Comment by livarcocc** [comment]
I think at this point, we can go ahead and close this. If there is still any un-addressed concern, please go ahead and re-activate.
