### ISSUE TITLE
Build targeting .NET Framework 4.6 doesn't work on Win7 x86

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/cli#4063]
## Steps to reproduce

project.json:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "net46": { }
  }
}
```

Program.cs:

```csharp
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

Build:

` dotnet publish -r win7-x86 -o out`

## Expected  behavior
Run executable on Windows 7 x86 machine and see 'Hello World!'

## Actual behavior
Run executable on Windows 7 x86 machine and see the following error:

```
This version of C:\Users\tasou\Desktop\temp.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
```

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview2-003121)

Product Information:
 Version:            1.0.0-preview2-003121
 Commit SHA-1 hash:  1e9d529bc5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14904
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by twsouthwick** [comment]
I installed the latest preview (preview3-003223), and it continues to fail when I build with the 64-bit SDK, but succeeds when I build with the 32-bit SDK.

**Comment by davidfowl** [comment]
This is a known issue with the tools today. It infers the architecture of the output based on the tool's architecture (which isn't right). I believe you can work around this by setting a compilation  option in the `project.json`.

https://github.com/dotnet/cli/blob/30557a179afee0afbab3fa21080594a175e6cd1c/src/dotnet/commands/dotnet-compile/ManagedCompiler.cs#L89-L91

/cc @anurse

**Comment by anurse** [comment]
Yeah, @davidfowl is right about the current behavior. It is a known issue, and should be resolved when we migrate to MSBuild. We made the choice to apply this default based on the bitness of the CLI because it was the least disruptive way to make _something_ work :). We agree it is absolutely not ideal.

If you don't have any native dependencies (outside of Windows itself), you can just set `compilationOptions.platform` in `project.json` to `anycpu`, and the executable will support **both** x86 and x64 deployment.

However, if you have native dependencies (i.e. custom native DLLs you deploy and P/Invoke into), you'll need to build separately for each architecture, and you can use a technique like the following (which **adds** `debug_x86`/`release_x86` configurations so you can easily create separate builds): https://github.com/aspnet/RazorTooling/blob/d9dfc2a6ac81963d85c8c66f1e501f4a008da080/src/Microsoft.AspNetCore.Razor.Design/project.json#L26

**Comment by twsouthwick** [comment]
Thanks! That worked to get us unblocked.
