### ISSUE TITLE
project.json/nuget versioning improvement

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#427]
Currently the versioning of packages/project is not intuitive (for setting version of the project, not for dependencies).

Examples:
- project.json accepts `1.0.0-*` but doesn't `1.*` or `1.0.*` or just `*`
- version `1.0.0-abc-123` is ok but `1.0.0-123-123` is not
- `1.0.0.0.1` is not accepted
- documentation about this: https://docs.nuget.org/create/versioning is super verbose but the same could be expressed with a simple regex and that would actually be even more helpful as you wouldn't have to read it all and would actually explain all details way better
- no mechanizm of auto-increasing
- there is a lot of suffixes you can use but none of them is preferred. I.e. should new dev use -beta -prerelease or simply assume that release version has 0 as last digit and anything above is revision

**Comment by krwq** [comment]
Actually when I think of it now we could just use date and a tag as a version.

**Comment by anurse** [comment]
Few notes:

`1.0.0-*` being the only supported float is intentional. It's designed after Maven's SNAPSHOT version token and is only designed for working directly with CI builds (i.e. it isn't a full "floating version" system, since it is closely tied with the feed you use)

All the NuGet versioning logic is designed after the Semantic Versioning standard: http://semver.org/ (v1.0) and isn't likely to deviate from that. Semantic Version intentionally leaves the suffix formatting up to package authors.

It's weird that `1.0.0-123-123` doesn't work. That sounds like a NuGet bug.

If you want to clear up the documentation on NuGet, I suggest filing a bug on https://github.com/NuGet/NuGetDocs so it will be seen by the NuGet team.

**Comment by piotrpMSFT** [comment]
@krwq this seems like it belongs in the nuget repo. Once your concerns are addressed there, let's bring back any integration that needs to happen in CLI to take advantage!
