### ISSUE TITLE
dotnet restore3 fails with OutputPath not set unless it is explicitly set in the csproj

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#4287]
Just create a csproj like below:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp1.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.NETCore.Sdk">
      <Version>1.0.0-alpha-20160930-2</Version>
    </PackageReference>
  </ItemGroup>

  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

Then run dotnet restore3.

Actual result:

Microsoft.Common.CurrentVersion.targets(729,5): error : The OutputPath property is not set for project 'MSBuildTestAppPackageRefs.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform=''.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.

Expected result:

restore should have succeeded without the user setting OutputPath in the csproj.

**Comment by emgarten** [comment]
Restore3 does not directly use the OutputPath property or check the configuration.

**Comment by emgarten** [comment]
This error occurs when ``Configuration`` is set either by passing the property in, or by an environment variable. The CI may set the environment variable ``Configuration=release`` before the build and it gets applied to the tests when they run, this would explain why it happens there and not locally.

This problem is not related to Restore3, using the above repro project I get these results when running any target.

#### Command
``dotnet.exe msbuild .\newproj.csproj /t:clean``
#### Result
``Build succeeded.``



#### Command
``dotnet.exe msbuild .\newproj.csproj /t:clean /p:Configuration``
#### Result
``Microsoft.Common.CurrentVersion.targets(729,5): error : The OutputPath property is not set for project 'newproj.csproj'.``

**Comment by emgarten** [comment]
I believe this has been fixed in MSBuild, please re-open if you are still seeing this.
