### ISSUE TITLE
Migration: Folder Migration without skip project references blows up when project.json is deleted

### ISSUE THREAD

**Issue by brthor** [dotnet/cli#4304]
When migration deletes the project.json left behind after migration, folder migration blows up.

This is because folder migration finds every project and follows it's P2Ps independently. After a P2P is already migrated it's project.json is deleted and the next project that tries to migrate that P2P blows up.

**Comment by piotrpMSFT** [comment]
@brthor if migration fails what is the current recovery story? Can users just modify their PJ/GJ/etc. and try again? Or do they need to delete e.g. csproj files before retrying?
1. If migration fails for all projects, I assume we can make changes and re-run migration since no csproj's are generated.
2. If migration fails for some projects, do the successfully migrated projects need to have their csproj's deleted before re-attempting? Or will they overwrite the existing csproj's?

I'm trying to decide when it's safe to move PJ's to backup. My current PoR is to leave all PJ's in-place and not create a `.backup` directory until the migration is fully successful.

We discussed a number of interesting migration scenarios that should be considered in this feature:
1. migrate a `global.json`. In this scenario, I plan to `.backup` the `project.json`s IFF migration was successful for all projects; they will be left behind if any project failed to migrate. None of the `project.json`s will be removed as any of them may be necessary to migrate the remaining projects. We could probably do a little better by finding the projects which are not referenced by any remaining projects... but that seems more confusing than its worth. It's also feasible that projects will fail to migrate due to missing p2p's, in which case deleting those that seem fully migrated will be detrimental.
2. migrate a `project.json` with no p2p references. I plan to `.backup` the `project.json` IFF migration was successful for the project; it will be left behind if it fails to migrate.
3. migrate a `project.json` with p2p references. In this scenario, any peer directories will be candidates for reference resolution despite there being no global.json. In this scenario the project.json's will always be left behind since we cannot determine that all p2p's have been addressed.
4. migrate a `project.json` that is in the context of a `global.json`. This scenario will be handled as (3) above, for the same reasons. 

Put it another way, PJs get moved to `.backup` only for migrations of `global.json` or `project.json` with no P2P references.

You've thought through this scenario a lot. Are there other safe opportunities for cleaning up PJ artifacts?
