### ISSUE TITLE
post-compile script runs before referenced project's output is copied and there's no post-build script anymore

### ISSUE THREAD

**Issue by prochan2** [dotnet/cli#4355]
## Steps to reproduce
1. Create a class library containing some public API. ("Class Library")
2. Create a .NET Core project using xproj/project.json and use there the API from the previous step. ("Main Program")
3. Add a post-compile script to the project.json of the Main Program which works with the output assembly of the Class Library located in the output directory of the Main Program.
4. Build the Class Library.
5. Build the Main Program.
## Sample solution:

[PostCompileScriptIssue.zip](https://github.com/dotnet/cli/files/519027/PostCompileScriptIssue.zip)
## Expected  behavior

When the post-compile script is ran, it has the output assembly of the Class Library available in the output directory of the Main Program.

(If you try to build the Main Program again, it passes because the output assembly of the Class Library is in the output directory of the Main Program since the first build of the Main Program.)
## Actual behavior

The call of the post-compile script fails during the first build of the Main Program because the output assembly of the Class Library is not available in the output directory of the Main Program at the moment.
## Notice

In the previous versions of project.json specification, there used to be post-build scripts but no post-compile scripts. Now it it the other way round. Wouldn't it be useful to have them both?
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by blackdwarf** [comment]
I've changed the repro slightly and I'm adding it here. The crux of the changes was to make it work with .NET Core all-up and to migrate to msbuild. Since the program that loads assemblies is now a portable app, the invocation of the script in csproj uses `dotnet`.  Also, the program that loads assemblies was changed to just test whether the file path that was passed as an argument exist. 

All in all, the issue does not repro anymore. Will close this issue. 

[repro_changed.zip](https://github.com/dotnet/cli/files/563004/repro_changed.zip)
