### ISSUE TITLE
dotnet on mac: "-bash: dotnet: command not found"

### ISSUE THREAD

**Issue by explorer2309** [dotnet/cli#4357]
## Steps to reproduce
I have Sierra version of OSX on which I tried following the installation instructions a few times.
This is what I get:

```
 ▷  brew install openssl
Warning: openssl-1.0.2j already installed

 ▷  ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln: /usr/local/lib//libcrypto.1.0.0.dylib: File exists

 ▷  ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
ln: /usr/local/lib//libssl.1.0.0.dylib: File exists
```

When I use the installer (`dotnet-dev-osx-x64.1.0.0-preview2-003131.pkg`), it works fine

The path `/usr/local/share/dotnet` does exist

## Expected  behavior

When I run "dotnet" command, I expect it to work

## Actual behavior

Command dotnet does not work. The terminal says
`-bash: dotnet: command not found`

## Environment data
None

**Comment by livarcocc** [comment]
Is this in Sierra?

**Comment by explorer2309** [comment]
Yes. This is in Sierra.

**Comment by pealmeid** [comment]
This happens because the installation package does not add the `dotnet` executable location to the `PATH` environment variable. This issue is mentioned in https://github.com/dotnet/core/blob/master/cli/known-issues.md#users-of-zsh-z-shell-dont-get-dotnet-on-the-path-after-install, but apparently it does not affect only `zsh` users. You need to add this path manually.

In my case the path was `/usr/local/share/dotnet`, so I ran (from the command line):

    export PATH=/usr/local/share/dotnet:$PATH

This runs `path_helper` and adds a `dotnet` file to `/etc/paths.d`. This file contains the path to the executable and is added to the environment `PATH` every time a new terminal shell is opened (there are other ways to add the `dotnet` location to the path but my understanding is that this is the recommended way).

**Comment by explorer2309** [comment]
Thank you. Running ` ln -s /usr/local/share/dotnet/dotnet /usr/local/bin ` from the page in the link you mentioned worked for me.

**Comment by chubbsnes65** [comment]
I have an similar issue, when I try to run 

dotnet /path/to/my/dll

I recieve the same error, but the diference is I'm trying to run in to a shell script in os x.

I hope someone can helpe 

Thanks.

**Comment by livarcocc** [comment]
That happens when the host does not find the actual dll in the path you provided. When that happens, it does not treat the path as a dll and instead passes that to the CLI and the CLI ends up treating it as a command, which it does not find either and you end up with the error message you are seeing.

So, make sure that the path to your dll is correct and that the file actually exists in that location.

**Comment by chubbsnes65** [comment]
I'm back to solve this issue for my app but my paths are ok, I made this lots of times just fail with the new version.

**Comment by dahrari** [comment]
I'm not even on mac and I'm getting this same error. 
If the _dotnet /path/to/dllfile.dll --myapparg_  is run by cron, it throws that error. If I just copypaste the same exact line and run it from bash, it executes successfully.
