### ISSUE TITLE
Building .Net Core library in lab machines

### ISSUE THREAD

**Issue by rnagpal** [dotnet/cli#4383]
I've been developing the .NET Standard library for our product using Visual Studio 2015 Update 3 and .net core SDK that I downloaded from the .net core home page.

It's time to build the library in our lab machines which only have visual studio 2013 installed and use the msbuild to build rest of our product as a NetFx library.

Is there a way for me to build a .net core library in those lab machines which only have vs 2013 toolset? The build calls the firs.proj at the root of our enlistment and builds everything underneath. Any suggestions on How can I integrate building of .net core library in this environment?

What are the steps involved to automate this?

**Comment by wjk** [comment]
@rnagpal As I understand it, the .NET Core SDK is completely independent of the Visual Studio version. You can even install the SDK on a machine with no version of Visual Studio on it at all, and it should still work. The SDK includes a bundled copy of MSBuild and Roslyn, with versions pinned to what the CLI expects.

As far as I know, if you have the .NET Core SDK installed, you can then type `dotnet build3 dirs.proj` at a command prompt, and it will proceed to build that file. (Always use `dotnet build3` — or whatever its replacement is; #4205 tracks removing the trailing "3" from this command — instead of directly running `msbuild.exe`, or you will almost certainly invoke the wrong version of MSBuild.) Any arguments passed after `dotnet build3` will be passed on to MSBuild as-is. Hope this helps!

**Comment by rnagpal** [comment]
@wjk Thanks for your comments.

Seems like "dotnet build3" is not yet supported in preview-2 of cli tools. I've the latest 1.0.1 toolset: 1.0.0-preview2-003133

Any recommendations of a workaround in my case?

**Comment by wjk** [comment]
At least in my experience, you’ll need preview-3 or later for this to work (I have version 1.0.0-preview3-003705 on my Mac, and it recognizes `dotnet build3`).

**Comment by livarcocc** [comment]
Correct. These commands are not going to be added to preview2. Also keep in mind, that in the short future, the '3' commands are actually going to turn in the regular commands.

https://github.com/dotnet/cli/issues/4205
