### ISSUE TITLE
Installing preview-3 breaks VS2015 and dotnet cli

### ISSUE THREAD

**Issue by byatis** [dotnet/cli#4384]
Installed latest daily build with SDK installer. After that Visual Studio doesn't start and from cli my project says:

The imported project "C:\Program Files\dotnet\sdk\1.0.0-preview3-003805\Extensions\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> decl
aration is correct, and that the file exists on disk.  C:\Users\xxx\Documents\Visual Studio 2015\Projects\myproj.xproj 
## Environment data

`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview3-003805)

Product Information:
 Version:            1.0.0-preview3-003805
 Commit SHA-1 hash:  edf2fc1f53

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64

**Comment by feedsbrain** [comment]
I have same issue ...

**Comment by piotrpMSFT** [comment]
@livarcocc we need to try to repro this tomorrow...

**Comment by feedsbrain** [comment]
Btw, I manage to resolve the issue by cleaning **%UserProfile%\.nuget\packages** ... I deleted all the content (after removing the old version of dotnet-cli) then it's ok ...

**Comment by livarcocc** [comment]
This happens because the new CLI (preview3) will try to build the xproj (because it is a *proj) file and it fail.

It can't handle xproj nor project.json.

The real fix here is to add a global.json with the following.

```
{
  "sdk":
  {
    "version": "1.0.0-preview2-003121"
  }
}
```

cc @leecow as we will have to make this know for people taking the preview3 CLI. This should not be a problem for projects created from VS, because the VS template already includes the global.json with the information above. But for dotnet new projects, we don't and people are going to have to add it themselves.
