### ISSUE TITLE
Invoking Project Tools fails with 'No executable found matching command'

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/cli#4402]
## Steps to reproduce
Repro projects at https://github.com/prafullbhosale/ProjectToolSample
Steps :
https://github.com/prafullbhosale/ProjectToolSample/blob/master/ReadMe.md

## Expected  behavior
Prints `Hello` on the console.

## Actual behavior
Fails with error `No executable found matching command dotnet-project-tool-sample`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003842)

Product Information:
 Version:            1.0.0-preview3-003842
 Commit SHA-1 hash:  3ae14ab618

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

cc @livarcocc @mlorbetske

**Comment by livarcocc** [comment]
This is by design.

The tool property is:

```
<DotNetCliToolReference Include="dotnet-portable">
      <Version>1.0.0</Version>
</DotNetCliToolReference>
```

And not the one below. Note the "s" in tools. It is supposed to be singular. Where did you guys find the plural "s"? It was initially documented like that, but it was a typo and the NuGet guys changed it to be singular.

```
<DotNetCliToolsReference Include="ProjectToolSample">
    <Version>1.0.0-*</Version>
</DotNetCliToolsReference >
```

After I made this change to the csproj under test/demo, both command succeeded and printed Hello.
