### ISSUE TITLE
place-binary file locking (causing pdbs to not match dll)

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#444]
place-binary step doesn't fully work on few projects. I.e:
```
x:\oss\cli-2\src\Microsoft.DotNet.ProjectModel>dotnet compile
Running X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile.exe
> X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile.exe
Process ID: 6312
Compiling Microsoft.DotNet.ProjectModel for DNXCore,Version=v5.0
X:\oss\cli-2\src\Microsoft.DotNet.ProjectModel\bin\Debug\dnxcore50\Microsoft.DotNet.ProjectModel.dll -> X:\oss\cli-2\artifacts\win7-x64\stage2\bin\Microsoft.DotNet.ProjectModel.dll
Sharing violation
X:\oss\cli-2\src\Microsoft.DotNet.ProjectModel\bin\Debug\dnxcore50\Microsoft.DotNet.ProjectModel.pdb -> X:\oss\cli-2\artifacts\win7-x64\stage2\bin\Microsoft.DotNet.ProjectModel.pdb
1 File(s) copied
x:\oss\cli-2\src\Microsoft.DotNet.ProjectModel\project.json(16,52): warning NU1007: Dependency specified was Microsoft.Extensions.FileSystemGlobbing >= 1.0.0-rc2-15791 but ended up with Microsoft.Extensions.FileSystemGlobbing 1.0.0-rc2-15797.

Compilation succeeded.
x:\oss\cli-2\src\Microsoft.DotNet.ProjectModel\project.json(6,31): warning NU1012: Dependency conflict. Microsoft.Extensions.FileSystemGlobbing 1.0.0-rc2-15797 expected System.Collections >= 4.0.11-beta-23506 but got 4.0.11-beta-23504
    3 Warning(s)
    0 Error(s)
x:\oss\cli-2\src\Microsoft.DotNet.ProjectModel\project.json(7,24): warning NU1012: Dependency conflict. Microsoft.Extensions.FileSystemGlobbing 1.0.0-rc2-15797 expected System.Linq >= 4.0.1-beta-23506 but got 4.0.1-beta-23504

Time elapsed 00:00:02.0587713

< X:\oss\cli-2\artifacts\win7-x64\stage2\bin\dotnet-compile.exe exited with 0 in 2427 ms.

x:\oss\cli-2\src\Microsoft.DotNet.ProjectModel>
```

Note: "sharing violation". This is coming from xcopy inside place-binary. Seems like "Microsoft.DotNet.ProjectModel.dll" is being used by dotnet-compile. We should be probably running that after the process is finished or unload the dll from memory (not sure if that is supported by runtime)

Succeeding build despite error is reported here: https://github.com/dotnet/cli/issues/443

**Comment by anurse** [comment]
Yeah, that's a fairly common occurrence with these scripts. We had the problem with NuGet too. Generally you have to make sure you use a different `dotnet` to compile when you want to actually use `place-binary`'s feature. We could make it so the PDB only gets copied if the DLL copy succeeds. That would probably resolve the immediate issue.

In general, `place-binary` shouldn't be run during the full build (which is where this occurs most frequently), but it's relatively harmless (because it gets overridden by the publish immediately following it). This is generally why I avoid putting the dev build on the path though, instead using `scripts/dev-dotnet.[ps1|sh]` to temporarily use the dev build.

**Comment by anurse** [comment]
What's the desired outcome here? Generally this only occurs when you try to use your build output to compile `dotnet-compile` again. In general, using your build output to modify itself isn't going to work :)

**Comment by anurse** [comment]
`placebinary` is gone
