### ISSUE TITLE
Run3 doesn't work with `--project`

### ISSUE THREAD

**Issue by eerhardt** [dotnet/cli#4447]
## Steps to reproduce
Have a project in a separate directory than the current directory.
`dotnet run3 --project App\App.csproj`

## Expected  behavior
The project should build and run.

## Actual behavior
```
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

The build failed. Please fix the build errors and run again.
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview3-003882)

Product Information:
 Version:            1.0.0-preview3-003882
 Commit SHA-1 hash:  7da6ee0325

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by dsplaisted** [comment]
I've been adding a test for this in the SDK repo, and there is also a bug that needs to be fixed in the .NET CLI.  The `EnsureProjectIsBuilt` method doesn't pass the path to the project to build to MSBuild, so it will either fail saying there isn't a project in the current directory (or maybe that there are multiple projects), or it will build the wrong project and then run a possibly-outdated version of the specified project.

You can work around this (or will be able to once you have a version of the SDK with dotnet/sdk#301 fixed) by first building the project and then passing the `--no-build` parameter to run3.

**Comment by monojoli1992** [comment]
[Run3](https://run3.me/) Game project. ?
