### ISSUE TITLE
Current working directory for dotnet run3 should be project directory

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#4473]
## Steps to reproduce
Create a netcoreapp that does this:
```c#
using System;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("cwd = " + Directory.GetCurrentDirectory());
    }
}
```

dotnet run3

## Expected  behavior
App prints
```
cwd = C:\dev\MyProjectFolder
```
## Actual behavior
App prints
```
cwd = C:\dev\MyProjectFolder\bin\Debug\netcoreapp1.0
```

## Environment data
`dotnet --info` output:

Product Information:
 Version:            1.0.0-preview3-003857
 Commit SHA-1 hash:  060762090d

SDK version: microsoft.net.sdk/1.0.0-alpha-20161021-1

**Comment by livarcocc** [comment]
@eerhardt Do you know why we are setting the working directory for run3 instead of using the directory from where the command is being executed? Was that intentional?

The behavior described by @natemcmaster was the one we had in project.json, but after we added the runworkingdirectory to run3, we changed to what he is seeing.

**Comment by livarcocc** [comment]
cc @srivatsn @dsplaisted Who may know the answer for the question above.

**Comment by eerhardt** [comment]
> @eerhardt Do you know why we are setting the working directory for run3 instead of using the directory from where the command is being executed? Was that intentional?

Yes, this was intentional for a few reasons:

1. When running/debugging a project in Visual Studio, the current working directory is set to the output directory by default.  We wanted to keep "dotnet run", Visual Studio F5, and VS Code F5 consistent so the app runs the exact same no matter which client was executing it.
2. With the move to .csproj, there are new properties that were not available with project.json.  Most relevant here is the `<StartWorkingDirectory>` property.  `dotnet run3` now respects this property, and will start the app in the working directory specified by that property - just like VS would.

**Comment by eerhardt** [comment]
See https://github.com/dotnet/sdk/issues/98 for some more detailed discussion around this design decision.

**Comment by livarcocc** [comment]
So... the current behavior is the correct behavior for run3?

**Comment by eerhardt** [comment]
> So... the current behavior is the correct behavior for run3?

IMO - yes.  The default behavior should be consistent across VS, VS Code, and 'dotnet run'.

I could imagine `dotnet run3` adding options to use the current working directory, or to be able to specify the working directory from the command line, in order to support calling `dotnet run3` for a specific working directory.

But as of right now, this is the designed behavior of `run3`.

**Comment by natemcmaster** [comment]
> The default behavior should be consistent across VS, VS Code, and 'dotnet run'.

I'd argue the context of invoking "dotnet run" is different enough to justify different behavior. VS != command line.

In addition, this is a big breaking change. Almost everyone upgrading from the project.json will find this problematic. Here are the two common scenarios I've encountered while dogfooding this preview:

1. Invoking a command line tool with relative file paths. "dotnet run" will not work as expected if a user invokes `dotnet run -- ../somefile.txt`. As the relative path is not relative to the command line directory, but the output dir.
2. Web projects. This change means web projects now need copy all static content (JavaScript, stylesheets, images) to the output directory. Not only is this slow, but it breaks the inner dev loop for editing JS/CSS while the website is running. (e.g. the file being served is not the file I am editing in VS.) To make _any_ change to JS file, I have to stop and rebuild to get the JS file into the right output directory. That the web templates/DSK need to override the default working directory.

cc @davidfowl @DamianEdwards

**Comment by eerhardt** [comment]
> Web projects. This change means web projects now need copy all static content (JavaScript, stylesheets, images) to the output directory. 

How will this work in VS?  What will be the working directory when F5'ing?  - /cc @BillHiebert

**Comment by davidfowl** [comment]
> How will this work in VS? What will be the working directory when F5'ing?

It's the project folder. This is *super* important for web projects.

**Comment by eerhardt** [comment]
> It's the project folder. This is super important for web projects.

One option is that the Web.Sdk can set the RunWorkingDirectory to be the project folder.  That's why the property exists.

What happens if someone does `/someOtherDir$ dotnet run --project /pathToWebProject/proj.csproj`?  What do you expect the working directory to be then?  Would it be `/someOtherDir`?  Or the project folder?

**Comment by davidfowl** [comment]
@eerhardt it doesn't work with ASP.NET core. Our templates set the ASP.NET content root to the working directory. We don't look at anything else.

**Comment by natemcmaster** [comment]
> What happens if someone does `/someOtherDir$ dotnet run --project /pathToWebProject/proj.csproj`? 

@eerhardt that's a good point. I would have expected the current PJ behavior, which is the project from -p is run in the cwd of the CLI, so /someOtherDir in the example above.

**Comment by srivatsn** [comment]
I had filed https://github.com/dotnet/roslyn-project-system/issues/589 not knowing the history and Dave pointed out this was done for web projects. If the argument is consistency then I think everything having the cwd as the project directory will work fine right. @eerhardt any concerns?

**Comment by piotrpMSFT** [comment]
if we're not consistent, we need to know what property migration needs to set to successfuly migrate projects. As @natemcmaster pointed out, this would be a big breaking change.

**Comment by natemcmaster** [comment]
FWIW to preserve existing behavior with PJ, I've been adding `<RunWorkingDirectory>$(MSBuildStartupDirectory)</RunWorkingDirectory>` to all of my projects.

**Comment by piotrpMSFT** [comment]
We just discussed and have a plan to account for this. @eerhardt will share for feedback.

**Comment by eerhardt** [comment]
> FWIW to preserve existing behavior with PJ, I've been adding <RunWorkingDirectory>$(MSBuildStartupDirectory)</RunWorkingDirectory> to all of my projects.

This is not 100% true.  Existing behavior with PJ and `dotnet run` is to use the current working directory of the console/terminal you are using.

**Comment by eerhardt** [comment]
OK - here's the plan that we've put together after some extensive discussion.

1. For migrated projects, we insist that `dotnet run` works exactly the same as it did with project.json.  That means for `dotnet run` it will use the current working directory of the command line.  This will be accomplished by adding a property `<DefaultRunWorkingDirectory>false</DefaultRunWorkingDirectory>` to all migrated projects.
2. For new ASP.NET apps, by default the `RunWorkingDirectory` will be set to the project directory.  So no matter if you are in VS, or in some random folder on the command line, the default working directory will be the project directory.  And your web app just works.
3. The only contentious question is "What is the default working directory for console apps?"  My thinking is that VS F5 and `dotnet run` should work the same by default.  That way whether you are in VS or on the command line, your app runs the same.  The question is: "Should the default be the project's output directory or the project directory?".  Classic .csproj console apps used the output directory.  New .xproj apps used the project directory.

- My proposal is we keep the current .xproj behavior of using the project directory as the default working directory.
- The reasons for this are:
  - This makes the default experience of `dotnet run` understandable - which is to run it from the project directory.  That way your working directory is the same directory as where you called `dotnet run` from.
   - We can keep VS F5 consistent with `dotnet run` - they both work from the project directory by default.
   - This is consistent between console apps and web apps.  No need to differentiate between the two.

Please share your thoughts/concerns/questions/feedback on this plan.

**Comment by livarcocc** [comment]
For 2. above, is there work that needs to be done in the SDK.Web package to implement that?

**Comment by eerhardt** [comment]
> For 2. above, is there work that needs to be done in the SDK.Web package to implement that?

With my proposal - no work is required by the SDK.Web. The defaults for console and web would be the same - the project directory.

If we decide we want a different default for console apps than the project directory, then SDK.Web will need to set the default for web projects.

**Comment by natemcmaster** [comment]
> This is not 100% true.

@eerhardt Good point. $(MSBuildStartupDirectory) just preserves the CLI experience of PJ on command-line only. (I'm not using VS.)

> My proposal is we keep the current .xproj behavior of using the project directory as the default working directory.

My two cents: the semantics of directories in PJ are right. i.e. `dotnet run` should use terminal current working directory, not project dir. It's consistent the CLI experience of other tools and languages (node, python, etc) and consistent with `dotnet app.dll`. Matching VS F5 behavior is less important as VS has GUI for setting cwd. On command-line, `cd` is the native gesture for setting cwd.

But if you decide to do this breaking change, may I request a flag on dotnet-run to set cwd? e.g. something like `dotnet run --cwd . -p ../OtherProj/`.

**Comment by eerhardt** [comment]
What happens when `<StartWorkingDirectory>` (an existing MSBuild property) is set in the project?  Should `dotnet run` respect that property?  Or should the CLI semantics override that property?

**Comment by eerhardt** [comment]
The thing I don't want to see is users getting confused and logging bugs because their app runs just fine when F5'ing in VS, but when they run it from the command line the app fails.  Then they think that `dotnet run` is broken because their app runs just fine from VS.  Thus, the attempt to keep `dotnet run` and VS F5 work the same.

I do agree with you that `cd` is the gesture for setting cwd in the CLI.  But the wrinkle here is MSBuild has properties like `<StartWorkingDirectory>` and new features like the debug profiles that are coming in Dev15.  What should win - the cwd on the command line, or the properties coming from MSBuild/the project?

For the MSBuild conversion of `dotnet run`, I was attempting to follow the same rule as we use everywhere else:  MSBuild is the master.  The project contains all the logic for itself - build, publish, pack, how to run it, etc. And all the "clients" like the dotnet/cli, VS, VS Code have as little logic in them as possible.  They take their orders from MSBuild, and that way they all get a consistent experience no matter how the project is built, published, packed, run, etc.

This can be an exception to the rule, if we feel that the working directory of the CLI should override what the project says.  Again, I just don't want users to have their app run correctly in one place (like VS) and fail in another (like dotnet/cli).

**Comment by eerhardt** [comment]
Alright @natemcmaster, I've thought about it more and I think you've convinced me.  By default, `dotnet run` should use the current working directory of your console/terminal, just like it did for project.json based projects.

However, `dotnet run` will respect `<StartWorkingDirectory>` if it is explicitly set in the .csproj.  So the rules for `dotnet run` are as follows:

1. Ask the project for its `<RunWorkingDirectory>`, if it returns something, use that value as the working directory.
2. If `<RunWorkingDirectory>` is empty, it will use the cwd of the console/terminal.


In the https://github.com/dotnet/sdk the rules for defaulting `RunWorkingDirectory` are:

1. If `<StartWorkingDirectory>` is set, use it.
2. For .NETFramework and .NETCoreApp, leave `RunWorkingDirectory` blank by default.  (and for all other TFMs for now).

This only requires removing 2 lines in the dotnet/sdk:

https://github.com/dotnet/sdk/blob/c1a276fb456606e2b19d4646f8239d2546790d42/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L146
https://github.com/dotnet/sdk/blob/c1a276fb456606e2b19d4646f8239d2546790d42/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets#L154

The CLI already works correctly with this change.  If `RunWorkingDirectory` is blank, the current working directory is used.

The only problem is Visual Studio.  @BillHiebert - VS will need to uptake this change.  If `RunWorkingDirectory` comes back blank, VS will need to default the working directory during F5.

*NOTE*: The reason there are 2 properties `<StartWorkingDirectory>` and `<RunWorkingDirectory>` is because `<StartWorkingDirectory>` already exists, and users and VS set that property already.  The reason we made a new property `<RunWorkingDirectory>` is to align it with the other "run" properties: `<RunCommand>` and `<RunArguments>`.  The public contract between the dotnet/sdk and the "clients" are these `<RunXXX>` properties.  Also, with debug profiles coming, the debug profile might want a different working directory than what `<StartWorkingDirectory>` is set to.  So creating a new property for the contract made sense.

**Comment by dsplaisted** [comment]
👍 to by default to using the current directory for `dotnet run`.

Does that mean that points 1 and 2 above for web projects will be handled by the Web SDK?

**Comment by eerhardt** [comment]
> Does that mean that points 1 and 2 above for web projects will be handled by the Web SDK?

No, with the latest plan the Web.Sdk doesn't need to change.  We will get the same behavior as project.json based `dotnet run`, which worked for web scenarios.

`dotnet run` will use the current directory.  VS will need to default the working directory to the project directory just like it did for .xproj.  Web.Sdk won't need to do anything.

**Comment by dsplaisted** [comment]
So does that mean that if you do `dotnet run` on a web project from outside of the project folder it won't be able to find any of its assets?

**Comment by eerhardt** [comment]
> So does that mean that if you do dotnet run on a web project from outside of the project folder it won't be able to find any of its assets?

Correct.  It will work the same as it does with project.json and `dotnet run` today.  One could argue that this is a "feature" that allows you to run your web app with a different set of assets from a separate directory.  (if that is desired)

**Comment by davidfowl** [comment]
BTW we (ASP.NET) spent weeks on designing this experience when we did the DNX -> dotnet CLI shift. We think we ended up with the best compromise... (all things considered)

**Comment by BillHiebert** [comment]
Note that VS tooling already behaves this way. For ASP.NET applications the working directory is always the project root. Console applications default to the project folder unless RunWorkingDirectory is set in the project, or it is overridden in the launchprofile.json file.

**Comment by natemcmaster** [comment]
👍 this (https://github.com/dotnet/cli/issues/4473#issuecomment-256531057) sounds like a good solution. Thanks @eerhardt :)

**Comment by bruce-willis** [comment]
@natemcmaster 

> FWIW to preserve existing behavior with PJ, I've been adding <RunWorkingDirectory>$(MSBuildStartupDirectory)</RunWorkingDirectory> to all of my projects.

I found a slightly better solution for this. Instead of `$MSBuildStartupDirectory` it's better to use `$(MSBuildProjectDirectory)`, cause if you launch a solution from _recent project_ in Start menu 
![recent](https://i.imgur.com/f4iAhRe.png)
and paste 
```cs 
Console.WriteLine(System.IO.Directory.GetCurrentDirectory());
```
this, the output will be: _C:\Windows\System32_ instead of project folder 
![sys32](https://i.imgur.com/yf3Yt9D.png)
