### ISSUE TITLE
Versioning convention

### ISSUE THREAD

**Issue by krwq** [dotnet/cli#450]
What are we planning to call versions for dev and stable packages?
Currently this is 1.0.0-dev-12345

We need to in particular take a look what can have version and stick with one format.

**Comment by piotrpMSFT** [comment]
1.0.0-12345
1.0.0-rel-12345
1.0.0-dev-12345
?

**Comment by krwq** [comment]
what would be the difference between the rel and no-rel?

**Comment by anurse** [comment]
Some SemVer quirks to be aware of (we hit some of these in ASP.NET ;)): 

* `1.0.5-foo` is considered **older** than `1.0.5-foo-1234`
* The part after `-` is compared/sorted as a simple string, so make sure you zero-pad any numbers (i.e. `1.0.0-dev-00001` not `1.0.0-dev-1`. It also means that once you have `1.0.0-beta-something` you can't really decide later to have `1.0.0-alpha-something` because it sorts as an "older" version.

**Comment by piotrpMSFT** [comment]
This is being tracked in #668
