### ISSUE TITLE
Migrate creates csproj based off of outputName

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4506]
Migrating a project.json with a `buildOption` `outputName` chooses to create the new csproj with the outputName instead of the original project name.

[RazorTooling in ASP.NET](https://github.com/aspnet/RazorTooling/blob/dev/src/Microsoft.AspNetCore.Razor.Tools/project.json) is a great example of this. Migrate ends up creating `dotnet-razor-tooling.csproj` instead of `Microsoft.AspNetCore.Razor.Tools.csproj`.

/cc @livarcocc

**Comment by livarcocc** [comment]
Is this related to this: https://github.com/dotnet/cli/issues/4487.

Basically, right now we don't intend on changing that. We will change the csproj to be the outputname since msbuild uses that to figure out assembly name, etc. However, we will set a PackageId if the outputname is different from the containing folder.

Would this address your concerns.

**Comment by NTaylorMullen** [comment]
Ouch, so msbuild has no way to specify a different output .dll name in the csproj contents?

**Comment by livarcocc** [comment]
There is an AssemblyName property. But honestly, I don't know why this was the route that we chose instead of setting the AssemblyName to begin with and then defaulting the project name to the project folder name.

Unless we know of a reason to have taken this approach, I actually think I would prefer to set AssemblyName and set the project name to folder name, it would match better how things were in project.json.

cc @piotrpMSFT @krwq 

@krwq This may affect your fix for the packageid above.

**Comment by piotrpMSFT** [comment]
is the suggestion that we:
- ALWAYS inherit the csproj file name from the containing directory name
- ALWAYS translate PJ.outputName to <AssemblyName> in the csproj

If that's right, I like it. This is conceptually much cleaner than having csproj names differ and have an implied impact on the output file.

**Comment by livarcocc** [comment]
For the first bullet, yes. That's correct.
For the second bullet, it should say ALWAYS translate PJ.outpuName to AssemblyName in the CSPROJ.

**Comment by NTaylorMullen** [comment]
Woohoo! Awesome, glad we're taking this approach. Makes a lot more sense in my opinion 😄

**Comment by krwq** [comment]
This should be fixed with https://github.com/dotnet/cli/pull/4536
