### ISSUE TITLE
dotnet /? -> Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#4539]
Catching arbitrary exceptions and passing off their message alone as a user error is a colossal anti-pattern. Please stop it. 
## Steps to reproduce

`dotnet /?`
## Expected  behavior

If you want to be mean, something like "error: invalid switch: /?"
If you want to be nice, just give me dotnet --help
## Actual behavior

`Object reference not set to an instance of an object`
## Environment data

```
.NET Command Line Tools (1.0.0-preview3-003913)

Product Information:
 Version:            1.0.0-preview3-003913
 Commit SHA-1 hash:  967957698e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
```

**Comment by blackdwarf** [comment]
On `1.0.0-preview3-004056` when running `dotnet /?` I get: 

`No executable found matching command "dotnet-/?"`. 

Not ideal, but better than the exception. :) We should change the error message if possible though.

**Comment by piotrpMSFT** [comment]
@blackdwarf this will need to be spec'd. If we want some list of commands to result in `did you mean` then we need to know what those mappings are. Assigning to you for spec'ing...

**Comment by nguerrera** [comment]
How about showing usage for any unrecognized command?

**Comment by blackdwarf** [comment]
@nguerrera that could be a good first step. I will do some thinking here and update the issue with the plan on Mon.

**Comment by blackdwarf** [comment]
So, here is a plan of sorts. Since we currently have a relatively small number of commands still, I think we should stick with just showing a better output, with the option of "did you mean X" be available in the future. 

For now, here is how I would like to see it:

* On unrecognized command, return the following: "Unrecognized command {0}. Please run dotnet --help for a list of commands".
* On an unrecognized switch (which is what this issue is about, as in /?), display a short form of help for the options, similar to what `git` does. This would actually take the form of the SYNOPSIS we have on our docs (e.g. https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build). 

I see that for Preview 3 if I pass in a bad switch like `dotnet publish --foo`, the error will come from MSBuild. Though I understand the *why* of it, I would imagine that a much cleaner user experience would be for the CLI to "report" the error.

**Comment by jgoshi** [comment]
Discussed this with @blackdwarf and we decided to special case /? to be equivalent to --help. That's all we'll do since we cannot detect unknown args in cases we pass them blindly to msbuild. The latest version doesn't throw a null reference exception anymore and will just say that No executable found matching command "dotnet-unknowncmd" if you call dotnet unknowncmd
