### ISSUE TITLE
Parameterless dotnet restore/build confuse xproj for buildable project file.

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#4563]
## Steps to reproduce
- Add xproj to a directory with a csproj
- Run dotnet restore or dotnet build

## Expected  behavior
- restore/build choose the only csproj file in the directory and succeed

## Actual behavior
- `MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.0-preview3-003933)

Product Information:
 Version:            1.0.0-preview3-003933
 Commit SHA-1 hash:  6fcbefa4f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

## Extra
This happens when migrating a project.json/xproj project. The xproj is left behind which then results in the cli thinking it can build it. My bet is that we're doing `.*proj` to capture other languages. Feel free to close if this is intended behavior.

**Comment by livarcocc** [comment]
We have made a change to move the PJ and the xproj to the backup folder once migration happens, so this won't be an issue.

We don't want to only look for csproj because that is not really the only thing that we can handle. We handle what MSBuild does. We could be explicit about excluding xproj, at best, but given that we are moving these files away, I don't think that is needed.

Re-activate if you feel strongly about excluding xproj.

Btw, this change to move the files went in in a latter build than 3933.
