### ISSUE TITLE
Standardize dotnet's Project Search Algorithm (i.e. how project.json files are found)

### ISSUE THREAD

**Issue by bgribaudo** [dotnet/cli#4569]
## Expected  Behavior
`dotnet restore`, `dotnet build`, `dotnet test`, `dotnet pack` all use the same search algorithm to look for projects (i.e. project.json files). 

When run from a project's top-level directory, each should find child project.json files per global.json's configuration.

If no project.json files are found, a standardized, user-friendly error message should be displayed.

When the transition is made from project.json -> csproj/MSBuild, these same expected behaviors should hold true for finding csproj files.

## Actual Behavior
Assuming a project structure of:
```
\MyProject
    global.json => { "projects": [ "src", "tests" ] }
    \src
        \MyProject
            project.json
    \tests
        \MyProjects.Tests
            project.json
```

- ### `dotnet restore`
    When run from the top-level directory (e.g. \MyProject), restores dependencies for the projects in both `\src` and `\tests`. 

    **Comments:** This is the **expected behavior**.

- ### `dotnet build`
    When run from the top-level directory, errors with `Couldn't find 'project.json' in current directory`.

    **Comments:** Does not find projects in `\src` and `\tests`. However, provides user-friendly error message.

- ### `dotnet test`
    When run from the top-level directory, errors with:

```
    dotnet-test Error: 0 : System.InvalidOperationException: C:\SomePath\MyProject\project.json does not exist.
      at Microsoft.DotNet.Tools.Test.TestCommand.GetProjectPath(String projectPath)
      at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```

**Comments:** Does not find projects in `\src` and `\tests`. Does not provide user-friendly error message.

- ### `dotnet pack`
    When run from the top-level directory, errors with: `Unable to find a project.json in C:\SomePath\MyProject\project.json`

    **Comments:** Does not find projects in `\src` and `\tests`. Error message is better than `dotnet test`'s but not as friendly as `dotnet build`'s.

## Recommendations
- Standardized the various commands mentioned above so that they all search for projects like `dotnet restore`.
- If no projects are found, have the command output a message similar to `dotnet build`'s (i.e. `Couldn't find 'project.json' in current directory or the directory structure configured in global.json`--or maybe  `Couldn't find 'project.json' in the current directory or in the directory structure configured by global.json` if a global.json file exists).

## Related Issues
Portions of the above are touched on by #2752, #3136 & #3501.

## Environment Data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by bgribaudo** [comment]
CCing @blackdwarf (per https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/issue-filing-guide.md)

**Comment by piotrpMSFT** [comment]
Fully agreed on standardization, though the team decided to move in a different direction. Specifically, we decided to have all of the commands require a path to a `root` artifact from which a closure is determined. This means you can run a command from a directory containing a `.csproj` file, or you can pass a relative or absolute path to such a file. From that file we'll find any others it references and perform the action on them as well if needed. `.sln` files will provide a way of performing actions on a number of files that might not be otherwise related.

The reason for this direction is that the `restore` behavior proved unwieldy in scenarios where you might have project.json's that are under the root directory but not desirable to restore. There was no way around it but to restructure your whole project structure. We believe that the two mechanisms for referencing closures [.sln and .csproj refs] enable similar behaviors to what `restore` used to do, while giving you control over your project's structure.

Try out the preview3 installers linked from this repo's home page to take the functionality out for a spin!

**Comment by bgribaudo** [comment]
Thanks, @piotrpMSFT.
