### ISSUE TITLE
`dotnet test` does not use contentFiles from NuGet dependencies

### ISSUE THREAD

**Issue by conniey** [dotnet/cli#4645]
## Steps to reproduce

1. Clone https://github.com/conniey/webrepo
2. Open `NetCoreApp.sln`
3. Build solution
4. Run test `xUnitLib.Program.TestFoo`

I tried to set `<CopyNuGetImplementation>true</CopyNuGetImplementation>` but it did not work either.

## Expected  behavior

The test passes.  Interestingly, when the .NET Core application `ConsoleApp2` is run, it works like it is supposed to.

## Actual behavior

Test Name:	xUnitLib.Program.TestFoo
Test FullName:	xUnitLib.Program.TestFoo
Test Source:	C:\Users\conniey\Documents\Visual Studio 2015\Projects\NetCoreApp\src\xUnitLib\Program.cs : line 14
Test Outcome:	Failed
Test Duration:	0:00:00.019

Result StackTrace:	
at Icu.NativeMethods.u_getVersion(VersionInfo& versionArray)
   at Icu.Wrapper.get_IcuVersion()
   at xUnitLib.Program.TestFoo() in C:\Users\conniey\Documents\Visual Studio 2015\Projects\NetCoreApp\src\xUnitLib\Program.cs:line 15
Result Message:	Unable to load DLL 'icuuc54.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14959
 OS Platform: Windows
 RID:         win10-x64

**Comment by piotrpMSFT** [comment]
If you check the output directory `bin/Debug/netcoreapp1.0/win7-x64` you will see that icuuc54.dll is present. The issue here seems to be that `Wrapper` is expecting icuuc54.dll to sit next to icu.net.dll. Since icu.net.dll sits in the package cache and icuuc54.dll sits in the project's output directory they currently cannot find one another. 

Try the information [here](https://github.com/dotnet/cli/issues/3233). If fixing packaging for the native dependency is not an option, consider that icu.net.dll needs to accept a path parameter by which you can pass to it the path to icuuc54.dll. You can then scan the app's base path to find the native content file and pass it in to the wrapper. 

Best of luck!

**Comment by conniey** [comment]
Thanks! repackaging my NuGet using `runtimes/{rid}/native` fixed the issues where dotnet test would not work

**Comment by piotrpMSFT** [comment]
Great :D
