### ISSUE TITLE
[Question] embedding cli executor?

### ISSUE THREAD

**Issue by nictaylr** [dotnet/cli#4661]
Hello,

I want to embed `dotnet`'s built-in portable application executor in my application.
My goal is to be able to launch and possibly attach to any portable .NET Core `.dll` application.

In other words, I want to use the functionality of `dotnet SomePortableCommandLineApp.dll` in my own application without invoking the `dotnet` executable. In Framework .NET I would use an AppDomain, but I'm not sure how to do this in .NET Core.

How can I accomplish this?

Thanks!

**Comment by piotrpMSFT** [comment]
I presume you want to do this in managed code. The issue you will run into is that some types, particularly in the core framework, cannot be loaded twice in the same CLR instance. This means that if your Host app depends on one version and your Target app depends on another then you may hit some hard-to-diagnose issues.

That disclaimer aside, can you just load the Target assembly and use reflection to invoke Main?

**Comment by nictaylr** [comment]
yes, i would like to use managed code. invoking main through reflection should be fairly straightforward.
will i be able to avoid these issues by using the reflection approach? if so, then i could just use that.

in addition, would it be possible to do this in unmanaged (c++ for example) code? i would like to load the clr from unmanaged code in a hopefully platform-agnostic way.

thanks!

**Comment by piotrpMSFT** [comment]
You won't be able to avoid these issues by using the reflection approach. Reflection itself will load e.g. System.Object, System.String, etc. which might conflict in version with the Target app. 

The unmanaged code option is much better here. Since that code would bootstrap the CLR for the target app, the app would fully own the dependencies loaded.

Why don't you start with the `dotnet` host and build up from there? The sources for the host live here: https://github.com/dotnet/core-setup/tree/master/src/corehost
