### ISSUE TITLE
Add ability to search for and install packages

### ISSUE THREAD

**Issue by jchadwick** [dotnet/cli#4674]
Nobody wants to manually edit MSBuild XML files to add package references.  If you can `dotnet restore` then you should be able to `dotnet search [query]` to search the NuGet repo or at least `dotnet install [package name]` to install a package whose name you already know.

cc: @blackdwarf

**Comment by blackdwarf** [comment]
Thanks for the comment @jchadwick. This issue is tracked as part of the #4521 issue. I will close this, but can you please add any comments over on that issue? 

Thanks!

**Comment by NuclearFishin** [comment]
Hi guys, I thought I would just comment on this one since the referenced issue #4521 has been closed, but that only pertains to adding packages and does not discuss search? Is a search feature being considered or have I just missed it? Things I checked so far:

- The `dotnet` command
- Intellisense within the `.csproj` file in Visual Studio Code
- Google ;)

I think search would be a handy addition to the CLI, as the name of a NuGet package is not always obvious, eg `Newtonsoft.Json`. It's a common feature among other package managers, eg: `npm search`, `pip search`, `composer search`. Thanks for your time!

**Comment by livarcocc** [comment]
@jonsequitur Seems like you auto-complete work enables a part of this search feature.

**Comment by jchadwick** [comment]
Since #4521 didn't resolve the issue, can we re-open?

**Comment by ti24horas** [comment]
@jonsequitur auto-complete only works for official nuget repository. For internal repos, it won't appear.
