### ISSUE TITLE
Add inter-project graph in WorkspaceContext

### ISSUE THREAD

**Issue by troydai** [dotnet/cli#470]
Build a internal project dependencies graph in `WorkspaceContext`.

Usage:
* Track all projects require a restore after one or more lock file/project file are changed.
* Invalid a project entry when it's dependency is invalid.

**Comment by cdmihai** [comment]
I was also intending, at some point, to do a project dependency graph for incremental (and potentially concurrent) compilation. 

Wondering if we can use the same graph structure for both restore and compilation ... 

I need to :
- traverse and build the graph in certain order
- make each node sensitive to all the requested target frameworks (project path -> project contexts)
- for each node, get its source file, if any
- somehow solve conflicts (same project appears multiple times in graph with different versions)

**Comment by brthor** [comment]
@cdmihai The intention of  #445 is that there would be no confilicts in these cases

**Comment by troydai** [comment]
@cdmihai It seems to be a good fit. The intention here is to enable scenario in which dependencies change of one project will be escalated to its dependents. The usage of this is in tooling like OmniSharp and VS project model server. 

To help your purpose, the dependency graph can be exposed. I suppose the traverse algorithm to be implemented independently once the data structure is settled. The node should be determined by _project path_, _framework_ and _configuration_.

**Comment by cdmihai** [comment]
Sounds good. Do you plan on making the entire graph unique to one runtime / framework / configuration combination, or will there be one graph to represent all, and then one can retrieve the desired runtime/framework/configuration combination at the node (project) level?

For me the implication is whether I'd have to recreate this graph for every combination, or only once.

@brthor 
I'm still a beginner at understanding nuget depdency graphs :) AFAIK, even if the project.json files are pruned and up to date, one can still get conflicts (conflicting paths: A->B->X_2.3.4 and D->E->F->X_3.4.5). Even if your project has the most up to date version of its own direct dependencies (A and D), something, somewhere might still conflict somewhere. Is that a right understanding?
I guess that for compilation purposes this is not relevant, because the portion of the graph that has sources (and needs built) is actually owned by the user and represent the user projects that need to be built (and therefore, hopefully, there should not be version conflicts)
