### ISSUE TITLE
Microsoft.NETCore.App 1.1.0 + vs 2017!! RC

### ISSUE THREAD

**Issue by lobster2012-user** [dotnet/cli#4756]
## Steps to reproduce
net core console project template
console.writeline(...)
update reference on Microsoft.NETCore.App to 1.1.0 (with previous versions all good)
It was updated from via nuget from 1.0*

## Actual behavior
Program                                       exited with code 
Программа "[12344] dotnet.exe" завершилась с кодом -2147450749 (0x80008083).

## Environment data
`dotnet --info` output:

https://github.com/lobster2012-user/test_vs7

```dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64```

**Comment by piotrpMSFT** [comment]
I'm not able to get a local repro. Can you share the `dotnet --info` output and perhaps your repro project so we can get to the bottom of this? Please re-open once info is available.

**Comment by lobster2012-user** [comment]
https://github.com/lobster2012-user/test_vs7


```dotnet --info
.NET Command Line Tools (1.0.0-preview3-004056)

Product Information:
 Version:            1.0.0-preview3-004056
 Commit SHA-1 hash:  ccc4968bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64```

**Comment by piotrpMSFT** [comment]
I see a failure as well, though a different one:

```
The specified framework 'Microsoft.NETCore.App', version '1.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
     {PATH}
  - The following versions are installed:
      1.0.1
  - Alternatively, install the framework version '1.1.0'.
```

but this is because I've not installed the 1.1 runtime from here:
https://www.microsoft.com/net/download/core

@schellap, in case the host error code tells you something.

**Comment by twsouthwick** [comment]
@piotrpMSFT I'm seeing the original as well with the latest VS 2017 RC and tools installed.

`The program '[6720] dotnet.exe' has exited with code -2147450749 (0x80008083).`

It seems to happen every other launch, so it doesn't completely block development, but it is definitely annoying.

```
dotnet --info

.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
```

**Comment by piotrpMSFT** [comment]
@twsouthwick thanks for the extra details. #5059 seems related. There was an issue that was recently fixed in the dotnet SDK which, due to similar symptoms, likely addresses this.

https://github.com/dotnet/sdk/pull/424
https://github.com/dotnet/sdk/pull/471

Can I ask that you save off a 'failing' and 'passing' solution directory and diff them? Let's be sure that one of those bugs tracks the artifact that's causing the failure you're seeing.

**Comment by dotnetgator** [comment]
For what it may be worth, I just ran into this...created a new .NET Core console app project in VS2017 RC, updated the NuGet to 1.1, built fine, then when I ran I got 0x80008083.  Turns out the problem was I didn't have the .NET Core 1.1 runtime installed.

Looking at the "All Downloads" page for .NET Core [here](https://www.microsoft.com/net/download/core#/current), there's a note for Visual Studio 2017 that reads (emphasis added):
> (*) Visual Studio tools include .NET Core 1.0.1. To add .NET Core 1.1 support _you need to also install the .NET Core 1.1 runtime._

**Comment by Coruscate5** [comment]
With RTM, it looks like .NET Core is 1.1 by default - all remote servers need to be upgraded before re-publishing upgraded projs to IIS
