### ISSUE TITLE
`-v` option should behave equivalently for all msbuild commands

### ISSUE THREAD

**Issue by TheRealPiotrP** [dotnet/cli#4823]
## Steps to reproduce
`dotnet msbuild -v diag`

## Expected  behavior
Like other msbuild forwarding commands `restore;build;pack` et al, this should invoke `dotnet msbuild /v:diag`

## Actual behavior
Exit Code: 1
StdOut:
Microsoft (R) Build Engine version 15.1.0.0
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1016: Specify the verbosity level.
Switch: -v
For switch syntax, type "MSBuild /help"

## Environment data
`dotnet --info` output:

@blackdwarf are we sure we want to have `-v` and `/v`? The original appeal was there, but given the variance in invocation pattern `-v diag` vs. `/v:diag` I'm worried this will create more angst than good. It just did for me.

@krwq since you looked at this code last, why the delta in behavior?? Other msbuild forwarding commands handle this well, according to `When_dotnet_command_invokes_msbuild_with_diag_verbosity_Then_arg_is_passed`...

**Comment by blackdwarf** [comment]
@piotrpMSFT no, we are not, but the idea of `dotnet msbuild` is to provide access to "raw" MSBuild in all its glory. This is why stayed with MSBuild style of switches. Of course, we could support both forms, that is, `/v` and `-v` even on `dotnet msbuild` to cover both use cases.

**Comment by krwq** [comment]
@piotrpMSFT, I agree with @blackdwarf - we have had this conversation on Slack before and since `dotnet msbuild` is as @blackdwarf mentioned pure msbuild experience I think it is not expected to provide such switch

**Comment by piotrpMSFT** [comment]
Ok, I like the reasoning. I opened the issue because the tests for `-v` are in the msbuild integration tests, which should include things we do for all msbuild invocations. This one stood out as an odity. If `-v` is not an msbuild integration feature but is a helper for a subset of commands then we need to move the test to an appropriate container. That container would own behavior common to the semantic wrapper commands, but not common to all commands that invoke msbuild.

The conversation here will capture this for the time being, but need to clean up the tests.

@livarcocc @jgoshi in case they also run across the test anomaly.
