### ISSUE TITLE
CLI has bad behavior when a csproj already exists in the folder

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#4851]
When calling `dotnet migrate` on a project.json which has a csproj file next to it, the CLI gives bad error messages and leaves files in a torn state. It both says that the migration has succeeded and that it has failed. It deletes the project.json file but leaves the csproj file unchanged.

```
E:\projects\veldrid\src\Veldrid>"E:\Tools\dotnet-dev-win-x64.latest\dotnet.exe" migrate
Project Veldrid migration succeeded (E:\projects\veldrid\src\Veldrid)
Project backup migration succeeded (E:\projects\veldrid\src\Veldrid\backup)
Summary
Total Projects: 2
Succeeded Projects: 2
Failed Projects: 0

Cannot create a file when that file already exists
Migration failed.
```

**Comment by livarcocc** [comment]
@jonsequitur Another one around the area that you are playing with right now. Assigning to you.

**Comment by piotrpMSFT** [comment]
migration is not designed to modify existing csproj files. In this scenario, we should detect that the file we will produce already exists and provide a useful error message along the lines of `Migration Failure: output file {projectname}.csproj already exists. To migrate this project please first delete {projectname}.csproj and then run migration again.` @blackdwarf

**Comment by blackdwarf** [comment]
This is a good solution. We should exit if the folder contains another csproj file.

**Comment by livarcocc** [comment]
@blackdwarf @jgoshi Can we talk to see if this is indeed the right solution? Should we really fail even if migration is able to continue?

**Comment by jonsequitur** [comment]
I think this depends on why there's a csproj there, e.g. is the csproj the result of a migration or is it something that was created by the user, e.g. to have different projects using the same source files.

**Comment by jgoshi** [comment]
Without knowing the intent, what should migration do? The current behavior is migration succeeds and just skips migrating the file. Is that ok? It could lead to subtle errors because the user will think their project.json file got migrated even when it didn't.

**Comment by jonsequitur** [comment]
@blackdwarf @livarcocc @jgoshi I think an explicit error is clearer here in absence of an ability to infer intent, perhaps with a prompt that allows the user to specify that they'd like migration to continue and skip this project.

**Comment by blackdwarf** [comment]
I would say an error would be preferable for me. With a good error, the solution is a trivial `mv myoldproj.csproj myoldproj.backup && dotnet migrate`.

**Comment by jgoshi** [comment]
Sounds good. I'll go with the error message approach.

**Comment by blackdwarf** [comment]
Hate to rain on a parade, but do we have that error message?

**Comment by jgoshi** [comment]
I was going to use what Peter suggested above. You mean do we have a localized message? No, but can't I add one for RTM?

**Comment by blackdwarf** [comment]
Nope. Is this something that is blocking people and that can live with an English error message? Or is this something that we can release note and fix in RTM+?

**Comment by jgoshi** [comment]
We also have another problem with this approach that I'm not sure what to do...

Say we migrate and 1 project successfully migrated but the other didn't because of this error. Then when I rename that one project and try to run migration again the first one (that succeeded the first time) will have this error message. The reason is we don't move project.json files to backup directory unless all projects we tried were successfully migrated.

**Comment by blackdwarf** [comment]
Ungh.

**Comment by jgoshi** [comment]
Here's a couple of options.
1. If we detect a project.json and a csproj with our output name at the start of migration, then rename their csproj file and run migration. If we already migrated the file as part of migrating dependencies, etc. then skip it. This means that in the case of a failed migration. Then running it a second time will cause us to re-migrate everything again (including projects migrated in the previous run).

2. Skip migration in these cases but call it out a little clearer (write out why we skipped the file at the end of the report). Requires loc or an English only string.

3. Fail migration. This has the problem mentioned above about re-running migration causing those that were successful before to fail now. Requires loc or an English only string.

4. Do nothing. The current behavior is we skip migrating the file. But it's not clear that we skipped it because it already exists before the call to dotnet migrate.

Thoughts?

**Comment by blackdwarf** [comment]
I like the #1 the most, but we also need strings for that: you have to tell the user you moved her cheese around. SQL Server has the same thing when upon upgrading the DB (e.g. when attaching SQL2005 DB to a SQL2008 instance) it will rename certain objects that cause conflicts to a GUID. However, it gives you a very detailed report after that. 

Do we have something like that in the migration? A file that we drop?

**Comment by jgoshi** [comment]
Look at this file:
src\dotnet\commands\dotnet-migrate\MigrateCommand.cs in the function GetProjectReportSuccessContent. Looks like we are not localizing the strings in the migration report saying success. So, it should be fine to write out that we moved projects and not localize that part too.

I guess I should move all those strings to LocalizableStrings.cs anyway for whenever is the next time we localize? Or I'm not even allowed to touch that file?

Then the next question is: what do I rename the file to. And do you want me to move that file (along with project.json) to the backup directory?

**Comment by jonsequitur** [comment]
Maybe the file should be renamed to its original migration date so people can correlate outputs to successive migration attempts?

**Comment by blackdwarf** [comment]
@jonsequitur I would say that the following would be a decent scheme: `<original_name>-moved-ddmmyyyy.<ext>`. Thoughts?

@livarcocc @nguerrera take a look at @jgoshi question above. I don't think we can add anymore strings anywhere, right?

**Comment by piotrpMSFT** [comment]
We discussed this offline. Migration will move the pre-existing csproj file to the backup directory. It will keep the original name in the backup directory.
