### ISSUE TITLE
'Migrating' from .NET Framework to .NET Standard

### ISSUE THREAD

**Issue by mpoettgen** [dotnet/cli#4874]
What would be best practice when trying to convert a whole bunch of '.NET Framework' csproj-projects to '.NET Standard'/'.NET Core' csproj-projects, optionally targeting multiple frameworks?

The projects are mostly libraries that should be simple enough to compile targeting .NET Standard, but is there any (planned) tool support to convert the traditional csproj files into the new ones?

**Comment by piotrpMSFT** [comment]
@srivatsn thoughts?

**Comment by piotrpMSFT** [comment]
@mpoettgen I don't think we have a doc yet. I've done the process a few times manually, though. Perhaps I can help with comments?

In general, I've had the most luck by:
1. `dotnet new` a core template
2. Add stuff to it until it builds your project
3. delete the old csproj file

**Comment by michael-x** [comment]
Any update on this?

**Comment by MNF** [comment]
Added a link to the article, how it can be done manually now http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/

**Comment by szalapski** [comment]
MNF, that seems to be about Visual Studio 2017, not about .NET Standard at all.

**Comment by GuardRex** [comment]
The general porting docs are at: [Porting to .NET Core from .NET Framework](https://docs.microsoft.com/dotnet/core/porting/). There are a couple of sub-topics under that which will hopefully be of assistance.

**Comment by stijnherreman** [comment]
@GuardRex there's some useful info in there but they need updating, see dotnet/docs#2255

**Comment by GuardRex** [comment]
@stijnherreman Yes, since I wrote that :point_up: a few weeks ago, it's in the bullpen at the review stage with https://github.com/dotnet/docs/pull/2467. It's subject to changes (usually not major changes tho). We don't have a built version of that one that can be seen, but the raw GH version is at: https://github.com/GuardRex/docs-1/blob/85e025b022b2f37263f2dbfbd0ea59fbd04d49f3/docs/core/porting/libraries.md

WRT .NET Standard specifically in that porting topic: One of the changes was to rip out the content that can be cross-linked because it can't be adequately covered there and it's a duplication of content, so the .NET Standard info is going to stay in [the .NET Standard topic](https://docs.microsoft.com/dotnet/standard/net-standard) (at least until we get into review and finalize that decision).
