### ISSUE TITLE
Include ASP.NET in Offline Package Cache

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4957]
Currently we're able to restore a Console application offline in CLI. We need to also make sure that the default Web template is also restorable offline.

This will impact the offline archiving build step. We need to make sure this continues to work well.

**Comment by livarcocc** [comment]
We can achieve this by using the web app template to generate the nuget cache that we archive. Should be a really simple change.

Though we should keep an eye on the size that the archive will grow to be now.

Also, will it still make sense to keep this archive in blob next to the shared framework? Now that it will include more than M.NC.App? We will also have to manually delete the lzma file from blob, so that it gets re-generated and uploaded.
