### ISSUE TITLE
Migration duplicates content items that are already provided by web sdk props leading to failed publish

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#4975]
## Steps to reproduce

1. Migrate https://github.com/balaTest/ProjectKTestProjects/blob/master/Dev14_K101/Tooling202/AspNetCoreWebApp_NoAuth_1/src/AspNetCoreWebApp_NoAuth_1/project.json#L52
2. dotnet publish it 

## Expected  behavior

It publishes successfully

## Actual behavior

```
C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Publish.targets(100,5): error MSB3094: "DestinationFiles" refers to 1 item(s), and "SourceFiles" refers to 2 item(s). They must have the same number of items.
```

## Environment data
```
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233
```

**Comment by livarcocc** [comment]
@nguerrera Migration is moving content that is explicitly marked for publish in the project.json.

We need to find a way to keep these items in sync between migration and the web sdk without requiring changes from migration every time that the web sdk changes. Otherwise it will be a game of cat and mouse.

Right now, what is the the Web Sdk including?
