### ISSUE TITLE
localized strings used as property names in RunCommand

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#4977]
https://github.com/dotnet/cli/blob/706b8a802d49be079fef570b354a70056aa2ad6f/src/dotnet/commands/dotnet-run/RunCommand.cs#L70

@vsccarl that dictionary should contain the concrete property names, not descriptors thereof. Can you revert the localization here?

Notice that the dictionary is built up and then sent to a project evaluator. If these strings get localized then the evaluator will produce different behaviors based on locale.

/cc @krwq @livarcocc @jgoshi we'll need to keep an eye out for issues like this or we'll be in big trouble when @nguerrera checks in the first pass at localized strings.

@MattGertz this kind of issue is going to be tough to spot in all cases. We'll need to think about how we will set up some localized CI machines in the very near future.

edit: here as well:
https://github.com/dotnet/cli/blob/706b8a802d49be079fef570b354a70056aa2ad6f/src/dotnet/commands/dotnet-run/RunCommand.cs#L90

**Comment by dasMulli** [comment]
Similar (own issue?): a translated string is used to translate the argument `TargetFramework` here: https://github.com/dotnet/cli/blob/706b8a802d49be079fef570b354a70056aa2ad6f/src/dotnet/commands/dotnet-run/Program.cs#L29

I wouldn't expect strings in those locations to pop up in e.g. German because `TargetFramework` is "a thing" in NuGet, csproj files and the corresponding MSBuild argument etc. I think only the description string should be translated.

**Comment by MattGertz** [comment]
@piotrpMSFT You should talk to the compiler guys; although most teams have a number of strings that need to avoid loc (properties, mostly), they in particular have lots of them because of the language itself.  IIRC, they use string constants for all of those, and in the file that defines them, they have a big warning notice that says "don't loc these."

**Comment by piotrpMSFT** [comment]
@MattGertz thanks. We do need to figure out a CI story, however, if we're to have any confidence that these tools are being implemented meaningfully.

**Comment by piotrpMSFT** [comment]
@dasMulli yep, that's another. I may need to find time to implement  some pseudo-loc story so we can get ahead of loc'd content and loc'd CI. @nguerrera do we have any tools for pseudoloc'ing?

**Comment by nguerrera** [comment]
Note that over-localization can be fixed without regard to freeze deadline.

I am thinking about how to do pseudo loc in this xlf world. Once we have a pipeline that generates resources during build, it will be easy to add to that, but we are going to have to do conversion outside build and check in converted files for RC.3 given the time constraint .

**Comment by piotrpMSFT** [comment]
@nguerrera do you think we'll be able to override the locale used by dotnet as suggested in #4988?

**Comment by nguerrera** [comment]
Yes. I'll reply with details when I have a moment to get in to them.

**Comment by dasMulli** [comment]
So apparently this has been translated (in the languages I checked): https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-run/xlf/LocalizableStrings.ja.xlf#L46
and used here: https://github.com/dotnet/cli/blob/rel/1.0.0/src/dotnet/commands/dotnet-run/RunCommand.cs#L77
So I guess this is going to be quite a ✨ surprise ✨ on `dotnet run -c Release`?

**Comment by livarcocc** [comment]
This is present in many different places. We need to do a pass through the code and fix it.

**Comment by nguerrera** [comment]
Specifc issue mentioned here are fixed by by #5509. We will be implementing the override and running unit tests on non-English, which would catch other issues like this.
