### ISSUE TITLE
Properly detect RIDs

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#498]

**Comment by anurse** [comment]
FYI, I should be able to resolve this soon. I'm working on adding the necessary OS detection to our Platform Abstractions library: https://github.com/aspnet/PlatformAbstractions - That library will be able to generate accurate RIDs for the current OS.

**Comment by MichaelSimons** [comment]
@anurse, Can you help me understand your vision for how the changes you mention in the aspnet Platform Abstractions library will be of use to CLI?  How can the code be shared or are you suggesting the code is copied between the two?

**Comment by gkhanna79** [comment]
@anurse If a library is marked for osx.10.10 and I am publishing the package on osx.10.x, where x>=10, will your solution work? I hope we are not going to be in situation where folks cannot perform repo builds because we cannot publish packages on OS versions higher than what libraries are marked for.

**Comment by gkhanna79** [comment]
Cc @davidfowl what are your thoughts?

**Comment by MichaelSimons** [comment]
@gkhanna79, My understanding is that this issue is regarding the logic that auto detects the RID of the current machine.  In talking with piotrpMSFT, our current goal is that CLI will explicitly declare support for the the platforms that it can run on.  When it is running on a supported platform, it should be able to target other platforms even if those platforms weren't supported at the time the running CLI was shipped.  When targeting platforms besides the current one, the user must explicitly specify the target RID (e.g. `dotnet restore --runtime osx.10.x` or `dotnet publish --runtime osx10,x`).  This issue is about when running on osx.10.11, the user should not be forced to specify the runtime argument.

**Comment by anurse** [comment]
The Platform Abstractions library, despite the repo name, is not an ASP.NET library, it is a purely standalone library that P/Invokes the necessary things to discover the OS version. The dotnet-cli will use this library to determine a sane default RID.

@gkhanna79 Yes, as with all other RIDs, we do walk down the graph through older versions to find compatible packages.

**Comment by gkhanna79** [comment]
@anurse Thanks for the explanation. Are we planning to move this library to the CLI repo?

**Comment by anurse** [comment]
Not sure what the plans are yet. It's part of the `Microsoft.Extensions` namespace so it'll probably be among things like https://github.com/aspnet/Configuration, https://github.com/aspnet/Logging, etc.

It doesn't have to be in the CLI repo for the CLI to use it, so we just need to find a final home for these things. Ideally, these would all be CoreFX APIs anyway (the PlatformAbstractions library is just needed because there aren't any CoreFX APIs that provide the information we need)

**Comment by MichaelSimons** [comment]
dotnet/corefx#4741 may add some of the functionality in CoreFX provided by PlatformAbstractions.

**Comment by anurse** [comment]
As long as we get Distro name and version, it could be enough.

**Comment by anurse** [comment]
I've adjusted the title to be a little more accurate and will use this issue to cover porting the RID detection that now exists in PlatformAbstractions.

**Comment by MichaelSimons** [comment]
@anurse, are you working on this issue or did you want me to take a look at it?  Your last comment makes me think you are already working on it.

**Comment by anurse** [comment]
I'm working on it, almost done just been distracted by a few meetings ;)
