### ISSUE TITLE
Unable to resolve log4net dependencies in Windows server 2012 R2 and ubuntu 14.04

### ISSUE THREAD

**Issue by Tharunkumar** [dotnet/cli#4981]
## Steps to reproduce
1) Create an app in ASP.netcore(1.0.0-preview2-1-003177) with log4net.netcore , log4netExtensions.netcore nuget packages installed.
2) Copy the source code to a server machine with Windows server 2012 R2 installed or ubuntu 14.04
3) Install .netcore framework sdk (1.0.0-preview2-1-003177) in the server machine.
4) open cli and navigate to directory where project.json is located and enter 'dotnet restore'

Note : these packages are getting restored in my local machine with Windows 8 OS and the specified .net core framework installed. 

My local machine dotnet --info output

![image](https://cloud.githubusercontent.com/assets/2314442/21046486/01ea1af0-be2b-11e6-9d9b-9557ea079bc8.png)

## Expected  behavior
log4net packages needs to be restored

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/2314442/21046442/c201a444-be2a-11e6-9bf8-b864665d2ca2.png)

## Environment data
`dotnet --info` output:

![image](https://cloud.githubusercontent.com/assets/2314442/21046450/cf7503d2-be2a-11e6-98fd-b92ce9933fca.png)

The nuget package sources i have tried are 

<add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
<add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
<add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />

**Comment by piotrpMSFT** [comment]
log4net is built using the old NuGet package format. It does not specify compatibility with Microsoft.NetCore.App and therefore is not restored. I can see that here: https://www.nuget.org/packages/log4net/ since there are no specified Frameworks, as there are for e.g. https://www.nuget.org/packages/Newtonsoft.Json/9.0.2-beta1.

If you think the package is compatible you will want to add a 

```
<PackageTargetFallback>portable-net45+win8+wp8+wpa81</PackageTargetFallback>
```

property, though match the value to whatever is the directory name inside the nuget package.
