### ISSUE TITLE
add option to configure locale of cli

### ISSUE THREAD

**Issue by enricosada** [dotnet/cli#4988]
Now that dotnet/cli has localization i think is useful to have a way to tell the cli to use a specific language (for errors/descriptions/etc).

It's useful for:

- when the cli commands are invoked from other programs (ide/shell) who have a language set (different from os default). In windows is really hard for example without arg afaik.
- specify a language in ci servers
- tests who check error messages (not all errors have a distinct id)

a similar related command line option is `/preferreduilang` of `csc`.

**Comment by dasMulli** [comment]
If implemented, it would be great to also have an environment variable controlling this.
e.g. `DOTNET_PREFERRED_UI_LANG`.
(Although `UI` seems weird for a pure console app here. `DOTNET_CLI_LANGUAGE`?)

**Comment by piotrpMSFT** [comment]
@dasMulli @enricosada I think we'll need this feature to support testing of localization. Since the default setting comes from the environment, I think an environment variable will be a very natural override. `DOTNET_CLI_LANGUAGE` sounds quite good... @blackdwarf ?

@enricosada are there scenarios that are strictly better enabled by a switch? The implementation there would be much more involved since it'd need to get plumbed through every command...

@nguerrera is there any override by default in our loc infra?

**Comment by enricosada** [comment]
An env var is fine. I cannot think an use case where cmdarg is better than env var. 

I think the only OS without an env var convention for locale is Windows AFAIK.

On osx/unix the cli should read the `LANG` env var or at least `LC_MESSAGES`.

**Comment by nguerrera** [comment]
> On osx/unix the cli should read the LANG env var or at least LC_MESSAGES. But is not the coreclr should initialize by itself?

Yes, AFAICT, coreclr on *nix will initialize default CurrentUICulture based on LANG, LC_ALL, and/or LC_MESSAGES. I got lost in the code at the point it went to ICU, but basically if any of these are set, then we let ICU decide the default, otherwise we default  to InvariantCulture. cc @ellismg in cases I've misread that.

IMHO, there should be a separate override that is cross-platform, independent from the OS mechanisms, and has higher priority than the OS mechanisms. This will make it easier to test things uniformly across operating systems.

**Comment by ellismg** [comment]
This is correct, Nick.  The relevant code in the CLR (for interested parities) is here: https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/locale.cpp#L123

**Comment by nguerrera** [comment]
As far as how to implement an override, since the CLI gets its own process and doesn't have to share threads with other components wanting different locales, it should be sufficient to simply set [CultureInfo.DefaultThreadCurrentUICulture](https://msdn.microsoft.com/en-us/library/system.globalization.cultureinfo.defaultthreadcurrentculture(v=vs.110).aspx) early in Main().

Other things to note:

* Visual Studio sets VSLANG={numerical LCID} and there are internal guidelines to respect that. Not all tools do (I've started a conversation about tightening these guidelines and scrubbing in Visual Studio >2017), but doing so is the cheapest way to get the correct behavior if VS spawns you and the VS language pack selected differs from the OS language.

* We'll also want the override to propagate down to msbuild and transitively to csc. I can't figure out how to supply an override to msbuild (cc @cdmihai), but csc invoked via common targets would respect `PreferredUILang={name}` env var that would flow to msbuild property.

**Comment by cdmihai** [comment]
@nguerrera Would VSLANG be enough, or should msbuild also introduce a command line argument for the locale?

**Comment by nguerrera** [comment]
I think VSLANG should be enough

**Comment by dasMulli** [comment]
I'd like to have an (additional / fallback?) env var that starts with `DOTNET_` to be in line with `DOTNET_SKIP_FIRST_TIME_EXPERIENCE`, `DOTNET_CLI_CAPTURE_TIMING`, `DOTNET_PACKAGES_CACHE` and `DOTNET_DISABLE_MULTICOREJIT`.
It does seem a bit strange to explicitly need to configure an "VS" thing to set a CLI option, although respecting it is perfectly reasonable.

**Comment by cdmihai** [comment]
This opens the issue of tool specific environment names. MSBuild's environment variables start with the string `MSBUILD` so should we then have `VSLANG` , `MSBUILDLANG`, and `DOTNET_LANG`? :) Though this is a bit problematic, it implies that either the upstream tool needs to set all the env vars of the downstream tools (top down) or the downstream tool needs to know about all the upstream tool's vars (bottom up). Since VS kind of imposed the top down model, it means that MSBuild would need to know about both `VSLANG` and `DOTNET_LANG` because both the CLI and VS are upstream of MSBuild. By extension, Roselyn would have to interpret MSBUILDLANG :)

Or we can just settle on one string, `VSLANG`, because it was the first. Or we can ask VS to change it to something more tool agnostic.

**Comment by cdmihai** [comment]
Discussed this in our daily stand-up. We do like the idea of forking the msbuild evaluation based on the SDK attribute to fix a bunch of wrong things with msbuild, which would be breaking changes otherwise. However, right now the change does not meet the bar for VS2017.

After this release, we may look into ways of forking evaluation and preserving backwards compat.
