### ISSUE TITLE
vsfeedback on migration

### ISSUE THREAD

**Issue by rrelyea** [dotnet/cli#4991]
See https://developercommunity.visualstudio.com/content/problem/4629/is-missing-after-upgrading-an-xproj.html

After upgrading a .NET Framework xproj file to csproj, the win7-x86 is missing from the csproj.
There is little to no documentation about that setting on how to have it set in the new csproj. I had to compare a newly created csproj from VS2017 to the generated one.

Error is
Error		RuntimeIdentifier must be set for .NETFramework executables. Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64.	HBTI.ServiceTech.Web2	C:\Users\jsgoupil\.nuget\packages\microsoft.net.sdk\1.0.0-alpha-20161104-2\build\Microsoft.NET.RuntimeIdentifierInference.targets	45	

EXPECTED
It should either assign a runtime identifier, or ask for one when migrating.

**Comment by livarcocc** [comment]
any chance we can get the xproj/project.json that is migrating incorrectly? During migration we already add any RuntimeIdentifiers as long as they already existed in your project.json.

**Comment by dbreshears** [comment]
I was able to repro by creating an ASP.NET Core Web Application (.Net Framework) in VS2015U3.  Then migrated that using VS2017 RC.2

**Comment by livarcocc** [comment]
This is not necessarily a bug.
 
The problem here is that when you have RuntimeIdentifiers (plural) set, you need to build/publish specifying which runtimeidentifier you want to use through the --runtime flag.
 
Like this:
``` 
dotnet restore
dotnet build --runtime win7-x64
dotnet run --runtine win7-x64
```
The reason why we put all the runtimes during migration is because a Rid is required when working with a full framework application. Because you may also have a .net core TFM in your project, if we just put win7-x64 in there, you won’t be able to build/run your app in a platform other than windows.
 
I don’t believe we are doing anything wrong in this case, just that the whole runtime identifiers story needs to be better explained.

**Comment by piotrpMSFT** [comment]
@livarcocc we should add back RID infrence on `run`...

**Comment by livarcocc** [comment]
So, what I will do here is preserve the rids from PJ, if there are any set there and only if there aren't, then add them all.

If the RID story changes in the SDK, then obviously, it will get regret in migration, but for now, that's all that we can do and maintain a working csproj.

**Comment by piotrpMSFT** [comment]
`run` should still infer. Probably `test` as well

**Comment by livarcocc** [comment]
@piotrpMSFT I am fine with that, but we should only infer runtime when using a TFM that requires that, like full framework. If the application has netcoreapp and runtime identifiers, I don't think that we should infer runtime then. At that point, the app is still fully a portable application and the decision to use it as a stand alone app is still happening during publish.
