### ISSUE TITLE
Targeting Linux from Windows

### ISSUE THREAD

**Issue by inwenis** [dotnet/cli#4998]
## Steps to reproduce
mkdir crossCIssue
cd crossCIssue
dotnet new
remove "type": "platform" from project.json
add "runtimes": { "ubuntu.16.04-x64": {} } in project.json
dotnet restore
dotnet build -r ubuntu.16.04-x64
dotnet publish -c release -r ubuntu.16.04-x64
move files to clean Ubuntu 16.04 machine
run ./crossCIssue.exe

## Expected  behavior
./crossCIssue.exe should run

## Actual behavior
bash: ./crossCIssue.exe: cannot execute binary file: Exec format error

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

## Checking the file format
file ./crossCIssue.exe on Ubuntu:
dotnetCross2.exe: PE32+ executable (console) x86-64, for MS Windows

**Comment by TravisBoatman** [comment]
You don't need to run `dotnet build` just run `dotnet publish -c release -r ubuntu.16.04-x64` after it's finished you can run the app with `dotnet myapp.dll`

**Comment by inwenis** [comment]
I don't have dotnet provided on my Ubuntu, this is why I want to create a self contained package. Besides - will skipping `build` fix the issue?

**Comment by dasMulli** [comment]
The file shouldn't be named `*.exe` if your build setup is correct.. `dotnet publish -c Release -r some-RID` should output an executable to `bin/Release/netcoreapp1.1/ubuntu.16.04-x64/publish/crossCIssue`. Copying the whole `publish` directory to the target machine is supposed to work, provided all system-prerequisites are met.

**Comment by inwenis** [comment]
@dasMulli thanks! Now I've realised that I need to run the file:
`dotnetCross2\bin\release\netcoreapp1.1\ubuntu.16.04-x64\publish\dotnetCIssue`
All the time I was trying to run:
`dotnetCross2\bin\release\netcoreapp1.1\ubuntu.16.04-x64\dotnetCross2.exe`

What is the `dotnetCross2.exe` file for?

**Comment by dasMulli** [comment]
@inwenis 
So that is a mixture of a bug/known issue and a limitation.. Cli copies a hosting binary there. If your development machen is the same runtime you develop for, this is what is can be run after a `dotnet build` for the runtime (you can specify multiple runtimes).
Issue: https://github.com/dotnet/cli/issues/2343
So it allows you to build and run things fast without copying too much. The build output is very developer machine specific and not intended to be portable.. And because you can't run the linux/mac specific output/host on windows and can't just copy the folder because of local machine references, the "wrong" host being there doesn't really matter anyway. (So it can theoretically work in some scenarios but it may blow up). Only the produced dll/output will matter for publishing. And since the tooling is being moved to msbuild /  `.csrpoj`-files, this will stay unfixed.

**Comment by inwenis** [comment]
@dasMulli I must admit I don't fully understand everything in your last comment, but my issue is solved anyway, thanks!
