### ISSUE TITLE
dotnet migrate should not need to add Content Update items for patterns already covered by Web SDK

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5044]
## Steps to reproduce
Using VS 2017 RC.2 (CLI 1.0.0-preview4-004233)
git clone https://github.com/balaTest/ProjectKTestProjects
cd Dev14_K101/Tooling202/AspNetCoreWeb_IndAuth_WithAI_1
dotnet migrate

## Actual behavior
This gets added to csproj
```
    <Content Update="wwwroot\**\*;**\*.cshtml;appsettings.json;web.config">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
```

Above happens because of following section from xproj project.json
```
  "publishOptions": {

    "include": [

      "wwwroot",

      "**/*.cshtml",

      "appsettings.json",

      "web.config"

    ]

  },

```
## Expected behavior
Many of the above patterns are already covered by the globs in the Web SDK. Migration should be smart and add a 'Content Update' item only when it's not covered by existing globs.

cc @mlorbetske @DamianEdwards

**Comment by livarcocc** [comment]
This would mean that CLI would have to not only understand the patterns in the SDK (which we do in a agreement manner). However, that means I would also have to be able to discern if this falls into  the SDK pattern, versus simply taking it, since it was specified by the user. Or even, I would have to take some of the user specified values out and keeps others in.

Unless we feel strongly about this. I would rather keep the code simple.

**Comment by livarcocc** [comment]
As discussed at the tools sync meeting. We are closing this bug. The risks here far out weight its benefits.
