### ISSUE TITLE
Past preview builds archive

### ISSUE THREAD

**Issue by mikehaas763** [dotnet/cli#5045]
Is there a list or archive of past preview builds? For example, links all point to latest which is preview5 at this point but I'd like to get preview 4.

**Comment by blackdwarf** [comment]
@mikehaas763 we are working on it. Expect an update by EOD tomorrow.

**Comment by piotrpMSFT** [comment]
While waiting for the docs, you can take the latest URL for the artifact you want [e.g. Windows Installer x64] and swap out the version number to be `1.0.0-preview4-004233`:

```
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-win-x64.latest.exe
```
becomes
```
https://dotnetcli.blob.core.windows.net/dotnet/Sdk/1.0.0-preview4-004233/dotnet-dev-win-x64.1.0.0-preview4-004233.exe
```

The same pattern applies to all of the links on the home page. I hope this helps until the real doc is live :)

**Comment by blackdwarf** [comment]
@mikehaas763 the release notes are on: https://github.com/dotnet/core/blob/master/release-notes/preview4-download.md. Since @enricosada already opened a similar issue at #5009 I will close this one down with the link I specified and we will keep the other issue to track the work for README.md mods. Hope that is OK.
