### ISSUE TITLE
Custom dotnet core app sdk tool(dll) can not executed (v1.0.0-preview5-004275)

### ISSUE THREAD

**Issue by DoCode** [dotnet/cli#5126]
## Steps to reproduce
- Create a default dotnet core app (dotnet-hello-world.dll): `dotnet new -l c# -t console`.
- Place the path to the published dll (dotnet-hello-world.dll) into the system path.

## Expected  behavior
- Execute: `dotnet hello-world`.
- Output: `Hello, World!`.

## Actual behavior
- Output: `No executable found matching command "dotnet-hello-world"`.

## Environment data
`dotnet --info` output:  

.NET Command Line Tools (1.0.0-preview5-004275)

Product Information:
 Version:            1.0.0-preview5-004275
 Commit SHA-1 hash:  f1c16e59d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004275

**Comment by livarcocc** [comment]
This is by design. dotnet does not look for dlls to execute in the path. If you want to execute the application through the path, I would suggest that you publish the application as a stand alone app using
```
dotnet publish -r <runtime_of_the_platform_you_want_to_run_at>
```

That will generate a your_app.exe in the output. You can then add that output folder to the path and executing your_app.exe will work.
