### ISSUE TITLE
When migrating projects with a single tfm, dotnet migrate should not need to add Condition for PackageTargetFallback

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5140]
## Steps to reproduce
Using VS 2017 RC.2 (CLI 1.0.0-preview4-004233)
git clone https://github.com/balaTest/ProjectKTestProjects
cd Dev14_K101/Tooling202/AspNetCoreWebApp_OnCore_Empty_1
dotnet migrate

## Actual behavior
This PackageTargetFallback line gets added to the csproj

```
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    ... 
    <PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.0' ">$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>

```

## Expected  behavior
Condition in the PackageTargetFallback line is not needed when the project is targeting a single tfm

It can simply be:
```
  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    ... 
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>

```

**Comment by livarcocc** [comment]
Well, the issue here is that this PackageTargetFallback was condition in the project.json. I know that it would work in the single TFM case, but it would not be the same behavior as the project.json. For everything we have been doing in migration, we have been keeping the behavior in MSBuild the same as the project.json. This has been one of our top requirements for migration and making this change would break that.

cc @piotrpMSFT
