### ISSUE TITLE
After project is created, we get an error: error occurred attempting to run the project model server process (1.0.0-preview4-004233)

### ISSUE THREAD

**Issue by alexidsa** [dotnet/cli#5188]
## Steps to reproduce
VS2015, .NET Core 1.1, Visual Studio 2015 Tools (Preview 2) 

1. New class library project

## Expected  behavior

Project created

## Actual behavior

![](https://alexidsa-gmail.tinytake.com/media/479ea6?filename=1483430622556_03-01-2017-03-03-42.png&sub_type=thumbnail_preview&type=attachment&width=496&height=305&_felix_session_id=bad7e8c4e8c3926dfd30ed8b9bafdf5b&salt=MTIzNjMzN180NjkzNjcw)

## Environment data
.NET Command Line Tools (1.0.0-preview4-004233)

Product Information:
 Version:            1.0.0-preview4-004233
 Commit SHA-1 hash:  8cec61c6f7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004233

**Comment by piotrpMSFT** [comment]
Looks like you have a preview2 and preview4 CLI installed on your machine. We moved from project.json to msbuild in preview3. Since CLI, by default, uses the latest version of itself... your project is trying to launch using an incompatible CLI.

Take a look at https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md#how-do-i-work-with-projectjson-and-csproj-on-the-same-machine

Add the global.json described in that doc to the root of your project directory. You may need to adjust the version number to match the 1.0.0-preview2-* you have installed. To find that, run `where.exe dotnet` to find where your `newest` CLI is installed, then go up a few directories to see what other versions are there.

Sorry about the hassle. Changing out project systems has been a challenge!

**Comment by Korporal** [comment]
@piotrpMSFT Your response says "...the 1.0.0-preview2-* you have..." but he installed 1.0.0-preview4-* NOT 2.

You mention preview-3 will installing that fix the problem? 

Also preview 3 has name ".Net Core SDK 1.0 Preview 3" does that differ from .Net Core 1.0.1?

I posted in your "core" repo, issues that this stuff is utterly confusing and making very hard to get much done.

Bear in mind I was trying to follow thus tutorial 

http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

Clearly whatever he installed worked fine, so how/where can we get EXACTLY the same .Net Core stuff that he used??

**Comment by piotrpMSFT** [comment]
@Korporal @alexidsa certainly did install preview4-004233, as you say. However, the project is being opened with preview2 tooling for Visual Studio 2015. preview3+ are not compatible with Visual Studio 2015. The workaround I offer will fix VS 2015 by locking the project to a preview2 CLI.

As you say, it's confusing. Once VS2017 ships you will be able to `dotnet migrate` these project.json projects to msbuild and eliminate this class of issues.
