### ISSUE TITLE
AspNetCoreWebApp_OnCore_Empty_1 : Run 'dotnet migrate' at the solution folder does not migrate the sln file

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5238]
## Steps to reproduce
Using VS 2017 RC.3 (d15prerel.26106.02 with CLI 1.0.0-preview5-004382)
git clone https://github.com/balaTest/ProjectKTestProjects
cd Dev14_K101/Tooling202/AspNetCoreWebApp_OnCore_Empty_1
dotnet migrate 
dotnet restore

## Actual behavior
Restore fails

![image](https://cloud.githubusercontent.com/assets/8246794/21736856/90f83eda-d428-11e6-9279-bfc62a1b7979.png)

## Expected  behavior
Running "dotnet migrate" on the solution folder should migrate the sln file as well. You should not need to run "dotnet migrate AspNetCoreWebApp_OnCore_Empty_1.sln"

**Comment by livarcocc** [comment]
@blackdwarf do you have any issues with making this the migration order of preference:

dotnet migrate (no args)

- if the current folder has sln file, migrate the sln.
- if the current folder has global.json file, migrate global.json
- if the current folder has csproj file, migrate csproj.
- otherwise migrate the folder.

Any concerns?

**Comment by DustinCampbell** [comment]
That seems right to me.

**Comment by blackdwarf** [comment]
@livarcocc as we discussed offline, nope :)

**Comment by livarcocc** [comment]
I believe we discussed that we are not going to do this. Mainly because doing it removes the capability of migrating an entire folder if there is a sln or global.json in it. Basically, we don't have a flag to say, migrate directory (instead of solution of global.json) and we can't add one now because of the loc freeze.

If the user wants to migrate a sln or a global.json with just the projects referenced in those projects, he has to be explicit and use dotnet migrate sln or dotnet migrate global.json

cc @piotrpMSFT @blackdwarf @DustinCampbell

**Comment by DustinCampbell** [comment]
That's unfortunate, though I get the reasoning. Also, my gut says that this won't hit many.

**Comment by livarcocc** [comment]
Ok, I think what we should do here is compromise. When we do dotnet migrate in a folder that contains a sln, we should migrate the entire folder, for the reasons explained above. That means, that we will not restrict the migrated projects to those in the sln file. However, we should still see that there is a sln file in the same folder in which migration was run and we should update that sln file to point to the new csproj files.

I believe that this is a compromise that will meet most peoples expectations. There are a couple of corner cases, but I don't think they are worth complicating this for it at this point. An example of a corner case is if your sln file points to a project in a parent or sibling folder of the folder containing the sln. Because migration is running based on the current folder (and we are not adding the sln file projects to the search paths) we won't find these projects.
