### ISSUE TITLE
Dotnet run  --> failed with error dialog: "dotnet has stopped working"

### ISSUE THREAD

**Issue by jinujoseph** [dotnet/cli#5264]
## Steps to reproduce
- Copy the folder \\mlangfs1\public\Jinuj\TestCases\AspNetCoreWeb_IndAuth_WithAI_1 to your machine 
- dotnet migrate 
- dotnet restore 
- dotnet build 
- dotnet run 
## Expected  behavior
runs successfully

## Actual behavior
Dotnet run  --> failed with error dialog: "dotnet has stopped working"
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging, Version=1.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
![image](https://cloud.githubusercontent.com/assets/12449387/21828857/b3c0bb5a-d747-11e6-97d4-09b9ba218f6a.png)

dmp file at : \\mlangfs1\public\Jinuj\TestCases\dotnet.dmp 
## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0-preview5-004382)

Product Information:
 Version:            1.0.0-preview5-004382
 Commit SHA-1 hash:  84730e31a6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview5-004382

**Comment by livarcocc** [comment]
This is happening because during migration we update the tools versions to 1.0.0.msbuild3-final. One of these tools, likely EntityFrameworkCore.Tools, has a dependency on 1.0.3. However, the packages in PJ are still pointing to 1.0.0. We can see that because when we restore, there are downgrade warnings.

The issue here is that some tools package took a dependency on 1.0.3. Now, we can either change the package back to 1.0.0, or we can have migration work around this problem by migrating the packages being downgraded to a new version.

**Comment by livarcocc** [comment]
EF tools are being downgraded to https://github.com/aspnet/EntityFramework.Tools/pull/42. This is a no-op for migration.

**Comment by livarcocc** [comment]
Jinu, this is now fixed. A new EF package has been published. I believe it will be inserted into tomorrow's VS build.
