### ISSUE TITLE
`dotnet add package` with `--version`  fails

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/cli#5296]
## Steps to reproduce
`dotnet new`
`dotnet add package Microsoft.AspNetCore --version 1.1.0`

## Expected  behavior
Adds PackageReference
```xml
<PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
```

## Actual behavior
Fails.

> Please specify one package reference to add.

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview5-004478)

Product Information:
 Version:            1.0.0-preview5-004478
 Commit SHA-1 hash:  4d3e2872fe

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/namc/.dotnet/sdk/1.0.0-preview5-004478
```

**Comment by livarcocc** [comment]
@mishra14 can you take a look?

**Comment by mishra14** [comment]
@livarcocc  @natemcmaster can you try `dotnet add package --version 1.1.0 Microsoft.AspNetCore `?

**Comment by krwq** [comment]
@mishra14 if the issue is that positional args need to go after named args then I think we need to reiterate some design of command line parser cc: @blackdwarf

**Comment by natemcmaster** [comment]
Yes, changing order fixes issue. :+1: for order-insensitive command args parsing.

**Comment by blackdwarf** [comment]
Yes, this is not good. It also breaks the overall pattern of invoking. Not horribly so, but still. 

@krwq @livarcocc what would it take to fix this?

**Comment by piotrpMSFT** [comment]
We need to fix this. I see how we got here: `dotnet add project` supports adding multiple projects. That pattern was followed in `dotnet add package`, having it treat the package name, instead of accepting it as an argument. This is what gives an order to the expected inputs.

This approach is inappropriate because the rest of the command is not set up to support multiple packages in a single invocation. In fact, the implementation enforces this viewpoint by ensuring that only a single package name is passed in.

The fix here is quite simple and should have no UX degradation. We should convert the package name to an app.Argument, as is done in `dotnet migrate`'s Program.cs.

**Comment by mishra14** [comment]
PR: https://github.com/dotnet/cli/pull/5372
