### ISSUE TITLE
dotnet.exe unpacks a bunch of packages on first execution, even if VS use filled up the user package folder already

### ISSUE THREAD

**Issue by rrelyea** [dotnet/cli#5325]
## Steps to reproduce
1) in VS, go ahead and create some .net core 1.0.3 and .net core 1.1.0 apps.
2) Restore in VS.
3) launch dev command prompt
4) cd to a project directory
5) dotnet pack (or any command, I think)

## Expected  behavior
don't unpack a bunch of packages, if they aren't needed

## Actual behavior
A command is running to initially populate your local package cache, to improve restore speed and enable offline access. This command will take up to a minute to complete and will only happen once.
Decompressing 100% 6059 ms
Expanding 100% 72023 ms

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc3-004502)

Product Information:
 Version:            1.0.0-rc3-004502
 Commit SHA-1 hash:  db2282a055

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004502

**Comment by piotrpMSFT** [comment]
@rrelyea we have two ways to deal with this. 

First, CLI offers an environment variable called DOTNET_SKIP_FIRST_TIME_EXPERIENCE which can be set when a hosting environment [VS, VS Dev Console] guarantees that the first-run experience has otherwise been accounted for.

Second, and likely better, we could do a better job of asking NuGet whether particular packages are already installed in the current context's packages directory. Is there a NuGet API that would let us quickly make this determination during the first-run experience? `NuGet.IsPackageInstalled("Microsoft.NetCore.App", "1.0.3");` for example?

**Comment by piotrpMSFT** [comment]
ping @rrelyea

**Comment by piotrpMSFT** [comment]
I opened a tracking issue in nuget/home. I agree with @rrelyea that being able to detect that the cache is already primed would be a nice UX improvement. I hope we can get an appropriate API in time.

**Comment by livarcocc** [comment]
We have actually unified the offline cache in 2.0 between VS and the CLI. Closing this issue.
