### ISSUE TITLE
Migration: https://github.com/aspnet/SignalR

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5381]
1. Go to https://github.com/aspnet/SignalR
2. Download as zip
3. dotnet migrate signalR.sln
4. dotnet restore signalR.sln

There are a bunch of restore errors in ChatSample.csproj (but they don't seem to affect the build).

**Comment by livarcocc** [comment]
I tried a couple of things here.

First, I tried to build using PJ itself, and my build there is failing. There are a bunch of packages that it can't restore. So, it seems like it does not work in PJ even.

However, after migrating, dotnet restore <sln_file> did succeed, but build fails with different issues.

@anurse @pakrym is there any secret to build signalR? Also, anything special in the build itself, so that we may need to do to be able to run dotnet build on the migrated sln file?

Please, re-activate this issue when you have more information.
