### ISSUE TITLE
Run 'dotnet migrate' fails on a machine that has both VS 2015 and VS 2017 installed - No executable found matching command "dotnet-migrate"

### ISSUE THREAD

**Issue by balachir** [dotnet/cli#5401]
## Steps to reproduce

1. Using a SxS machine VS 2015 U3 with .NET Core 1.0.1 Tooling x VS 2017 RC.3 (d15rel.26118.01)
       - 2 versions of CLI  are installed : 1.0.0-preview2-003131 and 1.0.0-rc3-004517
2. git clone https://github.com/balaTest/ProjectKTestProjects
3. cd Dev14_K101/Tooling202/AspNetCoreWebApp_OnCore_Empty_1
4. dotnet migrate 

## Actual behavior
dotnet migrate fails

![image](https://cloud.githubusercontent.com/assets/8246794/22129796/1289db82-de5d-11e6-913e-912c2f63cfad.png)

## Expected  behavior
dotnet migrate to succeed

**Comment by livarcocc** [comment]
The issue here is that the project has a global.json in it that has the skd version set to preview2. So, after you clone it and run dotnet migrate, the host is invoke the preview2 CLI which does not contain a migrate verb.

The fix here is to go ahead and delete the global.json and then run dotnet migrate.
