### ISSUE TITLE
migration should ignore files/folders in publishOptions section from project.json since csproj would have broken files displayed in the tree

### ISSUE THREAD

**Issue by abpiskunov** [dotnet/cli#5413]
## Steps to reproduce
Se TFS bug 369933 that came form vsfeedback:

When I tried opening my existing ASP.NET Core solution in VS2017 that I had created with VS2015 some of the files and wwwroot folders have a warning symbol on their icon in the solution explorer and they cannot be opened.

Original solution is here: https://github.com/danroth27/AspNetCoreModules/tree/dynamic

Migrated solution: https://github.com/danroth27/AspNetCoreModules/tree/msbuild

## Expected  behavior

no broken files/folders after migration

## Actual behavior

wwwroot and appsettings.json appear as broken items in the tree

## Environment data
`dotnet --info` output:

Proposed fix: 
	In project.json user could specify any file/folder that did not exist in disk (like in this case wwwroot and appsettings.json did not exist at all for that project). When we migrate to csproj and add them to project, project system thinks that files must exist and shows them in the tree with warnings. To solve that migration could:
-	Check if given item is a specific folder/file (not a glob) then check if file or folder exists on disk – then add it, otherwise not. 
-	If it is a glob then always add it, since globs would not add items to project when they don’t exist on disk.

**Comment by piotrpMSFT** [comment]
We'll take a look at this for 1.0.0-rtm if time permits. I'm very nervous about taking the suggested fix. My particular concern are files that were added to the project.json because they were generated by tools [code generators and the like]. Taking the fix will mean that we would break such projects.

@abpiskunov I understand there is a list of files that was added by default to project.json Web templates. Do you have an enumeration of these that we could track explicitly?

**Comment by piotrpMSFT** [comment]
We decided not to pursue this issue in migration for 1.0.0. The risk of breaking projects that depend on code generators, something we saw on several occasions due to project.json's limited support for build variables/configurations, outweighs the challenge of removing non-existent files from a csproj via the VS IDE.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#32
