### ISSUE TITLE
Does a build dependency influence the minimum netstandard?

### ISSUE THREAD

**Issue by Qowy** [dotnet/cli#5431]
Let's say I am building a library and all of my API would be compatible with netstandard1.2 or similar.
However I would require a build dependency that has a minimum version netstandard1.6

Now I would have to set the target framework in my library to netstandard1.6 right?
However would my library technically work once compiled with netstandard1.2? (if i would just manually declare the package as netstandard1.2, if that is even possible)

**Comment by ericstj** [comment]
I'm not 100% sure what you mean by "build dependency" here.

Suppose you have API that's compatible with netstandard1.2: that means your reference assembly can be netstandard1.2.

Now if you need a netstandard1.6 API to implement that api then it means your implementation must be netstandard1.6.  If this was all you packaged you'd run into places where folks could compile but would be missing implementation at runtime.  

Now suppose you can just provide a "better" implementation with netstandard1.6 dependencies but can also implement it with netstandard1.2 dependencies.  In that case you could include both implementations in the package and "cover" the entire netstandard1.2 set of frameworks, where netstandard1.6 frameworks get a "better" implementation.

Let me know if this answered your question, otherwise please clarify what you mean by "build dependency".

**Comment by Qowy** [comment]
I was thinking about something like this (from [https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json)

 ```
 "dependencies": {
        "System.Reflection.Metadata": "1.3.0",
        "Microsoft.Extensions.JsonParser.Sources": {
          "type": "build",
          "version": "1.0.0-rc2-20221"
        },
        "Microsoft.Extensions.HashCodeCombiner.Sources": {
          "type": "build",
          "version": "1.1.0-alpha1-21456"
        },
        "Microsoft.Extensions.DependencyModel": "1.0.0-*"
    }
```
Where it states: 

> build is known as a development dependency and is only used for build-time. It means that the package should not be published or added as a dependency to the output .nupkg file. It has the same effect of setting supressParent to all.

I currently have no need for this, so the question is somewhat academic but suppose Microsoft.Extensions.JsonParser.Sources is a netstandard1.6 package and the rest of my library is only using netstandard1.2 APIs. What is the required netstandard of my library after publishing.
I could not find any documentation about this.

**Comment by ericstj** [comment]
Since all the other packages are being resolved as netstandard1.6 you're getting assembly refs to higher versions of some of those package assets, along with API that might even be automatically preferred.  Imagine a library with an netstandard1.2 api `void Foo(object)` and a netstandard1.6 overload `void Foo(string)`.  You can't prevent yourself from using the netstandard1.6 API but it'll be missing from a netstandard1.2 framework.  As such it is never really safe to *lie* about what TFM a library was built against.

It looks like what you want is something like  `"type": "build"` + `"imports": "netstandard1.6"`, but just for a single package.  The only way to do this safely without lifting up the dependencies of that package would be to have a `netstandard1.6` scope (eg: package graph) for that library and its entire closure.  This entire scope would need to be passed to the compiler under an [alias](https://msdn.microsoft.com/en-us/library/yabyz3h4.aspx).  After doing that, you might be able to make it work, but its of dubious use since there wouldn't be any types shared between the alias scope and outside it.

/cc @davidfowl @terrajobst

**Comment by davidfowl** [comment]
@Qowy This should be filed on nuget. This is something we want to do for things like:
- MSBuild tasks
- Roslyn analyzers

It's been talked about a bunch but never implemented.
