### ISSUE TITLE
Migration: excluded files need to be removed

### ISSUE THREAD

**Issue by jgoshi** [dotnet/cli#5461]
If a project.json uses an exclude statement, then the migrated csproj file needs to use Remove. For example:

&lt;Compile Remove="FileToRemove"/&gt;

We need to do the same thing for resources too. Otherwise the migrated project fails to build.

**Comment by jgoshi** [comment]
When this is fixed, re-enable the build part of this test:
WhenMigratingAProjectWithDeprecatedCompileBuiltInOptionsItSucceeds

**Comment by NTaylorMullen** [comment]
Doing `<Compile Remove="FileToRemove"/>` doesn't seem to work. We work around this by doing 

`<Compile Include="**/*.cs" Exclude="WhatWeWantToExclude" />`

I assume there's an underlying msbuild or sdk issue here. Where should I file a follow up issue?

**Comment by livarcocc** [comment]
@NTaylorMullen I don't understand how your workaround does not hit issues with duplicate sources since the Include **/*.cs is implicitly done in the SDK. You will end up with potentially duplicate files right?

I think we should file an issue with MSBuild to start, to see why Remove is not being honored.

cc @rainersigwald

**Comment by rainersigwald** [comment]
Can you give an exact example? @cdmihai is looking at some possibly-related behavior

**Comment by NTaylorMullen** [comment]
Spoke to soon here. There were some underlying custom build bits on our end interfering which then made it seem like Remove wasn't working.
