### ISSUE TITLE
dotnet migrate should raise transitive framework assemblies from project referenes

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/cli#5494]
Trying to utilize a transitive project references framework assembly results in build errors.

Note: This used to work in project.json land (built the repro in project.json then migrated).

After discussion [here](https://github.com/NuGet/Home/issues/4412) the decision was to raise these framework assembly refs at the dotnet migrate level.

**Comment by livarcocc** [comment]
Yeap. We were actually doing that in the past, but I didn't realize that one SDK implemented transitive dependencies that this was not included there as well.

I will bring back that feature.

**Comment by srivatsn** [comment]
@livarcocc @333fred will this require keeping around project.jsons of P2Ps and cause all the ordering problems we were having for partial migrations and such?

**Comment by livarcocc** [comment]
Sri, that's what I was thinking about. This would bring back those problems and affect VS migration. 
The way I see it, we have a couple of options:

1. Make this work if the `--skip-project-references` is not passed. But that means that whenever the flag is passed (100% the case for VS), projects may be migrated missing this information.
2. Make migration find project.json for dependencies in the backup folder. But in this case, I think we should also allow for the backup folder to be passed to migration, so that migration is not aware of how VS calculates the path to this folder. This would be potentially a significant change for migration so late in the game and I am a bit nervous about taking it.
3. Fix this in NuGet and the SDK?
4. Do nothing. Migrate these projects wrong and have people add the references themselves.

I am not sure why NuGet decided not to honor this in the MSBuild world. But I feel like none of the options above are ideal for the stage we are in the cycle.

cc @piotrpMSFT @DustinCampbell

**Comment by piotrpMSFT** [comment]
We're not going to be able to address this for 1.0.0. We need to take time to determine if this fix belongs in CLI, NuGet, or a combination of the two.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#28
