### ISSUE TITLE
MsBuild help is shown when I need dotnet help.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#5564]
## Steps to reproduce
dotnet publish /?

## Expected  behavior
I get publish help

## Actual behavior
I get msbuild help

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-rc3-004530)

Product Information:
 Version:            1.0.0-rc3-004530
 Commit SHA-1 hash:  0de3338607

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc3-004530

**Comment by blackdwarf** [comment]
The `/?` switch is passed to MSBuild because we don't handle it in the CLI. The `/?` switch for us is not valid as help. However, this is confusing for users, I agree. Assigning this to me to specc out how to unify the advanced commands and overall CLI commands help-wise and messages wise for 2.0.0.

**Comment by livarcocc** [comment]
This has ben fixed in 2.0.
