### ISSUE TITLE
Native DLL's used through platform invoke arent loaded from AppContext.BaseDirectory

### ISSUE THREAD

**Issue by PurelySimple** [dotnet/cli#5622]
## Steps to reproduce
1. Create a new console project (ie MyApp) that outputs `Console.WriteLine(AppContext.BaseDirectory);`
2. Reference a native DLL call on a method using `[DllImport("MyNative.dll")]`
3. Make a call to that method in the application
4. Run `dotnet build` on the project
5. Copy MyNative.dll to the output directory (ie bin\Debug\netcoreapp1.1)
6. Run `dotnet <MyApp.dll>` from **within the output directory**. Everything should work fine. AppContext.BaseDirectory will be the output folder.
7. Go to another location (such as the project root) and run `dotnet <path\to\MyApp.dll>`
8. Failed to find MyNative.dll but AppContext.BaseDirectory will still be correctly set as the output folder (which contains the native dll).
## Expected  behavior
I would expect any native DLL's referenced from an assembly to reside along side it and behave like other managed DLL's by being loaded from AppContext.BaseDirectory and not wherever the `dotnet path\to\app.dll` was invoked from.

This is especially problematic as VS2017 seems to invoke the compiled app DLL from the project root and not the bin\Debug\netcoreapp1.1\ directory where it resides. I have to keep a separate set of native DLL's in the project root for them to be found.

## Actual behavior
The platform invoke call throws an exception saying the native DLL couldn't be found.

## Environment data
`dotnet --info` output:

$ dotnet --info
.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-rc4-004771

**Comment by piotrpMSFT** [comment]
@gkhanna79 this seems like a host issue. Can you confirm before I move?

**Comment by gkhanna79** [comment]
In either of the cases above, I do not believe the native binary is in the deps.json since the steps call out copying it explicitly. Otherwise, the host, which only uses the native entries in deps.json and sets their respective folders as native dll search paths, should have found it.

I think this sounds more like an interop layer design coming into play.

@yizhang82 @luqunl should be able to help here.

**Comment by PurelySimple** [comment]
I can confirm that the referenced native DLL is not in the deps.json. In a more elaborate project than the one I described in the repro steps, I use the following in my csproj to make sure my native DLL's get copied to the output directory on build.
```
  <ItemGroup>
    <None Include="Native-x64\*.dll">
      <Link>%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
```
Whether its copied via the project or manually it makes no difference. The native DLL has to reside in the directory where `dotnet` is invoked from and not the directory the app is.

**Comment by piotrpMSFT** [comment]
@PurelySimple if this can be fixed in the interop layer, we'll be waiting for a new netcoreapp version to consume the fix. In the short term, can you work around by putting the native dependency into a nuget package and resolving it from a local "file system" nuget package store? This will help the native dependency get into the deps file. If you're targetting multiple native platforms, it also sets you up for managing runtime-specific versions!

**Comment by PurelySimple** [comment]
@piotrpMSFT Yes, I can work around it in the meantime. I do plan on targeting multiple native platforms in the future and its good to know that native dependencies will work through nuget packages. Thanks.

**Comment by piotrpMSFT** [comment]
@gkhanna79 where is the best place to track the Interop feature request/issue? I'm worried it will get lost here...

**Comment by gkhanna79** [comment]
Please file it in CoreCLR repo and CC @yizhang82

**Comment by piotrpMSFT** [comment]
Thanks. Closing this copy.
