### ISSUE TITLE
dotnet run application arguments handling

### ISSUE THREAD

**Issue by dibyendumajumdar** [dotnet/cli#5640]
Hi

When I run my application using dotnet run, and specify application arguments, I expect the application to receive application arguments only. But it also receives a bunch of garbage arguments.

For example:

dotnet run MyApp.dll -- arg1

The application should receive 'arg1' as first argument.
Instead it receives, 'MyApp.dll', '--', 'arg1' which seems nonsensical.

**Comment by piotrpMSFT** [comment]
This would be a breaking change at this point. Let's revisit in 2.0.

**Comment by dasMulli** [comment]
@dibyendumajumdar are you trying to run a specific dll? This is meant to be done via `dotnet MyApp.dll`. `dotnet run` is for building and running a project from source.

I think the behaviour in this case should be:
If arguments contain "--", then everything before that is passed as MSBuild argument. In case of `MyApp.dll`, this hopefully causes msbuild to error out. Maybe some magic tells you that you likely meant to run `dotnet MyApp.dll` instead because you passed `.dll`. If someone deliberately wants to pass `--` to the application, then you have to add a second one: 
```
dotnet run -- -some -options -- a-file -not-an-option
```

**Comment by dibyendumajumdar** [comment]
@dasMulli I am building and running from source at the moment.

**Comment by livarcocc** [comment]
When doing it in the latest 2.0 CLI, I get what is expected: the arguments that come after the -- are passed to the application:

```
dotnet run -- a b c d e f g
Arguments: a,b,c,d,e,f,g
```

This issue seems to be fixed. If I got it wrong, please, re-activate.
