### ISSUE TITLE
How to update Visual Studio 2015.3 CLI version?

### ISSUE THREAD

**Issue by Mds92** [dotnet/cli#5755]
I'm using Visual Studio 2015.3
Recently I worked with .Net Core, you can see it [here](http://stackoverflow.com/questions/42297154/dependency-does-not-support-framework-netstandard-version-v1-6-visual-studio-2),
So, I get latest version of `.Net Core` SDK and Runtime from the following link:
`https://github.com/dotnet/core/blob/master/release-notes/rc4-download.md`
So my .Net Core version is as the following
![dotnetcore-version](https://cloud.githubusercontent.com/assets/4269991/23077182/b58a5f20-f558-11e6-9d86-2260d26ec104.jpg)
But in Visual Studio I get the following version
![dotnetcore-vs-version](https://cloud.githubusercontent.com/assets/4269991/23077229/e6104d26-f558-11e6-8503-c1c109583c52.jpg)

What's wrong and how I can update Visual Studio CLI version?

**Comment by mairaw** [comment]
Visual Studio 2015 only supports up to Preview2. The latest tooling is only supported in Visual Studio 2017 RC.

**Comment by Mds92** [comment]
Thanks

**Comment by livarcocc** [comment]
@Mds92 you probably have a global.json at the root of your repo that has an SDK version set in it pointing to preview2.

Nevertheless, @mairaw is right, VS2015 supports up to Preview2 and won't work with rc4. Also, rc4 does not support project.json. If you are using project.json, you will have to migrate it to MSBuild in order to use RC4. You can do that using the dotnet migrate command. More on this here: https://github.com/dotnet/cli/blob/rel/1.0.0/Documentation/ProjectJsonToCSProj.md
