### ISSUE TITLE
Messy Version Numbers

### ISSUE THREAD

**Issue by Timothy-Liu** [dotnet/cli#5936]
## Steps to reproduce
1. Download the latest version dotnet-dev-win-x64.latest.exe
2. Double click to run it
3. The installation UI shows it is installing .NET Core SDK **1.0.3**
4. After install finished run command "dotnet", it shows "Version : **1.1.0**"
5. Run command "dotnet --version", it shows **1.0.1**-rc4-004953
6. Navigate to Control Panel -> Programs -> Programs and Features, it shows .NET Core SDK **1.0.1** (x64)

## Expected  behavior
1. Consistent version number.
2. Or, point out what is the number for (for example .NET Core CLR version or CLI version)

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1-rc4-004953)

Product Information:
 Version:            1.0.1-rc4-004953
 Commit SHA-1 hash:  9b69969149

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.1-rc4-004953

**Comment by livarcocc** [comment]
For the 1.0.1 release of the CLI, we have update the installers to display this new version and that's also what dotnet --version and dotnet --info will display. These two commands display the SDK version.

However, running dotnet alone will still show 1.1.1 and that's because that shows the version of the latest runtime available in the machine.

There is an issue in core setup tracking improving this part of the experience here: https://github.com/dotnet/core-setup/issues/1593.
