### ISSUE TITLE
`dotnet new console -o app` creates source files with execute permissions on linux

### ISSUE THREAD

**Issue by AArnott** [dotnet/cli#6016]
## Steps to reproduce

On "Ubuntu for Windows 10":

```
dotnet new console -o hwapp
ls -l hwapp
```

## Expected  behavior

```
total 0
drwxrwxrwx 2 andrew andrew   0 Mar 12 08:08 ./
drwxrwxrwx 2 andrew andrew   0 Mar 12 08:08 ../
-rw-rw-rw- 1 andrew andrew 170 Mar 12 08:08 hwapp.csproj*
-rw-rw-rw- 1 andrew andrew 175 Mar 12 08:08 Program.cs*
```

Specifically note how the source files do not have the `x` attribute.

## Actual behavior

```
total 0
drwxrwxrwx 2 andrew andrew   0 Mar 12 08:08 ./
drwxrwxrwx 2 andrew andrew   0 Mar 12 08:08 ../
-rwxrw-rw- 1 andrew andrew 170 Mar 12 08:08 hwapp.csproj*
-rwxrw-rw- 1 andrew andrew 175 Mar 12 08:08 Program.cs*
```

Specifically note how the source files *do* have the `x` attribute, making linux think they are scripts meant to be executed.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```

**Comment by livarcocc** [comment]
Moved the issue to the templating repo: https://github.com/dotnet/templating/issues/424.

**Comment by ibqn** [comment]
I have also noticed that, so that almost every file which `dotnet new` creates is turned into script, which might be executed by mistake (or on purpose by the manipulated nuget package) and damage your system. In my opinion, this is a huge security issue and so far there is no stable release, which has this issue addressed (dotnet 2 will the first one). LOL, welcome to the world of windows.
