### ISSUE TITLE
[MIGRATION]: copyToOutput not converted correctly

### ISSUE THREAD

**Issue by Daniel15** [dotnet/cli#6068]
## Steps to reproduce
project.json:
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "copyToOutput": {
      "mappings": {
        "foo.txt": "../bar.txt"
      }
    }
  },
  "dependencies": {
  },
  "frameworks": {
    "netcoreapp1.0": {}
  }
}
```

Then run `dotnet migrate project.json`

## Expected  behavior
`copyToOutput` is correctly migrated across

## Actual behavior
The `copyToOutput` line is migrated across as:
```
<None Update="..\bar.txt">
  <Link>foo.txt</Link>
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
```

Visual Studio doesn't appear to recognise this at all. It doesn't show the file in the Solution Explorer, and it is not copied across as part of the build.

After manually adding the link in Visual Studio, it looks like this is the correct syntax:
```
<Content Include="..\bar.txt" Link="foo.json">
  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</Content>
```

## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15031
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```
cc @blackdwarf @livarcocc

**Comment by livarcocc** [comment]
This is a known issue though I couldn't find the issue for it right now.

The problem is that the SDK has an implicit globing for None but only for files under the project folder. Because you are referencing a file higher up in the folder structure, it is not being picked up by that glob and the update there does not add as an upsert.

I believe if you used None instead of Include and simply changed Update to Include this would also work.

In the end, we decided not to do glob evaluation during migration and play safe for the majority of projects.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/cli-migrate#17
