### ISSUE TITLE
Migration results in project losing files outside the project directory

### ISSUE THREAD

**Issue by sepidehMS** [dotnet/cli#6111]
## Steps to reproduce
1. Clone https://github.com/dotnet/buildtools/tree/master/src/BinaryRewriting/BclRewriter
2. dotnet migrate

## Expected  behavior
csproj including source files outside of the directory it's in

## Actual behavior
csproj does not include the source files outside its own directory

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by livarcocc** [comment]
I looked at the repo, I didn't see any reference to the sources outside of project folder in the project.json.

**Comment by sepidehMS** [comment]
My issue is about the sources included in the [.csproj file](https://github.com/dotnet/buildtools/blob/master/src/BinaryRewriting/BclRewriter/BclRewriter.csproj). After migration they all got removed.

**Comment by livarcocc** [comment]
the source for migration is the project.json, we don't look at the csproj for that and the project.json has not reference of sources outside of the project folder.

**Comment by sepidehMS** [comment]
I see. Is this something you might be willing to add later? As many projects use the csproj to include source files.

**Comment by livarcocc** [comment]
No. We have no plans to improve migration further actually and we definitely have no plans to look for information in a csproj and merge with the project.json.

If you already have a csproj, why are you trying to migrate? If you are just trying to use the new csproj format, I would say you need to hand edit your csproj. There is not tooling for that.

**Comment by sepidehMS** [comment]
OK, thank you. Yes, I was using migration as an easy way to port to .NET Core 2.0 and to get the new .csproj format.

**Comment by livarcocc** [comment]
Sorry, that's not what we intended with migration. It is a project.json to csproj migration tool.

**Comment by danmosemsft** [comment]
@livarcocc 

(1) it seems this caused dataloss of a real project as it overwrote the csproj. Might not customers hit this also?
(2) Should migration of a project.json proceed if there's no .xproj?
(3) Should migration of a project.json proceed if there's no OutputType (referring to https://github.com/dotnet/cli/issues/6110 here)

We're doing a lot of migration testing as part of our .NET Core 2.0 validation and mostly it's going well aside from this one.

/cc @terrajobst

**Comment by livarcocc** [comment]
1. The csproj is getting overwritten, true. But that's why we move it to a backup folder. This is a very weird scenario where you have a project.json that you don't really use and a csproj that you do use but you want to migrate.
2. Of course. Not every project is guaranteed to have an xproj. xproj is a VS construct and many people who use the CLI (project.json) never opened their projects in VS to create one.
3. In project.json world, not having a OutputType meant it was a library and migration maintains that understanding.

Like I said, dotnet migrate's goal is not to move you to the new csproj format. It is to move you from project.json to csproj (which happens to use the new csproj format).
