### ISSUE TITLE
Implement SDK resolvers

### ISSUE THREAD

**Issue by livarcocc** [dotnet/cli#6112]
- [ ] Resolver that uses the same policy for finding a CLI as the host, including global.json
- [ ] Resolver that resolves to the current VS SDKs folder
- [ ] Remove duplicated SDKs from VS
- [ ] Install the resolvers in VS

**Comment by dsplaisted** [comment]
The resolver should support overriding the folder it looks for SDKs in via an environment variable, so that we can test new versions of the SDK, as well as so that it's possible to point Full Framework MSBuild at an "install" of the CLI that was downloaded and unzipped instead of installed globally on the machine (see eg https://github.com/dotnet/sdk/issues/1083#issuecomment-292077797).

**Comment by rainersigwald** [comment]
By release, it would be very nice if this the resolver was available in the Build Tools installer as well as full VS's netcore workload. That would address https://github.com/Microsoft/msbuild/issues/1697.
