### ISSUE TITLE
Build sln targeting single framework moniker when lib and app.

### ISSUE THREAD

**Issue by alistair** [dotnet/cli#6117]
Im sorry if this is 1) obvious and not a bug or 2) difficult to understand

## Steps to reproduce
git clone https://github.com/alistair/dotnetcore-multitargetting
Notice that the sln has 2 projects.  MyLibrary and MyApp

MyLibrary has netstandard1.0 and net46 target frameworks
MyApp has netcoreapp1.0 and net64 target frameworks

cd dotnetcore-multitargetting
dotnet restore
dotnet build -f netcoreapp1.0 // notice the red build output
dotnet build -f netstandard1.0  // notice the red build output

Wonder how the ... you are meant to just build core version of the application as you are on linux and cant ( or dont want to ) do both

## Expected  behavior

Be able to run

dotnet build -f core and only build the netstandard and netcoreapp target frameworks like you would be able to if you only wanted to build the net46 version

aka you can do this ( i assume)

dotnet build -f net46
but you cant do this
dotnet build -f dotnetcore

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1

**Comment by livarcocc** [comment]
@piotrpMSFT Didn't you do something about passing this down to the project when building a solution?

**Comment by hotchkj** [comment]
Also interested to know the answer to this; it's not in current documentation if it exists.

Build analysis tools like SonarQube require a single framework build, so if you e.g. have a set of multi-target projects, where some are assemblies and some are unit test applications, it's pretty much impossible to call either `dotnet build` or `msbuild` correctly to build the 'Core' flavour, unless there's some magic identifier that lets me say to the projects 'this really means netstandard if you're a library, and netcoreapp if you're an application'.

**Comment by livarcocc** [comment]
This is a considerably complicated issue, because we need to understand, in the context of the solution, that your parameter is only meant strictly for some projects, while for others we need to find the best matching TargetFramework. We haven't solved this problem and we probably won't solve it for the next release either.

The way we deal with it in our own projects is by setting something like this in the projects:
```
<TargetFrameworks>netcoreapp1.0;net46</TargetFrameworks>
<TargetFrameworks Condition=" '$(OS)' != 'Windows_NT' ">netcoreapp1.0</TargetFrameworks>
```

I just tried this out in the repo you provided above and it builds successfully on Windows and OSX. With the added bonus that you don't need to change your build command across OSes. Just run dotnet build.
