### ISSUE TITLE
Fix dotnet-cli version numbers

### ISSUE THREAD

**Issue by anurse** [dotnet/cli#618]
It looks like the version numbers have gotten a little weird. There have been some changes here that I'm not familiar with but now we're getting AssemblyInformationVersion set to `1.0.0-1.0.0.1450461120` which is invalid for a NuGet version... I think it's because we're setting `DOTNET_BUILD_VERSION` to a full version number, when it is expected to only be the part after `-` (for example `1.0.0-*` gets resolved as `1.0.0-[DOTNET_BUILD_VERSION]`, not `[DOTNET_BUILD_VERSION]`).

/cc @Sridhar-MS @krwq @piotrpMSFT @brthor

**Comment by brthor** [comment]
`DOTNET_BUILD_VERSION` does contain the full version right now, which is useful because it's used for the versions of the packages.

`VersionSuffix` contains the bit you are looking for. 
( https://github.com/dotnet/cli/blob/master/scripts/build.ps1#L21 )

It doesn't look like we have an equivalent for Non-Windows. @krwq  ?

**Comment by blackdwarf** [comment]
Fixed in #449 . Reopen if encountered again.
