### ISSUE TITLE
Webpack not auto-building while app is running

### ISSUE THREAD

**Issue by Conner05** [dotnet/cli#6214]
## Steps to reproduce
1) Create new project with `dotnet new angular`
2) Restore packages and install dependencies with `dotnet restore` and `npm install`
3) Run the project with `dotnet run`
4) Make a change to any component. For example, append `HELLO, WORLD` to the **home.component.html** file
5) Save the change. **Notice the browser does not auto-refresh**
6) Refresh the browser - the change is **NOT** applied
7) Stop the project the project
8) Run the project again with `dotnet run` - notice the change is **STILL NOT** applied
9) Stop the project again
10) Run `webpack`
11) Run the project with `dotnet run` - VIOLA! Now the change **is** visible

## Expected  behavior
I expect to be able to make a change and, upon saving, see the change reflected in my browser.

## Actual behavior
No changes can be seen until the `webpack` command is ran at the command line.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0

**Comment by livarcocc** [comment]
@mlorbetske do you know where this bug belongs?

**Comment by mlorbetske** [comment]
@SteveSandersonMS would know

**Comment by livarcocc** [comment]
@mlorbetske @SteveSandersonMS Can you guys help me find the right repo for this issue?

**Comment by SteveSandersonMS** [comment]
@Conner05: It sounds like you're just running in production mode, whereas you have to be in development mode for HMR and Webpack Dev Middleware to be active. If you switch to dev mode and still get this issue, could you please re-file it in [the JavaScriptServices repo](https://github.com/aspnet/javascriptservices/issues)?

I'll mark this closed because even if it is a bug we'd prefer it to move to the JavaScriptServices repo. Hope that's OK!
