### ISSUE TITLE
dotnet run slow performance.

### ISSUE THREAD

**Issue by andreolvr** [dotnet/cli#6224]
I created a simple ASP.NET Core Web Api CRUD application with Visual Studio 2017. When i run it with VS via Debug > Start Without Debugging it takes 3-5 seconds. But if i run the same project with _dotnet run_ via command line it takes 6-12 seconds to start.

My dotnet --info:
```
.NET Command Line Tools (1.0.0)

Product Information:
 Version:            1.0.0
 Commit SHA-1 hash:  e53429feb4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0
```

**Comment by livarcocc** [comment]
Do you get this repeatedly or just for the first time?

I wonder if you just hit the first run experience, where for the first time you use the CLI we pre-populate your nuget cache.

**Comment by livarcocc** [comment]
Other than that, it would be helpful if you could share logs with us by running dotnet run /v:diag

**Comment by andreolvr** [comment]
> Do you get this repeatedly or just for the first time?

Repeatedly. 

Nothing happens when I run **dotnet run /v:diag**. It start the app, just like **dotnet run**, no log file is created.

**Comment by livarcocc** [comment]
VS is faster because VS is "running all the time" and it keeps a database of the stage of its assets. So, when you do a run there, it knows before hand whether it needs to do a build or not, for instance.
In the case of the CLI, we need to run checks and calculate the execute command on the fly, which is why it takes longer.

Granted, it should not take as long as you are seeing and we definitely have space for improvement. This issue is tracking overall CLI/MSbuild improvements: https://github.com/dotnet/cli/issues/5918.

We can continue the conversation there.

**Comment by cevarief** [comment]
Previously using dotnet 1.0.0-preview2-1-003177, it runs 2-3 seconds. After upgrading to 1.0.3 it takes 5-6 second until console show application listening http://localhost:5000.

**Comment by dmbarbour** [comment]
This may be more closely related to #6421, an issue with `dotnet run` specifically rather than build times or `dotnet exec`.
