### ISSUE TITLE
Ubuntu build failures

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/cli#623]
@Sridhar-MS After syncing to your changes, I see the following failure:

> dpkg-buildpackage -rfakeroot -D -us -uc
dpkg-buildpackage: source package dotnet-dev
dpkg-buildpackage: source version 1.0.0.1450562558-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Microsoft <dotnetcore@microsoft.com>
 dpkg-source --before-build dotnet-dev-1.0.0.1450562558
dpkg-buildpackage: host architecture amd64
dpkg-checkbuilddeps: Unmet build dependencies: debhelper (>= 9)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc failed
gkhanna@gkhanna-Mac-Ubuntu:~/Github/gkhanna79/cli$ 

Also, I see the following:

> Published to /tmp/DotnetCLITests/f041f328-b33b-4487-aba5-a383f2f2325f/some/dir
Published 1/1 projects successfully
Executing - /tmp/DotnetCLITests/f041f328-b33b-4487-aba5-a383f2f2325f/some/dir/TestApp 
This string came from the test library!
Executing - dotnet publish /tmp/DotnetCLITests/090ba0fb-21b9-4ec7-9e15-53246be75bb0/TestApp/project.json     
'/tmp/DotnetCLITests/090ba0fb-21b9-4ec7-9e15-53246be75bb0/TestApp/project.json' cannot be published  for '<no framework provided>' 'ubuntu.14.04-x64'
Finished:    Microsoft.DotNet.Tools.Publish.Tests

Any thoughts?

**Comment by brthor** [comment]
To resolve this, I think we should separate the packaging from the regular build. Additionally the package script should check dependencies before continuing.

This is caused because the build is trying to create the debian package, but that process has a number of dependencies (see here https://github.com/dotnet/cli/blob/master/scripts/docker/Dockerfile)

As a workaround you can install docker (https://docs.docker.com/engine/installation/ubuntulinux) and set this environment variable prior to doing the build:
`PACKAGE_IN_DOCKER=true`

**Comment by blackdwarf** [comment]
Pass the `--nopackage` option to skip any packaging on build. This should fix it. Reopen if encountered again.
