### ISSUE TITLE
How to reproduce `dotnet publish` output?

### ISSUE THREAD

**Issue by sm-g** [dotnet/cli#6325]
I cannot complete migration to VS2017 because I need publishing selfhosted aspnet core project on full net461 and current cli fails to build my project. With SDK 1.0.0-preview2-003133 combination of 

1. msbuild14 cspjos
2. dotnet build xproj --no-dependencies
3. dotnet publish xproj

works, but with SDK 1.0.0 `dotnet publish` begin to do `dotnet build` first, and `dotnet build` fails itself.

But I'm able to build with `msbuild15`.

I'm looking for info about which files from `bin\Debug\net461` should be copied to reproduce `dotnet publish`?

**Comment by livarcocc** [comment]
The reason it fails is because the CLI does not support old style csproj projects. msbuild can handle those.

It should be possible for you to do something like msbuild <csproj> /t:publish to publish that project.

But do note that I am not sure if you can do that to xprojs. The last release of the CLI that supported xproj/project.json was preview2. 1.0.0 only supports msbuild projects.

**Comment by sm-g** [comment]
So with new cli we still cannot reference regular dll-project (non-core) from core project?

> But do note that I am not sure if you can do that to xprojs
After migration there is only new-csprojs.

> msbuild /t:publish 
This do something, but not as cli. For example, no "WebApp.xml" file in pushlish output and all "appsettings.xxx.json" copied.
