### ISSUE TITLE
Document and clarify the parameters for dotnet-install

### ISSUE THREAD

**Issue by JohnRusk** [dotnet/cli#6344]
## Steps to reproduce

Follow the instructions here to try to install version 1.1.1 of the shared runtime: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script

## Expected  behavior

It works

## Actual behavior

_None_ of the channel names documented there work.  Web searches return nothing that documents what do use.

By _guessing_ I found that the correct channel name for installing 1.1.1 is '1.1.0'.  E.g. 

`source ./dotnet-install.sh --channel 'release/1.1.0' --version '1.1.1'  --shared-runtime`

## Environment data
Ubuntu 16.04

**Comment by WernerMairl** [comment]
Same here, in my case for Windows Environments 
My findings - after a lot of investigations inside Source Repositories and Issues.

There are different versions of dotnet-install.ps1 in place (it seems that consolidation of arguments is in progress but nod yet done)

For production #5952 suggests to use 
https://dot.net/v1/dotnet-install.ps1
and it works with released versions but i was not be able to use one of the other channels

My intent was to install latest dotnet core 2.0 bits (nightly builds).
i found the following way/workaround:

1. using the script from master branch:
https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1
2. With the Channel = "rel-1.0.0" 
3. AND a explicit 2.0 Version like  "2.0.0-preview1-005805" 

i get the explicit version number by reading https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/latest.version

any try to use a predefined channel was not working (Download Exception)

Expected Behavior:

-Channel "Future" -Version "latest"

should return the latest nightly build of 2.0

**Comment by livarcocc** [comment]
For the latest from master, just pass -Channel "master".

@mairaw @richlander for documenting the functionality of the install script.

**Comment by mairaw** [comment]
@GuardRex since you're looking at the CLi commands, can you look at this issue? Thanks.

**Comment by GuardRex** [comment]
@mairaw Sure thing. I'll create a tracking issue in the morning and roll this into https://github.com/dotnet/docs/pull/2480.

@JohnRusk @WernerMairl I'll ping you on the issue. Thanks for researching it and describing your scenarios here. Let's follow-up over on the docs repo after I get the issue established, and we'll make sure we get some enhanced coverage in place.

**Comment by johnbeisner** [comment]
On April 17, 2017 this statement was true:
"to use https://dot.net/v1/dotnet-install.ps1 and it works with released versions but I was not be able to use one of the other channels"

However, the scripts at the aforementioned location have been updated recently and are working as expected. Be advised that the channels: "Preview" and "Future" are no longer supported.
