### ISSUE TITLE
dotnet-install should return structured (xml, json) output

### ISSUE THREAD

**Issue by WernerMairl** [dotnet/cli#6355]
## Steps to reproduce
the following PS-Call

`.\dotnet-install.ps1 -Version latest -Channel master -DryRun`

returns:

```
dotnet-install: Payload URLs:
dotnet-install: - https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview1-005807/dotnet-dev-win-x64.2.0.0-preview1-005807.zip
dotnet-install: Repeatable invocation: .\dotnet-install.ps1 -Version 2.0.0-preview1-005807 -Channel master -Architecture x64 -InstallDir <auto>
```

## Actual behavior
dotnet-install "calculates" the latest available version.

in this case "2.0.0-preview1-005807" is returned for "latest"

the output is readable for humans but not for programs....

intent: dotnet-install currently seems to be the only "official" API do read data from the "dotnet deployment system"

## Expected  behavior
for automation purposes we need a mechanism to return the output in a better structured/formatted way  like Xml, Json, Hashtable, at least without any comments and surrounding text.

`.\dotnet-install.ps1 -Version latest -Channel master -DryRun -ReturnAsHashtable`
can return:
```
@{
SpecificVersion = ''2.0.0-preview1-005807"
Channel = "master"
Architecture = "x64"
InstallDir = "<auto>"
}
```

i'm specially interested on the value for "SpecificVersion" because it is calculated inside "dotnet-install" !
alternative idea: reorganize the script so that it can be dot sourced AND the functions inside are public available/documented

regards
Werner Mairl

**Comment by wli3** [comment]
Hi Werner,

Thank you! I have some thoughts

1. I agree that this behavior is not friendly for machine especially for the “latest”. However, I am thinking the use case for CI, since it is for machine, it would be better to just used the “repeatable invocation”. Requiring the latest will introduce nondeterministic to the system. What is your use case that require a latest install?

2. for the format alone, there is a bash shell version of the script. https://dot.net/v1/dotnet-install.sh And we should keep the “feature parity”. In PowerShell, there is a build-in object model. However, for bash, it is string based. XML and JSON are not typical output format. For example, If JSON is the output format, parsing a JSON will require an extra component like jq. 

-Will

**Comment by livarcocc** [comment]
Also, if you want to know which version of the SDK was pulled down by the script, you can add a dotnet --version to your script that invokes the install script and parse that.

**Comment by WernerMairl** [comment]
@livarcocc , @wli3 
My primary usecase is retrieving the specific version number for "latest" **without** downloading the package (i have multiple versions installed side by side, and with that version i can avoid the download if the version is available locally)

this is why "dotnet --version" does not helps => i'm calling dotnet-install with the "-DryRun" Argument!

Workaround: yes i can clone and modify the dotnet-install.ps1 to get that information from the current feeds but then i'm depending on **private** implementation details of the dotnetcore deployment system!

I understand the impact/restrictions coming from bash/shell.

Any other idea how to resolve the specific version number (for a certain channel) ?

a) without downloading a full version
b) using only "public" API (without using blackbox infomation)

Werner

**Comment by wli3** [comment]
@WernerMairl 

If this script can print a json to console. It is still not reliable since the down stream console app need to parse and "look for" the json. In this case, it will not be easier or more reliable than parse current format by awk. The "right way" might be  .\dotnet-install.ps1 -Version latest -Channel master -DryRun -ReturnAsHashtable **-OutputRepeatableInvocation:json** and only RepeatableInvocation is printed. However, this will require a lot work. And I don't think this issue have enough attraction yet to gain a high probity.

Could you try to pipe to awk or similar console app for now?

**Comment by WernerMairl** [comment]
a) i understand your points
b) i have a workaround for now (parsing the output), and i see some option for me (including a refactoring of "dotnet-install.ps1" into a reusable module for this purpose....

c) feel free to close this issue

thank you all!

Werner
