### ISSUE TITLE
Rid restore questions

### ISSUE THREAD

**Issue by tmds** [dotnet/cli#6484]
When running `dotnet restore -r fedora.24.x64` on `dotnet new console`,
these packages are installed:
```
  Installing runtime.linux-x64.Microsoft.NETCore.DotNetAppHost 2.0.0-preview1-002021-00.
  Installing runtime.linux-x64.Microsoft.NETCore.DotNetHostResolver 2.0.0-preview1-002021-00.
  Installing runtime.linux-x64.Microsoft.NETCore.App 2.0.0-preview1-002021-00.
  Installing runtime.linux-x64.Microsoft.NETCore.DotNetHostPolicy 2.0.0-preview1-002021-00.
```

Now adding an additional package:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
  </ItemGroup>
```

And doing a restore, again using the `fedora.24-x64` rid, some unexpected packages show up:
```
...
  Installing runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.0.
  Installing runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
  Installing runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0.
...
```

## Questions

1. Is it correct that when _Publishing for RID specific runtime (self contained = false)_ none of the packages listed in the first restore operation are used?
2. Why is System.Security.Cryptography.OpenSsl restored for the unrelated RIDs as part of the second restore?

cc @eerhardt

**Comment by eerhardt** [comment]
A few things are going on here.  Hopefully I can explain it all correctly.

For your first restore, you are using .NET Core 2.0.  We have drastically changed the way a few things work in 2.0.
1. There are no longer individual "System.XXX" packages like we did in 1.x. Instead, all the System.XXX assemblies are packaged directly in the Microsoft.NETCore.App package.
2. We no longer have individually built packages for each Linux distro.  Instead, we have a "portable" `linux-x64` RID, which contains assets that will work across the majority of Linux distros that we support.  All the supported Linux distro RIDs are "based" on this `linux` RID.  See https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/readme.md for a good explanation on how assets are picked based on RIDs and their graph.

So now to explain what you are seeing - in the first restore you are only referencing base .NET Core 2.0 packages and we don't have `fedora` specific assets, so you only get the portable `linux` assets.

When you add the ASP.NET `1.1.1` package, it references the .NET Core 1.1 packages (a. the individual System.XXX packages and b. ones with distro-specific assets).  Since we moved assets from packages named System.Console and System.Runtime into one Microsoft.NETCore.App package, NuGet has no way of knowing that these are really the same assets and the versions should be consolidated like usual.  So NuGet restores both the `1.1` packages and the new `2.0` package.

So to specifically answer your questions:

> Is it correct that when Publishing for RID specific runtime (self contained = false) none of the packages listed in the first restore operation are used?

If you are `self contained = false`, that means you are running on top of a shared framework.  All of the packages listed in the first restore operation are part of the Microsoft.NETCore.App shared framework.  Thus they are excluded from publish, just like a normal portable app.

> Why is System.Security.Cryptography.OpenSsl restored for the unrelated RIDs as part of the second restore?

Above I answered why this package even gets into the restore graph. To understand why the `osx` and `ubuntu` assets are being restored, you need to look deeper into the `System.Security.Cryptography.OpenSsl` package. This one is built a little differently than the rest of the System.XXX packages.  If you look at the dependencies listed here: https://www.nuget.org/packages/System.Security.Cryptography.OpenSsl/4.3.0, you see it is dependent on `runtime.native.System.Security.Cryptography.OpenSsl`.  And that package has dependencies on `runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl`, `runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl`, etc.  So when you restore the base/identity package with no RID in its name, you get all the RID-specific packages as well.  I can't remember exactly why this package was built this way, @bartonjs @weshaggard or @ericstj can explain if you need to know "why".

**Comment by eerhardt** [comment]
BTW - if you are actually trying to do ASP.NET development on .NET Core 2.0, you should use the ASP.NET 2.0 packages, not the 1.1 packages.

**Comment by tmds** [comment]
@eerhardt Thanks for the clear explanation!

> If you are self contained = false, that means you are running on top of a shared framework. All of the packages listed in the first restore operation are part of the Microsoft.NETCore.App shared framework. Thus they are excluded from publish, just like a normal portable app.

OK, so these packages are not used for selfcontained = false. This matched with my expectation.

> And that package has dependencies on runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl, runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl, etc. So when you restore the base/identity package with no RID in its name, you get all the RID-specific packages as well. I can't remember exactly why this package was built this way, @bartonjs @weshaggard or @ericstj can explain if you need to know "why".

I think the split has to do with being able to trim the dependencies during the publish based on the rid. It looks like the restore operation itself doesn't trim.
