### ISSUE TITLE
dotnet-install scripts reference needs to be clearer about the canonical URLs for download scripts

### ISSUE THREAD

**Issue by rianjs** [dotnet/cli#6541]
This is the page I'm referring to:
https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script

Ticket #5952 has pretty URLs for dotnet-install scripts:
* https://dot.net/v1/dotnet-install.sh
* https://dot.net/v1/dotnet-install.ps1

Pretty URLs make me think these are authoritative. Not having a hard-coded error for a default value (the `production` channel) makes me think that's meant to be the source of truth, even though the `production` channel is currently broken.

However [the documentation says](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script) to download the scripts from the CLI Github repo.

So which is it?

My gut says using github as the source of truth, making people live on the bleeding edge of the latest merge to `master` probably isn't the best plan. Clarity would be good.

**Comment by livarcocc** [comment]
@mairaw can we update the documentation to point to the pretty URLs?

@rianjs The production channel was actually never used and master, rel/1.0.0 and rel/1.0.1 have rel-1.0.0 as their default channel.

**Comment by omajid** [comment]
I would like to vote a -1 for pointing to https://dot.net/v1/dotnet-install.sh by default.

My reason is as follows: unlike the versions of the scripts on github, where the community can contribute changes and open PRs and things get fixed, there's no way the community can contribute to fixing https://dot.net/v1/dotnet-install.sh if something is broken.

Case in point: https://github.com/dotnet/cli/issues/6023. I pushed some fixes to dotnet-install.sh on github in a matter of days, but it has been 2 months since then and I haven't been able to fix https://dot.net/v1/dotnet-install.sh.

My concerns would go away if there was some automated (or even manual) sync between dotnet-install.sh on github and on dot.net/v1/ that was regular.

**Comment by mairaw** [comment]
Sure, if that's what you guys want.

**Comment by johnbeisner** [comment]
Addressed via:
https://github.com/dotnet/cli/pull/7330
https://github.com/dotnet/cli/pull/7332
https://github.com/dotnet/cli/pull/7336
https://github.com/dotnet/cli/pull/7342
https://github.com/dotnet/cli/pull/7355

**Comment by johnbeisner** [comment]
Addressed via:
https://github.com/dotnet/cli/pull/7330
https://github.com/dotnet/cli/pull/7332
https://github.com/dotnet/cli/pull/7336
https://github.com/dotnet/cli/pull/7342
https://github.com/dotnet/cli/pull/7355
