### ISSUE TITLE
dotnet pack PackageVersion fails when using short form of /property (/p:PackageVersion)

### ISSUE THREAD

**Issue by joaonlforte** [dotnet/cli#6551]
## Steps to reproduce
`$ dotnet pack ClassLibrary.csproj /p:PackageVersion=x.y.z`

## Expected  behavior
Should have created a nuget package with the explicit version passed (x.y.z)

> ClassLibrary.x.y.z.nupkg

## Actual behavior

> Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.
**MSBUILD : error MSB1008: Only one project can be specified.**
Switch: p:PackageVersion=x.y.z

However if the msbuild long form of a property is used it works!!

`dotnet pack ClassLibrary.csproj /property:PackageVersion=x.y.z` <= **works fine**

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by wli3** [comment]
no repo on latest release/2.0,0 build 
![image](https://cloud.githubusercontent.com/assets/6993335/25969296/47d96ef8-3649-11e7-9900-d3ace902fbb4.png)

However, it does repo on 1.0.3
![image](https://cloud.githubusercontent.com/assets/6993335/25969252/27baa740-3649-11e7-8f1d-2f279a1ef75a.png)

**Comment by wooderz** [comment]
I just experienced this issue on version 2.1.4, works fine when using the long form /property:PackageVersion..

![image](https://user-images.githubusercontent.com/4377107/36744370-8e147c6a-1be4-11e8-9a21-577020895ef4.png)

![image](https://user-images.githubusercontent.com/4377107/36744386-990826b2-1be4-11e8-9031-232e9b1e777e.png)

![image](https://user-images.githubusercontent.com/4377107/36744408-a924cdde-1be4-11e8-927d-b9af9236083d.png)

**Comment by trullock** [comment]
Issue also exists on 2.1.202

**Comment by dasMulli** [comment]
@trullock I suggest you create a new issue with detailed repro steps (can't repro using original steps)

**Comment by dasMulli** [comment]
if there is a `/p` directory or file, it won't work btw.

You can use `-p:PackageVersion=1.2.3` instead.

A similar change has been made to use `-m` instead of `/m` to avoid collisions on *nix systems with a `/m` directory

**Comment by dasMulli** [comment]
@trullock please include OS version / `dotnet --info` output, using WSL (window subsystem for linux) etc.

**Comment by grajdeanserghei** [comment]
The issue is reproduced if you run it from `git bash`. If command is run from `cmd` then it works as expected. All screenshots above are from `git bash`.

The output from `git bash` with /p: and /property

![image](https://user-images.githubusercontent.com/1830410/45595168-59fdfb80-b9b0-11e8-964b-10a6567f518c.png)

The output from `cmd` with short form

![image](https://user-images.githubusercontent.com/1830410/45595186-8fa2e480-b9b0-11e8-9ecb-5657dcd2f031.png)

@dasMulli, Should I open a new issue?

**Comment by livarcocc** [comment]
@grajdeanserghei please file a new issue for this.

**Comment by dasMulli** [comment]
@grajdeanserghei you wrote`/pproperty` instead of `/property`, I suggest using
`-p:PackageVersion=1.2.3`

**Comment by livarcocc** [comment]
LOL, good catch @dasMulli

**Comment by grajdeanserghei** [comment]
@dasMulli , you're right, I uploaded wrong screenshot
I wanted to upload this one
![image](https://user-images.githubusercontent.com/1830410/45600685-55196600-ba09-11e8-8fdc-41937740d698.png)

Indeed it works with `-p:PackageVersion=1.2.3` instead of `/p:PackageVersion=1.2.3`. It works it both `git bash` and `cmd`. Probably documentation should use `-p:` syntax instead.

Any way, I'll open a new issue.

Thanks
