### ISSUE TITLE
Regression: dotnet-compile regressed with dotnet-build introduction

### ISSUE THREAD

**Issue by borgdylan** [dotnet/cli#663]
The ```dotnet-compile``` has been broken with the ```dotnet-build``` PR. Before calling compile used to compile each dependency to its own bin folder and then reference those binaries where they stood. Now it references the binaries within the bin folder of the current project. This means that calling ```dotnet-compile``` in a project that has dependency projects will not work while ```dotnet-build``` runs OK outputting the whole dependency closure in the current project's bin folder.

**Comment by cdmihai** [comment]
I my understanding that was the correct intended change: the Compile verb just compiles a project, without doing anything with dependencies. The dependencies that need to be compiled get there by previous invocations of Compile on them.

So you now have to type `dotnet build` instead of `dotnet compile` to achieve the same effect.

For this PR I tried as best as I could to have build behave in the exactly same way as compile.

Regarding your comment that the pre-build Compile used to compile each dependency in its own bin folder, that may not be so. If I'm reading the code right, the old compile put everything in the root project bin folder: https://github.com/dotnet/cli/blob/0b2a6fee2edee2a140387ed50dc7c4606c112ff4/src/Microsoft.DotNet.Tools.Compiler/Program.cs#L253
Compile only used the project's bin folder if the --output flag was not used: https://github.com/dotnet/cli/blob/0b2a6fee2edee2a140387ed50dc7c4606c112ff4/src/Microsoft.DotNet.Tools.Compiler/Program.cs#L488

Please tell me if my previous assessment of Compile's output path handling is wrong. Since it would mean I did not preserve behaviour and I need to update build.

**Comment by cdmihai** [comment]
Issue #532 discusses the new user experience.

**Comment by borgdylan** [comment]
If I am not wrong, in previous builds I only used to get the project's actual binaries in its bin folder and not the binaries of all the closure. Before the bin folder had differing contents when compiling or publishing. That is difference if very blurred in the last builds. I will test a prior build I have lying around and check its behaviour.

**Comment by borgdylan** [comment]
OK, I was wrong big time. Thanks for clarifying that build is what should be used instead of compile as from now on. The current rendition of dotnet-build is behaving as intended.

**Comment by borgdylan** [comment]
The only extra change I would encourage would be to change the root README.md to use build rather than compile. Many people read that when they try the CLI for the first time.

**Comment by cdmihai** [comment]
Good point, I totally missed that one. Thanks!
