### ISSUE TITLE
dotnet-install.ps1: Retry failed downloads

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#6687]
We have occasionally seen `dotnet-install.ps1` fail to download the CLI:

```
[15:17:53]   [Step 3/4] dotnet-install: Downloading https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006082/dotnet-dev-win-x64.2.0.0-preview2-006082.zip
[15:18:35]   [Step 3/4] Failed to download https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0-preview2-006082/dotnet-dev-win-x64.2.0.0-preview2-006082.zip.
```

To address this, I think `dotnet-install.ps1` should retry failed downloads.  As a suggestion, here's how we added retries to our copy of the script:

https://github.com/aspnet/KoreBuild/commit/16761e4bcfa3d199289eaa94001442c0682c4037?w=1

**Comment by WernerMairl** [comment]
retry can be a good idea, but i suggest to investigate into the root cause of the issue(s)
One of the reasons for failed downloads should be solved with #6579 

During the work where i found 6579, the biggest problem was the error message that says only "failed download" and nothing about the timeout.....
so probably improving the error messages (coming from http/download Client) should be a good invest - retry can be helpful but only on a small number of scenarios....

regards
Werner
