### ISSUE TITLE
Increased build time for project with large number of node modules

### ISSUE THREAD

**Issue by mikeharder** [dotnet/cli#6936]
## Steps to reproduce
1. Clean Win10 VM
2. Install Chocolatey
  A. https://chocolatey.org/install
3. Admin command prompt
  A. `choco install nodejs`
  B. `npm install --global --production windows-build-tools`
4. `git clone https://github.com/mikeharder/scripts`
5. `git clone https://github.com/aspnet/JavaScriptServices`
6. `cd JavaScriptServices`
7. `git checkout dbdc81a06a50a853a6025c975edc584ab9719572`
8. Build with CLI 6127
  A. `set PATH=%PATH%;%USERPROFILE%\.dotnet\x64`
  B. `set KOREBUILD_DOTNET_VERSION=2.0.0-preview2-006127`
  C. `set KOREBUILD_DOTNET_SHARED_RUNTIME_VERSION=2.0.0-preview2-25324-03`
  D. `..\scripts\korebuild-cleanup.cmd`
  E. `build.cmd`
  F. Time: 00:06:48.71
9. Build with CLI 6215
  A. `set PATH=%PATH%;%USERPROFILE%\.dotnet\x64`
  B. `set KOREBUILD_DOTNET_VERSION=2.0.0-preview2-006215`
  C. `set KOREBUILD_DOTNET_SHARED_RUNTIME_VERSION=2.0.0-preview2-25401-01`
  D. `..\scripts\korebuild-cleanup.cmd`
  E. ` build.cmd`
  F. Time: 00:40:00.48

**Comment by nguerrera** [comment]
I suspect this is due to the changes around assigning link metadata automatically in SDK. @dsplaisted

**Comment by dsplaisted** [comment]
Does this setup create MSBuild items for each file in the node modules folder?  If so, then the Link metadata feature could regress it.

**Comment by dsplaisted** [comment]
It looks like this is slow because the Microsoft.AspNetCore.SpaServices project is using `Microsoft.NET.Sdk` and not `Microsoft.NET.Sdk.Web`.  The `node_modules` folder is only excluded [in the Web SDK](https://github.com/aspnet/websdk/blob/afbcec9b0951d09088f26e98e6aca6114e0d32ee/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L15), so this project gets `None` items created for each file in the `node_modules` folder.

The slowdown between the two builds is probably related to the [LinkBase feature](https://github.com/dotnet/sdk/pull/1246) (though I haven't validated this yet).  But if it's valid to have a `node_modules` folder in a project that doesn't use the Web SDK, then we should probably exclude `node_modules` folders in the base `Microsoft.NET.Sdk`.

As a workaround, you can add the following to your projects:

```xml
<DefaultItemExcludes>$(DefaultItemExcludes);**\node_modules\**;node_modules\**</DefaultItemExcludes>
```

**Comment by dsplaisted** [comment]
Looking at this more, it looks like the `npm` folder in the SpaServices project also has a lot of files in it.  So you'd also need to include that folder in the `DefaultItemExclude` property.

**Comment by livarcocc** [comment]
Closing this as a dup of https://github.com/Microsoft/msbuild/issues/2314. It has been fixed and we will pick up a new MSBuild as soon as it is available.
