### ISSUE TITLE
Is it possible to publish latest build on Azure?

### ISSUE THREAD

**Issue by Ponant** [dotnet/cli#6958]
Sorry if this is a nuts question. I am on .NET Core 2.0 Preview 2 (latest build) on the latest VS 2017 Preview (updated today) and I cannot publish to Azure the web app template, but I can publish  a template from .NET Core 2.0 Preview 1. Is that by design of latest builds until they are released?

**Comment by livarcocc** [comment]
You can not publish to azure a portable app. The reason for that is that the runtime that preview2 targets has not been deployed to azure yet. You can either modify you project so that it targets a runtime already deployed to azure (like the one that preview1 targets) or you can publish your app as a self contained application.

**Comment by Ponant** [comment]
thanks @livarcocc , that clarifies my doubt(s). Cheers
