### ISSUE TITLE
CLI should produce portable PDBs on Windows

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/cli#704]
Currently the .NET CLI invokes Roslyn on non-Windows platforms so that portable PDBs are produced, but on Windows, standard PDBs are still used. After discussing this with the Roslyn team, they would like the default to be that portable PDBs are produced everywhere, but there is an option to produce Windows PDBs on Windows.

Note that the support for portable PDBs in VS isn't in yet, so I would recommend that this bug be fixed **after** the beta release, so that there is time for VS to come out with a release that supports this.

**Comment by brthor** [comment]
@agocke This looks like a dotnet-compile-csc feature

**Comment by tannergooding** [comment]
FYI. @tmat

**Comment by NumberByColors** [comment]
# PDB generation plan:
* Build .NET Framework app/lib on Windows: Windows PDB by default, option for Portable PDB
* Build PCL lib on Windows: Windows PDB by default, option for Portable PDB
* Build .NET Core app/lib on Windows: Portable PDB by default, option for Windows PDB
* Build .NET Core app/lib on OS X or Linux: Portable PDB

We're not generating Portable PDBs in all cases because of the lack of Portable PDB tooling in the ecosystem at this point.

**Comment by gregg-miskelly** [comment]
[Visual Studio 2015 Update 2 CTP](http://go.microsoft.com/fwlink/?LinkId=626599) has now been released, and it includes support for portable PDBs. So we should now checkin the fix for this.

**Comment by gregg-miskelly** [comment]
NOTE: This fix was backed out, so this was NOT fixed for RC2.

#1743 tracks re-enabling portable PDBs
