### ISSUE TITLE
Support for strong name signatures (modern equivalent of sn.exe)

### ISSUE THREAD

**Issue by jkotas** [dotnet/cli#720]
The developers on Mac and Linux should be able to build libraries that are fully compatible with the full .NET, and could go in the GAC and be shadow-copied. It requires ability to strong name sign the libraries. Linux and Mac will only be toy development environments if full .NET Framework tools on Windows are be the only way to produce binaries compatible with the full .NET.

A new dotnet cli command is needed that is able to:
- Generate a new strong name private/public key pair
- Sign managed binary using strong name
- Verify strong name signature of binary

**Comment by jkotas** [comment]
cc @KevinRansom @jaredpar @terrajobst @tmat

**Comment by jkotas** [comment]
https://gist.github.com/jkotas/a21de87b790e06979635 is my prototype that can be reused to build this command.

**Comment by krwq** [comment]
@jkotas, I'm not sure if it's needed but it's possible thatt support for AssemblySignatureKey might need to be added

**Comment by piotrpMSFT** [comment]
@krwq I'd love for this to include the capabilities you developed for using KeyVault if we can make that work easily.

**Comment by krwq** [comment]
I think it's a good idea to have both offline and online way of signing. I think it should be fairly easy to add although as always it's just work which needs to be done and probably some unexpected issues on the way :smiley:

**Comment by terrajobst** [comment]
Good point. `AssemblySignatureKeyAttribute` isn't required (it's for older keys that use SHA1) but it would be good to also provide support for it. I'd make this a separate issue, though.

**Comment by morganbr** [comment]
Expanding on @piotrpMSFT's point, this would also need to have a reasonable key management story -- perhaps the options exposed by sn.exe are about right, with alterations appropriate to the platform's key management.

CC @bartonjs

**Comment by piotrpMSFT** [comment]
at the moment we plan to stick with ASP.NET's story for CLI repo. Namely, our SN key will be public and used only for identity generation. However, the work Krzysztof did to enable KeyVault integration provides a much more robust open signing story. SN.exe's options are insufficient since SN needed direct, unlocked access to the private key. Using KeyVault we need only to install a certificate that can authenticate against keyvault. If someone compromises our build then they may be able to sign arbitrary bits for a period of time but they will never have access to the key itself. What's more, this also enables a very clean bring-your-own-key story.

**Comment by piotrpMSFT** [comment]
Signing support is in place with the transition to the .NET SDK.
