### ISSUE TITLE
Weird msbuild behavior on Gentoo

### ISSUE THREAD

**Issue by svick** [dotnet/cli#7227]
I'm trying to use the portable Linux release of .Net Core SDK 2.0 Preview 2 on a Gentoo machine and I'm getting some strange behavior from msbuild, which means I can't run `dotnet restore`.

What I did:

```bash
~$ cat /etc/*-release
Gentoo Base System release 2.3
DISTRIB_ID="Gentoo"
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
~$ mkdir dotnet
~$ cd dotnet
~/dotnet$ curl -sSL -o dotnet.tar.gz https://aka.ms/dotnet-sdk-2.0.0-preview2-linux-x64-bin
~/dotnet$ tar xf dotnet.tar.gz
~/dotnet$ PATH=$PATH:$HOME/dotnet
~/dotnet$ cd ..
~$ mkdir hwapp
~$ cd hwapp
~/hwapp$ dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /afs/ms.mff.cuni.cz/u/o/ondep7am/hwapp/hwapp.csproj...
MSBUILD : error MSB1008: Only one project can be specified.
Switch: /afs/ms.mff.cuni.cz/u/o/ondep7am/hwapp/hwapp.csproj

For switch syntax, type "MSBuild /help"


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

~/hwapp$ ls
Program.cs  hwapp.csproj
~/hwapp$ dotnet restore
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
~/hwapp$ dotnet restore hwapp.csproj
MSBUILD : error MSB1008: Only one project can be specified.
Switch: hwapp.csproj

For switch syntax, type "MSBuild /help"
```

If I follow the same steps on a brand new AWS Gentoo VM, it works fine. So it looks like an issue specific to that machine, not to Gentoo in general.

What can I do to analyze this issue further?

**Comment by livarcocc** [comment]
Can you do a dotnet restore /v:diag > log.txt and share the log.txt file?

cc @rainersigwald

**Comment by svick** [comment]
@livarcocc That doesn't give any additional information:

```bash
~/hwapp$ dotnet restore /v:diag
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

**Comment by livarcocc** [comment]
@rainersigwald Any ideas how to debug this or what might be going on here?

**Comment by rainersigwald** [comment]
I haven't seen anything like this before, unfortunately. If I could reproduce it locally I'd probably try debugging or making private MSBuild bits that spewed more information. But since this is on Linux I bet we can use [wizardry](https://jvns.ca/zines/#strace-zine) instead.

@svick Could you share an `strace` of the failure? I think

```sh
strace -f -o missing_project_file dotnet restore
```

Should do the trick. Then zip and upload `missing_project_file*`, please.

**Comment by svick** [comment]
@rainersigwald That command produced only one file: [missing_project_file.zip](https://github.com/dotnet/cli/files/1173834/missing_project_file.zip)

**Comment by rainersigwald** [comment]
Thanks!

I think line 14175 is the problem:

```
6713  stat("/m", {st_mode=S_IFDIR|0755, st_size=60, ...}) = 0
```

@svick do you have a directory at the root level named `m`? That is, does `/m` exist on this machine?

**Comment by svick** [comment]
> @svick do you have a directory at the root level named m? That is, does /m exist on this machine?

Yes, `/m` does exist. It's a symlink to `/run/am`. It's not my machine, so I don't know what is the reason for that.

 Why would that be a problem?

**Comment by rainersigwald** [comment]
It's confusing the MSBuild command line parser into thinking that you're specifying `/m` as the project to build, rather than telling msbuild to build in multiprocess mode.

We should do better. I'm going to copy this bug over to MSBuild.

**Comment by rainersigwald** [comment]
This issue was moved to Microsoft/msbuild#2351

**Comment by rainersigwald** [comment]
@livarcocc There a couple of things that the CLI could do to work around this that are worth considering:

* Provide an escape hatch for the auto `/m` argument.
* Prefer the full form of default-passed command line arguments (would work around for this user but a person could have `/maxProcs` as a file, too, so that's not great).
* Use Unixy command-line-flag delimiters instead of Windowsy ones (i.e. `-m` instead of `/m`)

Unfortunately, I can't think of a current workaround if you do have a `/m` (that you can't just delete to work around our bug). You could `dotnet exec /full/path/to/msbuild.dll`, but that loses important environment variables that you'd have to reconstruct. Just specifying `/m:1` doesn't do the trick, because we're failing in argument parsing on the initial `/m`.

**Comment by svick** [comment]
@rainersigwald Thanks for the investigation and the explanation.

**Comment by livarcocc** [comment]
Let's use the CLI issue then to track changing /v /v:m parameters to use dask (-) instead: https://github.com/dotnet/cli/blob/93a4ae7f351160ae93030e2446d32117c85f5515/src/Microsoft.DotNet.Cli.Utils/MSBuildForwardingAppWithoutLogging.cs#L32.
