### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.

### ISSUE THREAD

**Issue by Itsathere** [dotnet/cli#7255]
## Steps to reproduce
1. %USERPROFILE%\.nuget\packages\nsoftware.InPay\tools\dotnet ./install-license.dll <key>

## Expected  behavior
It should work on asp.net core 

## Actual behavior
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\shared\Microsoft.NETCore.App
  - The following versions are installed:
      1.0.0
      1.0.0-rc2-3002702
      1.0.0-rc3-004459-00
      1.0.1
      1.0.4
      1.1.1
  - Alternatively, install the framework version '1.0.5'.

## Environment data
`dotnet --info` output:

Runtime Environment:
OS Name: Windows 10
Visual Studio 2017
ASP.NET Core

**Comment by Itsathere** [comment]
After installing the version 1.0.5 from [Microsoft](https://www.microsoft.com/net/download/core#/runtime).I am able to resolve my issue.

Thanks

**Comment by livarcocc** [comment]
This is by design. Your application targets 1.0.5 runtime, you must have it installed in order to run it.

**Comment by 68681395** [comment]
There is the same problem with my project, the workaround to resolve it successfully is that remove the item 'C:\Program Files (x86)\dotnet' from the Path of Environment Variable because I found I did not install the right netcore version under X86. I have not tried to install the proper version with x86, appreciate that you tell me if you have done that test.
