### ISSUE TITLE
Nuget Package / Nuget Symbol Package share same Id

### ISSUE THREAD

**Issue by tthiery** [dotnet/cli#728]
The DNX/xproj infrastructure created a Foobar.1.0.0.nupgk and a Foobar.symbols.1.0.0.nupgk. As part of a VSTS Build I uploaded both to a VSTS hosted NuGet Feed. But the feed rejected the second package with a 409 since the id of both packages was "Foobar" (the feed behavior seems correct to me).

Is this by intention (so I should stop uploading both) OR is this a bug?

Microsoft/vso-agent-tasks#846

ps: Have not verified whether CLI stil shows the same behavior, but with my quick cross-reading of the code, it looks like.

**Comment by krwq** [comment]
Hey @tthiery, thanks for reporting this issue. I've experienced similar thing and reported a bug to NuGet: https://github.com/NuGet/Home/issues/1920

I believe if you push them separately the symbol package will go to the symbol server and bulk push will treat all of them as regular packages. I believe that this is purely nuget issue but @anurse would need to confirm if there is something we need to do with names.

@anurse, do you know if the name is supposed to be different or is it just purely NuGet issue? How should this consumed by users in perfect world scenario?

**Comment by anurse** [comment]
The package ID is, I believe, expected to be identical. It does sound like there is a NuGet issue here.

Regardless, the safest workaround would definitely be to manually filter `*.symbols.nupkg` files out from the list of files you publish.

I think this is probably up for closing, since there is a NuGet issue tracking this and there isn't actually a dotnet-cli change here.

**Comment by brthor** [comment]
@anurse going to close this out, but could you quickly link to the nuget issue here?
