### ISSUE TITLE
Native installer prime cache always calling the highest SDK instead of the one being installed

### ISSUE THREAD

**Issue by wli3** [dotnet/cli#7282]

**Comment by livarcocc** [comment]
This is a problem when say, you install 2.0.1 and later on install 2.0.0. We will try to run the first run experience by invoking a dotnet command. Instead of then expanding the cache for 2.0.0 (which was just installed) we will do so for 2.0.1.

So, not only will the user not get the offline packages for 2.0.0, but when using 2.0.0, the user will keep getting a message about failing to prime the cache due to permissions.
