### ISSUE TITLE
TargetFramework inconsistent - netcoreapp2.0 vs netstandard2.0

### ISSUE THREAD

**Issue by jimrand1** [dotnet/cli#7335]
## Steps to reproduce
Using net core 2.0 on a MacBook with VSCode, create the helloworld app.
1) dotnet new console -o hwapp
2) Now do the Getting started with .NET Core on macOS
dotnet new sln
dotnet new classlib -o library

## Expected  behavior
1) <TargetFramework>netcoreapp2.0</TargetFramework>
2) <TargetFramework>netcoreapp2.0</TargetFramework>

## Actual behavior
1) <TargetFramework>netcoreapp2.0</TargetFramework>
2) <TargetFramework>netstandard2.0</TargetFramework>

Since I'm new with VSCode on the Mac vs Visual Studio on Windows, this might just be a lack of knowledge on my part. Is netstandard2.0 the same as netcoreapp2.0 or did the CLI mess up?
## Environment data
`dotnet --info` output:

**Comment by livarcocc** [comment]
In a nutshell, netcoreapp2.0 is for apps (like a console application) while netstandard2.0 is for libraries, which can then be consumed by other libraries or platforms, for instance, netcoreapp2.0 or net461.

**Comment by terrajobst** [comment]
> Is netstandard2.0 the same as netcoreapp2.0

No, it's not the same. `netcoreapp2.0` is the framework name for **.NET Core 2.0** while `netstandard2.0` is the framework name for **.NET Standard 2.0**. You can create class libraries that target .NET Core 2.0 instead of .NET Standard 2.0, however, this means that these libraries can only be consumed from .NET Core 2.0. By targeting .NET Standard 2.0 these libraries can be used from any .NET implementation (e.g. .NET Framework, .NET Core, Unity, Xamarin, Mono). Since that is much better, the CLI defaults you to `netstandard2.0`.

Does this help?

**Comment by jimrand1** [comment]
Yes.  This is great! Really appreciate it.

 

Lot’s to learn moving from the Windows world back to Unix and the open source world.  Still deciding .Net Core leveraging years of C# vs Node with Typescript.  

 

Thanks again.

 

Jim
