### ISSUE TITLE
NugetFallbackFolder not removed when SDK is uninstalled

### ISSUE THREAD

**Issue by Tratcher** [dotnet/cli#7362]
## Steps to reproduce
Uninstall .NET Core SDK 2.0.0

## Expected  behavior
C:\Program Files\dotnet\sdk\NugetFallbackFolder and its contents are removed

## Actual behavior
C:\Program Files\dotnet\sdk\NugetFallbackFolder and its contents are not removed

## Environment data
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  bfc25872d7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by ZUIcat** [comment]
So,,can I delete the folder?

**Comment by livarcocc** [comment]
You can delete the folder if you do not have any additional SDKs depending on it. I would it is best to delete it if you have no other SDKs installed.

Of course, if you do delete it, nothing will be broken, but we will download packages from NuGet instead of using the local cache. This may impact performance when running restore.

**Comment by wli3** [comment]
Several version of the SDK will share the same fallback folder. We need to implement/use ref counting on installer in order to delete the folder properly

**Comment by wli3** [comment]
@dsplaisted in 3.0 we will not have the extra nugetfallback folder in a different location and it will all be nested under sdk /VERSION folder right?

**Comment by livarcocc** [comment]
In 3.0, there will be no nugetfallback folder for the .net core SDK at all.

**Comment by wli3** [comment]
@livarcocc where does the assets go? it should be in side the sdk's msi ?

**Comment by dsplaisted** [comment]
There will be installers for each targeting pack that will be bundled.  They should be ref counted and removed correctly on uninstall.  We expect that they'll go in the `ref` folder.

**Comment by chojrak11** [comment]
Why is that `/usr/share/dotnet/sdk/NuGetFallbackFolder/microsoft.aspnetcore` containing subdirectories `2.1.1`, `2.2.0` and maybe others, instead of:
`/usr/share/dotnet/sdk/NuGetFallbackFolder/2.1.1/microsoft.aspnetcore`
`/usr/share/dotnet/sdk/NuGetFallbackFolder/2.2.0/microsoft.aspnetcore`

Then no confusion is possible or refcounting required. Upon uninstallation of SDK or whatever the version directory can simply be removed.

**Comment by livarcocc** [comment]
We have removed the fallback folder in .NET Core SDK 3.0 and I consider this issue now resolved.

Also, the versions you mentioned there are not tied to the SDK, but to the runtime package versions. And a fallback folder is a concept of NuGet and we just mimick it. It was not build for this.

**Comment by olegburov** [comment]
> In 3.0, there will be no nugetfallback folder for the .net core SDK at all.
> We have removed the fallback folder in .NET Core SDK 3.0 and I consider this issue now resolved.

@livarcocc do you mean if I install .NET Core SDK 3.0 on a clean machine, and do the following:

``` cmd
dotnet new console
dotnet run
```

I won't see the folder `C:\Program Files\dotnet\sdk\NugetFallbackFolder` on Windows?

**Comment by livarcocc** [comment]
Yes. More than that, you won't see that on any OS actually. That is of course, if you install on a clean machine where you haven't installed a 2.x/1.x SDK before.
