### ISSUE TITLE
dotnet restore fails when csproj contains an Import element with a relative path or $(ProjectDir) or $(SolutionDir)

### ISSUE THREAD

**Issue by gpakosz** [dotnet/cli#7411]
## Steps to reproduce

  1. Create a blank Windows UWP project with Visual Studio 2015
  2. Edit the `.csproj` (old format) and add an `<Import>` element
  3. Make the import element use a relative path:
    ```
    <Import Project="targets\dummy.targets" />
    ```
    or
    ```
    <Import Project="$(SolutionDir)targets\dummy.targets" />
    ```
    or
    ```
    <Import Project="$(ProjectDir)targets\dummy.targets" />
    ```

## Expected  behavior

`dotnet restore path\to\project.csproj` parses the `.csproj` correctly, just like Visual Studio or MSBuild does.

## Actual behavior

`dotnet restore path\to\project.csproj` complains the `<Import>` element can't find the `dummy.targets` file. 

Assuming `C:\Projects\dummy\dummy.csproj` and `C:\Projects\dummy\targets\dummy.targets`.
Even the error reporting is erratic: when you e.g. change the `<Import>` statement to
```
<Import Project="$(ProjectDir)XXXtargets\dummy.targets" />
```

The error message says:
```
C:\Projects\dummy\dummy.csproj(4,3): error MSB4019: The imported project "C:\Projects\dummy\XXXtargets\dummy.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

But if you use
```
<Import Project="$(ProjectDir)targets\dummy.targets" />
```

The error message says:
```
C:\Projects\dummy\dummy.csproj(4,3): error MSB4019: The imported project "C:\targets\dummy.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

My analysis (from the outside) is the following:
  - when the `<Import>` element is evaluated, `$(ProjectDir)` and `$(SolutionDir)` are not set and my `.targets` file is not found (for a reason)
 - `$(ProjectDir)` and `$(SolutionDir)` get set **before** printing the error message complicating the analysis

My workaround is to explicitly pass `/p:SolutionDir="%CD%\\"` when launching `dotnet restore` from the `.sln` directory.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3

**Comment by livarcocc** [comment]
Strictly speaking, the CLI does not support building old style csproj files. If you do that, our msbuild props/targets are not loaded through the SDK attribute.

The reason why we don't support building old style csproj is because it may reference props/targets that are only available to full msbuild and not present in the CLI. Which would actually explain the issue you are seeing where it works in msbuild/vs but not in the CLI. Likely, these properties are being set by some props/targets not present in the CLI.

In the CLI/SDK itself, we achieve something similar to what you are doing by using $(MSBuildThisFileFullPath) or <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), dir.props))\dir.props" />.
