### ISSUE TITLE
runtime option is not consistent across commands

### ISSUE THREAD

**Issue by mairaw** [dotnet/cli#7433]
## Steps to reproduce
```
dotnet run -h
dotnet clean -h
```

## Expected  behavior
Runtime option would look the same across commands.

## Actual behavior
In some cases, only --runtime works. In others, both -r or --runtime are accepted.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
This is by design, the problem here is that some of these options (the ones without the shorthand version) are coming from dotnet restore, because of implicit restore. And there are potential conflicts of parameters between the restore options shorthands and some of those supported by commands with implicit restore. So, to work around that, implicit restore options in other commands support only the long form.
