### ISSUE TITLE
Re-enable tests which depend on templates once there are templates for .NET Core 2.1

### ISSUE THREAD

**Issue by dsplaisted** [dotnet/cli#7476]
I'm updating the runtime to .NET Core 2.1 in the master branch.  Currently, this means that .NET Core 2.0 apps won't run (because they need the 2.0 runtime).  However, the templates don't yet support targeting .NET Core 2.1.  So I'm disabling the tests that depend on template creation.

When there are templates that support .NET Core 2.1, we need to re-enable these tests.

**Comment by nguerrera** [comment]
#7535

**Comment by badersur** [comment]
Thanks for referencing this issue @nguerrera 

Now I understand why I can't run any app! I used to download 2.1 SDKs and extracting it using my script, then I thought about deleting older SDKs before extracting! (because what could happen if I'm used to do so for a while and it always works?! :sob:)

I think it's better to use 2.1 runtime when you have templates supporting it, otherwise the experience is kinda broken IMHO...

**Comment by nguerrera** [comment]
Fixed by #7554

**Comment by nguerrera** [comment]
But see #7574 for two tests that had to be left disabled for a different reason.
