### ISSUE TITLE
LZMA archiver is sometimes omitting files on Windows builds

### ISSUE THREAD

**Issue by nguerrera** [dotnet/cli#7508]
Long file paths is one theory. I attached to the archiver and didn't find first-chance exceptions upon making my enlistment path very long, though.

Tagging @ericstj who appears to have written the archiver in case he has thoughts on where to start an investigation.

@johnbeisner is looking at this now.

It's must fix urgently for 1.1 servicing.

**Comment by ericstj** [comment]
Any more information about what's missing?  I would never expect us to drop files within a package, since that is just enumerating the binary content of the zip.  I could imagine us losing the extracted files if the OS wasn't giving us the files back.  Here's the releavant code:
https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Archive/IndexedArchive.cs#L411-L435

I don't believe Directory.EnumerateFiles throws when files matching the wildcard are longer than MAX_PATH, I believe they are just omitted.  @JeremyKuhne is that right?

**Comment by JeremyKuhne** [comment]
> I believe they are just omitted. 

For Core there should be no long path restrictions- I'll add some tests for this scenario to validate.

**Comment by johnbeisner** [comment]
@livarcocc 
We are testing for missing files; see: https://github.com/dotnet/cli/pull/7602

Do you feel that this is not sufficient?

**Comment by livarcocc** [comment]
Great. Thanks.
