### ISSUE TITLE
All sln tests pass but dotnet test exits with code 1

### ISSUE THREAD

**Issue by nmklotas** [dotnet/cli#7521]
Hi,

My XUnit test passes but ```dotnet test``` returns 1 (indicating failure).  I also see some stderr output that no tests are available for Console project, I think this output should not be stderr:
![image](https://user-images.githubusercontent.com/4801422/29706840-e6993b46-898b-11e7-83f0-663211afaab5.png)

## Steps to reproduce

in powershell:
```
git clone https://github.com/nmklotas/DotnetTestBugRepro.git
cd DotnetTestBugRepro
dotnet restore
dotnet build
dotnet test
$lastexitcode
```
$lastexitcode is 1  

## Expected  behavior
$lastexitcode is 0

## Actual behavior
$lastexitcode is 1

## Environment data
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0

  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

@blackdwarf

**Comment by tverboon** [comment]
Also in vstest repo: https://github.com/Microsoft/vstest/issues/411

**Comment by ssl9ek** [comment]
Ran into this as well. All unit tests are passing but I'm getting exit code 1 due to this "No test is available in" output. I agree that this line should not be in stderr, but rather a warning.

For solutions with multiple test projects, running dotnet test *.sln is simplest, but returns exit code 1, due to the non-test projects. I've yet to figure out how to run dotnet test on multiple test projects within a single command.

**Comment by livarcocc** [comment]
Please, continue this conversation in the vstest repo. This is something that primarily we would need to address there. Closing this one so that we can move the conversation there.
