### ISSUE TITLE
Performance impact by searching excluded directories

### ISSUE THREAD

**Issue by MovGP0** [dotnet/cli#7525]
## Steps to reproduce

* Create a web project 
* have a large folder with thousands of files in it (ie. `node_modules`)
* exclude the folder in the `.csproj` file for performance reasons 

```xml
  <ItemGroup>
    <Compile Remove="node_modules\**" />
    <Content Remove="node_modules\**" />
    <EmbeddedResource Remove="node_modules\**" />
    <None Remove="node_modules\**" />
  </ItemGroup>
```

## Expected  behavior

* the folder should be ignored by the dotnet command 
* project should load really fast in Visual Studio and JetBrains Raider 

## Actual behavior

* the folder is searched recursively 
   * (issue was determined using the Sysinternals Process Monitor)
* project takes way too long to load
* creating/renaming/refactoring files and folders in Visual Studio takes way longer
* more RAM consumption 

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d


```

**Comment by MovGP0** [comment]
see also: https://developercommunity.visualstudio.com/content/problem/101727/visual-studio-2017-seaches-excluded-folders.html

**Comment by dasMulli** [comment]
The problem here is that the items are added beforehand so to exclude the folder being searched is to add it to the `DefaultItemExcludes` property [like the web SDK already does for ASP.NET Core project](https://github.com/aspnet/websdk/blob/1fd3e2add57478aa29f99cbae06c8bf44c095588/src/ProjectSystem/Microsoft.NET.Sdk.Web.ProjectSystem.Targets/netstandard1.0/Microsoft.NET.Sdk.Web.ProjectSystem.props#L15).

To do it in non ASP.NET Core projects, you'd have to add a similar property redefinition to your csproj:
```xml
<PropertyGroup>
  <DefaultItemExcludes> node_modules/**;$(DefaultItemExcludes)</DefaultItemExcludes>
</PropertyGroup>
```

Note that there is a performance issue in glob expansion with patterns like `**/node_modules/**` at the moment so you'll have to add the folders explicitly (best at the start of the `DefaultItemExcludes` as shown above)

**Comment by MovGP0** [comment]
thank you! that's a working solution.
