### ISSUE TITLE
dotnet build / run taking too long due to enforced default restore

### ISSUE THREAD

**Issue by darkguy2008** [dotnet/cli#7587]
## Steps to reproduce
* Create a new empty web project.
* Run dotnet build
* Run dotnet run
* Compared to 1.x, it takes around 2-4x times than before.
* Run the same commands with --no-restore . Notice it's faster.

## Expected  behavior
* I am the developer. I am solely responsible for running dotnet restore in case I have missing packages.
* Commands should run with --no-restore as default, or at least have a global flag (or similar to .npmrc) to set it up. 

## Actual behavior
* dotnet restore is being enforced prior to build/run, so development isn't as streamlined as it used to be, it's slow. **SLOW**.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

![image](https://user-images.githubusercontent.com/6304136/30001374-7ec21a00-9049-11e7-9b76-c859c0c789fd.png)

**Comment by danmosemsft** [comment]
The build takes time as well as the restore. In my opinion, `dotnet run` should by default not do a build nor a restore, or there should be some other first class way to simply run (without needing parameters). Since there is no executable produced, I have no alternative but to use `dotnet run` today:

```
C:\dotnet.3\1>\t\timer ..\dotnet.exe run --no-build
..\dotnet.exe run --no-build
Hello world
Results of execution:

    Exit code 0
    Time of execution 0.502

C:\dotnet.3\1>\t\timer ..\dotnet.exe run
..\dotnet.exe run
Hello world
Results of execution:

    Exit code 0
    Time of execution 2.908

C:\dotnet.3\1>\t\timer ..\dotnet.exe run --no-restore
..\dotnet.exe run --no-restore
Hello world
Results of execution:

    Exit code 0
    Time of execution 2.025
```

**Comment by benaadams** [comment]
Can specify the build dll directly? Not great though
```
dotnet bin/Debug/app.dll
dotnet bin/Release/app.dll
```

**Comment by omajid** [comment]
See also https://github.com/dotnet/cli/issues/7610

**Comment by danmosemsft** [comment]
@benaadams perhaps if ther'es a .dll in the same folder then plain `dotnet` should just run it.

**Comment by svick** [comment]
@danmosemsft 

> In my opinion, `dotnet run` should by default not do a build nor a restore

I disagree.

I think that the primary use case of `dotnet run` is to run code after you've changed it, which is why it should do build and why it should also do restore if necessary. What is your use case where the performance of `dotnet run` matters, but you didn't change any code, so the binary doesn't have to be rebuilt?

It was annoying that on .Net Core 1.0, you had to often do `dotnet restore && dotnet run`. What you're proposing would mean that I would have to do `dotnet build && dotnet run`, which I think is still bad.

Instead, I think that `dotnet` should be optimized so that `dotnet run` is sufficiently fast.

> or there should be some other first class way to simply run (without needing parameters)

What's wrong with parameters? That they make the command too long?

**Comment by darkguy2008** [comment]
@svick .NET Core 1.0 was pretty fast at builds, it almost felt like using webpack which is kind of unreal considering how long a build uses to take in the .NET world aside from a simple Hello World app. 

Again, as developer I should be responsible for ```dotnet restore```. I don't need the build process to do a restore *everytime* if I didn't add any packages, and if the ```restore``` command would realize it doesn't need to connect each time it would be transparent, but it takes a lot of time and it hampers my productivity. Even more when ```dotnet run``` does a build, which in turn does a restore. Totally unacceptable.

See my example: 2s vs 6s, that's an improvement of 33% in build speed and if you find annoying to run ```dotnet restore && dotnet run```, I find it annoying to type ```dotnet build --no-restore && dotnet run --no-restore --no-build```. I'm surprised this doesn't seem annoying to you.

**Comment by danmosemsft** [comment]
@svick I don't disagree .. it occurs to me I've likely complained myself in the past that `dotnet run` failed because it didn't restore when it could know it needs to restore. 😄 

Re parameters: scenario is I've written some code and want to use it a few times, but without going to the trouble of publishing it or digging in the binaries directory.

Perhaps rather than change `dotnet run`, there could be a new verb, or `dotnet` without parameters in the folder of a project file could execute the output.

**Comment by livarcocc** [comment]
We have made implicit restore faster by not requiring it to run in a separate process from the msbuild invocation responsible for the build.

NuGet is also making implicit restore faster. Also notice that restore will not hit the network unless it really needs to, in the case of two restore ran one after the other that's only needed if you have any start dependencies, otherwise it will quickly (and soon, quicker still) identify that nothing has changed and stop.

And yet still, we are focusing a lot on performance improvements for build itself in the 2.2.0 timeline for the SDK.

Given all that, I am closing this issue now. There are a few other issues tracking run performance, build and restore. Just search this repo for issues tagged with Performance.

**Comment by vincenzoml** [comment]
I created a Makefile for my project that, in the target "run" uses dotnet path/to/dll if the target dll is newer than the source files. Otherwise, it runs dotnet run. When there is no need to build, execution of my program takes 0.2 seconds. In the same conditions, dotnet run --no-build --no-restore takes 0.8 seconds. This makes no sense to me. In the same conditions (executable not older than source), dotnet run takes 2.3 seconds. Which makes even less sense to me. It's not a matter of efficiency but a matter of *not doing anything* when the thing is already built. What's wrong  with such a simple behaviour?

**Comment by vincenzoml** [comment]
(no need to add, one can use GNU Make for doing what I did, and it's not an issue if someone in the team does not have it installed as dotnet run will anyway work fine).
