### ISSUE TITLE
dotnet path error

### ISSUE THREAD

**Issue by wuball** [dotnet/cli#7596]
## Steps to reproduce

1. New a project 'ASP.NET Core Web Application (MVC)' in visual studio 2017;
2. The project path is `E:\master\dotnet\WebApplication1\`
3. Publish project success and  **appsettings.json exists in PublishOutput**
4. The publish path is `E:\master\dotnet\WebApplication1\WebApplication1\bin\Release\PublishOutput`
5. Run project:
           1: `E:\> dotnet E:\master\dotnet\WebApplication1\WebApplication1\bin\Release\PublishOutput\WebApplication1.dll`
           2: `E:\master\dotnet\WebApplication1\WebApplication1\bin\Release\PublishOutput\> dotnet WebApplication1.dll`

## Expected  behavior
Run project 1
Error: **The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'E:\appsettings.json**'.

Run project 2
Success

## Actual behavior
Run project 1
Success

Run project 2
Success

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.1.0)

Product Information:
 Version:            1.1.0
 Commit SHA-1 hash:  d6f4336106

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.0

**Comment by livarcocc** [comment]
This is by design and happens because of where asp.net expects your appsettings.json file to be: in your current working directory.

When executing a dotnet application through dotnet.exe, the host does not change the CWD to the location of the dll that you are executing and maintains the CWD to where you are running the command from.
