### ISSUE TITLE
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/root/api'.

### ISSUE THREAD

**Issue by saulhamid** [dotnet/cli#7597]
## Steps to reproduce
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/root/api'.

## Expected  behavior
published API Project

## Actual behavior
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/root/api'.

## Environment data
`dotnet --info` output:

[root@asp api]# dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /opt/dotnet/sdk/1.0.4

**Comment by livarcocc** [comment]
We really need more info in order to be able to help out with this issue.

Like, how are you executing the app? What does your csproj look like?

In general, when we see something like this, this happens because you are trying to run a library, like an application. It is missing a file called <your app>.runtimeconfig.json, which indicates which runtime the application should target.

Please, provide additional information.

**Comment by livarcocc** [comment]
Closing it since we haven't heard back with additional information. Please, re-activate when you can answer some of my questions above.
