### ISSUE TITLE
The 'dotnet/buildtools' repo does not build on Debian 9 Stretch

### ISSUE THREAD

**Issue by bazzilic** [dotnet/cli#7622]
On Debian 9 (Stretch), do

```
git clone https://github.com/dotnet/buildtools.git
cd buildtools
./build.sh
```

It will fail due to inability to detect an OS while executing a script from this repository located at `scripts/obtain/dotnet-install.sh`.

After taking a closer look at the script, it is clear that this function does not detect Debian 9: https://github.com/dotnet/cli/blob/8e756edce1573c30c0c5a0708ff323dda0f673fc/scripts/obtain/dotnet-install.sh#L58-L109

**Comment by livarcocc** [comment]
@johnbeisner please, take a look.

**Comment by johnbeisner** [comment]
@bazzilic 
It appears that you are using an old version of dotnet-install.sh - please use the version at: https://dot.net[specifically: https://dot.net/v1/dotnet-install.sh]

**Comment by bazzilic** [comment]
How could a script in master branch be outdated? And why do other dotnet projects use the outdated script then?

**Comment by bazzilic** [comment]
Btw, the script you linked to has exactly same issue of not detecting Debian 9.

**Comment by johnbeisner** [comment]
@bazzilic
So looking into this further I can state a few more facts:
1. The dotnet/buildtools build is downloading a "1.0.0-preview2-1-003182" version of the SDK
2. In any version of the script we do not detect Debian 9 because in the 1.0 and 1.1 releases we did not publish Debian 9 specific packages. The list of platforms is finite and targeted.
3. Moving forward, we support Debian 9 with generic Linux portable packages - unfortunately that does not solve your current problem.

I cannot see a way for you to build the dotnet/buildtools on Debian 9 at this time
I will move this issue into dotnet/buildtools backlog to see if they can solve this.

**Comment by johnbeisner** [comment]
This issue was moved to dotnet/buildtools#1675
