### ISSUE TITLE
ctrl-c on `dotnet build` doesn't always stop build

### ISSUE THREAD

**Issue by danpere** [dotnet/cli#7683]
## Steps to reproduce
1. Run `dotnet build`.
2. Wait for version information notice to appear:
```
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```
3. Hit `ctrl`+`c`.

## Expected  behavior
No further output.

## Actual behavior
The entire build runs displaying the normal output for the build.

This sounds similar to issues #4856 and #7426. I'm creating a separate issue because those are about `dotnet run`, not `dotnet build`.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by peterhuene** [comment]
Hi @danpere,

This should now be fixed in 3.0 with https://github.com/dotnet/cli/pull/10720 (it'll be a little while before the fix shows up in the SDK nightly, though).

The `dotnet build` command is now consistent in its SIGINT handling so that it will allow the child MSBuild process to handle the SIGINT and terminate before the `dotnet build` command exits gracefully, returning the same exit code that MSBuild returned.

As I believe this is resolved, I am closing this issue.  Please reactivate it if you can reproduce the behavior with a recent 3.0 SDK build.  Thanks!
