### ISSUE TITLE
argument parsing treats --force:true argument special in user command line.

### ISSUE THREAD

**Issue by kellypleahy** [dotnet/cli#7863]
## Description

For some reason, `dotnet run` has special treatment for *user* arguments of the form `--force:foo`.  The `:` gets removed and the parameter gets split into two different entries in the `args[]` array.  This doesn't happen with other argument names (see below, with `--bob:true` it works as expected, but it **eats** the `:` on the `--force:true` argument.

## Steps to reproduce

1. dotnet new console
1. change body of main() to `Console.WriteLine(string.Join(",", args));`
1. run command line using `dotnet run -- --force:true --bob:true`

## Expected  behavior

output should be `--force:true,--bob:true`

## Actual behavior

output is `--force,true,--bob:true`

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by livarcocc** [comment]
@peterhuene, want to take a look at this one?

**Comment by peterhuene** [comment]
Sure thing! I'll take a look.

**Comment by peterhuene** [comment]
@kellypleahy: thank you for the detailed bug report!  I was able to repro this issue.

This issue is due to the parser not properly lexing when options following the "double dash" match expected tokens for the current command; in this case, `--force` is a valid option to the `run` command, so it splits at the value delimiter `:`, ultimately resulting in the two arguments being passed to the target program instead of a single argument.

The fix is to have the parser keep track of seeing the "double dash" and perform no more processing on the tokens following it.  I'll have the fix made to the parser repo soon.

**Comment by kellypleahy** [comment]
@peterhuene No problem!  Happy to help...
