### ISSUE TITLE
Re-enable copying output files to Stage 2 during CLI dev cycle

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#790]
https://github.com/dotnet/cli/pull/761

**Comment by cdmihai** [comment]
Now that CLI is incremental, I suggest that instead of the copy script I introduce a `Dev` or `BuildAndTest` flag to the CLI build script that only compiles stage2 and runs the tests. This way, CLI developers would call build.cmd -Dev which would only compile stage2 and run tests. Incremental building will skip projects did do not have to be rebuilt.

**Comment by piotrpMSFT** [comment]
CLI build is now sitting atop MSBuild and fundamentally rewritten. Closing as this applied to legacy code base.
