### ISSUE TITLE
Want to migrate on dnx to cli with entity framework core

### ISSUE THREAD

**Issue by ankurjasoria** [dotnet/cli#7942]
Hi Team,

I want to migrate from dnx to cli with entity framework but unable to find proper update and
unable to run dotnet ef cli command and find below error.

Error :
PS C:\test2\hwapp> dotnet ef
No executable found matching command "dotnet-ef"

I am sharing reference url below
http://www.bricelam.net/2014/09/14/migrations-on-k.html

Please update me any solution or any other reference url regarding same.

**Comment by livarcocc** [comment]
You will first have to migrate from dnx and project.json to the new csproj format. You can find some guidance about it here: https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md.

Note that because you are still in DNX, it is likely that migration won't be clean for you and you will have to edit your project.json so that it can be converted to csproj.

Also, make sure you have at least .NET Core SDK 1.0.0.

**Comment by ankurjasoria** [comment]
Hi Livar,
Thanks for updating !!
I have followed above url as reference and found below issue 

Error : 
PS C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform> dotnet migrate
No executable found matching command "dotnet-migrate"

I have created separate console application with the use of below cli command
- dotnet new
- dotnet restore
- dotnet build 
- dotnet run 
 All command working fine but unable to proceed further like What is my next step ?
I am sharing you my powershall command and status as below

PS C:\test3\myApp> dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  myApp -> C:\test3\myApp\bin\Debug\netcoreapp2.0\myApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.02
PS C:\test3\myApp> dotnet run
Hello World!
PS C:\test3\myApp> dotnet migrate
No project.json file found in 'C:\test3\myApp'.
Migration failed.
PS C:\test3\myApp> 

Please suggest me for same ?
