### ISSUE TITLE
dotnet build : Bin folder is empty when passing /t:rebuild 

### ISSUE THREAD

**Issue by johnkors** [dotnet/cli#7945]
## Steps to reproduce
`dotnet build myproject.csproj /t:rebuild` 

[Sample repo](https://github.com/johnkors/dotnet-build-target-rebuild/blob/master/build.cmd)

## Expected  behavior
A rebuilt project and contents in the output folder

## Actual behavior
An empty output folder

## Environment data
`dotnet --info` output:
```
λ dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by livarcocc** [comment]
If you want to specify targets, you should use `dotnet msbuild`, instead of `dotnet build`. Also, using `dotnet build`, if you want to do a full rebuild, you should pass `--no-incremental`.

This happens because dotnet build without the --no-incremental parameter will always pass the Build target to MSBuild, which means that when you do `dotnet build /t:Rebuild`, you are effectively invoking MSBuild with /t:Build /t:Rebuild.

Now, MSBuild only runs a target once, which means it will do a build and then the rebuild. As part of the rebuild, it will clean the output and then try the build again, which already ran and is therefore skipped. So, you get no files in the output.

This also happens when using msbuild directly with the two targets above and also happens for old style csproj files.

I am going to close this issue as the work-arounds I proposed above work. If you disagree, comment and we can continue the conversation.

**Comment by johnkors** [comment]
Right, ok. That behaviour was not very evident / clear from the docs, so thanks for taking the time to go into internal details and explain it!

From what I understand, the input I gave are part of an allowed set of input parameters,  but with dire consequences. The question then is; why does the CLI allow it to happen in the first place, if the outcome is really counter intuitive and having the opposite affect of what one is trying to do at the same time? I would have expected an early error message, if it's an unsupported scenario. 

WARN : "You're trying to mix a msbuild rebuild target with dotnet core build command. This will cause an empty output folder. See details <here>"
