### ISSUE TITLE
EF Migrations -> dnx to cli

### ISSUE THREAD

**Issue by kunalchawla2401** [dotnet/cli#7950]
Hi Team, 

I have a project where we do entity framework migrations through dnx. Now, when we are running this project on new machines (with latest version of VS 2015), I am not able to run dnx (may be because it is no longer supported). I want to migrate the project from dnx to cli in order to be able to create migration successfully through cli and updating the database as well. Can someone recommend me an easy way to do that or share any link for the same.

**Comment by livarcocc** [comment]
You will first have to migrate from dnx and project.json to the new csproj format. You can find some guidance about it here: https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md.

Note that because you are still in DNX, it is likely that migration won't be clean for you and you will have to edit your project.json so that it can be converted to csproj.

Also, make sure you have at least .NET Core SDK 1.0.0.

This is similar to #7942
