### ISSUE TITLE
Want to migrate on dnx to cli with entity framework core #7942

### ISSUE THREAD

**Issue by ankurjasoria** [dotnet/cli#7956]
Hi Livar,
Thanks for updating my previous issue #7942  !!
I am facing issue so reopen it again and I have taken  reference below url
https://github.com/dotnet/cli/blob/master/Documentation/ProjectJsonToCSProj.md

and found below issue with migrate command
Error :
PS C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform> dotnet migrate
No executable found matching command "dotnet-migrate"

I have created separate console application with the use of below cli command

dotnet new
dotnet restore
dotnet build
dotnet run

All command working fine but unable to proceed further like What is my next step ?
I am sharing you my powershall command and status as below

PS C:\test3\myApp> dotnet build
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

myApp -> C:\test3\myApp\bin\Debug\netcoreapp2.0\myApp.dll

Build succeeded.
0 Warning(s)
0 Error(s)

Time Elapsed 00:00:01.02
PS C:\test3\myApp> dotnet run
Hello World!
PS C:\test3\myApp> dotnet migrate
No project.json file found in 'C:\test3\myApp'.
Migration failed.
PS C:\test3\myApp>

Please suggest me for same ?

**Comment by livarcocc** [comment]
I am a little bit confused. You say above that you are getting a dotnet migrate command not found error. However, down below, after dotnet run, dotnet migrate is being found, but in that case, there is no project.json to be migrated. The project is already a csproj.

Note that project.json -> csproj migration is one thing. Entity Framework migration is another.

Also note, for your dnx project, confirm that you do not have a global.json file pinning the SDK version to an older (like 1.0.0-preview2) version.

**Comment by livarcocc** [comment]
Also, it would be helpful if you could share with us the content of `dotnet --info` command ran under C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform>. That would tells us exactly which version of the CLI is being used in that case and then we would know for sure if your problem is a global.json pinning you to an SDK version that did not support migrate.

**Comment by ankurjasoria** [comment]
Hi Livar,
Thanks for quick reply !!
I am clarify about my actual issue I want to migrate dnx to cli and then I'll can add,update etc my db migration through CLI ? 

I am new about CLI concept so I don't know possible simplified steps. So I have find out below refrence url by which I am trying my test project on CLI.

https://docs.oracle.com/cd/E17952_01/connector-net-en/connector-net-entityframework-core-example.html
  
and now I am sharing you command info below

C:\yoyo-center-management-system-master\CenterManagementSystem\DEV\src\CenterManagementSystem.Platform>dotnet --info
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

Please advice me about the same ?

**Comment by livarcocc** [comment]
Well, you need to do a few differents things:

1. Install a new CLI, either the latest 1.0 or the latest 2.0 CLI. You can find it at https://dot.net.
2. Remove your global.json that is currently pinning your CLI to an older version (1.0.0-preview2-003131). This CLI supports only project.json and does not contain the migrate command.
3. Migrate your project through dotnet migrate, to move them from project.json to csproj. Note that because you are still in DNX, you may need to hand edit your project.json into a valid project.json for the CLI to migrate. The migrate tool should give you appropriate error messages if any editing is needed.
4. At this point, you should have a good csproj project and you should be able to run the ef commands here.

**Comment by livarcocc** [comment]
This link contains more information on this as well: https://docs.microsoft.com/en-us/dotnet/core/migration/.
