### ISSUE TITLE
'dotnet clean' seems to ignore project NU1603 warning suppression

### ISSUE THREAD

**Issue by paultobey** [dotnet/cli#8027]
## Steps to reproduce
1. Create VS2017 solution for .NET Core 1.1 (error appears in 2.0 tooling, also, I believe)
2. Create console application project
3. Establish dependency on some NuGet package. In my case, I'm using Gray.Microsoft.AspNetCore.SignalR.Server. The important thing is that the package should have dependencies resolved by later versions of some package, generating a NU1603 warning during build.
4. Set project options to:
    a. suppress warning NU1603, and 
    b. treat warnings as errors.

## Expected  behavior
* When performing Clean build in VS2017, this works correctly. No NU1603 warnings are generated (and the clean succeeds). This is the expected behavior of 'dotnet clean <solution>', too.

## Actual behavior
* When performing 'dotnet clean <solution>', the warnings are displayed in the build output and the build fails (because we're set to treat warnings as errors).

In our case, this causes our local builds through VS2017 to work great, but our automated builds based on TeamCity to fail. The failure occurs in the 'clean' step only; 'build' actually uses the suppression option from the project correctly.

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.0.3)

Product Information:
 Version:            2.0.3
 Commit SHA-1 hash:  12f0c7efcc

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by peterhuene** [comment]
Hi @paultobey, thanks for reporting this issue!

I'm unable to exactly reproduce the problem as you describe, but this is what I'm seeing with 2.0, 2.1, and `master`:

* The warnings are coming from the `ReportAssetsLogMessages` target in the SDK.  This target is skipped if the project assets file does not exist; thus a restore operation must have occurred previously for any warnings to show up in the `dotnet clean` operation.
* If a restore occurred where the warnings were emitted previously (i.e. the `NoWarn` property had not yet been set in the project), the clean operation will emit the warnings regardless of whether or not the project file now has `NoWarn` set.  This is due to the clean operation not performing a restore that would have updated the project assets file to ignore the warning.  This can be reproduced after adding the package reference by:
  * `dotnet restore` (emits warnings)
  * edit project file to ignore the warning with `NoWarn`.
  * `dotnet clean` (still emits warnings)
* If a restore occurs after the warning is ignored in the project file, the clean operation will no longer display the warnings.  This is the result of the project assets file now having the warning ignored such that the `ReportAssetsLogMessages` task skips outputting the warnings.  This can be reproduced after adding the package reference by:
  * `dotnet restore` (emits warnings)
  * edit project file to ignore the warning with `NoWarn`.
  * `dotnet restore` (no warnings emitted)
  * `dotnet clean` (no warnings emitted)

I think the appropriate fix is to simply skip the `ReportAssetsLogMessages` target when doing a `dotnet clean` as I'm not sure why a clean operation would need to report nuget messages.  @livarcocc thoughts on this approach?

**Comment by paultobey** [comment]
Thanks. I believe scenario #2 is my situation. Another team member changed warnings to errors, I had to add the NoWarn, etc., but the build server probably didn't experience a 'dotnet restore'.

For my part, your solution is good. 'clean' is, I think, just supposed to remove build outputs. If there's a real NuGet error, that isn't needed until a build operation.

Paul T.
