### ISSUE TITLE
.NET Core SDK 2.0.3 has hard-coded version string in bundle UI

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/cli#8042]
@barnson commented on [Thu Nov 16 2017](https://github.com/dotnet/core-setup/issues/3427)

## Steps to reproduce

* Install dotnet-sdk-2.0.3-win-x64.exe, downloaded from https://www.microsoft.com/net/download/windows.

## Expected  behavior

The `Success` page tells me I installed version 2.0.3.

## Actual behavior

![image](https://user-images.githubusercontent.com/916265/32928786-c04e0ae8-cb21-11e7-9f4e-1093c96eed3a.png)

The loc string `FirstTimeWelcomeMessage` used on the `Success` page in the bundle has hard-coded `2.0.0` strings.

## Environment data

n/a

**Comment by Petermarcu** [comment]
Thanks @barnson , I moved it here where the SDK installer lives.

**Comment by barnson** [comment]
I spent 15 minutes trying to figure out which repo it belonged in. :)

**Comment by Petermarcu** [comment]
Nice, I know. we're actually working on some repo renaming to try to make things seem a little more obvious. Not sure if it will help a ton but I know its a bit of a challenge today.

**Comment by 4creators** [comment]
@Petermarcu @barnson 
I have noticed that problem yesterday as well and prepared temporary fix for the installer. Below are screenshots of two versions. Design is open to any changes requested 😃 Version data are sourced from `build/DependencyVersions.deps` and will update automatically with sources. If this is of any interest I can submit PRs for master and other branches.

![dotnetsdk-installer-02-01](https://user-images.githubusercontent.com/801959/32959353-a85f80ba-cbc1-11e7-828a-ae5637c11ee3.JPG)

![dotnetsdk-installer-02-02](https://user-images.githubusercontent.com/801959/32959377-b9f9e630-cbc1-11e7-8c33-a42b3e01a0c3.JPG)

And the second arrangement:

![dotnetsdk-installer-01-01](https://user-images.githubusercontent.com/801959/32959408-d952c498-cbc1-11e7-9768-497b2c0a7856.JPG)

![dotnetsdk-installer-01-02](https://user-images.githubusercontent.com/801959/32959415-df57c474-cbc1-11e7-9d17-e064d4d1e26e.JPG)

**Comment by Petermarcu** [comment]
@wli3 I'm sure is interested in a PR :)

**Comment by livarcocc** [comment]
@KathleenDollard can you take a look at the screenshots above and comment? I would like at least the .NET Core SDK version to match the number that will be installed on the disk for you. The number you are displaying right now does not.

Also, if we are showing some dependencies numbers there, should we show others? Like the template engine, the test console and NuGet?

**Comment by 4creators** [comment]
IMHO it would be great to show everything what is installed similar to about box for VS, but with finer granularity.

**Comment by akoeplinger** [comment]
The macOS installer has the same issue btw (2.0.3 in the title bar vs 2.0.0 in the summary screen):

![image](https://user-images.githubusercontent.com/1376924/32963584-bfa37b3c-cbd0-11e7-8126-3eb4140022ae.png)

**Comment by SamArmand** [comment]
Correct me if I'm wrong but I think this issue stretches beyond the UI. I updated to 2.0.3 but restoring NuGet packages still installs **Microsoft.NETCore.App 2.0.0** to my project. What's causing that?

![image](https://user-images.githubusercontent.com/1415052/32977521-0ab59f5c-cbfd-11e7-8212-120b8072e3d5.png)

**Comment by livarcocc** [comment]
@SamArmand that's intentional. This will guarantee that for portable applications your application will run on any runtime starting at 2.0.0. This is to prevent cases where you update to the latest SDK and publish your app, say, to Azure before that data center installs the 2.0.3, runtime. This way, that will continue to work.
There are no API changes in a patch release, so, this is perfectly safe.

If you are a self-contained app, then you need to set RuntimeFrameworkVersion 2.0.3 to target that runtime. That is currently a bug that we are working out how to solve.

In any case, this is unrelated to the version we print in the installer.

**Comment by dasMulli** [comment]
@livarcocc can't find the tracking issue now, but I was wondering why the implicit versions for the 1.* runtimes weren't raised to 1.0.8/1.1.5 in the 2.0.3 SDK - as far as I can tell it shouldn't be affected by the issue that's causing troubles for different versions for portable/self-contained (unless you want to fix the portable version to a lower version).

**Comment by livarcocc** [comment]
@dasMulli for the same reason we don't upgrade them for the 1.1.x SDK. If someone is targeting netcoreapp1.0 or 1.1 and updates their SDK to 2.0.3 and then publishes to a hoster that hasn't updated their runtime yet, the app is broken.

**Comment by KathleenDollard** [comment]
There are two aspects here

1) Change the UI on install to not use hard coded strings. Yippeee!!!! Excellent. Excellent. 

2) Adding several new version numbers to the UI. I don't particularly like this and feel strongly that this is a bad time to do it. 

Since we are diverging the runtime and SDK, the more clarity and simplicity we can provide, the less confusion from that change. The SDK is the thing they elected to install, so I want to reiterate that number (as before) and include the runtime for clarity (again, as before). 

I would like to discuss what scenarios exist where the versions of Roslyn, MSBuild, F#, etc. are important to users. I would like to use that discussion to guide the right places to provide that information. I'm skeptical that a passing install complete screen is the most useful place to put this information.

**Comment by dasMulli** [comment]
I think the installer should at maximum display versions vor included ""things"" that could also be installed on their own.

When I installed a 2.2.0 CLI, it would be good to know that I got a 2.1.0 runtime and package store with it. I may remind me to download a 1.1.* / 2.0.* runtime installer as well. (at some point there was a change setting the CLI version to 15.5 which I liked since it couldn't be confused with a runtime version like 2.0.3)

In contrast to that, I don't think showing the versions of roslyn, msbuild, f# and friends don't provide any actionable value. Since I cannot install a version of roslyn/msbuild/… alone, there is nothing I can do about it.

**Comment by 4creators** [comment]
> Adding several new version numbers to the UI. I don't particularly like this and feel strongly that this is a bad time to do it.

From developer perspective it is the most vital information. SDK is targeted at developers and consumers and having full and detailed version info on every part of it is just IMHO minimum info requirement.

> I would like to discuss what scenarios exist where the versions of Roslyn, MSBuild, F#, etc. are important to users

Everywhere where they are relevant - we are talking about development tools which won't be released in a 2 - 3 year cadence but my hope is that it will be 1 - 3 months cadence. With that granularity we need to know every detail of tool to get relevant support, raise issue in relevant repos etc. IMHO one of the reasons why ppl have hard time finding right repos for reporting issues is lack of relevant information on runtime and sdk components and their versions.

If I get any warnings or error and I have do dig up info for posting an issue it becomes particularly frustrating.

> I think the installer should at maximum display versions vor included ""things"" that could also be installed on their own.

Disagree - installer and even after installation should provide full info otherwise **we paternalise developers** who are anyway usually grown ups and quite fluent in parsing visually complexity associated with version numbers - if they are unable to do that most probably they will have hard time on their jobs.

> I don't think showing the versions of roslyn, msbuild, f# and friends don't provide any actionable value. Since I cannot install a version of roslyn/msbuild/… alone, there is nothing I can do about it

Wrong assumtpion - never underestimate devs

**Comment by 4creators** [comment]
Ahh just forgot - all Windows SDKs provide detailed information on every tool installed in their sdks, installers, logs etc.

**Comment by dasMulli** [comment]
> Wrong assumtpion - never underestimate devs

I don't. I'm the first one to learn roslyn, VS, msbuild version numbers by heart. But even VS has them tucked away in a help dialog. `dotnet --info` would be a more appropriate place to show all these details.
You also mentioned reporting issues. I don't think you'll re-run the installer just to get the version numbers when creating an issue.

But I really don't feel strongly about it.

**Comment by 4creators** [comment]
> dotnet --info

Agree - there should be an easy way to query for detailed tool info. It is very important for some scenarios where build scripts check for prerequisites or for error reporting.  But it would be a separate issue.

I would even suggest to have `dotnet &lt&;tool_name&gt&; --info/--version` syntax support.

**Comment by KathleenDollard** [comment]
@4creators: I'm not suggesting hiding this data from programmers. 

If we had a link on the installation summary that says "For details on SDK contents" we could provide a location where you can look this information up - and access it after the fact. 

Would that solve your concerns?

**Comment by 4creators** [comment]
Hmm .. I would say that yes and no. If I want to get info this will solve the problem but if I want to go with OSS spirit than the answer is no - this will not solve the problem.

I think very good example of what I am thinking about is an attempt to install some toolchain via `apt-get install` command on Debian and Debian derived Linux distros. What user is informed about before install will proceed these are all details of every package which will be installed on the machine including it's size, full version etc. I find this info very useful particularly if I am troubleshooting some build issues. Usually I keep tools versions memorized for several weeks after I have seen them once during install.

Another good example would be to have a look on the scope of info which will be provided by Linux distros during install once they will be able to build SDK fully from source and .NET Core will meet oss standards of the distros (what is not the case currently see issue https://github.com/dotnet/source-build/issues/187). I bet it would be info on every tool installed.

**Comment by KathleenDollard** [comment]
@4creators Looking at the spirit of your comments, I'm  even less happy with the version info in the completion dialog, because you talked about having that information _before_ or _during_ install. Supplying this info _after_ install does not meet that spirit. If the right info is available somewhere online, it's available before, immediately after, or two months later, that better meets the spirit of ensuring that programmers have the right information to make the right decision at the right time. 

So I suggest we 

- fix this now by updating the version numbers that were already there (runtime and SDK), and
- create a new issue to establish the right way to communicate the contents of each SDK.

**Comment by leecow** [comment]
@KathleenDollard - once a final plan is decided up, the changes are needed in the release/15.5 (soon to be release/2.1)

**Comment by eduherminio** [comment]
Quite offtopic, @livarcocc, but...

> If you are a self-contained app, then you need to set RuntimeFrameworkVersion 2.0.3 to target that runtime. That is currently a bug that we are working out how to solve.

Where can I follow the progress on that bug? Is there any workaround or is it possible to set it manually?
I'm afraid I need Core v2.0.3 in a self-contained app since this [infinite recursion bug](https://github.com/NLog/NLog.Web/issues/210) is solved in that version.

cc/ @danmosemsft, who tracked that bug until it was solved in v2.0.3 release

**Comment by Petermarcu** [comment]
Yes, you can set <RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion> in your project or pass /P:RuntimeFrameworkVersion=2.0.3 on the command line to publish and it should pick up 2.0.3.

**Comment by eduherminio** [comment]
Thanks :)

**Comment by poke** [comment]
@KathleenDollard 
> So I suggest we
> * fix this now by updating the version numbers that were already there (runtime and SDK), and
> * create a new issue to establish the right way to communicate the contents of each SDK.

I agree with this plan. The original list of installed components is good enough for the installer. As @dasMulli  said, those are the things that actually get installed and what I should be conscious about. The internal components are interesting from a debugging perspective but serve no real use while installing.

So if the SDK installer contains the .NET Core SDK, the .NET Core Runtime, and the Runtime Package Store, then those should list their actual version numbers.

*Then*, I would like to see `dotnet --info` expanded to include the full details about the individual components (e.g. MSBuild, NuGet, Roslyn), so that as a developer, I can easily see what versions of those things I am using when I do stuff.

In addition, I think it would be very helpful to have some resource online to see exactly which SDK version includes what versions of those bits. So that when someone refers to a specific SDK version, I have a way to look up what versions are involved (e.g. to see whether specific Roslyn features are available).
As an example, I was directed to this issue because of a discussion where we wanted to figure out what SDK version is the earliest to support a certain C# version. By being able to look up what Rosyln versions ship with each released SDK, this would have been a lot easier.

**Comment by dasMulli** [comment]
Since it is a sort-of-public slack channel I don't think @jchannon and @poke mind me posting this.
That's the conversation leading to revisit this.

<img width="1006" alt="screen shot 2018-01-10 at 16 34 04" src="https://user-images.githubusercontent.com/6129250/34780818-6a7a4072-f624-11e7-8135-ffe41cb2ab1f.png">
