### ISSUE TITLE
Add --list-sdks and --list-runtimes to the help of the Sdk

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/cli#8148]
## Steps to reproduce
- Build latest version on Ubuntu
- Go to a project where global.json specifies an earlier version
- `dotnet restore`
- Get an error:
> The specified SDK version [old version] from global.json [path/to/global.json] not found; install specified SDK version
- OK, so we need to edit global.json.  What's the new version?
- `dotnet --version`
- Get an error:
> The specified SDK version [old version] from global.json [path/to/global.json] not found; install specified SDK version

## Expected  behavior
I'd expect `dotnet --version` to always give me the version

## Actual behavior
If I'm currently in a folder with a `global.json` file, it doesn't give me the version, instead giving me an error that I need the version number it won't give me in order to fix.  This can be worked around by `cd`ing to a folder that doesn't have a `global.json` file, but it's still annoying

## Environment data

.NET Command Line Tools (2.1.1-preview-007094)

Product Information:
 Version:            2.1.1-preview-007094
 Commit SHA-1 hash:  f657648f07

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /home/osboxes/dotnet/roslyn/Binaries/dotnet-cli/sdk/2.1.1-preview-007094/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

**Comment by livarcocc** [comment]
In master (2.2.0 of the SDK), the host now implements a `--list-skds` and a `--list-runtimes` commands.

So, you can run `dotnet --list-sdks` to discover all the SDKs that that host can find.

dotnet --version is used explicitly to indicate what SDK you are using and changing it is a breaking change that I don't see us doing, specially because there is a gesture that you can use to achieve what you are asking for.

**Comment by masonwheeler** [comment]
@livarcocc Please reopen the issue; your explanation is wrong for several reasons.

First, your solution is not discoverable.  When you run `dotnet`, it tells you to run `--version` to get the current version, as does `dotnet --help`.  Neither of the commands you mention are described in either place.

Second, how is making it output the version before checking to see if the current config file is valid "a breaking change"?  What would that break?

Third, the same issue exists when running `dotnet --list-sdks`.

**Comment by livarcocc** [comment]
1. We will add these commands to the help content. This is indeed a bug. If you agree, I can re-activate this bug with a edited title of "Add --list-skds and --list-rutimes to the help message".
2. How would someone know that the version returned is the actual one or a "suggested" one? Also, the semantics of the command is, if it does not find it, it fails. Also notice that the error message you are seeing is not really coming from the --version command, but from the host, as it tries to resolve the SDK. So, if you type any SDK command, like dotnet build, you will get a similar result.
3. I don't follow what you mean. What do you mean the same issue exists? This is what I see when I type dotnet --list-sdks:

```
PS C:\> dotnet --list-sdks
2.1.3 [C:\Program Files\dotnet\sdk]
2.2.0-preview1-007609 [C:\Program Files\dotnet\sdk]
```

**Comment by masonwheeler** [comment]
1. That would be useful to fix, but it wouldn't address the actual bug.
2. Why is this question relevant?  How does someone know now whether the version returned is "actual" or "suggested", and why would it be any different in this case?  As for it coming from the SDK, does that mean that this bug is in the SDK and not in `dotnet`?
3. Are you typing it in a folder that contains a `global.json` file that's requiring a SDK version you don't have available?

**Comment by livarcocc** [comment]
1. You are mistaken. the --version command is implemented in the SDK and not in the host. Therefore, even for --version, it needs to find an SDK to be able to run it.
2. Today, when someone types dotnet --version and gets a number back, they assume that it is the SDK being used. We actually know of many tool and builds that rely on this in their logic. Which is why I don't believe that changing the behavior of --version is the right approach here.
3. Yes, I put in a global.json with a random version that I did not have installed. In your case, make sure that you are using the latest SDK from master for this. This change was made in the host that ships with the 2.1.0 runtime, which ships with the 2.2.0 SDK.

**Comment by livarcocc** [comment]
Fixed by https://github.com/dotnet/cli/pull/8324.
