### ISSUE TITLE
Attempt to pack a dotnet per project tool.

### ISSUE THREAD

**Issue by dazinator** [dotnet/cli#8183]
I am attempting to create my own "per project" tool, having read the docs here: https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility

The docs don't really explain how to go about creating, publishing, and packaging up a cli tool as a nuget package, so that it can be readily pulled into a given project, ready to be executed from the project directory.

Can you clarify:

1. Is it necessary to pack an `exe` or can you pack a `.dll` targeting `netstandard`
2. If it is necessary to pack an `exe` how do we create a a portable package? Do we need to pack multiple exe's for different RID's?
3. If it is necessary to pack an `exe` does this need to be `self contained`?
4. Whereabouts in the nuget package does the `exe / dll` go:
    1. Under /tools ? 
    2. Under /tools/targetframework ? 
    3 Under /tools/targetframework/rid ?
    4 Under /lib?
5. What should the `nuspec` file for the tool look like?

At the moment I am building and packaging my tool based on my assumptions to those questions. 
I am doing the following:

```
dotnet publish --self-contained -r win-x64
```

This builds the project and produces a `netcoreapp2.0/win-x64/published/` folder containing my exe called `dotnet-gluon-apkmanager.exe`

```
 dotnet pack /p:PackageVersion=1.0.0-alpha001
```

This produces a nuget package that has a `tools/winx64` folder containing the output of the `publish` step above - including `dotnet-gluon-apkmanager.exe`

I can add this to nuget package to my project:

```
 <DotNetCliToolReference Include="Gluon.Client.ApkManager.Cli" Version="1.0.0-alpha001" />
```

dotnet restore succeeds.

However when I `cd` into the project directory, and try to run

```
dotnet gluon-apkmanager
```

I get:

```
PS C:\Users\darrell.tunnell\Source\Repos\authenticator\src\Todo> dotnet gluon-apkmanager
No executable found matching command "dotnet-gluon-apkmanager"
```

I don't understand where the cli is looking for the exe, what are the rules it uses to find it (i.e where in the nuget package).

If someone could offer any light on this it would really help.

Thanks.

P.S I have tried comparing my package to the [Microsoft.EntityFrameworkCore.Tools.DotNet](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Tools.DotNet/) package, but the ef tools package is confusing me - i.e it packs both a dll, and an exe, and has a mystery prefercli file in the package root.

**Comment by livarcocc** [comment]
There is an example of such a tool here: https://github.com/dotnet/MVPSummitHackathon2016. It is slightly out of date, as in, it mentions a bug that has since been fixed.

So, essentially, you should pack a portable application, which will be a .dll. Your project should have the following format:

```
﻿<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
</Project>
```
And you should be able to just run `dotnet pack` on it. Notice that it must have a prefix fix of `dotnet`. So, its name should be something like `dotnet-hello`.

The prefercliruntime file is a file that tells the CLI to always run the tool against the runtime that the CLI targets. You should only do that if you are absolutely sure that you tool is not using any special runtime features and that it can be rollforward to a newer runtime. But staying on the same major version. We won't roll you forward from 1.0 to 2.0, but we will from 1.0 to 1.1.

Hope this helps.

**Comment by livarcocc** [comment]
Closing this issue as I believe the questions here have been answered. If you still have opens questions, please, comment and I will re-activate this issue.
