### ISSUE TITLE
Move all dependency copying from Compile into Publish

### ISSUE THREAD

**Issue by cdmihai** [dotnet/cli#825]
I've noticed that after the compile verb invokes CSC (it's main job), it starts doing a lot of stuff that's similar to what publish should do: it copies over dependencies, it copies the host, generates the deps file (this one is somewhere in between). I suggest that the following code be moved into publish: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Compiler/Program.cs#L335-L352

I also noticed that both Compile and Publish seem to be copying corehost.exe into [project_name].exe:
From Compile: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Compiler.Common/ProjectContextExtensions.cs#L105
From publish: https://github.com/dotnet/cli/blob/master/src/Microsoft.DotNet.Tools.Publish/PublishCommand.cs#L180

__Reasoning__
Publish should have the responsibility of putting together the project compilation output and the target dependencies together to get something that is dependency complete. So, after running Compile, the output dirs should only have compilation output (only stuff that comes out of csc and resgen). After running Publish, the output dirs should have the Compile output together with all the dependencies (build time, run time, deps, corehost copied, etc)

**Comment by piotrpMSFT** [comment]
@cdmihai I think we should split this into two issues, one for the shipping verbs and another for our build scripts.

### Shipping Verbs
For our shipping verbs, the distinction is intentional but there may be opportunity to converge a bit. The difference between compile and publish is that compile generates a locally runnable executable [deps file pointing to all Nuget dependencies, local copy of all project output and project dependencies, local copy of the host. Publish, on the other hand, builds on the above by copying all of the NuGet dependencies to a flat directory layout for deployment on another machine. This is intentional, though we may be able to have publish take advantage of the fact that compile already copied over some bits and focus primarily on NuGet scavenging. Keep in mind, though, that Compile output can typically [assuming no native code] go to a TFM-specific directory while Publish output must go to a RID+TFM specific directory.

### Build Scripts
Note that the restore of the runtime is used to generate the Runtime folder which is then used for runtime of CLI-produced apps. Publish copies that same runtime into the Bin directory for use by the CLI tooling. In order to clean this up [and significantly reduce package size] we need to add another probing path to the corehost which will cause it to attempt to use the parent directory as the DOTNET_HOME. I think this is feasible and is being tracked in #451.

**Comment by cdmihai** [comment]
I revived #729 for the runtime / build script and renamed this issue to cover the shared responsibility of Compile and Publish

**Comment by cdmihai** [comment]
Concerning Compile and Publish, it seems to me that what Compile is doing is a local machine flavor of Publish.

Is it correct to say that while Publish is producing a TFM+RID flavor of dependencies, Compile is doing a TFM+local flavor of dependencies. So basically Compile is doing a mini Publish. What happens if a user compiles for full framework on windows, but then publishes for net core on Linux. Would he get a weird mix of windows and Linux dependencies? (the files that do not overwrite each other.)

So, right now it seems to me that Compile is doing (invoke compiler) + (local Publish). I would break this up in two: have Compile's only responsibility to know how to invoke the compiler, and nothing else. Have Publish create two things: a TFM local flavor (the one that Compile did) and then another TFM+RID flavor.

Does this sound reasonable?

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
