### ISSUE TITLE
Arch Linux support: can I help at all?

### ISSUE THREAD

**Issue by markrendle** [dotnet/cli#834]
Sorry, don't know where else to ask the question.

I'm using Arch Linux (well, Manjaro). It's not clear why the distro is restricted, but if there's anything I could do to help get Arch supported, I'd be happy to try.

**Comment by piotrpMSFT** [comment]
The support matrix for CLI is driven by that of https://github.com/dotnet/corefx. Since we are tooling for [and built upon] CoreFx we cannot make headway in directions where the Framework is not available. 

I did a quick search and found this issue https://github.com/dotnet/corefx/issues/1641 which seems related. I think the best way to help would be to follow up in CoreFx to start with and then help us build the right native installation experience once the Framework is ready. 

Please reopen the issue if you see other paths you want to discuss :)

**Comment by markrendle** [comment]
CoreFx/CoreCLR are working fine on my Arch installation. When I try to build `cli`, it's actual hard-coded distro checks (for either `ubuntu-14.04` or `centos-7.1`) in the shell scripts that are preventing things from working.

**Comment by vindicatorr** [comment]
I know this is a bit old, but I too am seeing this.
I came to this issue when dnx flat-out failed on Arch (no error, no output at all).

I thought I'd try to compile dnx myself only to find that it's retired so I thought I'd check out cli.
Immediately I get a 404 with build.sh and finding that only osx, ubuntu and centos will work per the "current_os" function in ./scripts/obtain/install.sh

If dotnet is opensource, why is it needing to download something (packages?) from a microsoft server?
Hmm, doing ahead and downloading https://dotnetcli.blob.core.windows.net/dotnet/beta/Binaries/Latest/dotnet-ubuntu-x64.latest.tar.gz
just for shiggles. 49MB? Should be interesting to see what it's all about. I know I'm just diving in without first seeing what's all around me.

**Comment by shahid-pk** [comment]
@vindicatorr you only download dotnet-cli from microsoft servers which you don't require if compile from source , then you also download libraries like you do with npm, or gem but you can also have them compile from source. The libraries binaries comes from nuget (stable) and myget (unstable). The libraries source exist in dotnet/corefx repository, the runtime exists in dotnet/coreclr , this one is just a tool that makes things easy.

**Comment by vindicatorr** [comment]
Ya, I also found that out last night but encountered an issue building corefx (managed) https://github.com/dotnet/corefx/issues/6742#issuecomment-193778104
Thanks for that greater detail @shahid-pk.
