### ISSUE TITLE
Awkward message from CLI after successfully installing a global tool

### ISSUE THREAD

**Issue by danroth27** [dotnet/cli#8369]
The message displayed by the CLI after installing a global tool is awkward and needs an editorial pass:

```
C:\Users\daroth\Desktop\test>dotnet install tool dotnet-dev-certs --version 2.1.0-preview1-28051

The installation succeeded. If there is no other instruction. You can type the following command in shell directly to invoke: dotnet-dev-certs
```

If there is no other instruction?

**Comment by livarcocc** [comment]
Yes. We have that planned.

**Comment by KathleenDollard** [comment]
Yes, needs updating. Happy for comments on the right wording. 

The problem is that there is a scenario where you need to restart your shell. This occurs if you add the command after the first run and before you restarted your shell. The tool is, in fact, installed (success). But in this weird case, it is incorrect that you can just type blah and run the tool. 

I'll suggest that we not optimize too much for this side case, and assume the user will read other messages and change this to read:

"The installation succeeded and you can run the tool by typing: dotnet-dev-certs"

Is that enough? Or:

"The installation succeeded and you can run the tool by typing: dotnet-dev-certs
(If you the tool is not found, try restarting your shell)"

and if we go that route, is "shell" the right word.

**Comment by svick** [comment]
@KathleenDollard How hard would it be to detect that side case? If it's easy, maybe it would make sense to print a different message for it?

**Comment by KathleenDollard** [comment]
@wli3 can you comment on whether we can detect before printing message.

**Comment by wli3** [comment]
@svick @KathleenDollard We can, but we need more time and use a better error handling design (today, it is just a native way, something goes wrong, stop and print). @peterhuene and I have some idea.

**Comment by KathleenDollard** [comment]
I suggest we change the completion text to 

"The installation succeeded and you can run the tool by typing: dotnet-dev-certs
(If you the tool is not found, try restarting your shell)"

and not work further on knowing the error - since that error will already be displayed. 

@danroth27 does that sound OK?

**Comment by peterhuene** [comment]
This is what we currently have in master (preview 2):

```
$ dotnet install tool -g test.tool
If there were no additional instructions, you can type the following command to invoke the tool: somecommand
Tool 'test.tool' (version '1.0.0') was successfully installed.
```

Is this sufficient or do we want further changes?

**Comment by KathleenDollard** [comment]
You are correct that this is not the experience we want.

I thought we updated that text.

@William Li<mailto:wul@microsoft.com> do you have updated text. Otherwise let's look at this Monday.
________________________________

**Comment by KathleenDollard** [comment]
Not yet. It is still the original old one

-Will

**Comment by KathleenDollard** [comment]
Do we have an issue on that so everyone knows it's not my intent?
________________________________
From: William Li
Sent: Friday, February 23, 2018 1:04 PM
To: Kathleen Dollard; Peter Huene; dotnet/cli; dotnet/cli
Cc: Mention
Subject: RE: [dotnet/cli] Awkward message from CLI after successfully installing a global tool (#8369)


Not yet. It is still the original old one



-Will

**Comment by wli3** [comment]
I am lost... i believe this **is** the issue. And we haven't decided a perfect message yet. And current proposed message is in above.

**Comment by KathleenDollard** [comment]
I'm sorry. I was rushing through email and missed that this was a Github issue. I just mucked it up. 

Let's look at this on Monday.

**Comment by wli3** [comment]
Conclusion of Monday's meeting 
```
You can invoke the tool using the following command: somecommandTool 'test.tool' (version '1.0.0') was successfully installed.
```

When you don't have it on your PATH:
```
....
....

You can invoke the tool using the following command: somecommandTool 'test.tool' (version '1.0.0') was successfully installed.
```

Basically removed "If there were no additional instructions"

**Comment by KathleenDollard** [comment]
Don't we need to drop both "somecommandTool 'test.tool'" with the name of the tool?
________________________________

**Comment by wli3** [comment]
I don't think we talked about it. But it is the name of the tool. The first one is the command name, the second is the packageid. Like:

You can invoke the tool using the following command: vim 'will.awesome.vim' (version '1.0.0') was successfully installed.

**Comment by peterhuene** [comment]
I think there was some confusion because @wli3's examples are missing a newline between `somecommand` and `Tool`.
