### ISSUE TITLE
Add a "high importance" message when building using a preview version of .NET Core

### ISSUE THREAD

**Issue by AngelosP** [dotnet/cli#8457]
## Steps to reproduce
I have .NET Core 2.0 stable on my machine and a bunch of projects using it.
I download and install .NET Core 2.1 preview.
I build one of my existing .NET Core 2.0 applications.

## Actual behavior
Application is built using the 2.1 Preview build tasks & targets 

## Expected  behavior
Application is built using the 2.1 Preview build tasks & targets
+
A build message (classification "high importance") let's me know that I'm building the application using preview build tasks & targets. This message includes a link that points to documentation explaining the finer details.

## Comment
This isn't really about expected vs not-expected behavior. It's more about being transparent and not surprising anyone. Some will expect the application to build using the 2.1 preview build tasks & targets and that's great. This is about giving the people who didn't expect that an opportunity to learn that's what's happening.

**Comment by AngelosP** [comment]
Internal bug #556076

**Comment by dasMulli** [comment]
cc @KathleenDollard this is why I was talking about a global.json switch to prevent preview versions..

**Comment by KathleenDollard** [comment]
@dasMulli The issue that @livarcocc put here is to provide transparency for current and previous hosts. This can be done within the SDK, which has a more frequent release schedule. We do not believe that any change in host selection should happen in patches for the runtime/host. 

Thus the change suggested in this issue is needed, regardless of the resolution of broader global.json questions. And because (discuss there, not here, but it is relevant to the importance of this issue) it remains open whether we can have opt in to previews, rather than opt out for backwards compatibility reasons. If we have opt out, then we believe this message is still valuable for transparency. 

Do you see any problems with this message, or did you just want to ensure it was not seen as a solution to https://github.com/dotnet/core-setup/issues/3623 (it isn't).

**Comment by dasMulli** [comment]
No, I'm strongly in favour of this message. I just opened the linked issue a few minutes later.

**Comment by livarcocc** [comment]
@AngelosP @KathleenDollard what is the wording for this message?

**Comment by KathleenDollard** [comment]
Proposed: 

"dotnet build is using a Preview version of the .NET Core SDK"

This is the most clear to me, but I hate that it starts with lowercase d

@richlander

**Comment by livarcocc** [comment]
Also, this won't affect dotnet build only. It will affect most verbs.

**Comment by KathleenDollard** [comment]
Cancel previous. 

"You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://docs.microsoft.com/en-us/dotnet/core/tools/global-json"

Two questions: 

- Is this text clear and reasonable?
- Do we define links like this, and is there a different page we should use instead. 

cc @richlander 

Which version are we trying to get this into. Is today/tomorrow our deadline? (per the no escrow email I received.

**Comment by livarcocc** [comment]
This is going in for .NET Core 2.1 Preview2 (SDK 2.1.300-preview2). The escrow email you got was for 2.1.100.
