### ISSUE TITLE
Poor error message on version mis-match

### ISSUE THREAD

**Issue by BroadSight** [dotnet/cli#8522]
## Steps to reproduce

Have an asp.net core MVC project with a reference to `Microsoft.DotNet.Watcher.Tools` version 1.0.0.

Run `dotnet watch run` on a Linux system.

## Expected  behavior

The development server starts and recompiles on source file change.

## Actual behavior

The following message is given:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.0'.
```

This message says `Microsoft.NETCore.App` when it was really `Microsoft.DotNet.Watcher.Tools` that was the wrong version. Updating the version of `Microsoft.DotNet.Watcher.Tools` to 2.0.0 allows it to run correctly.

## Environment data
`dotnet --info` output:

```
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by livarcocc** [comment]
This is by design.

The error message is indicating that you did not have the runtime version (represented by Microsoft.NetCore.App) installed that the app `Microsoft.DotNet.Watcher.Tools` required to run. `Microsoft.DotNet.Watcher.Tools` version 1.0.0 requires runtime 1.0.0. While you had the 2.0 runtime installed.

Version 2.0.0 of `Microsoft.DotNet.Watcher.Tools` targets the 2.0 runtime and so runs in your box. It was just a coincidence that the versions happened to be the same number this time.
