### ISSUE TITLE
Allow project references to be used as tools

### ISSUE THREAD

**Issue by cesarbs** [dotnet/cli#854]
Currently tools only work as package references. If I try to use a project reference as a tool, I get a "not found" error.

It would be interesting to have the option of using project references as tools in cases where there's a tool specific to a single project's build. Having to publish a separate package for the tool is cumbersome.

An example is Kestrel, which has two projects under `tools\` (`GeneratedCode` and `LibuvCopier`) that are used during the build:

https://github.com/aspnet/KestrelHttpServer/tree/dev/tools

I'd like to be able to rename those to e.g. `dotnet-kestrel-codegen` and `dotnet-kestrel-libuvcopy` and use them as tools in `src/Microsoft.AspNet.Server.Kestrel/project.json`.

**Comment by piotrpMSFT** [comment]
@cesarbs this would be quite a bit of work and I'm not sure that the benefit is sufficient. If the tool is intended for a single repo then building it and calling the executable directly seems fairly straightforward.

**Comment by aL3891** [comment]
I would also like to see this, it makes developing tools easier for one thing but it's also nice and symmetrical, it makes the system easier to understand.

i'd fine with having this post rtm though.

**Comment by tuespetre** [comment]
The local development process for a CLI tool doesn't seem very accessible without this functionality.

**Comment by brthor** [comment]
This would require some nuget changes to make happen. Why is a `dotnet run` on the tool project itself insufficient?

In our repo we pack the tool, then use a local package source during restore of the consuming project, which works nicely.

cc @emgarten @joelverhagen

**Comment by joelverhagen** [comment]
Related NuGet issue: https://github.com/NuGet/Home/issues/2469

**Comment by aL3891** [comment]
It's just added friction to developing tools, I figured since this already works for regular packages, it would be possible to do for tools as well. For me personally, its not a deal breaker, but it would be handy :)

**Comment by Antaris** [comment]
When working with a utility project like `Microsoft.Extensions.DependencyModel`, using the `dotnet run` approach doesn't appear to work because I need to tool to run in the context of another target project. So for instance, if my tool relies on `DependencyContext.Default`, this will be the context of the tool project, not the target project.

I can't find any information on debugging CLI tools in the context of a target project, but I guess it would be similar to debugging the old `CompileModule` stuff from DNX, which was to throw in a `Debugger.Launch()` in the tool and attach a debugger at that point.

Not an ideal development experience. The docs themselves could do with some more information - I'd like to see some examples of triggering other CLI tools from with our own tools, so for instance, if my tool needs the target project to build, I'd like to issue a `dotnet build`, so examples of this would be handy.

**Comment by piotrpMSFT** [comment]
Tracking this in NuGet/Home#2469
