### ISSUE TITLE
dotnet test run for a test project copied onto another machine can't find built assemblies

### ISSUE THREAD

**Issue by evil-shrike** [dotnet/cli#8555]
## Steps to reproduce
I write a Dockerfile to run my tests in a Linux container:
```
FROM microsoft/dotnet:2.0-sdk
WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "test", "--no-build", "-f", "MyTest"]
```
If I build and run a container and then run dotnet test inside it:
```
dotnet test --no-restore --no-build -f testSubstitutionPredefinedMacroShouldAddSlashIfAbsent
```
It'll fail with error:
```
The test source file "/app/bin/Debug/MyTests.dll" provided was not found.
```
MyTests.dll is already built and it's inside bin/Debug/netcoreapp2.0 folder.
But `dotnet test` skips for some reason framwork folder ("netcoreapp2.0").

I understand that I can build project inside my container. But it's actually an over-complication and absolutely unneeded in this case (I'll have to setup nuget source and so on).

## Expected  behavior
dotnet test can locate built assemblies and run tests.

## Environment data
```
root@042be2152da4:/app# dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by dasMulli** [comment]
While I am not sure about the wrong path, the output of bin/Debug/netcoreapp2.0 folder is not portable and may not run correctly on other systems, because it relies on the global package cache (+ location path) of the system and user that built it.

To run tests on a different machine, use `dotnet publish` to generate a portable output (bin/Debug/netcoreapp2.0/publish) and use `dotnet vstest MyTests.dll` to run the tests.

**Comment by evil-shrike** [comment]
@dasMulli `publish` + `dotnet vstest` work fine for me. So copying bin/Debug/{fw} wasn't a good idea probably. Thank you!
