### ISSUE TITLE
Can't download latest sdk with Chrome (Failed - network error)

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/cli#8567]
## Steps to reproduce
From https://github.com/dotnet/cli 
click Windows x64 - Installer 
Download Start 
After few seconds,  (Failed - network error)

## Environment data
`dotnet --info` output:

Product Information:
 Version:            2.1.300-preview2-008028
 Commit SHA-1 hash:  3a34dfbc51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008028\

Microsoft .NET Core Shared Framework Host

  Version  : 2.1.0-preview1-26116-04
  Build    : eeb3a84e2142aba791fe003564b8afd048c45ff9

**Comment by livarcocc** [comment]
We just point to a URL to an azure blob storage somewhere. No magic happens here. Other folks have been reporting issues with accessing the blob storage, but Azure is reporting green on their status. So, there isn't much that we can do.

The only thing I can suggest is using our CDN when this happens, but when using a CDN, you will get latest to be whatever the CDN has cached, rather than what is actually latest in storage.

The CDN url is https://dotnetcli.azureedge.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe

**Comment by tmds** [comment]
I'm seeing this also.

**Comment by livarcocc** [comment]
does the CDN URL work for you?

**Comment by vRITHNER** [comment]
Hi, Sorry for the delay
Yes. Txs for the tip.
my 2ct is you should set the CDN by default to be safe ;-)
Txs
-Vince

**Comment by vRITHNER** [comment]
wrong button...

**Comment by tmds** [comment]
> does the CDN URL work for you?

It hasn't stopped but it isn't making much progress either...

wget https://dotnetcli.azureedge.net/dotnet/Sdk/master/dotnet-sdk-latest-linux-x64.tar.gz
...
  23.7KB/s    eta 64m 13s

**Comment by livarcocc** [comment]
The reason we can't use the CDN there is because that points to the latest build. We do that by simply updating the latest files in place in the blob storage. If we used the CDN, there would be no guarantee that it would actually be picking up the latest. It would simply pick up whatever latest the CDN has cached at the moment.

This would lead to issues like, latest says it is 8000, but I keep getting 7998.

**Comment by livarcocc** [comment]
Also, to close on this. In a situation like this, I would recommend using the install script to obtain the latest CLI.

The install script will download the latest CLI by version, instead of using the latest URL. Because of that, it can and uses the CDN URL instead of the raw blob storage.

If the install script does not work for you, then comment and we can re-activate this issue. Or file a new one.
