### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.2.0.0 on empty project

### ISSUE THREAD

**Issue by Muchaszewski** [dotnet/cli#8655]
## Steps to reproduce
* `dotnet new console`
* `dotnet publish`
* `cd bin\Debug\netcoreapp2.0\publish`
* `Application.dll`

## Expected  behavior
`Hello World!`

## Actual behavior
`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

## Additional info
`dotnet run` results in correct result `Hello World!`

**Comment by BenHewins** [comment]
Check out https://github.com/dotnet/sdk/issues/1906, `dotnet publish` does not produce classic windows executables by default.

You should be able to run it as `dotnet Application.dll`

**Comment by livarcocc** [comment]
@BenHewins is correct.

By default, the application you created above is a Framework Dependent App and as such, it can run on any of the .NET Core supported platforms by simply xcopying the contents of the publish folder and executing with `dotnet application.dll`. The reason you need dotnet is because since this app can run on many platforms, there is not standard executable across the platforms.

If this does not work for you, please just comment and we can re-activate the issue.
