### ISSUE TITLE
dotnet publish manual process & impact on npm package dependencies - need review

### ISSUE THREAD

**Issue by gitfortee** [dotnet/cli#8765]
Folks, 

I need some guidance. This is not an issue actually but please help. 

I am doing manual build/publish of a dotnet core & angular 4 web application in my development server(not the local machine). I use dotnet CLI tools to do the build & publish process. These are the steps I perform at this moment.

1. Download the source code from source control - I use TFS web interface to download source code to the Development server.

2. The node_modules folder is not checked in to the source control so it is not available when the source code is downloaded.

3. Run the dotnet publish command for the Client/Angular project from the respective folder within the source code downloaded.

4. Every time i do this process, in the command output i see 'x number of packages added' which i believe is the result of npm packages being installed.

5. At this stage, I am afraid if step #4 will install a different version of dependencies than what i have in my local machine since the package.json uses semver notation for dependencies.

6. I am also uncertain of what version of the dependencies mentioned in packages.json gets installed during #4 in the Development server because i do not see the 'x number of packages added' message when i run dotnet publish from the local machine - which i understand because i already have the node_modules folder in the local machine.

7. The issues mentioned in steps #4 & #5 persists each time i perform the manual build process @ the server. Thus leaves me uncertain of what happens to my npm package dependencies as explained in #6.
8. Is there a workaround for the issues mentioned above..?

9. Does anyone have the practice of upgrading npm package dependencies for their web projects periodically?

10. Or do you set the dependencies once and never upgrade the dependencies..?

**Comment by livarcocc** [comment]
@mlorbetske @vijayrkn to comment.

**Comment by mlorbetske** [comment]
This may be due to something included in the SPA templates - @SteveSandersonMS, any ideas? I don’t believe we have logic to trigger an NPM restore in our tasks/targets that would run during build or publish, so I’m thinking this is likely from something included in the project file itself. @gitfortee is it possible to share the contents of one of the csproj files?

**Comment by SteveSandersonMS** [comment]
> At this stage, I am afraid if step #4 will install a different version of dependencies than what i have in my local machine since the package.json uses semver notation for dependencies

You are right to be concerned about that, because if your production deployments ended up with different versions of dependencies than you've tested, there's no guarantee that behavior would be consistent (no matter what SemVer says).

But the good news is that this is a solved problem. Alongside your `node_modules` directory, you'll find either `package-lock.json` or `npm-shrinkwrap.json` (depending on your NPM version). One of these should be stored in source control. It captures the exact set of transitive dependencies, ensuring that the precise same set is restored, regardless of what `package.json` allows with its wildcards.

So, assuming that lock file is under source control, the dependency resolution is deterministic and doesn't suffer from the issue you're concerned about :)
