### ISSUE TITLE
dotnet restore no longer works for VS solutions that contain a mix of SDK and non-SDK projects

### ISSUE THREAD

**Issue by DaveSlinn** [dotnet/cli#8774]
Original issue was #7294 but prior to sdk version 2.1.100 that came out last week the VS 2017 15.6, dotnet restore would only display errors for projects it didn't understand.  Now it quits altogether and as such, has broken our automated builds.

I ask again - why can't it just ignore non-SDK projects it finds in the VS .sln files?

Here is an image of the step in our build def that now stops the build:
![image](https://user-images.githubusercontent.com/18301427/37315036-14796454-261d-11e8-92fa-1f2393e5f5a5.png)

And here is an image of the build working on a build PC without the 15.6 update (and thus, using dotnet sdk v 2.1.4):
![image](https://user-images.githubusercontent.com/18301427/37315063-3cf8184e-261d-11e8-9472-063c146c48ee.png)

**Comment by livarcocc** [comment]
I am moving this to NuGet for them to take a look first.

As for why we can't ignore projects we don't know... It is because we don't know which projects we actually don't know about. For instance, natively, the CLI does not support UAP projects, however, with the addition of a PackageReference, everything works.

We don't whitelist supported projects because there is no way for that list to be authoritative.

**Comment by livarcocc** [comment]
This issue was moved to NuGet/Home#6665

**Comment by DaveSlinn** [comment]
> As for why we can't ignore projects we don't know... It is because we don't know which projects we actually don't know about. For instance, natively, the CLI does not support UAP projects, however, with the addition of a PackageReference, everything works.
> 
> We don't whitelist supported projects because there is no way for that list to be authoritative.

Makes sense. I thought it would be as simple as SDK vs non-SDK thing. Thanks for forwarding issue.
