### ISSUE TITLE
Template for "dotnet new dotnettool"

### ISSUE THREAD

**Issue by kasper3** [dotnet/cli#9060]
It would be really nice to have `dotnet new dotnettool` template for ease of development.

Current experience:

```
dotnet2.1.300-preview3-008443.exe tool install XmlSchemaClassGenerator-beta --tool-path MyDir
```

gives:

> error NU1212: Invalid project-package combination for XmlSchemaClassGenerator-beta 2.0.102. DotnetToolReference project style can only contain references of the DotnetTool type
> The tool package could not be restored.
> Tool 'xmlschemaclassgenerator-beta' failed to install.

1. What does that mean and what is it trying to tell us?
2. How to fix it? We are investigating it over at: https://github.com/mganss/XmlSchemaClassGenerator/issues/56

Does that mean we need to modify https://github.com/mganss/XmlSchemaClassGenerator/blob/7e1889fb10bbb65ea495409ae776050e502559e2/XmlSchemaClassGenerator.Console/XmlSchemaClassGenerator.Console.csproj file and add `<PackageType>DotnetTool</PackageType>`  property? Something else?

This documentation doesn't say much about it: https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility#building-tools

The error message can be improved to be more human-readable, something like: "If you are the package owner, consider adding `<PackageType>DotnetTool</PackageType>` in your project file. See documentation at https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility#building-tools".. after the docs are updated.

**Comment by dasMulli** [comment]
The idea is that you set

```xml
<PropertyGroup>
  <PackAsTool>true</PackAsTool>
</PropertyGroup>
```

in the csproj file to make it work with `dotnet tool install`.

There is also 
```xml
    <ToolCommandName>dotnet-foo</ToolCommandName>
```
in case you want to use a different executable name than the project being packed.

The error message about the package type is probably a result of the inner workings of NuGet here.. 

@KathleenDollard @wli3 I don't think this error message should be displayed. it is technically correct but not helpful for global tool authors, since it isn't suggesting anything specific to the recommended approach.

**Comment by dasMulli** [comment]
This is different than the `DotNetCliToolReference`. A "global tool" as per 2.1 tooling doesn't work as a  `DotNetCliToolReference` and the other way around.
However you can publish a 2.0 app as a global tool using 2.1 tooling (by targeting `netcoreapp2.0` in the application)

**Comment by kasper3** [comment]
@xaviergxf, I think we need to use dotnet 2.1 to `pack`: `cd myproj && dotnet2.1preview.exe pack <other-args>`. Then it can be installed using dotnet 2.1 as `dotnet tool install yourtool` and `<DotNetCliToolReference Include="dotnet-mytool" Version="1.2.3" />` on both, dotnet core 2.0 (and 2.0 cli) as well as dotnet core 2.1.

**Comment by xaviergxf** [comment]
This means i need to install vs 15.7?

**Comment by kasper3** [comment]
I think .NET Core 2.1 release candidate will be made available next week or so.

Meanwhile, I am using nightly build only on command line. In win10 powershell:

```powershell
invoke-webrequest -Out dotnet21.zip https://dotnetcli.azureedge.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.zip
Expand-Archive dotnet21.zip -Force -DestinationPath c:\temp\dotnet21\ > $null

cd c:\projects\mytool-source\
c:\temp\dotnet21\dotnet restore -s https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
c:\temp\dotnet21\dotnet pack -c release

c:\temp\dotnet21\dotnet nuget push release\mytool.1.2.3.nupkg -sk <my-api-key>
```

**Comment by wli3** [comment]
@xaviergxf @kasper3 yes, you need to target 2.1. Since only 2.1.3xx SDK can consume global tools.(no dotnet too install on lower version)

The most easy way to pack tool is by adding PackAsTool and run dotnet pack. There is a "spec" that you can use to create your own tool by "manually" put right asset in right folder structure. There is no official document yet. Meanwhile you can reference tests(or test name) in [this folder](https://github.com/dotnet/sdk/tree/master/src/Tests/Microsoft.NET.ToolPack.Tests).

**Comment by KathleenDollard** [comment]
@kasper3 
We made a decision to path through NuGet messages (with a little clean up regarding how we use them). 

This ensures we aren't hiding important information for users to debug common problems, like version mismatches and mis-configured feeds. 

We also felt that certain messages, like the one you got, should appear and be resolved by the tool author when they test their tool. Thus, the author focused message. I agree with @dasMulli that this is a less than ideal message, but it is the sensible message for NuGet to output. I do not believe we will change this for this version. In the next version, we may recognize a handful of common NuGet messages and provide an additional line of text, which would suggest the PackAsTool fix. 

@kasper3 I do not understand what you are trying to do. If you have a  DotNetCliToolReference and current users, you will need to stick with that until your users have upgraded their SDK. 

_ALSO: Due to the way runtime roll forward works, tools created for a preview will not work in the next preview, RC or RTM. They must be recompiled and republished._ 

Global Tools are different than DotNetCliToolReference in the they we just create an executable shim for your .NET Core Framework Dependent application (dll) on the path. This provides no per project version management. 

In the next version of the SDK (after 2.1.300) we hope to include repo tools and will be working on that design in the coming months. Repo tools will be a version of the current design installed per application and more closely align with todays DotNetCliToolReference tools.

**Comment by kasper3** [comment]
@wli3, this was originally a feature request (first line): It would be really nice to have `dotnet new dotnettool` template for ease of development. :)

@KathleenDollard, thanks for sharing the info on usage and version compatibility. We don't currently have users, we were rehearsing the build with 2.1 preview builds. Once RTM is out, we will rebuild the product. However, the tool which was build with 2.1 preview2, gets error:

```
dotnet xscgen --help
The required library C:\Program Files\dotnet\host\fxr\2.0.6\hostfxr.dll does not support relative app dll paths.
```

This is not happening if we build with 2.1 preview3. Seems like things are improving quite rapidly. 👍

**Comment by kasper3** [comment]
Moved to https://github.com/dotnet/templating/issues/1511.
