### ISSUE TITLE
How to include a runtimeconfig.json?

### ISSUE THREAD

**Issue by roterdam** [dotnet/cli#9126]
I made a new .NET Core app in Visual Studio 2017 15.6 and added a "runtimeconfig.json" in my root directory next to the csproj and it doesn't work.

Whenever the project is output or published some random runtimeconfig.json is stuffed there.

Here is my file contents. And the true filename is "runtimeconfig.json". I've tried myapp.runtimeconfig.json, and other variations but nothing works.

```json{
  "runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    },
    "configProperties": {
      "System.GC.Server": true,
      "System.GC.Concurrent": true,
      "Microsoft.NETCore.DotNetHostPolicy.SetAppPaths": true
    }
  }
}```

**Comment by wli3** [comment]
Hi @roterdam,
You should name your `runtimeconfig.template.json` is the correct name of the file. You can find more here https://docs.microsoft.com/en-us/dotnet/core/tools/project-json-to-csproj#runtimeoptions

And you do not need the following part. It will be generated 
```json
"runtimeOptions": {
    "tfm": "netcoreapp2.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    },
```

There is an example
https://github.com/dotnet/sdk/blob/master/src/Assets/TestProjects/AppWithLibrary/TestApp/runtimeconfig.template.json

Please reopen if you have more question

**Comment by mattiasw2** [comment]
I want to disable the server GC, since it isn't aggressive enough and ends up using 100% of the 512 Mb the machine has. The application is a small kestrel apps, reads blobs up to size 300kb, and most likely the large object heap is the reason.

However,  `` "System.GC.Server": false, ``  is ignored, how to I change that value?

I created a file called runtimeconfig.template.json and put it on the root

```
{
  "configProperties": {
    "System.GC.Server": false,
    "foobar":  true 
  }
}
```

I added the foobar stuff to make sure the template is used.

However, the result is 

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp2.1",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "2.1.1"
    },
    "configProperties": {
      "System.GC.Server": true,
      "foobar": true
    }
  }
}
```
