### ISSUE TITLE
Building a Razor Class Library project generates refs directory in the build output

### ISSUE THREAD

**Issue by kichalla** [dotnet/cli#9135]
## Steps to reproduce
- dotnet new razorclasslib
- dotnet build
- open folder `bin\Debug\netstandard2.0`

## Expected  behavior
No refs directory

## Actual behavior
refs directory is present

## Environment data
`dotnet --info` output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-rc1-008662
 Commit:    6ae1926fb0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-rc1-008662\

Host (useful for support):
  Version: 2.1.0-rc1-26423-06
  Commit:  b50a96ee38

.NET Core SDKs installed:
  2.1.200-preview-007576 [C:\Program Files\dotnet\sdk]
  2.1.300-preview3-008646 [C:\Program Files\dotnet\sdk]
  2.1.300-rc1-008662 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-rc1-30613 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.0-rc1-30661 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-rc1-30613 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.0-rc1-30661 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1-26419-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-rc1-26423-06 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

cc @nguerrera

**Comment by livarcocc** [comment]
@dsplaisted can you take a look?

@pranavkm as I think I remember some discussion about this in another issue. Not sure it was the same thing though.

**Comment by pranavkm** [comment]
So this is pretty similar to https://github.com/dotnet/sdk/pull/2133. However, in this case it looks like the problem lies in the way reference assemblies from the NETStandard.Library package are setup. 

Here's the `Reference` item from Microsoft.NETCore.App that you get targeting `netcoreapp2.1`:

```
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0-rc1-26424-03\ref\netcoreapp2.1\Microsoft.Win32.Primitives.dll
     CopyLocal=false
     ExternallyResolved=true
     FusionName=Microsoft.Win32.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
     HintPath=C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0-rc1-26424-03\ref\netcoreapp2.1\Microsoft.Win32.Primitives.dll
     ImageRuntime=v4.0.30319  
     NuGetPackageId=Microsoft.NETCore.App
     NuGetPackageVersion=2.1.0-rc1-26424-03
     NuGetSourceType=Package
     OriginalItemSpec=C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.netcore.app\2.1.0-rc1-26424-03\ref\netcoreapp2.1\Microsoft.Win32.Primitives.dll
     Private=false
     ReferenceSourceTarget=ResolveAssemblyReference
     ResolvedFrom={HintPathFromItem}
     Version=
```

Compare it to the one for a project targeting `netstandard2.0`:

```
C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\ref\Microsoft.Win32.Primitives.dll
     CopyLocal=false
     ExternallyResolved=true
     Facade=true
     FusionName=Microsoft.Win32.Primitives, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
     ImageRuntime=v4.0.30319  
     NuGetPackageId=NETStandard.Library
     NuGetPackageVersion=2.0.3
     OriginalItemSpec=C:\Program Files\dotnet\sdk\NuGetFallbackFolder\netstandard.library\2.0.3\build\netstandard2.0\ref\Microsoft.Win32.Primitives.dll
     Private=false
     ReferenceSourceTarget=ResolveAssemblyReference
     ResolvedFrom={RawFileName}
     Version=
     Visible=false
```

Notice that it's missing the `NuGetSourceType` attribute which would is what the SDK uses to filter: https://github.com/dotnet/sdk/blob/e3894a03314c567be03fae59c84a802506d9de94/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L375. Is this an issue with authoring the NS.Library package?


Here's the `Reference` item for the same reference for a

**Comment by livarcocc** [comment]
@ericstj to comment on a potential authoring problem.

Does this repro if you manually target netstandard 2.0 or 2.1?

**Comment by dsplaisted** [comment]
@nguerrera @ericstj It looks like in this case we are getting bitten by the fact that NETStandard.Library doesn't set `NuGetSourceType`.  Should we update the package to add this metadata, update the SDK to use `NuGetPackageId` instead when determining whether to copy assemblies to the ref folder, or something else?

**Comment by livarcocc** [comment]
@kichalla what is the impact of having these refs in the build output? Size?

**Comment by pranavkm** [comment]
AFAIK, it's has no impact other than size. It'd certainly be nice to get this fixed for 2.1.0 (RTM).

**Comment by livarcocc** [comment]
I ask because I am sure shiproom will ask this question when we take this bug for approval. Right now, it is costing 4mb of ref assemblies in there.

**Comment by ericstj** [comment]
> @ericstj to comment on a potential authoring problem.

No authoring problem, IMHO.  Sure NETStandard.Library may be different / special and breaking some assumptions you have, but those assumptions may be incorrect.

I see two problems with the original issue statement.

1. *Why* do you expect these not to be present?  Is it because you expect the razor compilation to be able to pull them from the packages?  If so, how is it going to do that when we add them via a targets file?

2. Does this even make any sense at all for a `netstandard` library?  `NETStandard` libraries aren't runnable things so it seems really odd to me that we'd be trying to produce build output that is used for runtime compilation...

**Comment by ericstj** [comment]
Are you agreeing or disagreeing?  Sounds to me like this just further backs the point that it doesn't make sense to do anything for libraries (except perhaps to preserve defines / compiler args / etc).

**Comment by pranavkm** [comment]
We could change the Razor.Sdk to turn off PreserveCompilationContext for library projects. But the fact that setting it isn't an unsupported scenario (nothing in the Sdk complains when you set this flag in a class library) suggests that this is an issue either with the Sdk not correctly filtering out these assemblies or with the authoring of the package.

**Comment by ericstj** [comment]
Why do you say that?   See point number 1 above.

**Comment by pranavkm** [comment]
We had a chat about this and the plan is to turn off `PreserveCompilationContext` in the Razor.Sdk for class library projects. We don't fully very confident in making this change for 2.1 since we don't have enough test coverage for this, the plan is to address it as part of 2.2. I'll file a separate issue to see if want to consider addressing the extra refs in a netstandard targeting project with PreserveCompilationContext=true in the future.
