### ISSUE TITLE
Can't invoke global tool in bash

### ISSUE THREAD

**Issue by matkoch** [dotnet/cli#9208]
## Steps to reproduce
Install a global tool.

## Expected  behavior

Global tool should exist.

## Actual behavior

```
root@f43f17fa565a:/# dotnet tool list -g
Package Id           Version      Commands
------------------------------------------
nuke.globaltool      1.0.0        nuke
root@f43f17fa565a:/# bash
root@f43f17fa565a:/# nuke
bash: nuke: command not found
```

Everything works inside Windows.

## Environment data
```
root@f43f17fa565a:/# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008530
 Commit:    822ae6d43a

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300-preview2-008530/

Host (useful for support):
  Version: 2.1.0-preview2-26406-04
  Commit:  6833f3026b

.NET Core SDKs installed:
  2.1.300-preview2-008530 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by livarcocc** [comment]
This is a scenario that is validated very frequently by our team and lots of us actually use bash for our daily development.

Can you share more details about your environment that may shed a light on why this is happening to you?

How did you install the CLI? After installing it, did you restart your shell?

@peterhuene @wli3 what other information do we need to investigate this?

**Comment by peterhuene** [comment]
Hi @matkoch.  Can you confirm that `~/.dotnet/tools` is on your `PATH` environment variable?

**Comment by matkoch** [comment]
I actually tried this twice. One time in the docker image *microsoft/dotnet:2.1-sdk*, another time on macOS (but don't have the exact version right now). I've restarted the terminal in both cases (also can be seen in what I've pasted).

**Comment by matkoch** [comment]
Oh dear.... tried this one more time... it actually says that it's not on the PATH during install. That green text made me overlook everything else. Maybe you can make this a warning?

**Comment by peterhuene** [comment]
I'll see what we can do about colorizing this to make it stand out better.  Thanks for the feedback!

**Comment by matkoch** [comment]
But also let me ask, why this behavior should be different on Windows? I mean why do you put `"C:\Users\user\.dotnet\tools\nuke.exe` on PATH on Windows, but not `~/.dotnet/tools` on UNIX ?

**Comment by peterhuene** [comment]
Generally if you install the SDK through anything but the `.tar.gz`, the installer / package will attempt to modify your profile to automatically add it to the path.  This is what happens on Windows for the `.msi`.

The docker image untars the `.tar.gz` to install the SDK, so it should manually add `/root/.dotnet/tools` to the PATH for this to automatically work.

**Comment by matkoch** [comment]
I need to check what happened on macOS, because there it wasn't working too. And as for the docker image. I'm not sure, but as it's a _dotnet_ image, I would really assume that this is already done, or not?

**Comment by peterhuene** [comment]
For the OSX installer, it should work.  Let me investigate.  I'll reopen this issue for now.

**Comment by wli3** [comment]
@matkoch you need to restart you session as the output suggested. (Allow ~/.bash_profile to take affect).

But we do need to make sure our docker image has PATH exported already

> But also let me ask, why this behavior should be different on Windows and UNIX? I mean why do you put "C:\Users\user\.dotnet\tools on PATH on Windows, but not ~/.dotnet/tools on UNIX ?

Because these OS hands PATH differently

Windows
The shim will be stored under %USERPROFILE%\.dotnet\tools\. The path will be added to env:PATH during the first run in registry

Linux
The shim will be stored under $HOME/.dotnet/tools/. The path will be added to a new file under /etc/profile.d during first run under the installer

macOS
Similar to Linux, the shim will be stored under ~/.dotnet/tools/. However /etc/profile.d is available to macOS. A file under /etc/paths.d will be added to achieve the same result at the same timing.

**Comment by peterhuene** [comment]
@wli3 Using the 2.1.300-RC1 macOS installer, I don't see `/etc/paths.d/dotnet-cli-tools` created.

**Comment by peterhuene** [comment]
@livarcocc we have a regression here.  The native installers for OSX and Linux aren't properly adding the tools directory to `PATH`. 

This was caused by https://github.com/dotnet/cli/pull/8886/commits/19090744cb20c1e398555a2fdf47565c1167537e#diff-33264b5c87280447b56340237303e82dR12.  The changes in this PR included a no-op sentinel when running the first-run experience from the native installer.  It is modeled after the other no-op sentinel objects.  However, unlike the other ones, the tool path sentinel should return as *not existing* to cause the tool path to be added, but have a no-op create to prevent the sentinel file from being created for the root user.  Thus the fix is to change this line to return false.

**Comment by matkoch** [comment]
Thanks everyone!
