### ISSUE TITLE
Why so many SDKs?

### ISSUE THREAD

**Issue by 717009629** [dotnet/cli#9256]
![image](https://user-images.githubusercontent.com/16289643/39903916-11a30644-5508-11e8-8b61-f9fdd13c57f6.png)

Why they are coexist？ Not  Cover upgrade

**Comment by livarcocc** [comment]
The SDKs are built to work SxS. You can have as many as you want, this way, you can pin as SDK on a particular repository to a version while another repository is targeting a different version.

We have another issue open where we are considering doing a ref count on our MSis, so that in VS, we can uninstall an older VS installed SDK that is being replaced by a new one.
