### ISSUE TITLE
Not able to use dotnet build after converting net471 class library from packages.config to packageReference

### ISSUE THREAD

**Issue by SjoerdWesterhof** [dotnet/cli#9334]
## Steps to reproduce
Create a net471 framework class library
Reference a nuget package like Xunit
Create a test that runs and passes
running dotnet build results in a successfull build
Convert packages.config to PackageReference by using context menu is VS2017
running dotnet build results in a successfull fails that is cannot resolve references like 
"The type or namespace name 'Xunit' could not be found"

## Expected  behavior
That i am able to keep using dotnet build command for net471 project after migration

## Actual behavior
have to use msbuild to build solution

## Environment data
`dotnet --info` output:

.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

**Comment by dasMulli** [comment]
The CLI doesn't really support building classic csproj files.
It worked for packages.config projects because they contain everything that's needed for the build and it works as long as the build doesn't depend on features only available in the full framework version of MSBuild.

The VS installation has Microsoft.NuGet.props / Microsoft.NuGet.targets which do the work of adding dependencies from packages to the build. They don't exist in the CLI since different targets are brought in via its `Microsoft.NET.Sdk` SDK.

**Comment by SjoerdWesterhof** [comment]
So can i use the new csproj format for a net471 console app? I'm asking since i am using the new csproj format for an ASP.NET Core projecten running on net471?

**Comment by SjoerdWesterhof** [comment]
Thanks for your response. So how can i start an console app running on net471 with new csproj format?

**Comment by dasMulli** [comment]
Yes.

You could also create an ASP.NET Core App, and edit the csproj to change `TargetFramework` from `netcoreapp2.0` to `net471`.

You then have to remove the `Microsoft.AspNetCore.All` package (you can delete it in the csproj file as well) and add the individual NuGet packages you need - which means picking packages from the dependencies of https://www.nuget.org/packages/Microsoft.AspNetCore.All/2.0.8 until everything compiles again.

**Comment by SjoerdWesterhof** [comment]
Is this what i a supposed to be doing and supported? Or do you consider this to be a workaround?

**Comment by dasMulli** [comment]
Depends on what you want to do, my specific instructions are for getting asp.net core stuff to work on net* frameworks.
If you just want a console app, you can start from the console app .NET Core template and also change `TargetFramework` to `net471` (the project properties dialog won't offer to switch between .NET Core and .NET Framework).

@livarcocc can probably tell you what "supported" is. May be a difference between "it works and if there are bugs they will be fixed at some point" and "microsoft support will help you if you have a paid support contract".

**Comment by SjoerdWesterhof** [comment]
I'm using dotnet CLI. to build my solution on the build server. My solution is an ASP.NET Core application running on net471 with a majority of netstandard2.0 class libraries. There is however one .NET Desktop class library for using XUnit tests.
Until the PackageReference change i was able to compile this solution using dotnet cli. For now it seems the best option is building it using the  Build Tools for Visual Studio 2017 using MSBuild.exe or taking the actions you described. Since i read VS2017 is also using MSBuild.exe, i'm considering the former. This was my code gets compiled the same way by my local machine and the build server.

**Comment by dasMulli** [comment]
Ah if it is only about the test class library, you can also use the new SDK format for it..
e.g. create a .NET Core xunit test project and - as with asp.net - change the `TargetFramework` to `net461` instead of `netcoreapp2.0`. 

This template will also set up all the necessary bits to run the tests using `dotnet test` or `dotnet xunit`. (e.g. `dotnet test --logger trx` to generate trx files for use in TFS / VSTS builds or `dotnet xunit -xml results.xml` for classic xunit format)

**Comment by SjoerdWesterhof** [comment]
Ok thanks, i'll give that a try first
