### ISSUE TITLE
--release switch as a shortcut for -c Release

### ISSUE THREAD

**Issue by dasMulli** [dotnet/cli#9351]
Since most projects will only ever use the `Release` and `Debug` configurations, I suggest creating shortcut switches to avoid typing them out in full on the console:

`--release` shall be allowed everywhere `-c Release` is currently allowed.
similarly, `--debug` can be a shorthand way of specifying `-c Debug`.

Benefits:

* Faster to type
* Completion support
* Release configuration is commonly needed
* Typo mistakes are easy to make, especially since casing differences can lead to confusing build errors on linux (`-c Release` vs `-c release`).

Does this seem reasonable? Any feedback?

**Comment by NickCraver** [comment]
While I see the appeal, and do want Release promoted (especially for package builds), I would argue since Release is one on `n` (`n` being infinite) configurations, this is a bad cardinality exchange. The first question I see: "why isn't there a `--debug`?"

While *most* projects I agree only use `Release` and `Debug`, the number that use beyond that is very far from trivial. I wouldn't add the overload for this, just as MSBuild itself has never added anything specifically for release either.

I do disagree with `Debug` being the silent default for `dotnet pack` and such, though. However, I think those are better handled by requiring a `-c` argument and specific configuration rather than having a silent default, rather than making `--release` an easier-to-type one since it does nothing to really solve the most problematic cases (leave it off entirely), IMO.

**Comment by dasMulli** [comment]
I agree that it makes understanding the (msbuild) configuration system harder since it tries to hide the complexity involved.

My goal is to help the 90% use case where I want to teach people to do a `dotnet publish --release -r linux-x64 -o /my/outdir`.
This is similar to how `ng build` vs `ng build -prod` behaves.

I believe that once you get into build authoring and introduce more configurations, you are more likely to script your build / cli usage and the CLI's options will become less important.

Apart from that: I'm trying to remove additional configurations from existing projects since most of them have only been created for web.config transforms or selecting between config files. ASP.NET Core shifts focus onto configuring at run-time rather than build time. .NET 4.7.1+ makes this possible as well through config builders (https://dasmulli.blog/2018/01/21/use-appsettings-json-and-environment-overrides-in-classic-asp-net-apps/)

**Comment by NickCraver** [comment]
IMO, `publish` is the same case as `pack`. Anything that's for-end-user output I'd argue should require the `-c` argument. It doesn't tie anything to a specific subset of builds (where many may exist), but does enforce *having to choose*, which is the larger issue IMO.

Think about your current issues, is it because they're mistyping `-c Release`, or because they're not specifying a configuration at all? From what I've seen (admittedly anecdotal as well), it's almost always the latter. I'd love to see that issue more directly addresses, rather than papering over it a bit in a way that still side-steps the root of the problem.

**Comment by svick** [comment]
> Completion support

Note that `-c` does have completion support: if I type `dotnet publish -c R<tab>`, it completes to `dotnet publish -c RELEASE`.

Though it doesn't understand custom configurations, [`DEBUG` and `RELEASE` are hardcoded values](https://github.com/dotnet/cli/blob/6f6f28d/src/dotnet/CommonOptions.cs#L55).

**Comment by dasMulli** [comment]
> dotnet publish -c RELEASE.

That's actually not a very good casing default :( (https://github.com/dotnet/sdk/issues/375 https://github.com/dotnet/cli/issues/8920), I'll see to get a PR out..

**Comment by KathleenDollard** [comment]
If we supported -c [R|r|D|d] and tab completion, would that be adequate?

**Comment by dasMulli** [comment]
Do you mean completing `-c re[TAB]` into `-c Release`? that would be cool.

**Comment by kasper3** [comment]
Since there are all the available tools, can it scan the solution file to get the available configs? Lets say a solution has `Debug`, `Release` and `RelWithDebInfo` configurations defined in SLN file, typing `-c r<TAB><TAB>` should cycle between `Release` and `RelWithDebInfo` for that solution.

**Comment by KathleenDollard** [comment]
I think we should work to solve tab completion problems (including the goals of completing configurations and target frameworks) to solve this. 

I'm not convinced (yet) that this justifies an additional switch. 

@dasMulli can we move to resolving this issue?

**Comment by dasMulli** [comment]
Yes since the overall feedback was negative and we identified that we rather want to see better completion logic, let's resolve this.

Meanwhile, I've been trying to find places that had non-default `Release` capitalisation.
https://github.com/dotnet/cli/pull/9354, https://github.com/dotnet/dotnet-docker/pull/562, https://github.com/dotnet/docs/pull/5704

**Comment by dasMulli** [comment]
Not sure where to best track completion though. Completing capitalisation correctly for suggestions may need to go into https://github.com/dotnet/CliCommandLineParser but @kasper3's suggestion of evaluating the completion values from the csproj file may need things both there and here (if I'm not mistaken).

**Comment by dasMulli** [comment]
PR is out to complete `-c` based on the project file: https://github.com/dotnet/cli/pull/9788
