### ISSUE TITLE
Guidance on running dotnet [??????.dll] on linux-based shared hosting platforms 

### ISSUE THREAD

**Issue by las3r** [dotnet/cli#9405]
I'm building a solution for a shared hosting management system where server owners can give their clients the ability to run .net core web apps as opposed to PHP+MySQL hosting.

1. A server owner creates a hosting account (just like with every other hosting provider) for an end-user.
2. End-user creates a dotnet mvc app "HelloWebApp" on his local machine with VS2017
3. End-user proceeds to 'publish' his solution through VS2017 using FTP
*(so far so good - this is where my issue starts)*

From this point there's an issue, as the hosting server does NOT know what dll to start. A publish results in one or more binary (.dll) files and the hosting platform is unable to know which dll to start with `dotnet [filename].dll`. In this case the end-user is in control, as he can easily deploy 3 apps in succession with different names. I need a way to know which .dll is the one containing the main application.

The only thing really identifying the correct `filename.dll` in this case is the `web.config` file. Is there a way to run `dotnet run` based on the web.config? Or should I look for another way to get the right dll file to run?

**Comment by dasMulli** [comment]
A workaround would be to look for the `.runtimeconfig.json` and use the corresponding DLL (maybe  with a fallback to use the newest DLL if you find multiple runtimeconfig+DLL).

At the moment, there is no equivalent to web.config setup for any type of hoster (I assume you are not using IIS).
Am I right in assuming that you also don't want end users to know which OS you are using or don't want them to make assumptions about it? (enabling `.exe` for win and executable files for *nix is currently being worked at but that requires knowledge about the target system's OS / architecture).

In theory, users could also upload multiple applications into the same directory, which may or may not work (interfering DLL versions..)

Do you also allow Java systems? They have a similar problem since you'd need to select a class for an entry point unless there is a MANIFEST file in a jar describing the jar's main entry point. There isn't an equivalent for .NET's "just put a bunch of DLL/EXE files into a directory".

Do you have any kind of SDK or build tools you make available to users?

**Comment by las3r** [comment]
Right now I have a working implementation with `inotifywait` with the create/write-end events looking for changes with the web.config file. If it has changes, it will kill the running dotnet app and restart it with the new dll specified in the web.config. So this file (even although it doesn't do anything on linux) works for me in the current situation, but it feels a bit tacky.

In theory people would be able to upload multiple applications in the same folder, but we're only watching the hosting folder root for web.config. Even with multiple applications there'd be only a single web.config (meaning 1 dll definition).

We do not allow java, and we do not allow any build tools or anything. They use VS2017 to deploy their application using FTP.  They know the OS (it's a shared hostingserver with a hosting control panel, they can see most of the information you mentioned).

**Comment by livarcocc** [comment]
I don't believe there is anything that we can really do here. So, I am going to close this issue.

I would just like to re-iterate that deployment multiple applications flat into the same folder is dangerous and applications can be broken when that happens due to overwritten and not matching assemblies.
