### ISSUE TITLE
VBCSCompiler service remains in memory after `dotnet build` and consumes 100% of 1 CPU core and a lot of memory on Ubuntu

### ISSUE THREAD

**Issue by NikolayPianikov** [dotnet/cli#9434]
## Steps to reproduce

- create a temp directory with long full name (~>100 symbols)
- set the environment variable `TMPDIR` as full path to this temp directory
- build some dotnet project

⚠️ the memory runs out quickly and only the computer restart helps in some cases

[Sample repo](https://github.com/NikolayPianikov/dotnetcli_tpmdir_issue)

## Expected behavior

At least do not consume CPU and memory so hard

## Actual behavior

The process like

`/usr/share/dotnet/dotnet/usr/share/dotnet/sdk/2.1.300/Roslyn/bincore/VBCSCompiler.dll -pipename: xxx.F.DCgnN5efPzMYmbzHdZB6DrTe`

consumes 100% of 1 CPU core and a lot of memory

## Environment data

dotnet --version: 2.1.300
Ubuntu 18.04 LTS

**Comment by zone117x** [comment]
Surprised to see this is a core problem with the dotnet cli. Definitely thought it was a bug with the Team City runner. 
Any idea why this isn't being reported much more frequently? Is the pipename/service archecture that the Teamcity buildrunner use a unique method? 

Since this will probably take a while to get fixed and stable, I'm very interested in any workarounds. I tried setting /nodereuse=false in my build steps but the process spawns and sticks anyway.

**Comment by livarcocc** [comment]
You can turn off the VBCSCompiler by setting UseSharedCompilation=false. You can do that as a parameter to the build command, you can set that as a MSBuild property in your projects or you can set that as an environment variable.

You can also use the `dotnet build-server shutdown` command to stop any long running servers spawned by the CLI once your build is done.

I will also move this issue to Roslyn to be investigated there.

**Comment by livarcocc** [comment]
This issue was moved to dotnet/roslyn#27566
