### ISSUE TITLE
Allow pass through arguments to backend compiler

### ISSUE THREAD

**Issue by tijoytom** [dotnet/cli#953]
Trying to compile some unsafe code and hit this error from c# compiler

tijoytk@QUARKBOSON G:\tijoytest
> G:\cli\artifacts\win7-x64\stage2\bin\dotnet compile
Compiling tijoytest for DNXCore,Version=v5.0
G:\tijoytest\Program.cs(37,35): error CS0227: Unsafe code may only appear if compiling with /unsafe

Now i need to figure out how do i pass it to CLI  or what's equivalent command in CLI. Given that json options are not well documented , i think it's better to provide and option to pass argument directly to the backend compiler(c# ,vbc.exe etc) 

some thing like  "dotnet compile \`\unsafe\`  , the part with-in tilde will be passed along to c# compiler as such..

**Comment by tijoytom** [comment]
dotnet compile ``\unsafe``

**Comment by zach-folwick** [comment]
I also have some unsafe code to compile in linux.  At the moment we just execute dotnet publish and run the executable, but it appears we'll need to do `dotnet compile --unsafe` and *then* `dotnet publish` ?  Some documentation on using dotnet with unsafe code would be nice.

**Comment by davidfowl** [comment]
The json options are totally documented and you should set the allowUnsafe compilation option. It shouldn't be a command line argument.

**Comment by zach-folwick** [comment]
@tijoytom after some project.json sleuthing thanks to @davidfowl's input, I found the following:

{
         ....
     "compilationOptions": {
               "allowUnsafe": "true"
      }
    ....
}

thanks @davidfowl !

**Comment by tijoytom** [comment]
@zach-folwick @davidfowl  I think it's not just about the unsafe option , the question is more "why do I have to figure out (after some project.json sleuthing) the json option for CLI when I know what I need to pass to the c# compiler". After all the error message from C#  compiler makes it very clear and if I was invoking the c# compiler directly it's no effort for me to add /unsafe to the command line. C# ( Vbc.exe) has been around for a while and most .NET developers are familiar  with the command line options. Also I was not proposing another command line option for compile , but the ability to pass along anything to backend compier. ie anything between the tilde will be passed as such to backend compiler

**Comment by tijoytom** [comment]
@zach-folwick @davidfowl btw, "allowUnsafe": "true" in project.json doesnt seem to work.

**Comment by davidfowl** [comment]
> he question is more "why do I have to figure out (after some project.json sleuthing) the json option for CLI when I know what I need to pass to the c# compiler"

Because with *any* toolchain coordinating a system or tools you'd have to do the same. You just need to learn how the new system works. With msbuild it was a property in the csproj file. With `project.json` it's a property in  the `compilationOptions` section (and it does work).

> After all the error message from C# compiler makes it very clear and if I was invoking the c# compiler directly it's no effort for me to add /unsafe to the command line. C# ( Vbc.exe) has been around for a while and most .NET developers are familiar with the command line options.

I'd actually like to see you invoke the C# compiler directly to build *any* non trivial project :smile: . It's extremely cumbersome as the tool is very low level (which is why build systems coordinate tools like that). 

It's unfortunate we can't control errors like that from flowing out of the system and translate them into useful info (like specifying `allowUnsafe: true` in the project file). We should think about that a little bit.

> Also I was not proposing another command line option for compile , but the ability to pass along anything to backend compier. ie anything between the tilde will be passed as such to backend compiler

I think that has value, but not as a command line argument, it should be persisted in the project file so that builds are repeatable without knowing all of the command line arguments you need to pass.

**Comment by tiomke** [comment]
@tijoytom try  `"allowUnsafe": true`

**Comment by hjalle** [comment]
And from RC2 (I believe) compilationOptions have been renamed to buildOptions, so instead: 
"buildOptions": {
"allowUnsafe": "true"
}

**Comment by piotrpMSFT** [comment]
The team is actively working on enabling [MSBuild](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) and the component affected will be superseded by the new project system, so I am closing this issue.
