### ISSUE TITLE
dotnet-publish --no-build produces assembly with versions different than build output

### ISSUE THREAD

**Issue by Cobster** [dotnet/cli#9581]
During migration from netcoreapp2.0 to netcoreapp2.1 I found that the behavior of dotnet publish --no-build behaves differently.  

## Steps to reproduce

Create ASP.NET core web app.

**Website.csproj**
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <Version>0.0.0</Version>
    <FileVersion>0.0.0.0</FileVersion>
    <InformationalVersion>0000000000000000000000000000000000000000</InformationalVersion>
  </PropertyGroup>

   ...
```
Run build from command line and override the versions
```
dotnet build -c Release /property:Version=1.2.3 /property:FileVersion=1.2.3.4 /property:InformationalVersion=abcdef12
```
This produces an assembly with the correct overridden version values.

Next run publish
```
dotnet publish -c Release --no-build
```

## Expected  behavior
The assembly that is output from running `dotnet publish --no-build` has the same version numbers as the output from `dotnet build`.

## Actual behavior
A different assembly is produced, that contains the versions as specified in the csproj file.  This is different than what occurred when targeting netcoreapp2.0, even when .NET Core SDK 2.1.300 is installed.

## Environment data
`dotnet --info` output:

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by peterhuene** [comment]
So the assembly produced is identical from the previous build operation and contains the same assembly attributes, as one would expect.

However, the `.deps.json` file that was produced is not the same as the from the build output.  It looks like it was recreated vs. copying the one from the build:

```
25c25
<       "repro/1.2.3": {
---
>       "repro/0.0.0": {
3154c3154
<     "repro/1.2.3": {
---
>     "repro/0.0.0": {
```

@dsplaisted @nguerrera do you know why this might have changed in 2.1 when it seems that we must have copied the deps file previously (otherwise, how would it generate with the same version numbers since the global properties came from the build and not the publish?).

**Comment by nguerrera** [comment]
We generate the deps file for publish separately from the one for build.

I'm a little confused about which version this worked in previously. Wasn't 2.1.300 was the first version with publish --no-build (apart from ancient project.json-based pre-1.0 previews)?

**Comment by peterhuene** [comment]
You're correct.  I forgot `--no-build` wasn't in 2.0.

@Cobster Could you please describe how this worked previously?

**Comment by Cobster** [comment]
Indeed the 2.0 SDK does not provide the `--no-build` option.  I'm seeing a difference in functionality when using the 2.1 SDK to publish a project targeting `netcoreapp2.0`, and publishing a project targeting `netcoreapp2.1`.  

I created repository with a simple example of my use case https://github.com/Cobster/dotnet-cli-9581 ...however this example is **not producing the issue** as originally described.  I'll re-review my automation code where I first encountered this problem.  My hope is that I simply did something wrong. And if that's the case I apologize for taking your time on this issue.

**Comment by peterhuene** [comment]
I'll take a look at your repro shortly.  Also, no need for apologies as we're very grateful for your time to help improve .NET! 😄

**Comment by Cobster** [comment]
I've reviewed the automation code in the other project, and it is still experiencing the issue as described.
There is a difference between my project with the issue and the example repository.  My project with the issue originally targeted `netcoreapp2.0` but was later migrated to target `netcoreapp2.1`.

I'll go ahead and attempt the same migration in the example repo project that targets `netcoreapp2.0` to see if I can get the same behavior to occur.

**Comment by Cobster** [comment]
I tried many things to try and reproduce this issue in the example repository, but I was unsuccessful.  However, in the project experiencing the issue I deleted the `obj` folder, then ran a fresh build and publish.  Then everything started working as expected.  

I believe that my CI server is still producing this issue. I'll copy the contents of the `obj` folder and see if I can find the root cause.

**Comment by mbashov** [comment]
`dotnet publish --no-build` can trigger recompilation because of [the file with assembly attributes](https://github.com/Microsoft/msbuild/blob/b3f9eeab651c92bade6e4f64d11b59aa39e149cb/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3316,L3337) generated by MSBuild in [`/tmp` directory](https://github.com/Microsoft/msbuild/blob/b3f9eeab651c92bade6e4f64d11b59aa39e149cb/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3305). If, for example, `dotnet build` and `dotnet publish --no-build` are run in different containers, it is not obvious that those containers must share `/tmp` directory for `dotnet publish --no-build` to work properly.

The target chain leading to recompilation on `dotnet publish --no-build` i've seen was:
- `Publish`
- `_PublishNoBuildAlternative`
- `_RazorPrepareForPublish`
- `RazorCompile`
- `PrepareForRazorCompile`
- `RazorGenerate`
- `PrepareForRazorGenerate`
- `ResolveTagHelperRazorGenerateInputs`
- `Compile`
- `CoreCompile`

The file in `/tmp` gets regenerated by target `GenerateTargetFrameworkMonikerAttribute` triggered by `BeforeCompile`.

This recompilation is very nasty. The generated assembly can be different from the originally built. For some reason, it generates an assembly without embedded `.resx`, see [example here](https://gist.github.com/mbashov/26953f17d110186b02f7943f01438f81)

I think `dotnet publish --no-build` must fail if recompilation is required.

**Comment by nguerrera** [comment]
The way nobuild is supposed to work is that the compile target is not invoked. It is separate from whether Compile would be up to date when invoked. But it looks like razor publishing is pulling in Compile separately during prepare for publish? If so that dependency would would also need to be short circuited when NoBuild is set.

**Comment by nguerrera** [comment]
@rynowak

**Comment by dasMulli** [comment]
>  If so that dependency would also need to be short circuited when NoBuild is set

If that's going to be a larger change, please consider renaming to `NoBuildOnPublish` / `PublishWithougBuilding` or similar since NuGet already claimed `NoBuild` for packing. (and there's a bug with `GeneratePackageOnBuild` together with `dotnet publish`).

**Comment by nguerrera** [comment]
I still want to investigate if we can make it work while keeping NoBuild for both. When using msbuild instead of dotnet, it is much friendlier to say NoBuild across operations. Plus, breaking change of not using NoBuild.

**Comment by nguerrera** [comment]
But, excellent point, this should be considered before we spread NoBuild anywhere else! Thanks.

**Comment by nguerrera** [comment]
Yes, that's a good idea.

**Comment by rynowak** [comment]
@nguerrera - what exactly is the action item for Razor - to honor `NoBuild` and make sure we're no-oping in that ask?

/cc @pranavkm

**Comment by pranavkm** [comment]
Tracking RazorSdk specific work via https://github.com/aspnet/Razor/issues/2496

**Comment by dasMulli** [comment]
> I still want to investigate if we can make it work while keeping NoBuild for both.

I realise now that we've had this conversation before but I only remembered half of it.

**Comment by peterhuene** [comment]
@livarcocc bar check for 2.2.1xx.  From our side, this would be adding a target that check is conditional on `'$(NoBuild)'=='true'` and runs before `CoreCompile`; its sole task would be to emit an error informing the user that a build should not occur.

The original bug from this issue has been addressed for 2.2 by the Razor team.

**Comment by livarcocc** [comment]
Moved to 3.0

**Comment by nguerrera** [comment]
> I realise now that we've had this conversation before but I only remembered half of it

https://github.com/dotnet/cli/issues/9656 for future cross-reference
