### ISSUE TITLE
Namespace support for Global Tools?

### ISSUE THREAD

**Issue by stefandevo** [dotnet/cli#9600]
Will there be namespace support for global tools just like NPM has added?
When this feature gets popular the command names will have duplicates soon, so maybe a namespace will give it a more unique approach?
Like `@stefandevo/my-nice-tool` ?
Any thoughts?

**Comment by wli3** [comment]
@KathleenDollard

**Comment by KathleenDollard** [comment]
I think this would be awesome - I may think about naming challenges more than is healthy ;-)

But, I think we start ahead of where npm started because of our support for multiple feeds and that we install on package name, not tool name. So, I think `dotnet tool install` should be able to technically manage the popularity we hope to achieve. (IOW, the repo already resolves correctly)

@stefandevo: Are you also interested in resolution of tool names after installation, and do you have any scenarios? Times that you'd have two different tools, from two different authors (based on the npm pattern) with the same name. 

We're still designing repo tools, and have at least specifying versions on our radar. I'd love to hear more about name conflict scenarios people anticipate or have seen in npm. 

We opted for the super simple model for global tools, which means we don't currently have a way to control either then "namespace" or the version.

**Comment by dasMulli** [comment]
I believe there are some overlapping concerns with nuget.org's name model here.

Nuget.org recently introduced [registered prefixes](https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation) to make sure a person is the only one allowed to upload packages with that prefix. In my opinion, the bar to register a prefix is way too high and just opening an account with nuget.org should be enough for at least the username prefix (e.g. I should be the only one able to create a new `DasMulli.FooBar` package), but that's another discussion to have.

If nuget.org then restricted "simple name packages" (made-up term) like "dotnet-foobar" / "FooBarTool" etc. by default required some form of namespacing, this may help increasing the perceived trustworthiness of packages (personally, I'm frightened by a lot of packages on NuGet by authors without profiles and official sounding package names).

@stefandevo you could also upload that package as `stefandevo.compress-png` and then use `dotnet tool install -g stefandevo.compress-png`. Does that feel right or bad?

**Comment by stefandevo** [comment]
@dasMulli you are correct, that would be a solution by having the same packageId as toolname and use a prefix in both. I just was thinking of a way of "forcing" this for the global tools in a way that now with this new feature and relative small number of packages we start in a good way of doing this. Within a couple of months will we be facing lots of duplicate toolnames in my opinion and I am not sure how this is currently handled? What happens when you install the nuget package `Owner1.CompressPng` with toolname `CompressPng` and then package `Owner2.CompressPng` also with toolname `CompressPng`. What will happen and if they could be install both, how to execute the tool?

**Comment by KathleenDollard** [comment]
@dasMulli Have you filed your suggestion on having usernames be registered prefixes by default. I think it's a different feature precisely because they set a bar for having a registered prefix. So, there might be a slight variation, but being able to specify that a package should come from x easily seems a good idea

**Comment by KathleenDollard** [comment]
@stefandevo If you install two tools with the same tool name, you will get an error on the second saying it cannot be installed.

**Comment by dasMulli** [comment]
Just opened https://github.com/NuGet/Home/issues/7088, will add some more reasoning to it later.

**Comment by livarcocc** [comment]
I am going to close this issue as the situation seems to be handled.
