### ISSUE TITLE
dotnet build with multiple constants

### ISSUE THREAD

**Issue by HeinzmeierDornbuschFeldhausen** [dotnet/cli#9602]
Hello,

I have a newly created f# netcoreapp2.1 console app with a vanilla fsproj file. I want to pass multiple constants to dotnet build. This works and the constants are validated when I run the program:

`msbuild /p:DefineConstants="HELLO;WORLD"`

... but this fails with MSB1006 errors:

```
dotnet build /p:DefineConstants="HELLO;WORLD"
dotnet build /p:DefineConstants=HELLO;WORLD
dotnet build /p:DefineConstants=\"Hello,World\"
dotnet build /p:DefineConstants=\"Hello;World\"
dotnet build /p:DefineConstants='Hello;World'
(...)
```

Is there a way to make this work with dotnet build cli? Thanks for the help.

## Actual behavior

MSB1006 "property not valid..." is thrown

## Environment data

- dotnet sdk 2.1.300
- win7-x64

**Comment by peterhuene** [comment]
Hi @HeinzmeierDornbuschFeldhausen,

Could you try `dotnet build /p:\"DefineConstants=HELLO;WORLD\"`?  Note the backslashes around the double quote characters, which escapes them down to MSBuild.  MSBuild uses the double quotes around the property value to treat characters like `;` as literal values, rather than the command-line syntax to define multiple properties in a single option (e.g. `/p:First=Foo;Second=Bar` sets `First` to `Foo` and `Second` to `Bar`).

Thanks!

**Comment by peterhuene** [comment]
@HeinzmeierDornbuschFeldhausen I'm going to close this issue for now; please re-open if using the escaped quotes above does not have the desired effect.

Thanks for reporting this issue!
