### ISSUE TITLE
File systems with second level granularity cause random failures in Builder tests

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/cli#965]
We've seen several intermittent failures in `Microsoft.DotNet.Tools.Builder.Tests` today. Taking a brief look at sources, it seems there is at least a configuration issue.

https://github.com/dotnet/cli/blob/master/test/Microsoft.DotNet.Tools.Builder.Tests/IncrementalTests.cs#L17

Notice that the test name for the derived class is different than what is being passed to the base class. 

Since we've seen several PRs failing this test intermittently, we're not blocking on failures at the moment.

//cc @bbrthor

**Comment by cdmihai** [comment]
This happens only on OSX because HFS+ has second level timestamp granularity. Because Builder used the strict (greater than operator) to check for stale outputs, it caused false negatives incremental checks when an input file is changed within the same second as the previously built outputs.

The solution is to use >= when comparing the timestamps of inputs and outputs.

**Comment by brthor** [comment]
@cdmihai Might it be more reliable to use a hash rather than timestamp of the file?
I don't know how that would impact performance, but I think it's worth thinking about.

**Comment by cdmihai** [comment]
I agree. Hashing is superior to timestamps. CLI vNext will use hashes. :)
