### ISSUE TITLE
.Net Core App on PlayStation 4

### ISSUE THREAD

**Issue by alan1010ten** [dotnet/cli#9746]
How to run .Net Core App on PlayStation 4?

**Comment by peterhuene** [comment]
Hi @alan1010ten.  We don't currently have instructions or support running .NET Core on Playstation 4.

Running Linux on a PS4 isn't officially supported (as far as I'm aware), but if you are able to run Linux on your PS4, you may have some luck getting our [generic Linux x64 tarball to install](https://www.microsoft.com/net/download/dotnet-core/2.1).  Also depending on the distro that you're running, there's even a chance it might be available as a package from your distro's package manager.

Because this isn't officially supported, I'm going to close this issue for now.  If you are running Linux and are unable to get even the generic tarball working, please reopen this issue and describe the problem you're running into.  Thank you!

**Comment by bitrocket** [comment]
I understand the closing of the issue since it's not tracking any work, but I hope that it's okay if OP reports back his successes or failures - I love this kinda of stuff.

**Comment by peterhuene** [comment]
@bitrocket we would absolutely love to hear about the success or failure regarding running .NET Core on any platform :)

**Comment by benaadams** [comment]
Mono supports .NET on Playstation 4 https://www.mono-project.com/docs/about-mono/supported-platforms/playstation4/

However:

> The Mono for PlayStation®4 port is a free product but only accessible to registered PlayStation®4 developer.
