### ISSUE TITLE
Run DotNet on X86, Without OS

### ISSUE THREAD

**Issue by alan1010ten** [dotnet/cli#9811]
How to run DotNet on X86, without OS?

**Comment by shahid-pk** [comment]
.net calls into OS system calls  or API , coreclr has a PAL layer that has platform calls for unix , this layer emulates the windows OS sytstem calls and provide implementation for unix. Similarly corefx the base class libraries has PAL layer too.  .Net all in all depends on the underling OS for all its tasks. 
So this is impossible without implementing a kernel and required functionality in .Net itself which is a bad idea in my opinion since  .Net is an application framework not an OS. If you are looking for a minimal OS to run .Net then take a look at [Alpine](https://alpinelinux.org/about/) , its armhf based images are no larger than 31 MB.
