### ISSUE TITLE
dotnet-run, "Could not resolve coreclr path" on Ubuntu 15.04

### ISSUE THREAD

**Issue by mellinoe** [dotnet/cli#988]
I'm always seeing the `Could not resolve coreclr path` error, and I've done the following:

* set DOTNET_HOME to my stage2 directory, alias dotnet, then use `dotnet run` from my project directory
* call `dotnet run -p <path-to-project>` from my stage2/bin directory
* call `dotnet-run -p <path-to-project>` from my stage2/bin directory

The project I'm testing is just a new blank project created from `dotnet new`, which seems to be working fine for me on Ubuntu 15.04. Same with `dotnet repl`, although I didn't really test much beyond seeing if it ran and if commands worked. `dotnet restore` also seems fine. `dotnet publish` also works fine on my blank project, and I can also run the app from the bin/Debug/dnxcore50/ubuntu.15.04-x64 directory afterwards.

(This is with a clean build of cli from today)

@brthor

**Comment by piotrpMSFT** [comment]
What if you run 'dotnet run' directly from the project directory?

**Comment by mellinoe** [comment]
Sorry, that's what my first bullet was supposed to say. You mean running `dotnet run` from the directory of my test project?

**Comment by piotrpMSFT** [comment]
Thanks @mellinoe I created a new tag to track 15.04 and put this in the backlog. When we start 15.04 bringup we'll take a look!

**Comment by borgdylan** [comment]
A workaround includes copying the CoreCLR binaries manually. That gets past the clr not found issue but does not solve the lack of key dlls that should have been published such as System.Console.dll

**Comment by Jamlee** [comment]
installed `dotnet-dev` instead of `dotnet`.  and run `  sudo ln -sf /usr/share/dotnet-dev /usr/share/dotnet` . your problem will be resloved.

**Comment by TPoise** [comment]
Advice for others having this problem:

0.  Uninstall the previous dotnet if you got it using apt-get  (`sudo apt-get remove dotnet`)
1.  Install the latest unbuntu files in order directly using **`dpkg -i`** (the files an be found on the frontpage of github.com/dotnet/cli for ubuntu).  The files coming through apt-get aren't always the latest, and I still had the problem.
2.  Create a blank new directory and a new project using **`dotnet new`** then copy your existing files over if you have any.  For some reason, the existing directory is hosed up.  Backup the files if necessary and re-create the folder.
3.  **`dotnet restore`** then **`dotnet run`**

The problem was fixed for me on **1.0.0-beta-002202**

**Comment by piotrpMSFT** [comment]
We're going to 16.04, not 15.04.

**Comment by keitaroemotion** [comment]
Sometimes you encounter with this error because you don't have required configfile (i.g. appsettings.json etc...)

Please make sure all the dependencies (including jsons) are located on the directory you run your dotnet app.
