### ISSUE TITLE
dotnet test/run have inconsistent CWD

### ISSUE THREAD

**Issue by yoshiya8** [dotnet/cli#9896]
## Steps to reproduce
Create a .NET core app that simply prints out the current directory from the environment *and* a .NET core XUNIT test case that does the same:

    using System;
    namespace DotnetRun
    {
        class Program
        {
            static void Main(string[] args) => Console.WriteLine($"CWD: [{Environment.CurrentDirectory}]");
        }
    }

and

    using System;
    using Xunit;
    using Xunit.Abstractions;
    namespace DotnetTest
    {
        public class UnitTest1
        {
            private readonly ITestOutputHelper output;
            public UnitTest1(ITestOutputHelper output) => this.output = output;
            [Fact]
            public void Test1() => output.WriteLine($"CWD: [{Environment.CurrentDirectory}]");
        }
    }

1. Run the app: `dotnet run`
2. Note the output of the app.
2. Run the unit test with logging to capture the output: `dotnet test --logger "trx;LogFileName=C:\some\path\Results.trx"`
3. Get the output from the unit test: `Select-String -Path C:\some\path\Results.trx -Pattern "<StdOut>"`

## Expected  behavior
The current directory for each run would be the current directory of the shell that launched the `dotnet` command.

## Actual behavior
The current directory of the `dotnet run` is as expected. However, the current directory of the `dotnet test` is the directory of the `.dll` file ("`$pwd\bin\Debug\netcorapp2.0`")

**Comment by yoshiya8** [comment]
I believe this relates to: [https://github.com/dotnet/cli/issues/4473](url)

**Comment by peterhuene** [comment]
I finally got around to tracking down the source of the discrepancy between `dotnet run` and `dotnet test`.  Neither commands in the CLI set the current working directory.

The culprit is the [test host manager](https://github.com/Microsoft/vstest/blob/9ddaf36ee96c9ed961b9c1c2b806b20fbffb4659/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs#L234) that is spawning the console host and explicitly setting the working directory to the directory containing the test assembly.

I'll move this issue there.

**Comment by peterhuene** [comment]
This issue was moved to Microsoft/vstest#2004
